src/wallet.js

Add getWalletTransactionBySequenceId according to the documentation:
https://www.bitgo.com/api/#get-transaction-by-sequence-id

Add getWalletTransactionBySequenceId according to the documentation.

---

package.json

Keccak is not used.. why this package in dependencies?

Remove keccakjs from dependencies

---

src/wallet.js

Fixes ignoring of `compact` param by BitGo client

fixed compact param handling

---

src/config.js

We need to include DAI in the SDK config for krsProviders

[BG-9361] added dai to krsProviders

---

package-lock.json
package.json

Reviewers: bigly, james
Subscribers: tyler
Differential Revision: https://phabricator.bitgo.com/D10643

BRE-257. Update to 4.43.0

---

README.md
package-lock.json
package.json
src/v2/baseCoin.js
src/v2/coins/xlm.js
test/v2/unit/baseCoin.js

This will allow the returned string to be parsed into a number by callers more easily.

BG-9405: pass format options to toFormat for baseunit conversion

---

package-lock.json
package.json

Update release version inside package.json.

BRE-279. Update package.json

---

src/config.js

https://bitgoinc.atlassian.net/browse/BG-9596

[BG-9596] Update TUSD 

---

src/bitgo.js
src/clientRoutes.js
src/v2/coins/abstractUtxoCoin.js
src/v2/wallet.js
src/v2/wallets.js

BG-9501: Extend sequenced request ids to some express calls

---

src/pendingapproval.js
test/v2/integration/markets.js

need to delete fee rate, otherwise we get the error that we can't have feeRate and fee both specified during createTransaction

[BG-6524] must delete feeRate

---

src/config.js

https://bitgoinc.atlassian.net/browse/BG-9672
See list of ERC20 tokens to add here: https://docs.google.com/spreadsheets/d/1QodHn3JW7M-0qNpmXJmkBj9erAR2AtQ23CEiyGXmZzw/edit#gid=337136954

[BG-9672] Added ERC20 tokens for Sprint Quicksilver

---

package-lock.json

See JIRA ticket for additional details and rationale

BG-9679: Regenerate package-lock.json with npm 6.5.0

---

RELEASE_NOTES.md

BG-8526: Add release notes for 4.44.0 release

---

src/config.js

I added the wrong token address for WPX, update to correct one

[BG-9978] Update WPX Token Contract Address

---

src/config.js

Addded new ERC20 tokens to SDK for sprint raccoon:
https://bitgoinc.atlassian.net/browse/BG-9749

[BG-9749] -- Added new tokens for Sprint Raccoon

---

RELEASE_NOTES.md

BG-10247: Update release notes for version 4.45.0

---

src/clientRoutes.js
test/v2/integration/bitgoExpress.js

BG-10246: Correctly handle coinless routes with query params in bitgo-express

---

src/v2/coins/eth.js
test/v2/fixtures/eth.js
test/v2/integration/coins/eth.js
test/v2/unit/ethWallet.js
test/v2/unit/recovery.js

Part of: https://bitgoinc.atlassian.net/browse/BG-10112
This adds support for constructing an unsigned ETH recovery transaction.
Also adds the ability to sign 2nd signature on an ETH transasction

BG-10112 eth recovery additions

---

src/config.js

Added new ERC20 tokens for Sprint steven Strange
- AMON
- CRPT
- AXPR
- GOT
- EURS

[BG-10402] Add ERC20 Tokens for Sprint Steven Strange

---

package-lock.json
package.json

BG-10717: Update nyc to 13.3.0

---

RELEASE_NOTES.md

BG-10609: Add release notes for 4.45.1 and 4.46.0 releases

---

src/config.js

BG-10763 Add ERC20 tokens for Sprint Thanos

---

package-lock.json
package.json

Please review and approve after its CI has succeeded.

BRE-364 Updated SDK version to 4.47.0 for Sprint Thanos release rt20190221.

---

src/v2/coins/abstractUtxoCoin.js
test/v2/unit/coins/btc.js

BG-8668: Add total and per-input signature counts to `explainTransaction`

---

src/v2/wallet.js

https://bitgoinc.atlassian.net/browse/BG-10969

Add unspent selection strategy option

---

src/v2/pendingApproval.js

We don't want to rebuild since it doesn't provide any benefit for OFC txs and can cause some issues.

BG-11020: Prevent rebuilding OFC txs

---

src/config.js
test/unit/bitgo.js

Added new ERC20 Tokens:
Hxro
Refereum
Coineru Platinum
Coineru Silver
Coineru Gold
eToro New Zealand Dollar
eToro Japanese Yen
eToro Russian Ruble
eToro Chinese Yuan
eToro Swiss Frank
eToro United States Dollar
eToro Euro
eToro Pound Sterling
eToro Australian Dollar
eToro Canadian Dollar
eToro Gold
eToro Silver
AlphaSlot
Testnet Formosa Financial

[BG-11032] Add ERC20 Tokens for Sprint Uranus

---

src/wallet.js
test/unit/wallet.js

https://bitgoinc.atlassian.net/browse/BG-10933
The SDK's v1 sendMany call is returning incorrect fee and feeRates.
This PR fixes that.

BG-10933 fix v1 fee response from sendMany

---

package-lock.json
package.json
test/scripts/ci.sh

BG-10913: Update karma to 4.0.1 and re-enable npm audit

---

CODEOWNERS

BG-11021: Add CODEOWNERS file

---

LICENSE

BG-11170: Update license holder and years on license.

---

RELEASE_NOTES.md

BG-11109: Add release notes for BitGoJS 4.47.0

---

src/v2/coins/xlm.js
src/v2/coins/xrp.js
test/v2/unit/recovery.js

https://bitgoinc.atlassian.net/browse/BG-10379

BG-10379 xlm and xrp unsigned sweeps

---

package-lock.json
package.json

Update version in package.json.

BG-11206. Update package.json

---

src/expressApp.js
test/v2/integration/bitgoExpress.js

https://bitgoinc.atlassian.net/browse/BG-11092
Customer needs to access the oauth/token route but the proxy is blocking it.

BG-11092 proxy unblock oauth/token route

---

package-lock.json
package.json

Please review and approve. Thank you, guys.

BRE-392 Updated SDK version to 4.48.1 for hotfix release ru20190307a.

---

src/config.js

Cred - LBA
CDAG - CannDollar
Ethos - ETHOS

[BG-11449] Add ERC20 Tokens for Sprint Vision

---

src/v2/coins/abstractUtxoCoin.js
src/v2/wallet.js
test/v2/unit/wallet.js

https://bitgoinc.atlassian.net/browse/BG-10671?filter=-1
This will slightly speed up prebuildAndSignTransaction

BG-10671 call prebuild and get keychain in parallel

---

CODEOWNERS

* Add BRE team members as codeowners for package.json and package-lock.json
* Add tyler@bitgo.com and danny@bitgo.com as codeowners for all files

BG-11216: Update CODEOWNERS file

---

src/v2/coins/eth.js

https://bitgoinc.atlassian.net/browse/BG-11479
The WRW should be able to broadcast an unsupported token recovery without going through BitGo support
Previously, recovering unsupported tokens from live ETH wallets is problematic because the contractSequenceID's get messed up, as there was a long delay between the creation of the transaction and the eventual BitGo admin signature.
This PR allows the WRW to broadcast an unsupported token recovery to BitGo immediately after signing, which allows the user to recover these tokens without interfering with the contractSequenceIDs of their ETH wallet.
Successfully tested on test.bitgo.com with a local copy of BitGoJS

BG-11479 broadcast unsupported token recovery

---

RELEASE_NOTES.md

BG-11111: Add release notes for releases 4.48.0 and 4.48.1

---

src/v2/coins/eth.js
src/v2/coins/ofcToken.js
test/scripts/ci.sh

BG-11493: Fix lint errors and travis config

---

test/v2/integration/wallet.js

BG-11491: Use confirmed transfer for id lookup test

---

.drone.jsonnet
.drone.yml
.travis.yml
README.md
package.json

BRE-380: Configure drone and remove travis

---

src/bitgo.js
src/index.js

We want to have the possibility to overwrite the serverXpub is using for custom environments.
Also we need to expose the different environments that we have so we can swap keys.

BG-11144 - Overwrite serverXpub in initialization

---

src/bitgo.ts

This is allow admin access to go to the auth service in the micro-service's.

BG-10662 Condition on microservice url on admin access route

---

package-lock.json
package.json
scripts/copySjcl.js
tsconfig.json

* Replace usage of `cp` with script to copy sjcl.min.js to the right place
* Move some types packages and others into dependencies from dev deps

BG:11661: Fix windows install

---

src/config.ts

FET -- Fetch
UPT -- Universal Protocol Token
UPUSD -- Universal USD
UPBTC -- Universal Bitcoin
QSP -- Quantstamp
Remove NAS as it's going mainnet and 0 wallets have any of it

[BG-11695] Add ERC20 tokens for Sprint Wolverine

---

package-lock.json
package.json

Please review and approve my PR. Thank you.
[BRE-418](https://bitgoinc.atlassian.net/browse/BRE-418)
Updated SDK version 4.49.1 for hotfix release rv20190321b.

BRE-418 Updated SDK version 4.49.1 for hotfix release rv20190321b.

---

src/v2/coins/abstractUtxoCoin.ts

JIRA: BG-11572
Technically, prior to this commit, parseSignatureScript will work
for native segwit. However, the code was confusing and purposely
misclassified native segwit inputs as p2sh inputs. This commit
cleans up `parseSignatureScript()` (including adding extensive
explanatory comments) and correctly classifies native segwit
inputs.

BG-11572: Refactor parseSignatureScript for native segwit

---

.npmignore
package.json

* Exclude more unnecessary files from npm package

BG-11726: Generate js files from ts files on prepare

---

src/config.ts

Removing this token borked some wallets that had leftover policies for it

[BG-11899] Add Nebulas token back

---

package-lock.json
package.json

Update version to 5.0.2 for Wolverine hot fix.

BRE-435. Update package.json

---

src/v2/coins/btc.ts
test/v2/lib/recovery-nocks.ts

https://bitgoinc.atlassian.net/browse/BG-11986
21.co is now earn.com and they've discontinued their old fees endpoint

BG-11986 update 21.co fees endpoint

---

src/v2/wallet.ts

The `count` field was validated twice, remove the less specific one

[BG-6875] Remove extra validation in createAddress

---

example/v2/get-maximum-spendable.js
src/v2/wallet.ts
test/v2/unit/wallet.ts

[BG-11671](https://bitgoinc.atlassian.net/browse/BG-11671) Add new param `recipientAddress` to `maximumSpendable`.

BG-11671 update maximumSpendable params

---

.drone.jsonnet
.drone.yml
package-lock.json
package.json

* Re-enable `npm audit` in CI pipeline

BG-12013: Update nyc to 14.0.0 for vuln fix

---

package-lock.json
package.json

Update version for vision release.

BRE-441. Update package.json

---

package-lock.json
package.json

BRE-443. Update package.json

---

src/v2/keychains.ts
test/v2/unit/keychains.ts

[BG-11787](https://bitgoinc.atlassian.net/browse/BG-11787) Use the right method to update the keychain and update the unit tests.

BG-11787 use updateSingleKeychainPassword in keychain.ts

---

src/config.ts
test/unit/bitgo.ts

Huobi Token (HT)
Hydro (HYDRO)
LGO Exchange (LGO)
Upgrade: HedgeTrade (HEDG)
Upgrade: Insureum (ISR)

[BG-12032] Add ERC20 tokens for Sprint Xena

---

README.md
RELEASE_NOTES.md

Update release notes for the following versions released during xena:
* 4.49.1
* 4.49.2
* 5.0.1
* 5.0.2
* 5.0.3
* 5.0.4

BG-11891: Update release notes

---

src/v2/coins/abstractUtxoCoin.ts

JIRA: CT-128
Prior to this commit we could not spend native segwit inputs unless
they were the last input in the transaction. This bug was caused by
the fact that we would rebuild the transaction (and subsequently
clear the redeem script in the p2wsh case) after signing each
input. Then we would verify the input and it would pass for p2wsh
because the redeem script had been cleared. However, when we
rebuilt on the next input, the redeem script would be there again.
We don't reverify the previous input so it slips past verification
and we end up with an invalid tx hex. This commit splits up signing
and signature verification such that this cannot happen.
Side note: I am not sure why bitgo-utxo-lib returns a redeem script
for native segwit inputs. This seems like a bug but the SDK was …

CT-128: Separate signing and verification

---

package-lock.json
package.json

Bump version to 5.1.1

---

src/config.ts

WHT - WhatsHalal Token
AMN - Amon
BTU - BTU Protocol
TAUD - TrueAUD

[BG-12296] Add ERC20 Tokens for Sprint Y

---

package-lock.json
package.json

JIRA ticket: [BRE-463](https://bitgoinc.atlassian.net/browse/BRE-463)

BRE-463 Updated SDK version to 5.2.0 for sprint Yggdrasil release ry20190502.

---

src/config.ts

Sparrow Options (SPO) -- 0x89eafa06d99f0a4d816918245266800c9a0941e0
Trade Token X (TIOx) -- 0xd947b0ceab2a8885866b9a04a06ae99de852a3d4

[BG-12658] Add ERC20 Tokens

---

package-lock.json
package.json
src/v2/baseCoin.ts
src/v2/coins/algo.ts
src/v2/coins/talgo.ts

Intended as a skeleton for Algorand work. This includes algosdk, which will be used for transaction signing.

CT-220 - skeleton for algorand

---

modules/core/src/v2/enterprise.ts
modules/core/src/v2/trading/affirmation.ts
modules/core/src/v2/trading/affirmations.ts
modules/core/src/v2/trading/lock.ts
modules/core/src/v2/trading/payload.ts
modules/core/src/v2/trading/settlement.ts
modules/core/src/v2/trading/settlements.ts
modules/core/src/v2/trading/trade.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/test/v2/fixtures/trading/affirmation.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts

Listing settlements and affirmations, creating settlements, affirming/rejecting/cancelling affirmations, the works. :)

BG-12924 / Settlement

---

modules/core/package.json
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/talgo.ts
modules/core/test/v2/unit/coins/algo.ts
yarn.lock

Adds ALGO methods needed to create a new wallet.
https://bitgoinc.atlassian.net/browse/CT-220

CT-220 - Add ALGO key logic to create a wallet

---

modules/core/src/v2/trading/tradingAccount.ts
modules/core/src/v2/trading/tradingPartner.ts
modules/core/src/v2/trading/tradingPartners.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/fixtures/trading/tradingPartner.ts
modules/core/test/v2/unit/trading/tradingPartner.ts

Listing trading partners and balance checking.

BG-12925 / Manage trading network

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/fixtures/algo.ts
modules/core/test/v2/unit/coins/algo.ts

Enabling algorand build tx. Gotta clean up some ltitle things and write another test or two.

CT-223 - algorand build tx

---

modules/core/src/config.ts

Opiria Token (PDATA) -- 0x0db03B6CDe0B2d427C64a04FeAfd825938368f1F

[CT-376] Add ERC20 Tokens

---

modules/core/src/config.ts

need to add new constants to sdk for litecoin

BG-12826-add-ltc-and-docs

---

modules/core/src/config.ts

ShareToken (SHR) -- 0xee5fe244406f35d9b4ddb488a64d51456630befc
Vodi X (VDX) -- 0x91e64f39c1fe14492e8fdf5a8b0f305bd218c8a1
Orbs Token (ORBS) -- 0xff56cc6b1e6ded347aa0b7676c85ab0b3d08b0fa
Crypto.com (MCO) -- 0xB63B606Ac810a52cCa15e44bB630fd42D8d1d83d
ROOBEE (ROOBEE) -- 0xa31b1767e09f842ecfd4bc471fe44f830e3891aa
TenX Token (TENX) -- 0x515bA0a2E286AF10115284F151cF398688A69170
PRDX Token (PRDX) -- 0xE17900F23B7eBb2791F25f1eAa63d8F5E603e9a5
DRP Utility (DRPU) -- 0xe30e02f049957e2a5907589e06ba646fb2c321ba
Crypto.com Chain (CRO) -- 0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b

[CT-481] Add ERC20 Tokens

---

modules/core/src/v2/coins/eth.ts

This is required to get an accurate fee estimate -- I added it in the caller but forgot to add it here

CT-456 Ensure amount value passes through eth fee estimate

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

Add local signing using the eosjs ecc library

[CT-393] Add EOS Signing logic

---

modules/core/src/config.ts

ValorToken (VALOR) -- 0x297e4e5e59ad72b1b0a2fd446929e76117be0e0a
Compound Ether (CETH) -- 0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5
Compound DAI (CDAI) -- 0xf5dce57282a584d2746faf1593d3121fcac444dc
Compound USDC (CUSDC) -- 0x39aa39c021dfbae8fac545936693ac917d5e7563
Compound ZRX (CZRX) -- 0xb3319f5d18bc0d84dd1b4825dcde5d5f7266d407
Compound BAT (CBAT) -- 0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e
Compound Augur (CREP) -- 0x158079ee67fce2f58472a96584a73c7ab9ac95c1
Bitfinex LEO (LEO) -- 0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3
RLC (RLC) -- 0x607F4C5BB672230e8672085532f7e901544a7375

[CT-605] Add ERC20 Tokens

---

modules/core/package.json
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/markets.ts

* Also adds 'check-fmt' script to check prettier status

CT-361: Typescript markets

---

modules/core/src/v2/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts

We need to fixup Algo to be txHex instead of txBase64 (design decision) and then trust custodial implementation items

CT-256 - renaming txbase64 to txhex in algo & trust custodial implementation

---

modules/core/package.json
modules/express/package-lock.json
modules/express/package.json

Please verify that this change is exactly the same as those made on the rel/davidcity branch (disregard changes which were already introduced in master and were cherry-picked into the release branch).

Merge rel/davidcity

---

modules/core/src/config.ts

EMX (EMX) -- 0x75a29c405bd5ab2f3b35144af937ee98d390b5ee
Eden (EDN) -- 0x05860d453c7974cbf46508c06cba14e211c629ce
TrueCAD (TCAD) -- 0x00000100F2A2bd000715001920eB70D229700085
TrueHKD (THKD) -- 0x0000852600ceb001e08e00bc008be620d60031f2
LGO upgrade to 0x0a50c93c762fdd6e56d86215c24aaad43ab629aa

[CT-699] Add ERC20 Tokens

---

.eslintrc.json
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/internal.ts
modules/core/src/v2/keyDeriver.ts
modules/core/src/v2/pendingApproval.ts
modules/core/src/v2/pendingApprovals.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts

Also:
* Run prettier on more files
* Remove the generator-star-spacing rule for eslint

CT-362: Typescriptify pendingApproval and pendingApprovals

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/keychains.ts

https://bitgoinc.atlassian.net/browse/CT-360
Lets typescriptify this baby

Ct 360 typescript keychains

---

modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/teos.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/environments.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

https://bitgoinc.atlassian.net/browse/CT-637

CT-637 - Add EOS recovery support

---

Dockerfile
modules/express/README.md
modules/express/bin/bitgo-express
modules/express/package-lock.json
modules/express/src/args.ts
modules/express/src/clientRoutes.ts
modules/express/src/config.ts
modules/express/src/expressApp.ts
modules/express/test/unit/bitgoExpress.ts
modules/express/test/unit/config.ts

Previously, bitgo express could get configuration options in three
ways: command line arguments, environment variables, and hard coded
defaults. Some options were settable by one method, but not from others,
and the configuration option names were not consistent.
This change unifies these three configuration sources into a generic
configuration object which can decide which source should take
precedence over others.

CT-714: Unify express configuration systems

---

modules/express/README.md

* Add link to API docs
* Fix docker run command
* Separate docker and run from source instructions
* Add example on starting with command line flags with `npm run start`

CT-709: Further improve BitGo Express README

---

modules/core/.npmignore
modules/core/src/v2/baseCoin.ts
modules/express/package-lock.json
modules/express/package.json
modules/express/test/integration/bitgoExpress.ts
modules/express/test/integration/bitgoExpressV1.ts
modules/express/test/integration/eth.ts
modules/express/test/lib/asserts.ts
modules/express/test/lib/test_bitgo.ts
modules/express/test/lib/testutil.ts
modules/express/test/unit/bitgoExpress.ts
modules/express/test/unit/config.ts
modules/express/tsconfig.json
yarn.lock

* This should eventually be extracted out into a separate module which
can be used by any other module without doing a cross-module require

CT-774: Copy test_bitgo and testutil subset into express

---

modules/core/src/v2/coins/ofcToken.ts
modules/core/test/v2/unit/coins/ofcToken.ts

Looks like I didn't add isValidAddress support previously so I'm doing so now. Also adding support for a custom address format. See ticket for more details.

BG-13779: Add OFC address checking

---

modules/core/src/v2/coins/btc.ts

https://bitgoinc.atlassian.net/browse/CT-349

CT-329 Typescriptify BTC

---

modules/core/src/v2/coins/bsv.ts

https://bitgoinc.atlassian.net/browse/CT-348

CT-348 Typescriptify BSV

---

modules/core/src/v2/coins/btg.ts

https://bitgoinc.atlassian.net/browse/CT-350

CT-350 Typescriptify BTG

---

modules/core/src/v2/coins/ltc.ts

https://bitgoinc.atlassian.net/browse/CT-352

CT-352 Typescriptify LTC

---

modules/core/src/v2/coins/dash.ts

https://bitgoinc.atlassian.net/browse/CT-351

CT-351 Typescriptify Dash

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/rmg.ts

https://bitgoinc.atlassian.net/browse/CT-355
Because RMG just refuses to die

CT-355 Typescriptify RMG

---

modules/core/src/config.ts

TrueGBP (TGBP) -- 0x00000000441378008EA67F4284A57932B1c000a5

[CT-841] Add ERC20 Tokens

---

modules/core/src/v2/keycard.ts
modules/core/src/v2/wallet.ts

This PR is a continuation of #475.

CT-915: Correct params in downloadKeycard

---

modules/core/src/v2/trading/tradingAccount.ts
modules/core/test/v2/unit/trading/tradingAccount.ts

Added TradingAccount::calculateSettlementFees(), which takes parameters
about the amounts and currencies of a settlement and returns information
about the necessary fees to complete the settlement.

BG-13712 / Add calculateSettlementFees()

---

modules/core/src/config.ts

AGARWOOD (AGWD) -- 0xc3e419177044c9172823f06335d5d82aaf38a5c6
KOZJIN Token (KOZ) -- 0xd95e7d16000cbeb66acbf70b4a843d4346ff4555
Cryptoindex 100 (CIX100) -- 0x6393e822874728f8afa7e1c9944e417d37ca5878

[CT-938] Add ERC20 Tokens

---

modules/express/src/expressApp.ts

https://bitgoinc.atlassian.net/browse/CT-371

CT-371 typescriptify expressApp

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/recovery.ts

https://bitgoinc.atlassian.net/browse/CT-363

CT-363 Typescriptify recovery

---

types/bitgo-utxo-lib/index.d.ts

Signed commits from #524 
Thanks for the fix @workflow

SDKT-29: Fix incorrect types in bitgo-utxo-lib type declaration

---

modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/trx.ts

This will be the first leg of the create wallet path for Tron.

TRON-2 - Create wallet

---

modules/express/test/integration/eth.ts

https://bitgoinc.atlassian.net/browse/BLOCK-42
Update teth sendmany test - now that batching is enabled, sendmany should succeed

BLOCK-42 update teth sendmany test

---

modules/core/test/v2/integration/coins/xrp.ts

https://bitgoinc.atlassian.net/browse/BLOCK-3
Reenable XRP tests with new test wallet now that TXRP is back up

BLOCK-3 fix xrp tests

---

modules/express/README.md

https://bitgoinc.atlassian.net/browse/SERV-269
Update the docker production docs

SERV-269 update express docker production docs

---

modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/xlm.ts

The SDK already allows sending a tx to add or update a trustline, with this change it will also allow removing it.
https://bitgoinc.atlassian.net/browse/TOKS-33

TOKS-33 Allow removing Stellar trustlines

---

modules/core/src/v2/wallet.ts

* Combine consolidate/fanout into single method (line on the backend)
* Regroup and fix documentation (remove unimplemented params, add missing ones)
Issue: BG-14108

Add new method `wallet.manageUnspents`

---

modules/core/package.json
modules/core/src/v2/coins/trx.ts
yarn.lock

[TRON-70](https://bitgoinc.atlassian.net/browse/TRON-70) Tron send transaction

TRON-3 - hot wallet sending

---

modules/core/package.json

Hard code statics to 2.2.0 in SDK for Innsbruck hot fix release ri20190919e

Do 401 update statics

---

yarn.lock

Update yarn.lock for SDK Innsbruck hot fix release, ri20190919e

DO-402: Update yarn.lock for SDK Innsbruck hot fix release, ri20190919e

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/trx.ts

[TRON-76](https://bitgoinc.atlassian.net/browse/TRON-76) Fix pending approvals and align with the return types of other coins

TRON-76: Change signTransaction return type

---

modules/core/package.json
modules/core/test/v2/unit/coins/trx.ts
yarn.lock

[TRON-95](https://bitgoinc.atlassian.net/browse/TRON-95) Account lib output for the `toJSON()` function changed to match the network format, which fixed send transaction flow.

TRON-95: Update Account lib and fix tests

---

modules/core/test/v2/integration/coins/xlm.ts

The XLM testnet was reset earlier today, and the previous integration
test wallets have been deleted.
This commit sets the wallet ids to newly created XLM wallets, as well as
some minor cleanup of duplicated test code and missing types.

SERV-484: Recreate XLM integration test wallets

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

https://bitgoinc.atlassian.net/browse/BLOCK-108
We should allow users to take advantage of the unspent reservation system in the build route.

BLOCK-108 allow unspent reservation param in build

---

modules/core/package.json
modules/express/package.json
modules/statics/package.json
yarn.lock

Cut a merge branch (do-555-merge ) off the release branch (rel/la), rebased master into do-555-merge, merge do-555-merge into master

Do 555 merge

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/coins/trx.ts

[TRON-124](https://bitgoinc.atlassian.net/browse/TRON-124)

TRON-126 use xpub and xprv only for Tron

---

modules/core/src/v2/coins/trx.ts
modules/core/src/v2/environments.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts
package.json
yarn.lock

Initial PR for tron wallet recoveries. Still a WIP.

TRON-36 - trx recoveries, initial

---

modules/statics/package.json
modules/statics/src/map.ts
modules/statics/test/mocha.opts
modules/statics/test/unit/coins.ts
modules/statics/test/unit/deps.ts
package.json
yarn.lock

* Ensure no dependencies are added to package.json
* Ensure all ERC20 token contract addresses are unique

SERV-35: Add basic tests

---

modules/core/src/v2/trading/affirmations.ts
modules/core/src/v2/trading/payload.ts
modules/core/src/v2/trading/settlements.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/test/v2/fixtures/trading/affirmation.ts
modules/core/test/v2/fixtures/trading/payload.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts

This will update the trade payload request to v 1.2.0.

AGS-18 / Update SDK with payload changes

---

modules/core/src/v2/coins/algo.ts

This commit returns type, senderAddress, voteKeyBase64, and
voteLastBlock from explainTransaction. The OVC needs this data to verify
what it is signing.
JIRA: AIR-6

Return algo keyreg data from explainTransaction

---

modules/core/src/v2/coins/algo.ts

fix(core): Rename import instead of colliding with declared interface

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

BG-17564: Add redeemScript and witnessScript to SignTransactionOptions

---

modules/core/src/v2/trading/settlement.ts
modules/core/src/v2/trading/trade.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/unit/trading/settlement.ts

update create settlement for agency

AGS-18 / update settlement for agency

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

[BG-17812](https://bitgoinc.atlassian.net/browse/BG-17812) Add Tezos statics

BG-17812 Add Tezos statics

---

modules/core/src/v2/trading/affirmation.ts
modules/core/src/v2/trading/affirmations.ts
modules/core/src/v2/trading/lock.ts
modules/core/src/v2/trading/payload.ts
modules/core/src/v2/trading/settlement.ts
modules/core/src/v2/trading/settlements.ts
modules/core/src/v2/trading/trade.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/src/v2/trading/tradingPartner.ts
modules/core/src/v2/trading/tradingPartners.ts

Remove hidden tags and old refer trading partner

---

modules/statics/src/coins.ts

Add SUPPORTS_TOKENS feature to XLM and TXLM

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Avoids copying the asset for test and prod in the CDN
Ticket: BG-18627

Use prod icon for TCAT token

---

modules/core/RELEASE_NOTES.md
modules/express/RELEASE_NOTES.md

Update SDK release notes

---

modules/core/package.json
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/ofc.ts
modules/core/src/v2/coins/ofcToken.ts
modules/core/src/v2/coins/rmg.ts
modules/core/src/v2/coins/susd.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/recovery.ts
modules/core/test/v2/unit/coins/bch.ts
modules/core/test/v2/unit/coins/btg.ts
modules/core/test/v2/unit/coins/eos.ts
modules/core/test/v2/unit/coins/ofcToken.ts
modules/core/test/v2/unit/coins/trx.ts
modules/core/test/v2/unit/ethWallet.ts
modules/express/package-lock.json
yarn.lock

Update account-lib dependency in core module
Update yarn.lock
Update Express' package-lock.json
Wrap coins' signTransaction methods in coroutines
Yield on (TRON) calls to account-lib's transactionBuilder.build() method
Ticket: BG-18323

Update account-lib version to 1.0.0

---

modules/core/package.json
yarn.lock

Update version of account-lib to v1.0.1

---

modules/core/RELEASE_NOTES.md
modules/express/RELEASE_NOTES.md

Update release notes for bitgo@9.6.2, bitgo@10.0.0,
express@9.6.4 and express@9.6.5
Ticket: BG-18906

Update release notes

---

modules/core/package.json
modules/express/package-lock.json
modules/express/package.json
modules/statics/package.json

[https://bitgoinc.atlassian.net/browse/BG-19437](https://bitgoinc.atlassian.net/browse/BG-19437)
Post the publishing process to npmjs and dockerhub, we need to merge some changes from the release branch, rel/sdk, back to master branch.
Please note that modules/express/package-lock.json was updated dynamically during the publish of bitgo/express to dockerhub. I committed in a separate commit.
Please refer to the CI build and test runs.

BG-19437 SDK 11.0.1 release: Merge changes from rel/sdk to origin/master

---

modules/core/test/v2/integration/bitgo.ts

Disable v1 address labels integration test

---

modules/core/src/v2/trading/affirmation.ts
modules/core/src/v2/trading/affirmations.ts
modules/core/src/v2/trading/lock.ts
modules/core/src/v2/trading/payload.ts
modules/core/src/v2/trading/settlement.ts
modules/core/src/v2/trading/settlements.ts
modules/core/src/v2/trading/trade.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/src/v2/trading/tradingPartner.ts
modules/core/src/v2/trading/tradingPartners.ts
modules/core/test/v2/fixtures/trading/affirmation.ts
modules/core/test/v2/fixtures/trading/payload.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/fixtures/trading/tradingPartner.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts
modules/core/test/v2/unit/trading/tradingPartner.ts

agency was released but the sdk changes were never merged to prod.
This should update all endpoints to match what's expected on the API side

AGS-1 agency feature

---

modules/core/RELEASE_NOTES.md
modules/express/RELEASE_NOTES.md

Update release notes through version 11.0.2

---

modules/core/test/v2/integration/bitgo.ts

Re-enable OAuth integration tests

---

DEVELOPERS.md
modules/statics/src/coins.ts

From PR #739 
Additional information for third party contributors has also been added to DEVELOPERS.md
Ticket: BG-20985

Use new SNX proxy address

---

modules/express/package-lock.json
modules/express/package.json
yarn.lock

Update http-agent to 1.18.1, update package-lock

---

modules/core/example/js/algo/README.md
modules/core/example/js/algo/account-consolidation-build.js
modules/core/example/js/algo/account-consolidation-send.js
modules/core/example/ts/README.md
modules/core/example/ts/algo/README.md
modules/core/example/ts/algo/account-consolidation-build.ts
modules/core/example/ts/algo/account-consolidation-send.ts
modules/core/src/v2/wallet.ts

The examples in this commit are for customers to clearly see how
Algorand consolidations are accomplished.
Ticket: BG-20486

Algorand consolidate example clean-up

---

modules/core/RELEASE_NOTES.md
modules/core/package.json
modules/express/RELEASE_NOTES.md
modules/express/package-lock.json
modules/express/package.json
modules/statics/package.json
yarn.lock

Backmerge sdk release

---

.eslintrc.json
modules/core/src/v2/pendingApproval.ts
modules/core/test/v2/unit/pendingApproval.ts

Allow rebuilding consolidation transactions upon tx approval

---

modules/core/example/js/backup-key-creation.js
modules/core/example/ts/backup-key-creation.ts

Backup key creation example

---

modules/core/RELEASE_NOTES.md
modules/core/package.json
modules/express/package-lock.json
modules/express/package.json
modules/statics/package.json

Backmerge rel/rc for 11.2.0 release

---

modules/statics/README.md
modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/ofc.ts
modules/statics/src/utxo.ts

This adds the elliptic curve to a coin implementation as a descriptive
feature.
Ticket: BG-22126

Adding the Keycurve to Base Coin

---

modules/statics/src/coins.ts

Add TDAI to TERC20 tokens

---

modules/core/package.json
modules/express/package-lock.json
modules/express/package.json
modules/statics/package.json

Backmerge Rel/rc for 11.3.0 release

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Added HBAR and hedera coin structure to support node account Id.

---

modules/account-lib/src/coin/trx/keyPair.ts
modules/account-lib/src/coin/xtz/keyPair.ts
yarn.lock

Also, remove `npm.bitgo.com` from the yarn.lock file
Ticket: BG-23120
Ticket: BG-23121

Remove leftover imports of `bitgo-utxo-lib`

---

modules/account-lib/package.json
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/test/unit/coin/hbar/utils.ts
yarn.lock

Add validation utils methods for Hedera.
TICKET: BG-23023

BG-23023 Add HBAR Utils

---

modules/account-lib/src/coin/hbar/index.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/index.ts
modules/account-lib/test/unit/coin/hbar/utils.ts

BG-23023 Export HBAR utils

---

modules/account-lib/.gitignore
modules/account-lib/package.json
modules/account-lib/resources/hbar/protobuf/BasicTypes.proto
modules/account-lib/resources/hbar/protobuf/CryptoCreate.proto
modules/account-lib/resources/hbar/protobuf/CryptoTransfer.proto
modules/account-lib/resources/hbar/protobuf/Duration.proto
modules/account-lib/resources/hbar/protobuf/Timestamp.proto
modules/account-lib/resources/hbar/protobuf/Transaction.proto
modules/account-lib/resources/hbar/protobuf/TransactionBody.proto
modules/account-lib/src/coin/baseCoin/baseTransactionBuilderFactory.ts
modules/account-lib/src/coin/baseCoin/iface.ts
modules/account-lib/src/coin/baseCoin/index.ts
modules/account-lib/src/coin/eth/iface.ts
modules/account-lib/src/coin/hbar/ifaces.ts
modules/account-lib/src/coin/hbar/index.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/src/index.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/walletInitialization.ts
yarn.lock

This is the first implementation for hedera transactions.
It's a continuation of https://github.com/BitGo/BitGoJS/pull/804

Hedera Wallet initialization

---

modules/account-lib/src/coin/baseCoin/errors.ts
modules/account-lib/src/coin/hbar/index.ts
modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/hbar/utils.ts

There are several minor fixes to the wallet initialization code like proper error messages, lint errors, even validators, and core reorganization.
CLOSES TICKET: BG-23224

BG-23224 Clean up

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts

This PR add some JSDOC and remove unary operator usage with BigNumber

Bga 223 cleanup

---

modules/core/RELEASE_NOTES.md
modules/express/RELEASE_NOTES.md

Update release notes for bitgo@11.4.0 and @bitgo/express@9.7.0

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilder.ts
modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/src/index.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/walletInitialization.ts

This PR add signing implementation for wallet initialization.

add signature implementation

---

modules/account-lib/package.json
modules/account-lib/src/coin/hbar/transaction.ts

Add transaction hash calculated internally.
In the future we are going to use the functionality provided by hedera sdk

return txHash

---

modules/account-lib/src/coin/hbar/transaction.ts

Making txHash and idParts public

---

modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/transaction.ts

We add transaction test for account-lib

BGA-286 Add transaction sign unit test

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/ifaces.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts

Added transfer multisig transaction

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts

This PR add a from method in TransactionBuilderFactory that returns the proper builder for that transaction type already initialized.

add get builder from implementation

---

modules/core/test/v2/integration/coins/xrp.ts
modules/core/test/v2/integration/wallets.ts

Enable XRP integration tests

---

modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/hbar/transaction.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/hbar/utils.ts

Add a method to remove prefix in private and public keys.

Bga 316 change hard slice for keys

---

modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts

Fix broken master hbar test

---

modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

Adds gasPrice param to add wallet
Ticket: [BG-23720](https://bitgoinc.atlassian.net/browse/BG-23720)

Add gasPrice param to add wallet

---

modules/account-lib/src/coin/hbar/ifaces.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts
modules/core/test/v2/unit/coins/hbar.ts

Update toJson method to return a Hedera transaction object.

BGA-324 Update toJson method

---

modules/account-lib/src/coin/baseCoin/ed25519KeyPair.ts
modules/account-lib/src/coin/trx/keyPair.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
yarn.lock

Add a method to produce signatures using the ed25519 public key signature system and also to
verify them. Implemented for HBAR, but can be used for other coins too.
CLOSES TICKET: BG-23920

Implement sign and verify message

---

modules/core/src/v2/coins/hbar.ts

Adding necessary function for hbar in UI

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

BGA-19 - Add RIF and tRIF to statics

---

modules/statics/src/networks.ts

Fixing hedera explorer uri

---

modules/account-lib/src/coin/hbar/utils.ts
modules/core/src/v2/coins/hbar.ts
modules/core/test/v2/unit/coins/hbar.ts

Adding support for memoId in HBAR addresses

---

package.json
yarn.lock

Fixing npm audit failures in master

---

modules/core/src/config.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/celoToken.ts
modules/core/src/v2/coins/index.ts
modules/core/test/browser/browser.spec.ts
modules/core/test/v2/unit/coins/celoToken.ts

Adds relevant configs for supporting celo tokens in SDK
Ticket: BG-24044

Add Celo token support in SDK

---

modules/core/src/v2/coins/hbar.ts
modules/core/test/v2/unit/coins/hbar.ts

Add helper to allow pubkey validation

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/bsv.ts
modules/core/src/v2/coins/btc.ts
modules/core/src/v2/environments.ts
modules/core/src/v2/recovery/blockchairApi.ts
modules/core/test/v2/fixtures/coins/recovery.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts
modules/core/test/v2/unit/recovery/blockchairApi.ts

This PR:
- Adds a blockexplorer for BSV
- Adds functionality to recover BSV without BitGo
TODO
- Make sure BSV is replay safe

BG-15531 support nonbitgo bsv recovery in SDK

---

modules/core/src/v2/recovery/blockchairApi.ts

Add coin param to URL

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Adds musd token to statics
Ticket: BG-24677

Add musd ERC20

---

modules/account-lib/src/coin/baseCoin/index.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/hbar.ts
modules/core/src/v2/internal/seedValidator.ts
modules/core/test/v2/unit/coins/algo.ts
modules/core/test/v2/unit/coins/hbar.ts
modules/core/test/v2/unit/seedValidator.ts

Adds seed handling for Stellar to Hbar seeds

---

modules/core/src/bitgo.ts
modules/core/src/v2/environments.ts
modules/core/test/unit/bitgo.ts

Adds a new environment 'branch' which can serve the purposes of both dev & custom environments. Specifically, this branch allows for passing custom parameters when creating BitGo, but will otherwise be treated as a dev environment. 
JIRA: BG-25008

add 'branch' environment

---

modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/hbar/utils.ts

Adds an ability to convert stellar pubkeys to hbar/ed29915 pubkeys

---

modules/account-lib/src/index.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/gteth.ts
modules/core/src/v2/coins/index.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

This commit adds configurations to support the ETH Goerli testnet
CLOSES TICKET: BG-25415

Add support for ETH Goerli testnet

---

modules/core/src/v2/coins/xtz.ts
modules/core/test/v2/unit/accountConsolidations.ts

Enable address balance consolidation for XTZ
Ticket: BG-24653

Add support for XTZ account consolidation implementation

---

modules/account-lib/package.json
modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/src/coin/eth2/keyPair.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts
yarn.lock

Updates BLS initialization so client does not need to worry about dependency
Ticket: BG-26379

Update BLS initialization

---

modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/src/coin/eth2/keyPair.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/eth2.ts
modules/core/src/v2/coins/index.ts
modules/core/src/v2/coins/teth2.ts
modules/core/src/v2/environments.ts
modules/core/test/v2/unit/coins/eth2.ts

Adds ETH2 coin controller with methods for recovery, validating addresses, retrieving address/balance/nonce info.

Add eth2 coin controller

---

modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts

Adds pubkey aggregation to support wallet creation in platform
Ticket: BG-26472

Add BLS pubkey aggregation

---

modules/core/example/js/xtz/consolidate-account-balances.js
modules/core/example/js/xtz/create-address.js
modules/core/example/ts/xtz/consolidate-account-balances.ts
modules/core/example/ts/xtz/create-address.ts

chore: add consolidation examples for Tezos

---

modules/core/test/v2/unit/keychains.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Add Casper coin to Static module. 
https://simtlix.atlassian.net/browse/BGA-740
https://simtlix.atlassian.net/browse/BGA-893

Bga 893 740 add cspr to statics

---

modules/account-lib/test/unit/coin/eth2/keyPair.ts

This commit adds a test for ETH2 aggregated keys to ensure that they work in a n-of-n manner

test(eth2): add test for ETH2 aggregate key sigs

---

modules/statics/src/coins.ts

Removes fee address requirement from eth2 statics
Ticket: BG-27115

remove fee address config from eth2 statics

---

modules/core/webpack.config.js

The sed -i"" syntax for in-place replacement of unsafe eval code in the
webpack pipeline is not portable. This caused the unsafe eval code to
remain in the browser bundle since the release process was recently
switched onto an ubuntu machine.
Instead, replace invocation of sed -i"" with a simple node script that
is more portable.
Ticket: BG-27261

fix: replace sed with node script for replacing unsafe eval

---

modules/core/example/js/algo/account-consolidation-build.js
modules/core/example/js/algo/account-consolidation-send.js
modules/core/example/js/create-wallet-address.js
modules/core/example/ts/algo/account-consolidation-build.ts
modules/core/example/ts/algo/account-consolidation-send.ts
modules/core/example/ts/create-wallet-address.ts
modules/core/src/v2/wallet.ts
modules/express/src/clientRoutes.ts
modules/express/test/unit/routeHandlers.ts

Adding consolidateAccount to express

---

yarn.lock

chore: update yarn.lock with casper lib and deps

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/cspr.ts
modules/core/src/v2/coins/index.ts
modules/core/src/v2/coins/tcspr.ts
modules/core/test/v2/unit/coins/cspr.ts
package.json

Jira card: https://simtlix.atlassian.net/browse/BGA-1165

WIP: Add cspr and tcspr to core module

---

modules/statics/src/coins.ts

Adding new erc20 tokens for ofc so that we can start using for WD. These
currently display on test as empty icons so this will allow the UI to
pick these up and display the ofc token images

Adding new erc ofc tokens to statics

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

Adds support for the `walletVersion` flag in `generateWallet` requests
Ticket: BG-28508

fix: adds wallet version support in core

---

modules/account-lib/src/coin/baseCoin/baseUtils.ts
modules/account-lib/src/coin/baseCoin/index.ts
modules/account-lib/src/coin/xrp/index.ts
modules/account-lib/src/coin/xrp/keyPair.ts
modules/account-lib/src/coin/xrp/transaction.ts
modules/account-lib/src/coin/xrp/transactionBuilder.ts
modules/account-lib/src/coin/xrp/transactionBuilderFactory.ts
modules/account-lib/src/coin/xrp/transferBuilder.ts
modules/account-lib/src/coin/xrp/utils.ts
modules/account-lib/src/coin/xrp/walletInitializationBuilder.ts
modules/account-lib/src/index.ts

Add XRP skeleton in account-lib.
CLOSES TICKET: BG-28586

feat: add XRP skeleton

---

modules/core/src/config.ts
modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/recovery.ts

Cumberland wants to customize their own gas price and limit in the WRW. This PR introduces the necessary backend changes
Ticket: BG-24734

Allow user defined gas price and limit

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/utils.ts
yarn.lock

feat(account-lib): update the casper-client-sdk dependency to v1.0.16

---

modules/statics/src/coins.ts

fix: enable TEST token for testnet ofc

---

modules/statics/src/networks.ts

STLX-948 added explorer url, right now there's only one net, there's a ticket created to update the urls [STLX-1657](https://bitgoinc.atlassian.net/browse/STLX-1657)

feat(statics): add casper explorer url

---

modules/core/src/v2/coins/eos.ts
modules/core/src/v2/environments.ts
modules/core/test/v2/lib/recovery-nocks.ts

1. EOS blockexplorers no longer work, this PR replace them with new ones.
2. Check blockexplorer return value before indexing into its property to avoid weird bugs.

Bg 28948 Fix EOS recovery bugs

---

modules/core/src/v2/wallet.ts

BG-29290: whitelist messageKey param

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/util.ts

feat(account-lib): add pub key validation and address validation for CSPR

---

.github/workflows/stale.yml

chore: enable github action to close stale issues and PRs

---

modules/account-lib/src/coin/cspr/constants.ts

Updated Casper Node version to delta-10
Jira Ticket: [STLX-1716](https://bitgoinc.atlassian.net/browse/STLX-1716)

feat(account-lib): STLX-1716 Updated casper node version

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/constants.ts
modules/account-lib/src/coin/cspr/ifaces.ts
modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/walletInitializationBuilder.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transactionBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilderFactory.ts

Jira Ticket: [STLX-1458](https://bitgoinc.atlassian.net/browse/STLX-1458)

feature(account-lib): STLX-1458 from implementation for wallet initialization

---

modules/account-lib/package.json

Updated casper-client-sdk to version 1.0.19
Jira Ticket: [STLX-1666](https://bitgoinc.atlassian.net/browse/STLX-1666)

feat(account-lib): STLX-1666 Updated casper sdk version to 1.0.19

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/util.ts

Add private key validation using the Crypto util
Ticket: STLX-1345

feat(account-lib): implement isValidPrivateKey() method for CSPR

---

modules/account-lib/src/coin/cspr/constants.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/transactionBuilderFactory.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilderFactory.ts

From implementation for transfer transactions
[STLX-663](https://bitgoinc.atlassian.net/browse/STLX-663)

feat(account-lib): STLX-663 From implementation for transfer builder

---

modules/core/src/v2/coins/eth.ts
modules/core/src/v2/environments.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts
modules/statics/src/networks.ts

Fix testnet URL for etherscan and improve error catching for ETH recovery.

Bg 29498 fix eth recovery

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/recovery.ts

One gwei is 10^9 wei. The error message used an incorrect conversion.

fix: fix wei to gwei conversion

---

modules/account-lib/package.json

Update Casper Client SDK from v1.0.19 to v1.0.20
[STLX-1774](https://bitgoinc.atlassian.net/browse/STLX-1774)

feat(account-lib): STLX-1774 Update Casper SDK to version 1.0.20

---

modules/account-lib/src/coin/baseCoin/enum.ts
modules/account-lib/src/coin/trx/contractCallBuilder.ts
modules/account-lib/src/coin/trx/enum.ts
modules/account-lib/src/coin/trx/iface.ts
modules/account-lib/src/coin/trx/index.ts
modules/account-lib/src/coin/trx/transaction.ts
modules/account-lib/src/coin/trx/transactionBuilder.ts
modules/account-lib/src/coin/trx/utils.ts
modules/account-lib/src/coin/trx/wrappedBuilder.ts
modules/account-lib/src/index.ts
modules/account-lib/test/resources/trx/trx.ts
modules/account-lib/test/unit/coin/trx/transactionBuilder/contractCallBuilder.ts
modules/account-lib/test/unit/coin/trx/transactionBuilder/wrappedBuilder.ts

Add contract call builder 
Related issues
https://bitgoinc.atlassian.net/browse/STLX-1601

STLX-1601 Add Smart Contract calls support to TRX

---

modules/account-lib/src/coin/trx/contractCallBuilder.ts
modules/account-lib/src/coin/trx/transactionBuilder.ts
modules/account-lib/src/coin/trx/wrappedBuilder.ts

Update init builder in order to complement implementation done at stlx-1601
Ticket related : https://bitgoinc.atlassian.net/browse/STLX-4

Stlx 4 init builder

---

modules/account-lib/src/coin/trx/contractCallBuilder.ts
modules/account-lib/src/coin/trx/iface.ts
modules/account-lib/src/coin/trx/transaction.ts
modules/account-lib/src/coin/trx/transactionBuilder.ts
modules/account-lib/src/coin/trx/wrappedBuilder.ts
modules/account-lib/test/unit/coin/trx/transactionBuilder/contractCallBuilder.ts
yarn.lock

We add outputs and inputs on Tron implementation to complement STLX-1601 implementation ( contract calls implementation )
This includes
- define new interfaces extended from Entry
- new UT and complement others 
Also we have refactor to avoid repeated code between TransactionBuilder.ts and ContractCallBuilder.ts
Ticket related : [STLX-3](https://bitgoinc.atlassian.net/browse/STLX-3)

feat(trx account-lib): Trx outputs and inputs changes

---

modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts

Manually set owners and target arguments from deploy to TX JSON before return stringified transaction.
Jira Ticket: [STLX-1902](https://bitgoinc.atlassian.net/browse/STLX-1902)

fix(account-lib): STLX-1902 Fixed toBroadcastFormat method

---

modules/account-lib/package.json
yarn.lock

[JIRA - BG-29930)](https://bitgoinc.atlassian.net/browse/BG-29930)
Details of the issue are in ticket

fix(account-lib): BG-29930 Update and pin hashgraph sdk version

---

modules/bls-dkg/.gitignore
modules/bls-dkg/index.js
modules/bls-dkg/package.json
modules/bls-dkg/test/bls-dkg.js

feat(modules/bls-dkg): add BLS-DKG module needed for SDK key generation and HSM testing

---

modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transactionBuilder.ts

Set signature on transaction deploy
Ticket: STLX-2076

fix(account-lib): fix addSignature method of cspr transaction

---

modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transactionBuilder.ts

Set signatures on txBuilder deploy only once per call to the build() method
Depends on: #1047 
Ticket: STLX-2077

fix(account-lib): fix processSigning method of cspr transactionBuilder

---

modules/core/package.json
modules/core/src/errors.ts
modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

Implement  SignTransaction and SignMessage for Casper and unit tests
This depends on #1046 (Merged)
[STLX-676](https://bitgoinc.atlassian.net/browse/STLX-676)

feat(core): sign functions for casper

---

modules/account-lib/src/coin/eth/transactionBuilder.ts
modules/account-lib/src/coin/eth/utils.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/contractCall.ts

feat(eth): build contract call transactions

---

commitlint.config.js

fix(ci): ignore merge commits when checking commit messages

---

modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

Implementing explainTransaction method for Casper, unitests were added for the implemented method.
Jira Ticket: [STLX-677](https://bitgoinc.atlassian.net/browse/STLX-677)
- explainTransaction method implementation
- unitests for explainTransaction

feat(core): implement explain transaction method for Casper

---

modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transactionBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilderFactory.ts

Jira Ticket: [STLX-2031](https://bitgoinc.atlassian.net/browse/STLX-2031)

feat(account-lib): STLX-2031 Refactor to control over minimum transfer amount value

---

modules/core/src/v2/coins/hbar.ts
modules/core/test/v2/unit/coins/hbar.ts

fix(hbar): send the message signatures in hex instead of buffer

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/cspr/util.ts
modules/core/test/v2/unit/coins/cspr.ts

add method to verify msg and tx signatures
Jira ticket: https://bitgoinc.atlassian.net/browse/STLX-2048

feat(account-lib): add verifySignature Method

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add new token

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/resources/cspr/cspr.ts

[STLX-2313](https://bitgoinc.atlassian.net/browse/STLX-2313)

fix(account-lib): STLX-2313 Fix getAccountHash utils method

---

modules/account-lib/src/coin/cspr/transaction.ts

Jira Tickets: 
[STLX-2335](https://bitgoinc.atlassian.net/browse/STLX-2335)
[STLX-661](https://bitgoinc.atlassian.net/browse/STLX-661)

fix(account-lib): STLX-661 Fix Typo when accessing JSON field

---

modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilderFactory.ts

Rremoved async from sign and processSigning methods and improved jsdoc in loadPreviousSignatures method
[STLX-1798](https://bitgoinc.atlassian.net/browse/STLX-1798)

feat(account-lib): STLX-1798 Remove asynchronicity from some methods

---

modules/core/package.json
modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

update ut and add isValidAddress method
[STLX-2378](https://bitgoinc.atlassian.net/browse/STLX-2378)

feat(core): refactor casper address format

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

Add WETH and WBTC on Tron network
[stlx-2263](https://bitgoinc.atlassian.net/browse/STLX-2263)

feat(statics): add WETH and WBTC on tron

---

modules/core/package.json
yarn.lock

feat(core): add support for node 12, 14, 15

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add new param "requiesReserve" to all coins (only true for Casper)
[STLX-2337](https://bitgoinc.atlassian.net/browse/STLX-2337)

feat(statics): add requires reserve

---

modules/account-lib/src/coin/stx/contractBuilder.ts
modules/account-lib/src/coin/stx/iface.ts
modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/src/coin/stx/transactionBuilderFactory.ts
modules/account-lib/src/coin/stx/transferBuilder.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/contractBuilder.ts
yarn.lock

This PR adds from public key in stx contract builder. It also fixes memo issue in transfer builder. Memo was not being set in the builder from serialized tx.
cc @wesgraham

stacks: add from publicKey in contract buidler

---

modules/account-lib/package.json
modules/account-lib/src/coin/xtz/keyPair.ts
yarn.lock

chore: use new blake2b packages

---

modules/blake2b/index.js

chore: use @bitgo-prefixed blake2b-wasm in @bitgo/blake2b

---

modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

Use params.txHex instead of params.txJson in CSPR signTransaction method
Ticket: STLX-2555

fix(core): fix txPrebuild param in CSPR signTransaction method

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
yarn.lock

Update casper sdk version from v1.0.29 to v1.0.39
[STLX-2653](https://bitgoinc.atlassian.net/browse/STLX-2653)

feat(account-lib): update casper sdk version

---

modules/core/src/v2/coins/stx.ts
modules/core/test/v2/unit/coins/stx.ts

This checks if the given address is valid, and if it is one of the supported address versions (SingleSig or MultiSig on Mainnet or Testnet).

core: implement verifyAddress for stx

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

erc20 token support
https://bitgoinc.atlassian.net/browse/STLX-2758
New tokens added to coins.ts and base.ts:
HCN
HDO

feat(statics): eRC20 Token Support

---

modules/core/src/v2/coins/cspr.ts

feat(core): implement parseTransaction for CSPR

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilder.ts
modules/account-lib/src/coin/cspr/constants.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts

Set chain name based on the environment of the coin
Ticket: STLX-3016

fix(account-lib): fix chain name used in CSPR transactions

---

modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transactionBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/cspr/util.ts

Fix validation for CSPR addresses of ed25519 keys
Ticket: STLX-3021

fix(account-lib): fix CSPR address validation

---

modules/account-lib/src/coin/trx/utils.ts
modules/account-lib/test/unit/coin/trx/util.ts
modules/core/src/v2/coins/trx.ts

Change core to receive tx data parameter and change utils to receive hexs with 0x
This change is needed in order to complete : 
https://bitgoinc.atlassian.net/browse/STLX-3208

feat(core & account-lib): adapt tron to receive data for a contract call

---

modules/core/package.json
modules/core/src/v2/coins/trx.ts

fix(trx): asign trx builder acording to each transaction type

---

modules/statics/src/networks.ts

Changing on account and explorer URLs for CSPR
STLX-1657
https://bitgoinc.atlassian.net/browse/STLX-1657

feat(cspr): update CSPR explorer URLs

---

modules/account-lib/src/coin/algo/assetTransferBuilder.ts
modules/account-lib/src/coin/algo/index.ts
modules/account-lib/src/coin/algo/keyPair.ts
modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/src/coin/algo/transactionBuilderFactory.ts
modules/account-lib/src/coin/algo/transferBuilder.ts
modules/account-lib/src/coin/baseCoin/index.ts

Adds the skeleton implementation for onboarding Algorand to account lib.
Epic: [BG-31382](https://bitgoinc.atlassian.net/browse/BG-31382)

feat(account-lib) add skeleton implementation for Algorand

---

modules/account-lib/src/coin/algo/errors.ts
modules/account-lib/src/coin/algo/index.ts
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/test/resources/algo/index.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts
yarn.lock

Sets base attributes required for algo transaction and add validations checks
ticket: [BG-31556](https://bitgoinc.atlassian.net/browse/BG-31677)

feat(account-lib): add setters for algo txn builder

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts

This change can sometimes trigger a bug
Issue: BG-30090

Revert "allow disabling paygo outputs during utxo tx verification"

---

modules/core/src/v2/coins/stx.ts
modules/core/test/v2/unit/coins/stx.ts

stacks: add multisig support in signtransaction of core

---

modules/utxo-lib/README.md

feat(utxo-lib): use new package name and new external links

---

modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts

- Adds the flat fee option
- Adds the algosdk suggested parameters getter for convenience. 
ticket: BG-31556

Add suggested params to account lib for algo

---

modules/core/src/v2/wallet.ts

Added stakingOptions to the parameters whitelist in v2/wallet.ts
[stlx-3329](https://bitgoinc.atlassian.net/browse/STLX-3329)

refactor(core): update buildTx in Core

---

modules/core/src/v2/baseCoin.ts

Re-export accountLib imported transaction types
[stlx-3452](https://bitgoinc.atlassian.net/browse/STLX-3452)

feat(core): export tx Enum Type from core

---

modules/core/src/v2/coins/stx.ts
modules/core/test/v2/unit/coins/stx.ts

fix(core): stacks changed prv param type in StxSignTransactionOptions

---

modules/statics/src/coins.ts

In order to test Tron BitGo wallets, new test contract address has been created
Story related : [STLX-2796](https://bitgoinc.atlassian.net/browse/STLX-2796)
Task related : [STLX-2899](https://bitgoinc.atlassian.net/browse/STLX-2899)

feat(statics): update contract addresses

---

modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/test/unit/coin/algo/transaction.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/transferBuilder.ts

test(account-lib): algo payment tx from raw signed

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add new covalent token support

feat: add new token

---

package.json
yarn.lock

See https://www.npmjs.com/advisories/1755
Ticket: BG-32908

chore(root): add resolution for normalize-url@^6.0.1

---

modules/account-lib/src/coin/algo/index.ts
modules/account-lib/src/coin/algo/keyExclusionBuilder.ts
modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/baseCoin/enum.ts

keyreg type changed to wallet initialization

---

modules/statics/src/coins.ts

fix GDT contract
https://bitgoinc.atlassian.net/browse/STLX-3561
Fix GDT contract

fix(statics): fix GDT contract

---

modules/core/src/v2/wallet.ts

fix(core): correct typo when address parameter is missing

---

modules/core/src/bitgo.ts

Include request method in auth v3

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add wec token
https://bitgoinc.atlassian.net/browse/STLX-4228
New token added to coins.ts and base.ts: WEC
Change to lower case the address

feat(statics): add wec token

---

modules/account-lib/src/coin/algo/utils.ts

add estimate size for Algorand
[STLX-4476](https://bitgoinc.atlassian.net/browse/STLX-4476)

feat(account-lib): add estimate size

---

modules/account-lib/src/coin/algo/utils.ts

Revert "feat(account-lib): add estimate size"

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/keyRegistrationBuilder.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/transferBuilder.ts

add genesisID and genesisHash to Json() in transaction.ts and ifaces.ts
[STLX-4475](https://bitgoinc.atlassian.net/browse/STLX-4475)
Unitest updated

feat(account-lib): add genesisID and genesisHash to toJson()

---

modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

added Algo encodeObj support on account lib
STLX-4477

feat(account-lib): added Algo encodeObj support on account lib

---

modules/account-lib/src/coin/trx/contractCallBuilder.ts

change trx fee limit upper boundary, from 1000TRX to 5000TRX
stlx-4309

fix(account-lib)[STLX-4309]:  fix trx fee limit boundary

---

modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/contractBuilder.ts

fix(account-lib): add input/output in stx contract call

---

modules/account-lib/src/coin/algo/txnSchema.ts

feat(account-lib): algo key dilution fix

---

modules/utxo-lib/package.json
modules/utxo-lib/src/coins.js
modules/utxo-lib/src/networks.js
modules/utxo-lib/test/networks.js

* add `bitcoingoldTestnet`
References:
* bech32: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/chainparams.cpp#L332
* bip32: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/chainparams.cpp#L329
* pubKeyHash: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/chainparams.cpp#L326
* scriptHash: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/chainparams.cpp#L327
* wif: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/chainparams.cpp#L328
* forkId: https://github.com/BTCGPU/BTCGPU/blob/163928af05b09a20efe330157fd0dc8a5211e286/src/script/interpreter.h#L35
Issue: BG-34052

feat(utxolib): add bitcoingoldTestnet

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add NPXS Token again
stlx-4673

feat(statics): add NPXS Token again

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/transaction.ts

add close remainder to
[STLX-3878](https://bitgoinc.atlassian.net/browse/STLX-3878)

feat(account-lib): add close remainder to

---

modules/statics/src/coins.ts

related: https://github.com/BitGo/BitGoJS/pull/1302
ticket: BG-34227

fix(statics): remove duplicate tokens

---

modules/core/src/api.ts
modules/core/src/bitgo.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/btc.ts
modules/core/src/v2/coins/dash.ts
modules/core/src/v2/coins/ltc.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/zec.ts
modules/core/test/unit/wallet.ts
types/superagent/index.d.ts

* Move API functions from `bitgo` to `api`
* remove `superagent.Request.prototype.result` monkeypatch and move to
`BitGoRequest`
* Fix usages of monkeypatched superagent method to use `toBitGoResponse`
instead
* Add prettier to some touched files and clean up formatting errors
Ticket: BG-31214

fix(core): follow up improvements from PR #1292

---

modules/account-lib/src/coin/algo/assetTransferBuilder.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts

increase coverage and provide disable tokens funcionality
[STLX-3878](https://bitgoinc.atlassian.net/browse/STLX-3878)

feat(accountlib): add closeremaindeto and unit tests

---

modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/resources/algo/index.ts
modules/account-lib/test/unit/coin/algo/utils.ts

Move buildFeeInfo logic to account-lib.
[STLX-4754](https://bitgoinc.atlassian.net/browse/STLX-4754)

STLX-4754 build fee info migration

---

modules/core/src/config.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/algoToken.ts
modules/core/src/v2/coins/index.ts
modules/statics/src/index.ts

added algo token config on core
stlx-4986

feat(core): added algo token config on core

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/wallet.ts

allowed amount 0 on recipients for enable token
stlx-5021

feat(core): allowed amount 0 on recipients for enable token

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

add encodeAddress in account-lib and unit test
STLX-4525

feat(account-lib): add encodeAddress in account-lib and unit test

---

modules/core/src/v2/coins/trx.ts
modules/core/src/v2/wallet.ts

stlx-4309
- add feeLimit parameter to Send Options on core

feat(core): [STLX-4305] add feeLimit parameter to Send options

---

modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

adding multisigAddress
STLX-4563

feat(account lib): adding multisigAddress

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

add method generateAccount() in account-lib
STLX-4522

feat(account-lib): add method generateAccount() in account-lib

---

modules/account-lib/package.json
modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/src/coin/algo/transactionBuilderFactory.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts

[BG-34606](https://bitgoinc.atlassian.net/browse/BG-34606)
Updates to support migration of following transaction types:
1. Native transfers
2. Enable/Disable token
3. Token transfers
4. Keyreg transactions
5. Non-participating keyreg transactiosn

feat(algo): misc updates for platform migration to use account lib

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

implementation of generateAccoutn() in account-lib
STLX-5112

feat(account-lib): implementation of generateAccount() in account-lib

---

modules/account-lib/src/coin/stx/keyPair.ts
modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts

fix(account-lib): stx get signatures to return only signatures

---

modules/core/test/v2/unit/coins/ltc.ts

We can use plain utxolib for this
Issue: BG-25653

chore(core): remove prova-lib usage from ltc

---

modules/core/test/v2/unit/keychains.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Add support for AVAX on the C-Chain as AVAXC
CLOSES TICKET: STLX-5084

feat(statics): add AVAXC coin to statics

---

modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts

update verification methods
STLX-4593

feat(account-lib): update verification methods

---

modules/core/src/v2/coins/trx.ts

Make method name reflect the actual implementation

fix(core): fix method name to TRX.xpubToUncompressedPub

---

modules/express/.eslintignore
modules/express/package.json
modules/express/test/integration/bitgoExpress.ts
modules/express/test/integration/bitgoExpressV1.ts
modules/express/test/lib/asserts.ts
modules/express/test/lib/test_bitgo.ts
modules/express/test/lib/testutil.ts
modules/express/test/unit/bitgoExpress.ts

chore(express): run `eslint --fix` on .

---

modules/core/src/transactionBuilder.ts

refactor(core): fix eslint issues

---

modules/core/src/bitgo.ts

Prior to v12, we always called `handleResponseResult()` on the value returned
from the result of the call to platform, whether it was a v1 or v2 request.
After a bad refactor in v12, `handleResponseResult()` was no longer called when
using v1 auth. This broke callers who relied on this behavior for v1.
Instead, call `handleResponseResult()` on both return paths.
Additionally, add in some debug lines which were helpful in diagnosing this
issue.
Ticket: BG-34772

fix(core): fix regression in `addAccessToken` when using v1 auth

---

modules/account-lib/package.json
modules/account-lib/src/coin/avaxc/index.ts
modules/account-lib/src/coin/avaxc/keyPair.ts
modules/account-lib/src/coin/avaxc/resources.ts
modules/account-lib/src/coin/avaxc/transactionBuilder.ts
modules/account-lib/src/coin/avaxc/transferBuilder.ts
modules/account-lib/src/coin/avaxc/utils.ts
modules/account-lib/src/index.ts
modules/account-lib/test/unit/coin/avaxc/transaction.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/send.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/walletInitializationBuilder.ts
modules/core/package.json
modules/statics/package.json

feat(account-lib): skeleton code for avalanche c-chain in account-lib

---

modules/core/src/bitgo.ts
modules/core/src/keychains.ts
modules/core/src/transactionBuilder.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/erc20Token.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/ofc.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/coins/xtz.ts
modules/core/src/wallet.ts
modules/core/test/v2/unit/coins/eth.ts
modules/core/test/v2/unit/ethWallet.ts

refactor(core): use bip32 in more places

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/coins/trx.ts

fix prebuild transaction for tron contractCalls. Pending approvals weren't saving fee limit.
stlx-4989

fix(core):[STLX-4989] fix prebuild transaction for tron contractCalls

---

modules/account-lib/test/unit/coin/algo/utils.ts

add test unit getTrasactionByteSize
STLX-5491

feat(account-lib): add test unit getTrasactionByteSize

---

modules/express/src/clientRoutes.ts

fix(express): do not access `_promise`

---

modules/account-lib/src/coin/algo/assetTransferBuilder.ts
modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/keyPair.ts
modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/src/coin/algo/transferBuilder.ts
modules/account-lib/src/coin/algo/txnSchema.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/src/coin/baseCoin/ed25519KeyPair.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts

rebase account-lib in the bitgoJs and fixing errors
STLX-5609

feat(account-lib): rebase account-lib in the bitgoJs and fixing errors

---

modules/core/src/v2/coins/xrp.ts
modules/core/test/v2/integration/coins/xrp.ts

chore(core): use bip32 in xrp.ts

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

chore(core): use bip32 in eos

---

modules/core/test/v2/unit/coins/abstractEthCoin.ts

chore(core): use bip32 package in abstractEthCoin tests

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

chore(core): use bip32 in abstractUtxoCoin

---

modules/core/test/v2/unit/coins/ltc.ts

chore(core): use bip32 in ltc tests

---

modules/account-lib/src/coin/avaxc/utils.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/transfer.ts
modules/account-lib/test/unit/coin/avaxc/util.ts

[STLX-5148](https://bitgoinc.atlassian.net/browse/STLX-5148)

test(account-lib): Add Unit Test for AvaxC

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/avaxc.ts
modules/core/src/v2/coins/index.ts
modules/core/src/v2/coins/tavaxc.ts
modules/core/test/v2/unit/coins/avaxc.ts

[STLX-5265](https://bitgoinc.atlassian.net/browse/STLX-5265).

feat(core): Add support for Avalanche C-Chain

---

modules/core/src/v2/baseCoin.ts
modules/core/test/v2/integration/markets.ts
modules/statics/src/base.ts

chore: remove last mentions of rmg

---

modules/core/src/v2/coins/stx.ts

feat: add parseTransaction to stx

---

modules/account-lib/src/coin/avaxc/walletUtil.ts

Add AvaxWalletSimple.sol ABI to walletUtil.ts
JIRA Ticket: https://bitgoinc.atlassian.net/browse/STLX-5726
Changes:
Add AvaxWalletSimple.sol ABI to walletUtil.ts

feat(account-lib): Add AvaxWalletSimple.sol ABI to walletUtil.ts

---

modules/account-lib/src/coin/avaxc/walletUtil.ts

fix(account-lib): fix lint errors

---

modules/utxo-lib/test/integration_local_rpc/parse.ts
modules/utxo-lib/test/transaction_util.ts

feat(utxo-lib): test createTransactionBuilderFromTransaction

---

modules/core/test/browser/browser.spec.ts

[STLX-6514](https://bitgoinc.atlassian.net/browse/STLX-6514)

Stlx 6514 Fix browser tests

---

modules/utxo-lib/src/transaction.js

Reduce indentation
ce24cc8ef
refactor(utxo-lib): only support transparent inputs

refactor(utxo-lib): simplify hashForZcashSignature

---

modules/core/src/v2/internal/util.ts
modules/core/test/v2/unit/internal.ts

c8713ab1a
chore(test): add test xpubToEthAddress
Issue: BG-35804

fix(core): fix xpubToEthAddress

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

Previous code was needlessly elaborate

refactor(core): use standard sign call in v2 AbstractUtxoCoin

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/index.ts

feat(eos): add eos token support

---

modules/core/src/v2/wallet.ts

Jira Ticket : https://bitgoinc.atlassian.net/browse/BG-35555

feat(wp) : added support of cashaddr for create address using SDK

---

modules/statics/src/networks.ts

fix(tdash): fix incorrect explorerUrl for tdash

---

modules/express/src/expressApp.ts

https://bitgoinc.atlassian.net/browse/BG-35263
From Jira ticket regex will now match on any `/api` prefix

refactor: modify path regex for Bitgo Express proxy

---

.drone.jsonnet
README.md

chore: remove node 10 from list of supported versions

---

modules/core/src/legacyBitcoin.ts
modules/core/test/unit/legacyBitcoin.ts

feat(core): add toBase58Check to legacyBitcoin

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts

Jira Ticket : https://bitgoinc.atlassian.net/browse/BG-35557

feat(core) : added support for send on cashaddr

---

modules/account-lib/src/coin/eth/transaction.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/walletInitialization.ts

Eth transaction sign is missing update tx id. 
STLX-6667

feat(account-lib): transation hash is calclated wrongly

---

.drone.jsonnet
yarn.lock

chore(root): update yarn.lock, use --with-frozen-lockfile in drone

---

modules/core/package.json
yarn.lock

chore(core): bump superagent-proxy dep

---

modules/account-lib/src/coin/trx/contractCallBuilder.ts
modules/account-lib/test/unit/coin/trx/transactionBuilder/contractCallBuilder.ts

get trx fee limit from statics
Jira Ticket:
https://bitgoinc.atlassian.net/browse/STLX-6526

feat(account lib): Get trx fee limit from statics

---

.drone.yml
modules/utxo-lib/package.json
modules/utxo-lib/src/bitgo/UtxoTransactionBuilder.ts
yarn.lock

Fix nonstandard `Signer` import
Issue: BG-36608

chore(utxo-lib): depend on @bitgo/bitcoinjs-lib@6.0.0

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore(statics): update eos testnet tokens

---

modules/core/src/config.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/eosToken.ts
modules/core/src/v2/coins/index.ts
modules/core/test/browser/browser.spec.ts
modules/core/test/v2/unit/coins/eosToken.ts

feat(core): eos token configuration

---

modules/account-lib/src/coin/celo/transactionBuilder.ts
modules/account-lib/src/coin/eth/transactionBuilder.ts
modules/account-lib/src/coin/eth/types.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/transfer.ts
modules/account-lib/test/unit/coin/avaxc/transactionBuilder/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/avaxc/util.ts
modules/account-lib/test/unit/coin/celo/transactionBuilder/send.ts
modules/account-lib/test/unit/coin/celo/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/etc/transactionBuilder/send.ts
modules/account-lib/test/unit/coin/etc/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/contractCall.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/flushCoins.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/flushTokens.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/singleSigSend.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/walletInitialization.ts
modules/account-lib/test/unit/coin/rbtc/transactionBuilder/send.ts
modules/account-lib/test/unit/coin/rbtc/transactionBuilder/walletInitialization.ts

Add v field value in half sign and no sign transaction
STLX-6757

feat(account-lib): update eth behavior require by hsm3

---

modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/eosutil/abis.ts
modules/core/src/v2/coins/eosutil/boxAbi.json
modules/core/src/v2/coins/eosutil/chexAbi.json
modules/core/src/v2/coins/eosutil/eosioAbi.json
modules/core/src/v2/coins/eosutil/eosioNullAbi.json
modules/core/src/v2/coins/eosutil/eosioTokenAbi.json
modules/core/src/v2/coins/eosutil/iqAbi.json
modules/core/src/v2/coins/eosutil/testChexAbi.json
modules/core/src/v2/coins/eosutil/testIqAbi.json
modules/core/src/v2/coins/eosutil/usdtAbi.json
modules/core/test/v2/fixtures/coins/eos.ts
modules/core/test/v2/integration/coins/eos.ts

Supported tokens:
- BOX
- CHEX
- IQ
- USDT
Ticket: https://bitgoinc.atlassian.net/browse/STLX-6004
Testing done:
- added integration tests to explain transactions for CHEX token and native EOS.

feat(eos-tokens): update explain transaction to support EOS tokens

---

modules/account-lib/package.json
modules/core/package.json
yarn.lock

[STLX-7674](https://bitgoinc.atlassian.net/browse/STLX-7674)

feat(bitgojs): Update algosdk to last stable version

---

modules/core/test/v2/unit/coins/eosToken.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add eos mainnet token config and prefix token 

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add imxv2 token

---

modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/src/bitgo/types.ts
modules/utxo-lib/test/integration_local_rpc/generate/outputScripts.util.ts
modules/utxo-lib/test/integration_local_rpc/generate/types.ts
modules/utxo-lib/test/transaction_util.ts

refactor(utxo-lib): use Buffer[] in createTaprootScript2Of3

---

modules/account-lib/package.json
modules/core/package.json
modules/core/src/v2/coins/xlm.ts
yarn.lock

Update stellar sdk in core and account-lib to v9.0.1
Remove deprecated stellar-sdk types from core
Ticket: BG-38032

chore(core/account-lib): update stellar sdk

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Added Mainnet and testnet for Solana in networks.ts   
Added sol and tsol with REQUIRE_RESERVE feature in coins.ts   
Added sol to Underlaying assets and coinFamily in base.ts   
Added SolCoin with tokenAddress param and factory functions for sol and tsol tokens in account.ts
[stlx-8229](https://bitgoinc.atlassian.net/browse/STLX-8229)

feat(statics): define coin sol in statics

---

modules/statics/src/networks.ts

fix(xrp): fix incorrect explorerUrl for txrp

---

modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/transaction.ts
modules/account-lib/test/unit/coin/algo/utils.ts
modules/core/src/v2/coins/algo.ts

addition txType on account-lib
STLX-7611

feat(account-lib): addition txType on account-lib

---

modules/core/src/v2/wallet.ts

fix(xrp): incorrect types for ledgerSequenceDelta

---

modules/core/package.json
modules/core/src/errors.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/utxo/recover.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
yarn.lock

feat: add support for generating p2tr addresses

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

Create wallet with eip1559 fee params
bg-38441

feat(core): create wallet with eip1559

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

It broke with the double-signing workaround for p2tr

fix(core): repair replay protection input signing

---

modules/core/package.json
modules/unspents/package.json
modules/utxo-lib/package.json

fix(unspents): use latest rc as version instead of 2.3.0

---

modules/core/src/v2/coins/btc.ts
modules/core/src/v2/wallet.ts

fix(core): Load all needed keychains for taproot/algo signing

---

modules/account-lib/src/coin/dot/index.ts
modules/account-lib/src/coin/dot/keyPair.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/transactionBuilderFactory.ts
modules/account-lib/src/coin/dot/transferBuilder.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/src/coin/dot/walletInitializationBuilder.ts

@argjv @rliberal-simtlix @fdmirza @nimraarif21 
Issue: https://github.com/BitGo/BitGoJS/issues/1587

feat(account-lib): initial setup

---

modules/account-lib/package.json
modules/utxo-lib/package.json
yarn.lock

chore(utxo-lib): update to `@bitgo/bitcoinjs-lib@6.1.0-rc.2`

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/index.ts
modules/core/src/v2/coins/sol.ts
modules/core/src/v2/coins/tsol.ts
modules/core/test/v2/unit/coins/sol.ts
modules/statics/src/coins.ts

Added core skeleton for solana   
Uncommented accounts for solana in account-lib coins
[stlx-8776](https://bitgoinc.atlassian.net/browse/STLX-8776)

feat(core): add core skeleton for solana

---

modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts
modules/core/test/v2/fixtures/coins/stx.ts
modules/core/test/v2/unit/coins/stx.ts

- Add unpadMemo utils function
- Remove padMemo
- Adapts unit test
[STLX-9372](https://bitgoinc.atlassian.net/browse/STLX-9372)

feat(stx): Fix memo encoding for STX

---

modules/account-lib/package.json
modules/utxo-lib/package.json
yarn.lock

chore: update to `@bitgo/bitcoinjs-lib@6.1.0-rc.3`

---

.github/workflows/ci.yml
README.md

chore(node) update node version

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts
modules/statics/test/unit/coins.ts

@argjv @rliberal-simtlix @fdmirza @nimraarif21

feat(statics): dot statics setup

---

modules/account-lib/package.json
modules/account-lib/src/coin/sol/index.ts
modules/account-lib/src/coin/sol/keyPair.ts
modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/src/coin/sol/transactionBuilder.ts
modules/account-lib/src/coin/sol/transactionBuilderFactory.ts
modules/account-lib/src/coin/sol/transferBuilder.ts
modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/src/coin/sol/walletInitializationBuilder.ts
modules/account-lib/src/index.ts
modules/core/src/v2/coins/sol.ts

added skeleton for solana and solaka sdk
[stlx-8761](https://bitgoinc.atlassian.net/browse/STLX-8761)

feat(account-lib): add skeleton for solana

---

modules/account-lib/package.json
modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/test/resources/sol/sol.ts
modules/account-lib/test/unit/coin/sol/utils.ts

Implemented basic util methods for solana 
Added Unit tests
[stlx-8766](https://bitgoinc.atlassian.net/browse/STLX-8766)

feat(account-lib): implement basic util methods for solana

---

modules/statics/src/networks.ts

fix(tltc): update block explorer link for tltc

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/consolidateAccount.ts

fix(express): enable tezos consolidations route in express

---

modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/xlm.ts

Add validation for xlm muxed addresses
TICKET: BG-39117

feat(core): add send support for XLM muxed addresses

---

modules/account-lib/src/coin/dot/errors.ts
modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transaction.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/stakingBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unstakeBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/walletInitializationBuilder.ts

feat(account-lib): dot final review fixes

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/util.ts

Fixed isValidHex method to support upperCase letters  
Added unit tests
[stlx-9862](https://bitgoinc.atlassian.net/browse/STLX-9862)

fix(account-lib): fix CSPR address validation for encoding change

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/wallet.ts

We had a cyclical dependency:
`v2/baseCoin -> v2/wallet -> v2/abstractUtxoCoin -> v2/baseCoin`
Remove dependency from v2/wallet to v2/abstractUtxoCoin.

fix(core): break cyclical dependency

---

modules/core/src/v2/coins/dot.ts

@argjv @jrafael-simtlix @rliberal-simtlix @nimraarif21 @fdmirza

feat(core): dot core helpers

---

modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/test/unit/coin/sol/transaction.ts

previously, this would always return empty.
Ticket: STLX-10065

fix(sol): get signature data from a Sol transaction

---

modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/index.ts
modules/account-lib/src/coin/dot/stakingBuilder.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/transactionBuilderFactory.ts
modules/account-lib/src/coin/dot/transferBuilder.ts
modules/account-lib/src/coin/dot/txnSchema.ts
modules/account-lib/src/coin/dot/unstakeBuilder.ts
modules/account-lib/src/coin/dot/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts

@argjv @rliberal-simtlix @jrafael-simtlix @fdmirza

feat(account-lib): dot optimization

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/dot.ts
modules/core/src/v2/coins/tdot.ts
modules/core/test/v2/fixtures/coins/dot.ts
modules/core/test/v2/unit/coins/dot.ts

@argjv @rliberal-simtlix @jrafael-simtlix @nimraarif21 @fdmirza

feat(core): dot sign transaction

---

modules/account-lib/src/coin/algo/utils.ts

Issues: STLX-9929
Buffer were used in several places were an Uint8Array is expected. ALGO were using Uint8Array so when migrated to TS type errors were found.
Also some typos in comments were fixed.
One function was refactored a little to avoid duplicating the decoding.

fix(account-lib): fix types and overrestricted types

---

modules/statics/src/networks.ts
modules/statics/test/unit/coins.ts
modules/statics/test/unit/networks.ts

Issue: BG-39753
127421659
test(statics): tests for `coin.network.type`
Issue: BG-39753

fix(statics): inherit BitcoinTestnet from Testnet

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

implement signTransaction, isValidPub, isValidPrv, verifyAddress and generateKeyPair methods and
test
STLX-8786

feat(core): implement transaction signing methods

---

modules/statics/src/networks.ts

fix(ltc): update block explorer link for ltc

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/utxo/transaction.ts

fix(core): implement explainTransaction for p2tr

---

modules/core/src/v2/coins/utxo/WalletKeys.ts

docs(test): improve WalletKeys documentation

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

implement message signing
stlx_8108

feat(core): implement message signing

---

modules/account-lib/package.json
yarn.lock

chore: update polkadot keyring version

---

modules/core/src/v2/wallet.ts

chore(core): add missing idf params to `PrebuildTransactionOptions`

---

modules/account-lib/src/coin/baseCoin/baseTransaction.ts
modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/test/resources/dot/index.ts
modules/account-lib/test/unit/coin/dot/transaction.ts

@argjv @jrafael-simtlix @rliberal-simtlix @nimraarif21 @fdmirza

feat(account-lib): dot explain transaction

---

modules/statics/src/coins.ts

feat(statics): fix BXX address

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Ticket: STLX-10451
Onboarding BXXV1 to track the old BXX token for audit purpose after updating BXX.

feat: BXXV1 token onboarding

---

modules/core/src/v2/coins/dot.ts
modules/core/test/v2/unit/coins/dot.ts

feat(dot): implement signMessage

---

modules/core/src/bitgo.ts
modules/core/src/common.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/avaxc.ts
modules/core/src/v2/coins/dot.ts
modules/core/src/v2/coins/susd.ts
modules/core/src/v2/enterprise.ts
modules/core/src/v2/types.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/unit/bitgo.ts
modules/core/test/unit/keychains.ts
modules/core/test/unit/wallet.ts
modules/core/test/v2/integration/coins/eth.ts
modules/core/test/v2/integration/wallet.ts
modules/core/test/v2/unit/coins/dot.ts
modules/core/test/v2/unit/coins/token.ts
modules/core/test/v2/unit/coins/xlm.ts
modules/core/test/v2/unit/coins/xrp.ts
modules/core/test/v2/unit/enterprise.ts
modules/core/test/v2/unit/ethWallet.ts
modules/core/test/v2/unit/keychains.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts
modules/core/test/v2/unit/trading/tradingAccount.ts
modules/core/test/v2/unit/trading/tradingPartner.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts
yarn.lock

More removal of coroutines from unit test code and remaining implementation code (and hopefully the coroutine cleanup needed until we refurbish and reactivate the integration tests).
Ticket: BG-31214

Remove more coroutines

---

modules/account-lib/package.json
modules/core/package.json
modules/core/src/v2/coins/utxo/recovery/backupKeyRecovery.ts
tsconfig.json

For our node deployments this should not be an issue, since require Node 12 anyway.
The remaining question is browser support, which looks good for the 
features we care about:
Support: https://caniuse.com/?search=es2019
Issue: BG-40313

chore(root): target ES2019

---

commitlint.config.js

chore(root): restrict commit scopes to module names and `root`

---

modules/statics/src/networks.ts

Ticket: BG-31613 https://bitgoinc.atlassian.net/browse/BG-31613
Changed BitgoJs Batcher Contract Address to the one which is used in wallet platform.
https://github.com/BitGo/bitgo-microservices/blob/980e26f469ec20d418584408d865f05d8b161772/packages/wallet-platform/config/env/defaults.ts#L5374
This allows to send eth to multiple recipients in a single transaction.

refactor(statics): change batcherContractAddr

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/utxo/recovery/backupKeyRecovery.ts
modules/core/src/wallet.ts
modules/core/test/v2/unit/coins/utxo/address.ts
modules/unspents/README.md
modules/unspents/src/codes.ts
modules/unspents/src/dimensions.ts
modules/unspents/src/index.ts
modules/unspents/test/dimensions.ts

Please use https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/src/bitgo/wallet/chains.ts instead.

refactor(unspents): deprecate `Codes`

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/index.ts

add arc20token and implementation
STLX-9140

feat(static): add arc20token and implementation

---

modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts

fix(account-lib): update validitiyWindow dot validation

---

modules/account-lib/src/coin/dot/transactionBuilder.ts

chore(account-lib): update validity js docs

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/utxo/transaction.ts

The public keys passed to `AbstractUtxoCoin`'s `explainTransaction`
function are used to count the number of valid signatures on a
transaction. However, this new param was added as a required param which
causes some existing usages of `explainTransaction` to break. Instead
this new param should be optional and if it's not provided, we'll just
be unable to count the number of signatures. The rest of the behavior of
`explainTransaction` should remain as it was prior to the breaking
change.`
Ticket: BG-40467

fix(core): don't require `pubs` param to `explainTransaction`

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/utxo/transaction.ts

fix(core): restore `async` on `explainTransaction` in `AbstractUtxoCoin`

---

modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts

chore(account-lib): capitalize ValidityWindow type

---

modules/account-lib/src/coin/dot/iface.ts

chore(account-lib): expose txn types for dot

---

modules/account-lib/src/coin/eth/transaction.ts
modules/account-lib/src/coin/eth/utils.ts
modules/account-lib/test/unit/coin/avaxc/transferBuilder.ts

Add unit test for send token in Avaxc
Eth getToken util add filter for network since Avaxc has same address in testnet and mainnet. 
STLX-9814

Stlx 9814 native token unit test

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

feat(core): enhanced address verification in sdk with optional request parameters forwarderVersion, baseAddress and allowSkipVerifyAddress flag for the createdAddress.
BG-39200

feat(core): enhanced address verification in sdk 

---

modules/utxo-lib/src/addressFormat.ts

docs(utxo-lib): improve docs for toOutputScriptAndFormat

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/ofc.ts
modules/statics/src/utxo.ts
modules/statics/test/unit/coins.ts

- all coins except XTZ support custody

feat(statics): CoinFeature Custody

---

modules/account-lib/src/coin/sol/index.ts

Export Solana builders and transaction
Jira ticket:
https://bitgoinc.atlassian.net/browse/STLX-11064

feat(account-lib): Export Solana builders and transaction

---

modules/account-lib/package.json
modules/account-lib/src/mpc/curves.ts
modules/account-lib/src/mpc/shamir.ts
modules/account-lib/src/mpc/tss.ts
modules/account-lib/test/unit/mpc/tss.ts

adds key generation/combine along with message signing/combine/verify
Closes: BG-39242, BG-38662, BG-39243, BG-39712

feat: add TSS key generation and signing functions

---

modules/statics/README.md

merged https://github.com/BitGo/BitGoJS/pull/1689
but missed typo

chore: fix statics README typescript typo

---

modules/statics/src/networks.ts

fix(xrp): update deprecated explorer url

---

modules/statics/src/networks.ts

Updates explorer url for BCH
Ticket: BG-40963

fix(statics): update deprecated explorer url for BCH

---

modules/account-lib/src/coin/baseCoin/ed25519KeyPair.ts
modules/account-lib/test/unit/coin/sol/keyPair.ts

performs SLIP-0010 hardened derivation using an existing key's private key as the
seed.
Ticket: STLX-11014

feat(sol): implement derive address function

---

modules/statics/src/coins.ts

update decimalPlaces from 18 to 6 for C8P Token
Link JIRA: https://bitgoinc.atlassian.net/browse/STLX-6706
stlx-7754

feat(c8p token): update decimal places

---

modules/statics/src/coins.ts

update decimal places for c8p token
stlx-7754

feat(statics): update decimal places for c8p token

---

modules/account-lib/src/coin/baseCoin/iface.ts
modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts

implement validityWindow and sequenceId for Sol
stlx-9890

feat(account-lib): implement validityWindow and sequenceId for Sol

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/coins/eth.ts

fix(eth): allow for ENS resolution in WP to change recipient address for

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

Jira link: https://bitgoinc.atlassian.net/browse/STLX-10202
implement verify transaction for solana

Stlx 10202 verify transaction

---

modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/test/resources/sol/sol.ts

Changed Public key validation for Solana, using Crypto library
[STLX-11696](https://bitgoinc.atlassian.net/browse/STLX-11696)

fix(account-lib): changed key validation for Solana

---

modules/account-lib/src/keyPair/index.ts
modules/account-lib/test/unit/keyPair/index.ts

feat(account-lib): extend dot key pair tests

---

modules/core/src/config.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/avaxcToken.ts
modules/core/src/v2/coins/index.ts
modules/core/test/browser/browser.spec.ts
modules/core/test/v2/unit/coins/avaxcToken.ts

Add AvaxcToken coins in sdk
Improve coinFactory to support repeated token contract addresses between Mainnet and Testnet.
STLX-10425

feat(core): add AvaxToken coins in sdk

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/coins/eth.ts

Ticket: BG-41173
I'm an idiot and flipped the txParams and the txPrebuild. This PR fixes that. Well, not the me being an idiot part, but the flipping
.

fix(core): fix ENS resolution for eth sends

---

modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

Ticket: CR-478 https://bitgoinc.atlassian.net/browse/CR-478
We have decided to remove signingKeyId for addWallet function

fix(core wallets): removed signingKey capability

---

modules/account-lib/src/utils/index.ts
modules/account-lib/test/unit/utils/index.ts

A factory method for the newly introduced coin utils interface. We may need plans to incrementally refactor the existing coins to the new structure.
Ticket: STLX-10816

feat(account-lib): add util factory for coins

---

modules/statics/src/networks.ts

fix(statics): update zcash explorer url

---

modules/account-lib/src/coin/dot/transactionBuilder.ts

fix(account-lib): update dot feeOption jsdoc

---

modules/account-lib/test/unit/coin/avaxc/transferBuilder.ts
modules/core/src/v2/coinFactory.ts
modules/core/test/v2/unit/coins/avaxcToken.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

update USDC.e and USDT.e token names and fix test tokens in static and address to support Chainlink
STLX-11940

feat(static): add LINK token, update USDC.e and USDT.e token names to USDC and USDT

---

modules/account-lib/webpack.config.js
modules/core/webpack.config.js

- webpack5 minified versions broke hbar, this applies previous TerserPlugin settings for minifying bundle
STLX-12065

fix(webpack): fix hbar webpack

---

modules/statics/src/coins.ts

wtk token contract update
[STLX-11989](https://bitgoinc.atlassian.net/browse/STLX-11989)

feat(statics): wtk token contract update

---

modules/core/src/v2/coins/dot.ts
modules/core/test/v2/unit/coins/dot.ts

feat(core): support signing single sig dot transactions

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

we were extracting blockhash and feePayer from the wrong property
Ticket: STLX-12390

fix(core): fix verify tx for solana

---

modules/statics/src/coins.ts

change name to gHDO and gHCN
stlx-6767

feat(statics): change name to gHDO and gHCN

---

modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/test/unit/coin/sol/utils.ts

Fix isValidPublicKey to check for undefined pubKey    
Added unit tests
STLX-12460

fix(account-lib): fix isValidPublicKey to check for undefined pubKey

---

modules/account-lib/src/coin/near/index.ts
modules/account-lib/src/coin/near/keyPair.ts
modules/account-lib/src/coin/near/transaction.ts
modules/account-lib/src/coin/near/transactionBuilder.ts
modules/account-lib/src/coin/near/transactionBuilderFactory.ts
modules/account-lib/src/coin/near/transferBuilder.ts
modules/account-lib/src/coin/near/utils.ts
modules/account-lib/src/coin/near/walletInitializationBuilder.ts

TICKET: [STLX-12272](https://bitgoinc.atlassian.net/browse/STLX-12272)

feat(account-lib): near coin skeleton

---

package.json
yarn.lock

fix(root): resolve `node-fetch` to version 2.6.7

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

add NEAR coin config
TICKET: [STLX-12265](https://bitgoinc.atlassian.net/browse/STLX-12265)

feat(statics): add NEAR coin config

---

modules/account-lib/package.json
modules/account-lib/webpack.config.js
modules/core/package.json
modules/core/webpack.config.js

removed buffer library and fallback from webpack config for account-lib and core
STLX-12277

fix(root): removed buffer library and fallback from webpack config for account-lib and core

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

Fixed verityTransaction for sol so it only compares amount and address from recipients and output
objects    
Added unit tests
STLX-12684

fix(core): fix verityTransaction for sol

---

modules/statics/.prettierignore
modules/statics/.prettierrc.yml
modules/statics/CODEOWNERS
modules/statics/README.md
modules/statics/package.json
modules/statics/test/unit/base.ts
modules/statics/test/unit/coins.ts
modules/statics/tsconfig.json

Bring IDE config in sync with `yarn` target
Issue: BG-41897

fix(statics): apply prettier to full project

---

modules/core/package.json

fix(core): add missing dep on `@bitgo/blockapis`

---

modules/core/example/js/update-wallet-forwarders.js
modules/core/example/ts/update-wallet-forwarders.ts
modules/core/src/v2/wallet.ts

Added method to update deployForwardersManually and flushForwardersManually of a wallet
Ticket: [BG-41444](https://bitgoinc.atlassian.net/browse/BG-41444)

feat(core): update forwarder flags

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/sol.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/coins/sol.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts

updated createAddress to perform hardened derivation and added unit test
updated generateWallets and added unit test
[STLX-12543](https://bitgoinc.atlassian.net/browse/STLX-12543)

feat(core): update createAddress to perform hardened derivation

---

package.json
yarn.lock

chore(root): resolve `simple-get` to `^4.0.1`

---

CODEOWNERS

fix(codeowners): update codeowners to remove previous staff

---

modules/account-lib/src/coin/near/utils.ts
modules/account-lib/test/resources/near/index.ts
modules/account-lib/test/unit/coin/near/utils.ts

feat(account-lib): add NEAR util

---

modules/core/test/v2/unit/coins/sol.ts

add testing for staking using varifyTransaction and explatin transacction
STLX-10863

test(core): add testing for staking

---

modules/account-lib/test/unit/coin/dot/keypair.ts

Add test to make sure proper hardened key derivation is performed using DOT `keypair` class
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-13001

chore(account-lib): add tests for key derivation STLX-12770

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

Client send memo as an object but memo is treated as a string
STLX-13059

fix(core): Fix memo on core

---

modules/core/test/unit/wallet.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts

fix(core): fix nock body types

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

Improved prebuildAndSignTransaction to sign consolidation tx if they require to use the derivedKeyPair   
Added unit test
STLX-12996

feat(core): sign consolidate txns

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/sol.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/sol.ts

Added the address in the response of the deriveKey for sol
STLX-0000

refactor(core): add address to deriveKey for sol

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/dot.ts
modules/core/src/v2/coins/sol.ts
modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

implements tss wallet creation. only enabled for sol and dot.
other notable changes:
- randomize userId + email used when generating the ephemeral GPG key
- generate `addressDerivationKeypair` when creating TSS user keychain (can and should be de-duped in the future)
Ticket: BG-41492
Verified against testnet-06 (sol indexer isn't running in dev, gotta fix):
```
async function createTssWallet() {
const test = await bitgo.coin('tsol').wallets().generateWallet({
label: 'sol tss 2',
passphrase: 'Ghghjkg!455544llll',
multisigType: 'tss',
});
console.log(JSON.stringify(test, undefined, 2));
}
```
**Output**
```
{
"wallet": {
"id": "6202d633335cd700089ee54f30f45385",
"users": [
{
"user": "5cae3130f8f4561d51dfcbfdaafba9b9",
"permissions": [
"admin",
"view",
"spend"
]
}
],
"coin": "tsol",
"label": …
```

feat(core): impelement tss wallet creation

---

modules/core/src/v2/coins/dot.ts
modules/core/src/v2/coins/tdot.ts

chore(core): narrow any types in dot

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilder.ts

with TSS, we'll need to add the final signature to a transaction
Ticket: BG-42635

feat(account-lib): supporting adding signatures to transactions

---

modules/core/example/ts/eth/deployForwarder.ts
modules/core/example/ts/eth/flushForwarderToken.ts
modules/core/src/v2/wallet.ts

To enable users to  perform these operations from SDK as well. Ticket: STLX-12550

feat(core): add function in SDK and write examples for deploying forwarder

---

modules/account-lib/src/coin/baseCoin/baseTransaction.ts
modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/src/coin/sol/transactionBuilder.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/transactionBuilder.ts

implements add signature func for sol.
needed for TSS
Ticket: BG-42635

feat(account-lib): implement add signature for sol

---

modules/account-lib/src/coin/baseCoin/iface.ts
modules/account-lib/src/coin/sol/transactionBuilder.ts

moves Signature type to base
Ticket: BG-42635

chore(account-lib): move signature to base interface

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/baseCoin.ts
modules/core/test/v2/unit/coins/sol.ts

Added getSignablePayload for baseCoin and Sol  Added unit tests
STLX-0000

feat(core): implement getSignablePayload for baseCoin and sol

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/keychains.ts
modules/core/test/v2/unit/wallets.ts

adds a public conveninence method for clients to create a TSS Keychain
triplet.
Ticket: BG-41492

feat(core): add createTss func to keychains

---

modules/core/src/v2/coins/dot.ts

Add flag to DOT coin in core to allow requests for consolidation transactions
JIR ticket: https://bitgoinc.atlassian.net/browse/STLX-13186

chore(core): add flag to DOT for consolidation STLX-13186

---

package.json
yarn.lock

Update yarn.lock and remove unnecessary resolutions

---

modules/statics/src/networks.ts

Fix Solana's explorers to access transactions' details.
Jira ticket: https://bitgoinc.atlassian.net/browse/STLX-13338

fix(statics): Fix Solana transactions explorers

---

modules/core/test/v2/unit/coins/dot.ts
modules/statics/src/networks.ts

chore: deconstruct more dot resource

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Add MaticL coin config in statics
Ticket: [BG-41725](https://bitgoinc.atlassian.net/browse/BG-41725)

feat(statics): add maticl coin config

---

modules/core/example/js/algo/disable-token.js
modules/core/example/js/algo/enable-token.js
modules/core/example/ts/algo/disable-token.ts
modules/core/example/ts/algo/enable-token.ts

add examples of enable and disable token
STLX-13257

feat(core): add examples of enable and disable token

---

modules/account-lib/src/coin/algo/utils.ts

update algo decode transaction method on utils
STLX-13389

fix(account-lib): update algo decode transaction method

---

modules/express/src/clientRoutes.ts
modules/express/src/errors.ts
modules/express/src/expressApp.ts

addressing nits from #1944 and #2004
- remove external signing routes and comments for v1 wallet
- remove unecessary prototpe set in ExternalSignerConfigError
- add more descriptive debug msg for retries to external signer
- remove unnecessary `catch` block 
Ticket: BG-42470

refactor: address nits

---

modules/account-lib/DEVELOPER.md

- `npm test` doesn't work have to use `yarn test`

docs(account-lib): update DEVELOPER.md running test section

---

modules/account-lib/src/coin/sol/ataInitializationBuilder.ts
modules/account-lib/src/coin/sol/ataInitializationTransaction.ts
modules/account-lib/src/coin/sol/iface.ts
modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/src/coin/sol/transactionBuilder.ts
modules/account-lib/src/coin/sol/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/sol/transaction.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/ataInitBuilder.ts

https://bitgoinc.atlassian.net/browse/STLX-11958

feat(account-lib): include rent exempt amount in solana ata init transaction

---

modules/account-lib/src/coin/sol/ataInitializationBuilder.ts
modules/account-lib/src/coin/sol/ataInitializationTransaction.ts

https://github.com/BitGo/BitGoJS/pull/2036/
https://bitgoinc.atlassian.net/browse/STLX-11958

chore(account-lib): redefine type of transaction, followup pr to 2036

---

modules/account-lib/src/coin/near/utils.ts
modules/account-lib/test/resources/near/index.ts
modules/account-lib/test/unit/coin/near/utils.ts

add missing test for valid address
stlx-13732

test(account-lib): add missing test

---

modules/account-lib/src/coin/dot/batchTransactionBuilder.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/test/resources/dot/index.ts
modules/account-lib/test/unit/coin/dot/transaction.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/addressInitializationBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/batchTransactionBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/stakingBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unnominateBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unstakeBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/withdrawUnstakedBuilder.ts

fix(account-lib): OOM dot tests

---

modules/core/src/v2/coins/dot.ts

chore: set support tss to true dot test e2e

---

README.md
modules/account-lib/src/coin/dot/keyPair.ts
modules/account-lib/test/resources/dot/index.ts
modules/account-lib/test/unit/coin/dot/keypair.ts
modules/core/example/README.md

[Ticket: BG-43920](https://bitgoinc.atlassian.net/browse/BG-43920)

docs(core): update README.md module links and examples

---

modules/account-lib/package.json
modules/core/package.json
yarn.lock

bump algo and stellar sdks to address url-parser vulnerability
Ticket: BG-0000

chore: bump algo and stellar sdks
