modules/account-lib/src/coin/algo/index.ts
modules/account-lib/src/coin/avaxc/transactionBuilder.ts
modules/account-lib/src/coin/celo/stakingBuilder.ts
modules/account-lib/src/coin/celo/transactionBuilder.ts
modules/account-lib/src/coin/cspr/delegateBuilder.ts
modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/transactionBuilderFactory.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/undelegateBuilder.ts
modules/account-lib/src/coin/cspr/walletInitializationBuilder.ts
modules/account-lib/src/coin/etc/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/src/coin/rbtc/transactionBuilder.ts
modules/account-lib/src/coin/sol/ataInitializationBuilder.ts
modules/account-lib/src/coin/sol/index.ts
modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/src/index.ts
modules/statics/src/index.ts

- export Sol, Algo Interfaces
- export Edds & SolCoin
- remove imports to statics/dist
bg-41925

fix(statics): fix import/exports

---

modules/statics/src/networks.ts

Fixed STX explorer url
STLX-14219

fix(statics): fix stx explorer url

---

modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/pendingApproval.ts
modules/core/test/v2/unit/internal/tssUtils.ts
modules/core/test/v2/unit/pendingApproval.ts

Update sdk to recreate txRequest on pending approval
ticket : https://bitgoinc.atlassian.net/browse/STLX-13003

Stlx 13003 update sdk approval

---

modules/express/src/fetchEncryptedPrivKeys.ts

This file will help create a json with the users wallet ids and encrypted
private keys to be used by the external signer.
I created this file based off the files in `modules/core/example`. 

feat: add fetchEncryptedPrivKeys.ts

---

modules/express/EXTERNAL_SIGNER.md

add a description of how to run fetchEncryptedPrivKeys.ts
~Note: This PR should be rebased/merged after #2069~

doc: add documentation for fetchEncryptedPrivKeys.ts

---

modules/account-lib/src/coin/near/iface.ts
modules/account-lib/src/coin/near/transaction.ts
modules/account-lib/src/coin/near/utils.ts
modules/account-lib/test/unit/coin/near/transaction.ts
modules/account-lib/test/unit/coin/near/transactionBuilder.ts

Add explain transaction for Near
Jira ticket: https://bitgoinc.atlassian.net/browse/STLX-12649

feat(account-lib): add explain transaction for Near

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/near.ts
modules/core/src/v2/coins/tnear.ts
modules/core/test/v2/fixtures/coins/near.ts
modules/core/test/v2/unit/coins/near.ts

feat(core): implement sign transaction for NEAR

---

modules/account-lib/package.json
modules/account-lib/src/coin/algo/ifaces.ts
modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/src/coin/algo/txnSchema.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/resources/algo/index.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/keyRegistrationBuilder.ts
modules/core/package.json
yarn.lock

add stateproofkey param to algorand
STLX-10450

feat(account-lib): add stateproofkey param

---

modules/core/test/v2/unit/coins/ofcToken.ts
modules/statics/src/coins.ts

statics: Add ofcgteth coin
core: Add tests
STLX-14308

STLX-14308 - feature(Add coins for trading) Add GTETH Support for Trading

---

modules/account-lib/src/coin/near/transaction.ts
modules/account-lib/src/coin/near/transactionBuilder.ts
modules/account-lib/test/unit/coin/near/transaction.ts
modules/account-lib/test/unit/coin/near/transactionBuilder.ts
modules/account-lib/test/unit/coin/near/transferBuilder.ts
modules/core/src/v2/coins/near.ts

feat(account-lib): add TSS signing for NEAR

---

modules/core/src/v2/pendingApproval.ts

`getPrv` returns the decrypted private key as a string, not an
object
Verified in test:
Previously, throwing an error: `SyntaxError: Unexpected token u in JSON at position 0`
Now, able to approve:
```
{
"id": "621fe9dc6a4c6c000758aef5dee7054b",
"coin": "tsol",
"wallet": "621fae7f1c29490008a7d9993790e9aa",
"enterprise": "619e9d76bbfb5f0008ca15e7ca47ed49",
"creator": "5cb525d7e1b1328103076788fd6a07f9",
"createDate": "2022-03-02T22:04:12.245Z",
"info": {
"type": "transactionRequest",
"transactionRequest": {
"coinSpecific": {
"tsol": {}
},
"verificationItems": [],
"videoApprovers": [],
"requestedAmount": "100000000",
"fee": "5000",
"sourceWallet": "621fae7f1c29490008a7d9993790e9aa",
"recipients": [
{
"_id": "621fe9dc6a4c6c000758aef6",
"address": …
```

fix(core): fix tss pending approvals

---

modules/core/src/v2/coins/sol.ts
modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/sol.ts
modules/core/test/v2/unit/wallet.ts

feat(core): support creating solana ATA with sdk

---

modules/express/EXTERNAL_SIGNER.md
modules/express/README.md

update the documentation now that external signing mode is enabled for
production.

docs: remove external signer prod restriction

---

modules/core/src/v2/internal/blsUtils.ts
modules/core/src/v2/internal/mpcUtils.ts
modules/core/src/v2/internal/tssUtils.ts
modules/core/test/v2/unit/internal/blsUtils.ts
modules/core/test/v2/unit/internal/tssUtils.ts

HSM has adopted the same implementation as TSS on BLS-DKG.
BG-43029

refactor(core): update BLS-DKG utils for keygen to match the WP changes based on the HSM changes

---

modules/core/src/v2/environments.ts

Added node urls for Near
[STLX-14276](https://bitgoinc.atlassian.net/browse/STLX-14276)

feat(core): added node urls for Near

---

modules/account-lib/src/coin/near/transaction.ts
modules/account-lib/src/coin/near/transactionBuilder.ts
modules/account-lib/src/coin/near/transferBuilder.ts
modules/account-lib/src/coin/near/utils.ts
modules/account-lib/test/resources/near/index.ts
modules/account-lib/test/unit/coin/near/transactionBuilder.ts
modules/account-lib/test/unit/coin/near/transferBuilder.ts

Stlx 14208 refactor near builder

---

modules/core/src/v2/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts
modules/core/test/v2/unit/coins/algo/algoIsWalletAddress.ts

Companion Story for https://bitgoinc.atlassian.net/browse/BG-43270
**NOTE**: Please take a look if the path taken was correct
**NTE**: This PR requires https://github.com/BitGo/bitgo-microservices/pull/16489 to be merged first

Stlx 13809 implement is wallet address for algo

---

modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/util.ts
modules/core/src/v2/coins/stx.ts
modules/core/test/v2/unit/baseCoin.ts
modules/core/test/v2/unit/coins/stx.ts

Fixed isWalletAddress for STX
Added unit tests
[BG-43225](https://bitgoinc.atlassian.net/browse/BG-43225)
Subtasks: 
STX -> [BG-43277](https://bitgoinc.atlassian.net/browse/BG-43277)

fix(root): fix isWalletAddress for STX

---

modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/utils.ts

feat(account-lib): recover signature from raw tx

---

modules/core/src/v2/coins/eth.ts

add eip-1559 and replay protection options for unsigned json
which enables to properly construct replay protected eth tx from
ovc
Ticket: BG-44045

fix(core): support eip-1559 and eip-155 in wrw

---

modules/account-lib/src/coin/baseCoin/baseTransactionBuilder.ts
modules/account-lib/test/unit/coin/baseCoin/transactionBuilder.ts

Implement getValidityWindows as an optional method to validate and return a validated ValidityWindow
or default params
[STLX-11627](https://bitgoinc.atlassian.net/browse/STLX-11627)

feat(account-lib): validate ValidityWindows in baseBuildTransaction

---

modules/core/package.json
package.json
yarn.lock

- adds resolution for minimist
Ticket: BG-45291

chore(root): resolve high vulnerability

---

modules/core/test/v2/unit/coins/ofcToken.ts
modules/statics/src/coins.ts

statics: Add ofccspr and ofctcspr coin
core: Add tests
STLX-14909

STLX-14909 - feat(statics): add ofc casper coins support for trading

---

modules/account-lib/test/unit/coin/baseCoin/transactionBuilder.ts

fix validity windows unit test
[STLX-14936](https://bitgoinc.atlassian.net/browse/STLX-14936)

fix(account-lib): fix validity windows unit test

---

modules/statics/src/coins.ts

Ticket: BG-44943
I made a matching PR in WP: https://github.com/BitGo/bitgo-microservices/pull/16989

chore(statics): rename teth to reflect deprecation

---

modules/bitgo/example/ts/add-webhook.ts

chore(core): add low fee webhook example

---

modules/account-lib/src/coin/near/constants.ts
modules/account-lib/src/coin/near/contractCallWrapper.ts
modules/account-lib/src/coin/near/iface.ts
modules/account-lib/src/coin/near/stakingActivateBuilder.ts
modules/account-lib/src/coin/near/transaction.ts
modules/account-lib/src/coin/near/transactionBuilder.ts
modules/account-lib/src/coin/near/transactionBuilderFactory.ts
modules/account-lib/test/resources/near/index.ts
modules/account-lib/test/unit/coin/near/transactionBuilder/stakingActivateBuilder.ts

add deposit and stake builder for near
STLX-14821

feat(accont-lib): add deposit and stake builder for near

---

modules/account-lib/src/coin/hbar/ifaces.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/hbar/utils.ts
modules/account-lib/test/unit/coin/stx/util.ts
modules/bitgo/src/v2/coins/hbar.ts
modules/bitgo/test/v2/unit/coins/hbar.ts

Implemented isWalletAddress for HBAR 
Moved Core utils methods to AccountLib utils
Added unit test
Minor code improvements for STX
[BG-43225](https://bitgoinc.atlassian.net/browse/BG-43225)
Subtasks:
HBAR -> [BG-43273](https://bitgoinc.atlassian.net/browse/BG-43273)

feat(root): implement isWalletAddress for HBAR

---

modules/bitgo/src/v2/wallet.ts

[stlx-13577](https://bitgoinc.atlassian.net/browse/STLX-13577)

STLX-13577-feat(wallet-platform): add emergency param to whitelist

---

modules/bitgo/test/v2/unit/coins/fiat.ts
modules/bitgo/test/v2/unit/coins/tsusd.ts
modules/statics/src/account.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

statics:
* Add fiat coin to coins
* Create Class to represent fiat network
* Add tests for fiat
* Add tests for tsusd
STLX-13365

STLX-13365-feat(statics): Create FIAT-USD on SDK

---

modules/bitgo/src/v2/wallet.ts

- add backupKeychain and bitgoKeychain to signing params
Ticket: BG-43405

fix(core): add signing params for hopTx

---

modules/account-lib/test/unit/mpc/tss.ts

chore: add dot derive unhardended tests

---

modules/account-lib/src/coin/near/transaction.ts

fix(account-lib): add hash to signable

---

modules/sjcl/package.json

chore(sjcl): fix publish config

---

modules/account-lib/src/index.ts
modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/src/v2/wallet.ts
modules/bitgo/test/v2/unit/wallet.ts

TICKET: BG-44569
Partial revert of https://github.com/BitGo/BitGoJS/pull/2081

feat(bitgo): update tss hd wallet sharing

---

modules/bitgo/src/v2/wallet.ts

fix(bitgo): avoid throwing errors in wallet sharing

---

modules/statics/src/coins.ts

update contract nym erc20 token
update NYM contract
STLX-15409

feat(statics): update contract nym erc20 token

---

modules/bitgo/src/v2/wallet.ts

for tss wallets, signing transactions from root wallet and receive addresses will go
through the same tss signing flow.

feat: standardize tss signing flow

---

modules/bitgo/src/v2/coins/eth.ts
modules/bitgo/test/v2/unit/ethWallet.ts

chore(lumina): improve error logging for hop tx

---

modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/src/v2/keychains.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts
modules/bitgo/test/v2/unit/keychains.ts
modules/bitgo/test/v2/unit/wallets.ts

fix(bitgo): send passcodeEncryptionCode to fix mpc wallet pw reset

---

.github/workflows/ci.yml
modules/express/package.json
modules/express/test/integration/bitgoExpress.ts
modules/express/tsconfig.json
tsconfig.json
tsconfig.packages.json
yarn.lock

- opts out of TS Build system for express package
- adds a CI pipeline step to ensure docker build will not regress

fix(express): Fix docker build for BitGoJS Express

---

modules/bitgo/src/index.ts

added sdk-api export to bitgo index
STLX-0000

fix(bitgo): fix sdk-api export

---

modules/bitgo/src/v2/coins/near.ts
modules/bitgo/src/v2/coins/tnear.ts
modules/bitgo/test/v2/unit/coins/near.ts

Modify in near.ts on core the near constructor to support static and implement allow consolidation flag
STLX-15820

STLX-15820_modify_in_nearts_on_core_the_near_constructor_to_support_static

---

modules/bitgo/test/v2/unit/keychains.ts
modules/statics/src/avaxp.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts
modules/statics/test/unit/coins.ts

add statics for avaxp with generic utxo for future utxo coins that are
not a btc derivative
STLX-15947

feat(statics): create statics for avaxp

---

modules/bitgo/src/v2/coins/cspr.ts
modules/bitgo/test/v2/unit/coins/cspr.ts

refactored isWalletAddress for CSPR    
Fixed unit tests
[BG-43225](https://bitgoinc.atlassian.net/browse/BG-43225)

refactor(core): refactor isWalletAddress for CSPR

---

modules/account-lib/src/coin/near/index.ts

feat(account-lib): add missing exports for Near staking builders

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

CFX token deletion from bitgo wallet
BG-35239

feat(statics): cFX token deletion from bitgo wallet

---

modules/bls-dkg/index.js
modules/bls-dkg/test/bls-dkg.js

Implements HD in BLS-DKG lib so it can be used for the different SDK functionalities (e.g. ETH2
wallets creation)
BG-46338

feat(bls-dkg): bLS-DKG HD support library implementation

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

Add Polygon coin config in statics
Ticket: [BG-41725](https://bitgoinc.atlassian.net/browse/BG-41725)

feat(statics): add polygon coin config

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add fly coin

---

modules/statics/src/networks.ts

Replace `bn.js` by BigInt native implementation
STLX-16485

fix(statics): replace bn.js by BigInt native implementation

---

modules/sdk-core/src/v2/environments.ts

Select the HSM pub key based on the node environment.
STLX-16438

feat(sdk-core): select hsmpub key based on node env

---

modules/sdk-core/package.json
modules/sdk-core/src/account-lib/util/crypto.ts

- adds external modules explicitly to sdk-core package.json
Ticket: BG-47954

chore(sdk-core): update missing imports

---

modules/account-lib/src/mpc/curves/ed25519.ts

this change makes the ed25519 verify function more readable
TICKET:BG-48746

refactor(account-lib): refactor ed25519 verify

---

modules/bitgo/example/js/eth/list-wallet-addresses.js
modules/bitgo/example/js/list-wallet-addresses.js
modules/bitgo/example/ts/eth/list-wallet-addresses.ts
modules/bitgo/example/ts/list-wallet-addresses.ts
modules/bitgo/src/v2/wallet.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts

Added missing filters to the SDK for the list addresses API, along with unit tests & examples.
Ticket: BG-39897

fix: add missing examples and filters for list addresses api

---

modules/account-lib/src/coin/sol/utils.ts
modules/bitgo/src/blockchain.ts
modules/bitgo/src/keychains.ts
modules/bitgo/src/markets.ts
modules/bitgo/src/pendingapproval.ts
modules/bitgo/src/pendingapprovals.ts
modules/bitgo/src/travelRule.ts
modules/bitgo/src/wallet.ts
modules/bitgo/src/wallets.ts
modules/bitgo/test/lib/test_bitgo.ts
modules/bitgo/test/v2/fixtures/trading/affirmation.ts
modules/bitgo/test/v2/lib/asserts.ts
modules/bitgo/test/v2/unit/coins/abstractEthCoin.ts
modules/bitgo/test/v2/unit/coins/eth2.ts
modules/bitgo/test/v2/unit/coins/utxo/transaction.ts
modules/express/test/lib/asserts.ts
modules/utxo-lib/test/fixtures_thirdparty/fixtures.ts
modules/utxo-lib/test/integration_local_rpc/parse.ts
tsconfig.json

Without fixing errors associated with v1 code or tests.
Ticket: BG-48796

chore(root): add noImplicitThis to tsconfig.json

---

modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/avaxp.ts
modules/bitgo/src/v2/coins/index.ts
modules/bitgo/src/v2/coins/tavaxp.ts
modules/sdk-coin-avaxp/.eslintignore
modules/sdk-coin-avaxp/.gitignore
modules/sdk-coin-avaxp/.mocharc.js
modules/sdk-coin-avaxp/.npmignore
modules/sdk-coin-avaxp/.prettierignore
modules/sdk-coin-avaxp/.prettierrc.yml
modules/sdk-coin-avaxp/package.json
modules/sdk-coin-avaxp/src/constants.ts
modules/sdk-coin-avaxp/src/errors.ts
modules/sdk-coin-avaxp/src/iface.ts
modules/sdk-coin-avaxp/src/index.ts
modules/sdk-coin-avaxp/src/keyPair.ts
modules/sdk-coin-avaxp/src/transaction.ts
modules/sdk-coin-avaxp/src/transactionBuilder.ts
modules/sdk-coin-avaxp/src/transactionBuilderFactory.ts
modules/sdk-coin-avaxp/src/transferBuilder.ts
modules/sdk-coin-avaxp/src/utils.ts
modules/sdk-coin-avaxp/src/walletInitializationBuilder.ts
modules/sdk-coin-avaxp/tsconfig.json
tsconfig.packages.json

add avax-p-lib module decoupled from account lib.  Avaxp is a utxo based
coin but uses features of account lib.
Ticket: STLX-15980

feat(SDK-avax-p-lib): add avax-p-lib module

---

modules/account-lib/package.json
modules/sdk-core/package.json

- adds @noble/secp256k1 to sdk-core
Ticket: BG-48167

chore(sdk-core): include missing dependency

---

modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/index.ts
modules/sdk-core/src/bitgo/tss/index.ts
modules/sdk-core/src/bitgo/tss/types.ts

refactor(sdk-core): tss refactor

---

modules/account-lib/package.json
modules/sdk-core/package.json
yarn.lock

- moves dependency from account-lib to sdk-core
Ticket: BG-48711

fix(sdk-core): add paillier bigint dep

---

modules/sdk-coin-avaxp/package.json
modules/sdk-coin-avaxp/src/constants.ts
modules/sdk-coin-avaxp/src/keyPair.ts
modules/sdk-coin-avaxp/src/utils.ts
modules/sdk-coin-avaxp/test/resources/avaxp.ts
modules/sdk-coin-avaxp/test/unit/keyPair.ts
yarn.lock

Added avaxp keypair related functions and tests
STLX-16384

STLX-16384 Added avaxp keypair related functions and tests

---

modules/account-lib/test/unit/mpc/curves/secp256k1.ts
modules/sdk-core/src/account-lib/mpc/curves/secp256k1.ts

this change adds support for point multiplication in secp256k1 curve
TICKET: BG-50007

feat(account-lib): add support for point multiplication in secp256k1 curve

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): tokens begin june

---

modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/stx/utils.ts

replaced querystring(legacy feature of nodejs) for URLSearchParams
[STLX-17126](https://bitgoinc.atlassian.net/browse/STLX-17126)

refactor(account-lib): replace querystring for URLSearchParams

---

modules/sdk-coin-avaxp/src/errors.ts
modules/sdk-coin-avaxp/src/iface.ts
modules/sdk-coin-avaxp/src/transaction.ts
modules/sdk-coin-avaxp/src/transactionBuilder.ts
modules/sdk-coin-avaxp/src/transactionBuilderFactory.ts
modules/sdk-coin-avaxp/src/transferBuilder.ts
modules/sdk-coin-avaxp/src/utils.ts
modules/sdk-coin-avaxp/src/walletInitializationBuilder.ts

chore(sdk-coin-avaxp): fix broken import paths

---

.eslintrc.json
modules/abstract-utxo/src/abstractUtxoCoin.ts
modules/abstract-utxo/src/recovery/RecoveryProvider.ts
modules/abstract-utxo/src/recovery/backupKeyRecovery.ts
modules/abstract-utxo/src/recovery/crossChainRecovery.ts
modules/abstract-utxo/src/replayProtection.ts
modules/abstract-utxo/src/sign.ts
modules/account-lib/src/coin/cspr/index.ts
modules/bitgo/src/v2/coins/sol.ts
modules/bitgo/src/wallet.ts
modules/bitgo/test/v2/unit/coins/cspr.ts
modules/bitgo/test/v2/unit/coins/sol.ts
modules/bitgo/test/v2/unit/coins/utxo/address.ts
modules/bitgo/test/v2/unit/coins/utxo/recovery/backupKeyRecovery.ts
modules/bitgo/test/v2/unit/coins/utxo/recovery/crossChainRecovery.ts
modules/bitgo/test/v2/unit/coins/utxo/recovery/mock.ts
modules/bitgo/test/v2/unit/coins/utxo/transaction.ts
modules/bitgo/test/v2/unit/coins/utxo/util/keychains.ts
modules/bitgo/test/v2/unit/coins/utxo/util/nockIndexerAPI.ts
modules/bitgo/test/v2/unit/coins/utxo/util/transaction.ts
modules/bitgo/test/v2/unit/coins/utxo/util/unspents.ts
modules/blockapis/src/impl/BlockchairApi.ts
modules/blockapis/src/impl/BlockstreamApi.ts
modules/sdk-coin-avaxp/.eslintrc.json
modules/utxo-bin/src/parse.ts
modules/utxo-lib/src/addressFormat.ts
modules/utxo-lib/src/bitgo/bitcoincash/index.ts
modules/utxo-lib/src/bitgo/index.ts
package.json
yarn.lock

- prevent importing from internal modules
- fixes lint errors from new rule

chore(root): add eslint-plugin-import

---

modules/account-lib/src/coin/cspr/ifaces.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts
modules/bitgo/test/v2/unit/coins/cspr.ts

fix(cspr): allow string and large values for csp transferId

---

modules/statics/src/account.ts
modules/statics/src/coins.ts

feat(statics): add hbar token support + added hedera usdc token

---

modules/sdk-coin-avaxp/package.json

chore(avaxp): use bitgo bitcoinjslib

---

modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/index.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/tss/index.ts

feat(sdk-core): tss ecdsa key gen helper methods

---

modules/account-lib/test/unit/mpc/tss/eddsa/eddsa.ts
modules/sdk-core/src/account-lib/mpc/tss/eddsa/eddsa.ts

needed for OVC, where we capture user entropy from text or webcam input.
Ticket: BG-50406

feat: tss - support user supplied entropy during signing

---

modules/bitgo/src/v2/coins/dot.ts
modules/bitgo/src/v2/types.ts
modules/bitgo/test/v2/fixtures/coins/dot.ts
modules/bitgo/test/v2/unit/coins/dot.ts

feat: added explainTransaction and unit tests for dot

---

modules/account-lib/test/unit/coin/polygon/transactionBuilder/walletInitialization.ts

This PR removes console.log statements that were left out in the walletInitialization test file for polygon
Ticket: [BG-41722](https://bitgoinc.atlassian.net/browse/BG-41722)

chore(account-lib): remove console logs

---

modules/statics/src/coins.ts

chore: ofc for TRX

---

modules/sdk-coin-avaxp/src/delegatorTxBuilder.ts
modules/sdk-coin-avaxp/src/iface.ts
modules/sdk-coin-avaxp/src/keyPair.ts
modules/sdk-coin-avaxp/src/transaction.ts
modules/sdk-coin-avaxp/src/transactionBuilder.ts
modules/sdk-coin-avaxp/src/transactionBuilderFactory.ts
modules/sdk-coin-avaxp/src/utils.ts
modules/sdk-coin-avaxp/src/validatorTxBuilder.ts
modules/sdk-coin-avaxp/test/resources/avaxp.ts
modules/sdk-coin-avaxp/test/resources/errors.ts
modules/sdk-coin-avaxp/test/unit/keyPair.ts
modules/sdk-coin-avaxp/test/unit/transactionBuilder.ts
modules/sdk-coin-avaxp/test/unit/validateTxBuilder.ts

Features:
- Build AddValidator Tx 
- Half signed with user key
- Half signed with recovery key
- Full signed
- Get builder tx from raw tx. 
- KeyPair with cb58 
[STLX-16393](https://bitgoinc.atlassian.net/browse/STLX-16393)

feat(sdk-coin-avaxp): implement tx builder for add validator tx

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts

fix modulus for chaincode to be 2^256
TICKET: BG-50457

fix(account-lib): fix chaincode to use correct modulo

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add GMT token to statics
Ticket: BG-50749

feat: onboard solana GMT token

---

modules/bitgo/src/v2/coins/avaxc.ts
modules/bitgo/src/v2/coins/eth.ts
modules/bitgo/test/v2/unit/mmi.ts

chore: pass custodianTransactionId for avax /send

---

.github/workflows/ci.yml
package.json
yarn.lock

fix: temp remove codecov for ci audit fix

---

modules/sdk-core/package.json

updating noble to move away from our
fork to a stable official release
TICKET: BG-00000

chore(sdk-core):update noblejs

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/types.ts
modules/sdk-core/src/account-lib/mpc/util.ts

this change add support for ecdsa signing and verification for TSS
TICKET: BG-48874

feat(account-lib): add support for ecdsa sigining and verification tss

---

modules/bitgo/src/config.ts
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/solToken.ts
yarn.lock

allows us to access solana tokens using `bitgo.coin(tokenName)`
Ticket: BG-51343
Verified manually:
```
await bitgo.coin('tsol:usdc');
```

fix: register solana tokens

---

modules/sdk-coin-avaxp/src/lib/keyPair.ts
modules/sdk-coin-avaxp/src/lib/utils.ts
modules/sdk-coin-avaxp/test/resources/avaxp.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts
modules/sdk-coin-avaxp/test/unit/lib/keyPair.ts
modules/sdk-coin-avaxp/test/unit/lib/utils.ts

feat(sdk-coin-avaxp): keypair default encoder is hex

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Update validation to include eip1559 for changing fee
[STLX-17567](https://bitgoinc.atlassian.net/browse/STLX-17567)

feat(sdk-core): update validation to include eip1559

---

modules/account-lib/package.json
modules/account-lib/src/index.ts
modules/account-lib/tsconfig.json
modules/sdk-coin-avaxp/src/index.ts

feat(sdk-coin-avaxp): add into accountLib umbrella

---

.iyarc
modules/account-lib/package.json
yarn.lock

fix(account-lib): upgrading celo contractkit to v2

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add euroc test token

---

modules/account-lib/src/coin/hbar/constants.ts
modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/tokenAssociateBuilder.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/transactionBuilderFactory.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/sdk-core/src/account-lib/baseCoin/baseTransactionBuilderFactory.ts
modules/sdk-core/src/account-lib/baseCoin/errors.ts
modules/statics/src/index.ts

feat(account-lib): token associate transaction builder for hedera wallet

---

modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/tsconfig.json
modules/sdk-coin-bcha/.eslintignore
modules/sdk-coin-bcha/.gitignore
modules/sdk-coin-bcha/.mocharc.yml
modules/sdk-coin-bcha/.npmignore
modules/sdk-coin-bcha/.prettierignore
modules/sdk-coin-bcha/.prettierrc.yml
modules/sdk-coin-bcha/README.md
modules/sdk-coin-bcha/package.json
modules/sdk-coin-bcha/src/bcha.ts
modules/sdk-coin-bcha/src/index.ts
modules/sdk-coin-bcha/src/tbcha.ts
modules/sdk-coin-bcha/tsconfig.json
tsconfig.packages.json

feat(sdk-coin-bcha): refactor btg to its own module

---

package.json
yarn.lock

- fixes CI pipeline audit failures

chore(root): upgrade to lerna v5

---

modules/bitgo/package.json
yarn.lock

- take latest version with dependency vuln fixed

chore(root): bump moment version

---

modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
modules/bitgo/tsconfig.json
modules/sdk-coin-ada/.eslintignore
modules/sdk-coin-ada/.gitignore
modules/sdk-coin-ada/.mocharc.yml
modules/sdk-coin-ada/.npmignore
modules/sdk-coin-ada/.prettierignore
modules/sdk-coin-ada/.prettierrc.yml
modules/sdk-coin-ada/README.md
modules/sdk-coin-ada/package.json
modules/sdk-coin-ada/src/ada.ts
modules/sdk-coin-ada/src/index.ts
modules/sdk-coin-ada/src/keyPair.ts
modules/sdk-coin-ada/src/tada.ts
modules/sdk-coin-ada/src/transaction.ts
modules/sdk-coin-ada/src/transactionBuilder.ts
modules/sdk-coin-ada/src/transactionBuilderFactory.ts
modules/sdk-coin-ada/src/transferBuilder.ts
modules/sdk-coin-ada/src/utils.ts
modules/sdk-coin-ada/src/walletInitializationBuilder.ts
modules/sdk-coin-ada/test/unit/index.ts
modules/sdk-coin-ada/tsconfig.json
tsconfig.packages.json

feat(account-lib): cardano ada coin skeleton

---

modules/statics/src/networks.ts

This PR adds polygon testnet contract addresses for forwarderFactoryAddress and forwarderImplementationAddress
Ticket: [BG-51803](https://bitgoinc.atlassian.net/browse/BG-51803)

feat(statics): add polygon testnet contract address

---

modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/coin/stx/utils.ts
modules/bitgo/src/v2/coins/avaxc.ts
modules/sdk-coin-avaxp/package.json
modules/sdk-coin-cspr/src/lib/utils.ts

Update files considered invalid by `depcheck` while honoring language syntax and tests.
BG-50968

fix: update invalid files for depcheck

---

README.md

chore: update readme public branching strategy

---

scripts/check-package-dependencies.ts

Should make it more informative.
BG-00000

chore(bitgo): improve check-package-dependencies output

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

update terra a classic
BREAKING CHANGE: We are replacing the symbol of ust to usdtc same contract
BG-51357

feat(statics)!: update terra a classic

---

modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/test/resources/errors.ts
modules/sdk-coin-avaxp/test/unit/lib/validateTxBuilder.ts

feat(sdk-coin-avaxp): add cannot sign error

---

modules/bitgo/package.json
modules/bitgo/src/v2/coins/eos.ts
modules/bitgo/test/integration/accesstoken.ts
modules/bitgo/test/v2/unit/recovery.ts
yarn.lock

- calculate date diffs manually with native Date object
Ticket: BG-51039

chore(bitgo): remove moment dependency

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/src/lib/delegatorTxBuilder.ts
modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/src/lib/validatorTxBuilder.ts
modules/statics/src/networks.ts
modules/utxo-bin/.mocharc.js

bigint cannot be parsed when download transaction
Ticket: STLX-17918

fix(statics): update avaxp network to use number instead of bigint

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

This reverts commit d28bf4498a14be960330cc4fd531ba3acbfd1b3d.

Revert "feat(statics): update terra a classic"

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

allow passing in preview param when building consolidation requests for
TSS Custody wallets.
Ticket: BG-52429

feat: support preview mode for consolidation

---

modules/sdk-coin-celo/src/lib/types.ts

fix(celo): sanitize input

---

modules/sdk-coin-hbar/src/lib/index.ts

fix(sdk-coin-hbar): expose transfer builder class

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat(statics): add toekn MWT

---

modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
modules/sdk-coin-ada/package.json
modules/sdk-coin-ada/src/keyPair.ts
modules/sdk-coin-ada/src/utils.ts
modules/sdk-coin-ada/test/resources/index.ts
modules/sdk-coin-ada/test/unit/keyPair.ts
modules/sdk-coin-ada/test/unit/utils.ts
modules/sdk-core/src/account-lib/baseCoin/enum.ts
yarn.lock

feat(sdk-coin-ada): implement key pair and utils for ada sdk

---

modules/sdk-coin-avaxp/package.json
modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

Implement verify transaction for avaxp
STLX-3243

feat(sdk-coin-avaxp): implement verifyTransaction

---

modules/sdk-coin-avaxp/src/lib/delegatorTxBuilder.ts
modules/sdk-coin-avaxp/test/resources/avaxp.ts
modules/sdk-coin-avaxp/test/resources/errors.ts
modules/sdk-coin-avaxp/test/unit/lib/validateTxBuilder.ts

updated node validation to measure the bytes length
update stake error message literal to reflect actual amount
Ticket: STLX-18165

fix(sdk-coin-avaxp): fix avaxp validation issue

---

modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/test/unit/avaxc.ts

usage of keccak library was not right
Ticket: CR-665
usage: https://www.npmjs.com/package/keccak
also from Eth: https://github.com/BitGo/BitGoJS/blob/master/modules/sdk-coin-eth/src/eth.ts#L8
also added a unit test

fix(sdk-coin-avaxc): fix hop transactions

---

modules/bitgo/example/ts/avaxp/multisig-crosschain-export-import.ts

chore(bitgo): add example for avaxp export import

---

modules/sdk-coin-avaxp/src/lib/transactionBuilder.ts
modules/sdk-coin-avaxp/src/lib/utils.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts
modules/sdk-coin-avaxp/test/unit/lib/utils.ts

Remove methods convert avaxp addresses by adding or removing the `P-` prefix.
Ticket: STLX-18215

fix(avaxp): use "P-" prefix in avaxp addresses

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add coin feature for NEAR
STLX-18046

STLX-18046_add_coin_feature_for_NEAR

---

modules/bitgo/test/v2/fixtures/tss/ecdsaFixtures.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts

feat(sdk-core): add more ecdsa helper methods

---

modules/sdk-coin-hbar/src/hbar.ts
modules/sdk-coin-hbar/test/unit/hbar.ts

feat(sdk-coin-hbar): hbar verifyTransaction

---

modules/statics/src/coins.ts

feat(statics): add prime tokens ofc

---

modules/sdk-coin-bsc/package.json
modules/sdk-coin-bsc/src/bsc.ts
modules/sdk-coin-bsc/src/lib/index.ts
modules/sdk-coin-bsc/src/lib/resources.ts
modules/sdk-coin-bsc/src/lib/transaction.ts
modules/sdk-coin-bsc/src/lib/transactionBuilder.ts
modules/sdk-coin-bsc/src/lib/transferBuilder.ts
modules/sdk-coin-bsc/src/lib/utils.ts
modules/sdk-coin-bsc/test/unit/utils.ts

Ticket: BG-52425
Transaction tests will be written in another ticket

feat(sdk-coin-bsc): add transfer and transaction builders

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/src/lib/iface.ts
modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts
modules/sdk-coin-avaxp/test/unit/lib/transactionBuilderFactory.ts

Add more information for `explainTransaction` for Avalanche P-Chain
STLX-18209

chore(sdk-coin-avaxp): improve explain transaction

---

modules/bitgo/karma.conf.js
modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
webpack/bitgojs.config.js

feat(sdk-coin-ada): incorporate sdk-coin-ada back into bitgo

---

modules/sdk-coin-sol/src/lib/index.ts
modules/sdk-coin-sol/src/lib/instructionParamsFactory.ts
modules/sdk-coin-sol/src/lib/utils.ts
modules/sdk-coin-sol/test/unit/instructionParamsFactory.staking.ts
modules/sdk-coin-sol/test/unit/transaction.ts
modules/sdk-coin-sol/test/unit/utils.ts

fix: add support for durable nonces for Solana transactions
feat: export StakingActivateBuilder,
StakingDeactivateBuilderStakingWithdrawBuilder, StakingWithdrawBuilder
builders for Solana

fix: Add support for durable nonces for Solana transactions

---

modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-polygon/package.json
modules/sdk-coin-polygon/src/polygon.ts
modules/sdk-coin-polygon/src/tpolygon.ts
modules/sdk-coin-polygon/test/unit/polygon.ts

Ticket: BG-48023
Second signging was failing for polygon as it
was using method in eth, so overiding it in
polygon class

feat(polygon): add second signing for recovery

---

Dockerfile
modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
modules/bitgo/tsconfig.json
modules/sdk-coin-aca/.eslintignore
modules/sdk-coin-aca/.gitignore
modules/sdk-coin-aca/.mocharc.yml
modules/sdk-coin-aca/.npmignore
modules/sdk-coin-aca/.prettierignore
modules/sdk-coin-aca/.prettierrc.yml
modules/sdk-coin-aca/README.md
modules/sdk-coin-aca/package.json
modules/sdk-coin-aca/src/aca.ts
modules/sdk-coin-aca/src/index.ts
modules/sdk-coin-aca/src/taca.ts
modules/sdk-coin-aca/test/unit/index.ts
modules/sdk-coin-aca/tsconfig.json
tsconfig.packages.json

TICKET: [BG-52862](https://bitgoinc.atlassian.net/browse/BG-52862?atlOrigin=eyJpIjoiNGNiM2E4MDczZjhhNDA3Mzg4MmY1NGRlMTBjMGQ5NDYiLCJwIjoiaiJ9)

feat(sdk-coin-aca): add sdk-coin-aca module

---

modules/sdk-coin-avaxp/src/avaxp.ts

feat(avaxp): add recoverySignature method

---

modules/sdk-coin-bsc/README.md

Ticket: BG-53547
- Update the README

chore(sdk-coin-bsc): Update README

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

fix(sdk-core): tss ecdsa keychain encryption

---

modules/sdk-coin-polygon/src/polygon.ts
modules/sdk-coin-polygon/src/tpolygon.ts

fix(sdk-coin-polygon): fix sign for test polygon

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-hbar/src/hbar.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): add specialized enable token functions

---

modules/utxo-lib/src/networks.ts
modules/utxo-lib/test/networks.ts

refactor(utxo-lib): change doge network bip32 mainnet prefixes to default

---

modules/sdk-coin-algo/README.md
modules/sdk-coin-btc/README.md
modules/sdk-coin-eth/README.md
modules/sdk-coin-xrp/README.md

Quick fix to coin import examples found in README.md files.
BG-000000

chore: fix README coin import examples

---

modules/sdk-coin-sol/src/sol.ts

Ticket: BG-53197
These are the non-breaking sdk-coin-sol changes from https://github.com/BitGo/BitGoJS/pull/2604

feat(sdk-coin-sol): require token enablement for solana

---

modules/sdk-coin-avaxp/package.json

chore(sdk-coin-avaxp): update avalanche version in avaxp

---

modules/sdk-coin-sol/src/sol.ts

feat(sdk-coin-sol): enable Solana staking

---

modules/sdk-coin-btc/src/btc.ts
modules/sdk-core/package.json
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts
modules/sdk-core/src/bitgo/lightning/index.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

- create ILightning interface and add lightning() function to IWallet
interface
- create a stub implementation of the ILightning interface
Ticket: BG-54079

feat(sdk-core): create ILightning interface

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

fix(sdk-core): Fix sendTokenEnablements 

---

modules/sdk-coin-hbar/src/hbar.ts
modules/sdk-coin-hbar/test/unit/hbar.ts

fix(sdk-coin-hbar): verify transaction should work without token name

---

modules/sdk-core/src/bitgo/lightning/iLightning.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts

- GetInvoices and CreateDepositAddress do not take params
- add required params for LightningWithdrawal
- add optional params for PayInvoice
- add maximumBalance to response for GetBalance
Ticket: BG-54079

fix(sdk-core): fix lightning requests params

---

modules/abstract-utxo/src/abstractUtxoCoin.ts

refactor(abstract-utxo): remove unused UnspentParams and AddressInfo

---

modules/sdk-coin-aca/package.json
modules/sdk-coin-aca/src/index.ts
modules/sdk-coin-aca/src/lib/index.ts
modules/sdk-coin-aca/src/lib/keyPair.ts
modules/sdk-coin-aca/test/resources/index.ts
modules/sdk-coin-aca/test/unit/keypair.ts
modules/sdk-coin-aca/tsconfig.json
modules/sdk-coin-dot/src/lib/utils.ts
modules/sdk-core/src/account-lib/baseCoin/enum.ts

feat: add keypair to acala module

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/test/resources/keychains.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

feat(sdk-coin-avaxp): implement is wallet address method

---

modules/statics/src/networks.ts

chore: update eos mainnet explorer url

---

modules/sdk-core/src/bitgo/tss/ecdsa/types.ts

fix(sdk-core): add missing ecdsa helper type

---

modules/bitgo/src/v2/coinFactory.ts
modules/sdk-coin-aca/src/acaToken.ts
modules/sdk-coin-aca/src/index.ts
modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/tokenConfig.ts

add acala token config 

---

modules/bitgo/test/v2/unit/lightning.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts

- it generates lightning deposit address
Ticket: BG-54081

feat(sdk-core): add createDepositAddress to lightning

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/src/iface.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

Avaxp staking method does not send recipients
STLX-18437

feat(sdk-coin-avaxp): fix verify transaction method

---

modules/bitgo/test/v2/fixtures/lightning/lightning.ts
modules/bitgo/test/v2/unit/lightning.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts

- createInvoice() in lightning generates a lightning invoice
- a test code lives in /bitgo/test
Ticket: BG-54080

feat(sdk-core): add createInvoice to lightning

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): add support for enabling tokens on cold and custodial wallets

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): handle multiple token enables on chains that don't support it

---

modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-polygon/src/polygon.ts
modules/sdk-coin-polygon/test/unit/polygon.ts

This PR adds `signTransaction()` method in Polygon to solve issue in Polygon transfers and updates the test cases accordingly
[BG-54459](https://bitgoinc.atlassian.net/browse/BG-54459)

feat(sdk-coin-polygon): add signTx method

---

modules/bitgo/test/v2/fixtures/lightning/lightning.ts
modules/bitgo/test/v2/unit/lightning.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
yarn.lock

- it creates a new address if an address is not provided
- it creates a new sequenceId if it is not provided
Ticket: BG-54084

feat(sdk-core): add withdraw to lightning object

---

modules/bitgo/test/v2/unit/internal/tssUtils/common.ts
modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts

fix(sdk-core): ecdsa signing get user share

---

modules/statics/src/coins.ts

fix(statics): fix terc tokens to use goerli network

---

modules/statics/src/index.ts

chore: export AcaCoin in statics

---

modules/sdk-coin-ada/src/lib/utils.ts
modules/sdk-coin-ada/test/unit/utils.ts

fix(sdk-coin-ada): fix blockhash validation

---

modules/sdk-coin-avaxp/package.json
modules/sdk-coin-stx/package.json
modules/sdk-coin-xtz/package.json
modules/sdk-core/package.json
modules/unspents/package.json
yarn.lock

- replace rc3 with "npm:@bitgo/bitcoinjs-lib@6.1.0-rc.5"

fix(root): align versions of bitcoinjs-lib

---

Dockerfile
modules/bitgo/package.json
modules/bitgo/tsconfig.json
modules/sdk-coin-ethw/.eslintignore
modules/sdk-coin-ethw/.gitignore
modules/sdk-coin-ethw/.mocharc.yml
modules/sdk-coin-ethw/.npmignore
modules/sdk-coin-ethw/.prettierignore
modules/sdk-coin-ethw/.prettierrc.yml
modules/sdk-coin-ethw/README.md
modules/sdk-coin-ethw/package.json
modules/sdk-coin-ethw/src/ethw.ts
modules/sdk-coin-ethw/src/index.ts
modules/sdk-coin-ethw/test/lib/recovery-nocks.ts
modules/sdk-coin-ethw/test/unit/index.ts
modules/sdk-coin-ethw/tsconfig.json
modules/sdk-core/src/bitgo/environments.ts
tsconfig.packages.json

Add a module for ethw coin in preparation of an eventual ETH PoW fork. This coin only needs to
support recover function in order to be able to withdraw from that chain.
BG-55421

feat(sdk-coin-ethw): add ethw sdk module

---

modules/sdk-coin-ada/package.json
modules/sdk-coin-ada/src/ada.ts
modules/sdk-coin-ada/src/tada.ts
modules/sdk-coin-ada/test/resources/index.ts
modules/sdk-coin-ada/test/unit/ada.ts
modules/sdk-coin-ada/test/unit/getBuilderFactory.ts
modules/sdk-coin-ada/test/unit/keyPair.ts
modules/sdk-coin-ada/test/unit/transactionBuilder.ts

implement ada sdk interface
Ticket: [BG-50799](https://bitgoinc.atlassian.net/browse/BG-50799)

implement ada sdk interface

---

modules/sdk-coin-polygon/test/unit/polygonToken.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

fix(sdk-coin-polygon): update polygon token names

---

modules/statics/src/coins.ts

feat: enable sol staking feature

---

modules/sdk-coin-ada/src/ada.ts

feat(account-lib): add tss to ada coin interface

---

modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-sol/src/sol.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

fix(sdk-core): eth supports tss

---

modules/bitgo/test/v2/unit/internal/opengpgUtils.ts
modules/sdk-core/src/bitgo/utils/opengpgUtils.ts

Added a verification for share proofs. This is to verify that a u share that is being shared to the destined entity was actually sent by the sender of that u share.

feat(sdk-core): add verification of private shares

---

modules/account-lib/package.json
modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
yarn.lock

this change adds support for additional
hashing algorithms for ecdsa tss
TICKET: BG-55978

feat(account-lib): add support for additional hash algorithms

---

modules/sdk-coin-ada/src/ada.ts

fix(account-lib): added validate address function to sdk-coin-ada

---

modules/sdk-coin-sol/src/lib/transactionBuilderFactory.ts

Ticket: BG-56209
Add support to deserialize a Sol multi-assets transfer transaction including native and token transfers

feat(sdk-coin-sol): deserialize Sol transferBuilderV2 tx

---

modules/account-lib/src/index.ts

chore(account-lib): support bsc tx builder

---

modules/sdk-coin-avaxc/package.json
modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/avaxcToken.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-coin-avaxc/test/unit/avaxc.ts
modules/sdk-core/src/bitgo/environments.ts

feat(sdk-coin-avaxc): add recover method for wrw

---

.gitignore
DEVELOPERS.md
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
package.json

feat: adding support for message signing

---

modules/bitgo/example/js/ada/create-wallet.js

feat(ada): create wallet script

---

modules/sdk-coin-ada/test/unit/ada.ts
modules/statics/src/coins.ts

fix(statics): update ADA fullname

---

modules/sdk-coin-ada/src/ada.ts
modules/sdk-coin-ada/test/unit/ada.ts

fix(account-lib): update verifyTransaction for ada

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

* Update: Additional steps for bug and feature requests
* Add: Pull request template to set pull request expectations
BG-56523

feat: update repository templates

---

modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-coin-avaxc/test/unit/avaxc.ts

feat(sdk-coin-avaxc): add recovery support for unsigned sweep

---

modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-coin-avaxc/test/unit/avaxc.ts

fix(sdk-coin-avaxc): fix unsigned sweep format for ovc

---

modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

chore: update address separator to ~

---

modules/account-lib/test/unit/mpc/curves/secp256k1.ts
modules/bitgo/test/v2/fixtures/tss/ecdsaFixtures.ts
modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/curves/secp256k1.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts

feat(sdk-core): add recid to fully constructed signature

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

feat: add address validation for address array and multisig address

---

CODEOWNERS

- make CODEOWNERS a little easier for everyone

chore(root): update codeowners

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-polygon/package.json
modules/sdk-coin-polygon/src/polygon.ts
modules/sdk-coin-polygon/test/fixtures/polygon.ts
modules/sdk-coin-polygon/test/unit/polygon.ts
modules/sdk-core/src/bitgo/environments.ts

Ticket: BG-56221
Add support for Non-BitGo Recoveries
Changes:
recover and signFinal methods

feat(sdk-coin-polygon): support recovery

---

modules/statics/src/coins.ts

adds test polygon as erc20 token for goerli
BOS-556

feat(coins): adds test polygon as erc20 token for goerli

---

modules/statics/src/coins.ts

fix name husd for trading
STLX-19005

feat(statics): fix name husd for trading

---

modules/utxo-lib/package.json
yarn.lock

fix(utxo-lib): pin noble-secp256k1

---

modules/statics/src/networks.ts

fix(sdk-coin-ethw): update chainid for EthW

---

modules/statics/src/coins.ts

fix decimals token CHO
STLX-19069

feat(statics): fix decimals token CHO

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Ticket: BG-57413
WP updated ecdsa tss signing flow, this pr is matching that signing flow

fix(sdk-core): ecdsa tss signing flow update

---

modules/bitgo/example/README.md
modules/bitgo/example/ts/btc/check-lightning-balance.ts
modules/bitgo/example/ts/btc/create-lightning-invoice.ts
modules/bitgo/example/ts/btc/make-lightning-deposit.ts
modules/bitgo/example/ts/btc/make-lightning-payment.ts
modules/bitgo/example/ts/btc/pay-lnurl-request.ts
modules/bitgo/example/ts/btc/withdraw-lightning-balance.ts

Ticket: [BG-56923](https://bitgoinc.atlassian.net/browse/BG-56923)
Added examples in JavaScript and TypeScript showcasing Lightning/LNURL services in BitGoJS.
Includes:
- Checking a wallet's lightning balance.
- Getting a lightning deposit address and depositing on-chain funds to a wallet's lightning balance.
- Withdrawing from a wallet's lightning balance to on-chain funds.
- Making a lightning payment.
- Creating a lightning invoice.
- Paying an lnurl request.

feat(bitgo): add lightning and lnurl examples

---

.iyarc

- this github alert is only flagged as a medium severity and is only used by our dev tools, should not block us

chore(root): ignore GHSA-pqw5-jmp5-px4v

---

modules/sdk-coin-ethw/package.json
modules/sdk-coin-ethw/src/ethw.ts
modules/sdk-coin-ethw/test/lib/recovery-nocks.ts
modules/sdk-coin-ethw/test/unit/index.ts
modules/sdk-core/src/bitgo/environments.ts

For ETHw use RPC queries against a full node instead of a blockchain explorer
BG-55611

feat(sdk-coin-ethw): use ETHw full node RPC queries to recover funds

---

modules/utxo-lib/package.json
yarn.lock

fix(utxo-lib): use published bitcoinjs-lib

---

modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Add isTss flag support when building with intents
bg-53422

Bg 53422 add tss param support

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

with tx request full, creating a tx request will initiate the pending approvals by default. the preview flag is used to avoid initiating pending approvals. this is useful for when clients need to display a preview of the unsigned transaction (i.e. fees, amounts, etc.)
Ticket: BG-57904

fix: add 'preview' as whitelisted param for token enablement

---

modules/utxo-lib/package.json
yarn.lock

fix(utxo-lib): use BitGo published ecpair dep

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

TICKET: BG-58163
Adds mysten (SUI) coin to statics.

feat: add sui coin to statics

---

modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts

feat(sdk-core): add logic to handle ERC20 tokens for staking

---

package.json
yarn.lock

fix: update resolutions from yarn audit advisory

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add polygon tokens to statics
Ticket: BG-58273

feat(statics): add polygon tokens to statics

---

.github/workflows/beta-publish.yml

- commits local changes before publishing. --no-git-reset did not work.
- performs beta release on master merges
Ticket: BG-57161

chore(root): fix publish steps

---

.github/workflows/beta-publish.yml

- adds --yes to skip lerna prompts
Ticket: BG-57161

chore(root): skip prompt publish

---

Dockerfile

Change attribution by: @lfojacintho
The latest version of BitGo-Express docker image uses an outdated node base image. This base image contains several vulnerabilities that were fixed in more recent versions. I'm upgrading the base image to the latest version, which doesn't contain any known vulnerability.
BG-000000

fix(express): upgrade Express Dockerfile

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

We want to re-introduce ORCA and add GARI to the list of available SOL tokens. Start by updating statics.
STLX-19257

feat(statics): add ORCA and GARI to SOL token list

---

scripts/prepare-beta.ts

- beta published packages were not updated in other modules
- next version was missing the 'beta' tag
Ticket: BG-57161

chore(root): fix beta tags & linked packages

---

modules/sdk-coin-dot/src/dot.ts
modules/sdk-coin-near/src/near.ts
modules/sdk-coin-near/test/fixtures/near.ts
modules/sdk-coin-near/test/unit/near.ts
modules/sdk-coin-sol/src/sol.ts
modules/sdk-coin-sol/test/unit/sol.ts

Adding Near unsigned sweep recovery functionality, with additional unit testing
BG-58695
Unit testing

BG-58695 Near Unsigned Sweep

---

modules/bitgo/test/v2/unit/staking/stakingWalletNonTSS.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts

For matic, when building and signing transactions the eth wallet should be used
Ticket: BOS-636

feat(sdk-core): use eth wallet for building and signing token txs

---

modules/sdk-coin-sol/src/sol.ts
modules/sdk-coin-sol/test/fixtures/sol.ts
modules/sdk-coin-sol/test/unit/sol.ts

feat(sdk-coin-sol): update recover to support derived wallet address

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

add lido dao token
Ticket: 58873

feat: add new tokens

---

CODEOWNERS
Dockerfile
modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
modules/bitgo/tsconfig.json
modules/sdk-coin-sui/.eslintignore
modules/sdk-coin-sui/.gitignore
modules/sdk-coin-sui/.mocharc.yml
modules/sdk-coin-sui/.npmignore
modules/sdk-coin-sui/.prettierignore
modules/sdk-coin-sui/.prettierrc.yml
modules/sdk-coin-sui/README.md
modules/sdk-coin-sui/package.json
modules/sdk-coin-sui/src/index.ts
modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/index.ts
modules/sdk-coin-sui/src/lib/keyPair.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilder.ts
modules/sdk-coin-sui/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sui/src/lib/transferBuilder.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/src/tsui.ts
modules/sdk-coin-sui/test/unit/index.ts
modules/sdk-coin-sui/tsconfig.json
tsconfig.packages.json

Ticket: BG-58791
Created new module for SUI.

feat(sdk-coin-sui): create sui module

---

modules/bitgo/example/js/build-transaction.js
modules/bitgo/example/ts/build-transaction.ts

feat(core): adding example for tx-build
API doc: https://api.bitgo.com/docs/#operation/v2.wallet.tx.build
Ticket:
[BG-49936](https://bitgoinc.atlassian.net/browse/BG-49936)
[BG-58604](https://bitgoinc.atlassian.net/browse/BG-58604)

adding example for tx-build

---

modules/abstract-utxo/package.json
modules/blockapis/package.json
modules/sdk-core/package.json

- several packages were missing @types/superagent from dependencies, despite referencing these types directly

chore(sdk-core): include superagent types

---

modules/sdk-coin-sui/src/sui.ts

Ticket: BG-58176
Added SUI skeleton code, a lot of the skeleton code was already added when creating module, so this is only adding some missing functions in sui.ts

feat(sdk-coin-sui): added SUI skeleton

---

.github/workflows/beta-publish.yml
scripts/verify-beta.ts

- adds verify step to try and manually publish packages that failed from lerna
- set lerna publish log level to --silly to help troubleshoot

chore(root): add verify step to force publish

---

modules/sdk-coin-avaxp/src/lib/exportInCTxBuilder.ts
modules/sdk-coin-avaxp/test/resources/errors.ts
modules/sdk-coin-avaxp/test/unit/lib/exportC2PTxBuilder.ts

fix(sdk-coin-avaxp): nonce validation is not allow 0

---

modules/statics/src/tokenConfig.ts

JIRA ticket: https://bitgoinc.atlassian.net/browse/BG-59021

fix(statics): format polygon token if its an NFT BG-59021

---

modules/statics/src/networks.ts

This PR adds the mainnet polygon contracts in the statics
[BG-51803
](https://bitgoinc.atlassian.net/browse/BG-51803)

feat(statics): add mainnet polygon contracts

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Encoding user signer share to send to bitgo with base58, this is required because hsm expects this encoding rather than a hex encoding. 
Ticket: BG-58334
Updated current test.

fix(sdk-core): ecsda tss signing

---

modules/sdk-coin-ada/src/lib/stakingWithdrawRewardsBuilder.ts
modules/sdk-coin-ada/src/lib/utils.ts

TICKET: [BG-59208](https://bitgoinc.atlassian.net/browse/BG-59208?atlOrigin=eyJpIjoiYzU5ZDNkMjk4MjIwNDc4YzgzYTliOGYyNWM5MGNkYTEiLCJwIjoiaiJ9)

feat(sdk-coin-ada): add method to obtain reward address

---

modules/statics/src/coins.ts

JIRA ticket: https://bitgoinc.atlassian.net/browse/BG-58416

fix(statics): contract address of tpolygon name NFT BG-58416

---

modules/sdk-coin-ada/src/lib/transaction.ts

fix(sdk-coin-ada): check if serialization lib is loaded

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts

- includes optional spendingLimits

chore(sdk-api): fix accesstoken types

---

modules/bitgo/test/v2/unit/staking/stakingWalletCommon.ts
modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-dot/src/dot.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-near/src/near.ts
modules/sdk-coin-sol/src/sol.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/staking/iStakingWallet.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

allow getting a staking wallet for any coin
allow clients to send arbitrary properties when staking or unstaking
Ticket: BOS-649

feat(sdk-core): Allow getting a staking wallet for any coin

---

modules/abstract-eth/src/abstractEthLikeCoin.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Make sure that TSS wallet creations for EVMs have wallet version set as 3.

Bg 58908 validate istss evm

---

modules/sdk-api/src/types.ts

- type should be string to handle large precision

fix(sdk-api): fix txValueLimit type

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts

Ticket: BG-59051
I added a unit test. Integration testing has to wait until the underlying API exists.

feat(sdk-core): add helper to create backup TSS key share held by BitGo

---

modules/sdk-coin-sol/src/lib/transactionBuilder.ts

fix(sdk-coin-sol): fix incorrect sender in transaction builder

---

modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/test/unit/sui.ts

TICKET: BG-59017
implements isValidAddress

feat: implement isValidAddress for SUI

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

feat(sdk-core): add helper to finish backup TSS key share held by BitGo

---

modules/sdk-coin-sui/src/sui.ts

Throw this exception so that createAddress does not fail.

chore: throw MethodNotImplemented error for sui isWalletAddress

---

CODEOWNERS

updates team name
Ticket: BG-59899

chore: update blockchain-integration to altcoins

---

modules/statics/src/coins.ts

We want to re-introduce Solend to the list of available Solana tokens. Start by updating statics.
Note: coin already exists as an underlying asset, but was previously removed from coins list in statics.
TICKET: BG-60000

feat(statics): add SOLEND (SLND) Solana token to statics

---

modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/test/unit/sui.ts
modules/sdk-coin-sui/test/unit/transaction.ts

Ticket: BG-59020
Implemented Sui explain transaction and added missing verifyTransaction and fromRawTransaction unit tests

feat(sdk-coin-sui): added sui explain transaction

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

fix: create txrequest for message signing

---

modules/bitgo/example/js/sol/enableTokens.js
modules/bitgo/example/js/sol/enableTokensForAddress.js
modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/enableTokens.ts

adds token enablement support in express.
also adds examples for enabling tokens for SOL.
Ticket: BG-60201

feat: add token enablement support in express

---

modules/bitgo/test/v2/unit/staking/stakingWalletNonTSS.ts
modules/bitgo/test/v2/unit/staking/stakingWalletTSS.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): add support for ETH TSS staking

---

modules/sdk-coin-sui/package.json
modules/sdk-coin-sui/src/lib/keyPair.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/unit/keyPair.ts

TICKET: BG-59016
Implements SUI Keypair class for TSS support.
BG-59016

feat: implement sui keypair

---

package.json
yarn.lock

fix: lock types for @types/keyv

---

modules/statics/src/coins.ts

Ticket: [BG-60171](https://bitgoinc.atlassian.net/browse/BG-60171)
Add trading account ofcmana token

chore(statics): add mana ofcerc20 token

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): add fetchCrossChainUTXOs in wallet

---

modules/sdk-coin-near/src/near.ts

Update Near recover function to handle the case when the address is not on the blockchain (has not partake in any transaction before), and handle the case when the fund is insufficient to construct a recover transaction.
BG-60399
The failure scenarios that caught these bugs are now behaving as expected

fix(sdk-coin-near): fix near recover function

---

modules/account-lib/package.json
modules/account-lib/src/index.ts

Ticket: BG-60538
added sui to account-lib

feat(sdk-coin-sui): added sui to account-lib

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Ticket: https://bitgoinc.atlassian.net/browse/BG-60552
**Only the commit 2 is the actual bug fix-** 
For the workflow where bitgo holds backup, when SDK sends the user->backup shares to WP, it was not adding the chain-code due to which the commonKeychain derivation was failing in WP.
It also fixes the backup gpg public to be bitgo's GPG key when backup is held by third party.
These changes have been tested e2e with an external script which calls the SDK.

fix(sdk-core): small fixes/improvements for nike wallet creation

---

modules/bitgo/example/js/ada/send-staking-transaction.js
modules/bitgo/example/js/ada/send-unstaking-transaction.js

feat(sdk): add ada example tests for staking

---

modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

chore(sdk-core): improve error-handling for backup API calls

---

modules/statics/src/networks.ts

TICKET: BG-60676
Fix sui explorer url

fix: update explorer url for test mysten

---

modules/sdk-core/src/bitgo/utils/mpcUtils.ts

chore(sdk-core): use tx intent for bsc

---

modules/statics/src/networks.ts

fix(statics): change cardano testnet url to preprod testnet

---

modules/utxo-lib/package.json
yarn.lock

bump bitcoinsjs-lib version
Issue: BG-60780

build(utxo-lib): bump bitcoins lib version

---

modules/sdk-coin-polygon/package.json
modules/sdk-coin-polygon/src/polygon.ts
modules/sdk-coin-polygon/test/unit/polygon.ts

Ticket: BG-60612
Remove unused data from polygon recovery method
Ticket: BG-60612

fix(sdk-coin-polygon): remove unused data in recovery

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Ticket: [BG-60777](https://bitgoinc.atlassian.net/browse/BG-60777)
Adding Wrapped Doge ERC-20 Token

feat(statics): add wdoge

---

modules/sdk-core/src/bitgo/utils/opengpgUtils.ts

fixes eddsa proof generation
Ticket: BG-60907
Note to reviewer: not clear how to best unit test this change, but we manually verified with the HSM team by outputting the proof generated in existing unit tests and checking that HSM processes it as a valid proof.

fix: fix eddsa proof generation

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts

Ticket:BG-60844
Add data field for smart contract transactions.
- [ x ] Bug fix (non-breaking change which fixes an issue)

chore: add data field to payment intent

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/test_package_updates.yml

See warnings here: https://github.com/BitGo/BitGoJS/actions/runs/3380244649. The old checkout action was deprecated

chore(root): update action checkout to v3

---

.github/PULL_REQUEST_TEMPLATE.md

* Set PR template text to be fully commented out. Not needed for the description of the PR but is used a reminder for both internal and external users making PRs to this open source project.
BG-000000

chore: update PRs to be commented

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts

fix(sdk-core): ecdsa tss wallet creation

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

fix: typo in intent name for message signing

---

Dockerfile

- stellar-sdk crashes express while running linux:alpine
- switch to buster-slim & use apt-get to install OS deps
Ticket: BG-61260

fix(express): use buster slim over alpine

---

modules/express/package.json

- increment minor version for buster-slim release
Ticket: BG-61260

chore(express): bump expression version

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Adding support of test wdoge
Ticket: BG-61437

feat(statics): add twdoge

---

modules/statics/src/coins.ts

Ticket: BG-58420
Added OFC support to ERC20 tokens (ELF ENS EURS FUN FXS)

feat(statics): Add ERC20 tokens to OFC support

---

modules/bitgo/test/v2/unit/staking/stakingWalletCommon.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts

ref: https://bitgoinc.atlassian.net/browse/BOS-576

feat: add cancel staking request

---

modules/express/CHANGELOG.md

chore(express): update change log manually

---

modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts

Add tx type to fee estimation and build params
Ticket: BG-61826

Bg 61826 fee estimate type

---

modules/sdk-coin-cspr/src/cspr.ts
modules/sdk-coin-cspr/test/unit/cspr.ts

when creating new CSPR addresses, they are dervived from the wallet's root address. however, the wallet's root address is randomly generated and NOT derived from the user's keychain.
Ticket: BG-56147
Additionally, verified with a test script:
```
async function csprCreateAddress() {
const wallet = await bitgo.coin('tcspr').wallets().getWallet({ id: '61785623811e590008df8a42cb1f0bb1' });
const newAddress = await wallet.createAddress();
console.log(newAddress);
}
```

fix(cspr): fix isWalletAddress

---

modules/bitgo/src/v2/coinFactory.ts
modules/sdk-coin-trx/src/index.ts
modules/sdk-coin-trx/src/trxToken.ts
modules/statics/src/account.ts
modules/statics/src/tokenConfig.ts

TICKET: [BG-61338](https://bitgoinc.atlassian.net/browse/BG-61338?atlOrigin=eyJpIjoiNWUxNDE2YjYzMGYwNGEzNDk2Njg5MGY4ZTk1MmRiMTciLCJwIjoiaiJ9)

feat(sdk-coin-trx): add tron token skeleton

---

package.json
yarn.lock

build(root): bump babel loader to remove loader-utils

---

modules/bitgo/test/v2/unit/tss/eddsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts

fix(sdk-core): disabling vss for eddsa

---

modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-coin-avaxc/test/unit/avaxc.ts

feat(sdk-coin-avaxc): verify c to p hop export tx

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/test/unit/coins.ts

Change made due to conversation on related PR [here](https://github.com/BitGo/BitGoJS/pull/3031#discussion_r1028248256).
JIRA ticket: BG-62198

chore(statics): use more semantic name for coin feat BG-62198

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/features/constructFinalSignedMessageHash.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-61620
- Added a new function in eth.ts to construct final message hash. This is necessary as the `recid` gets handle in a specific way for evm.
- Added a new interface and a function to check if a class implements this interface. This is a better way to check for support instead of adding another method to basecoin.
- Updated getBitgoToUserLatestShare to include the requestType (either RequestType.tx or RequestType.message)
- Added a new Intent called IntentOptionsForMessage that extends IntentOptionsBase as it is necessary to send both the encoded and raw message since security team wants HSM to do their own encoding of the raw message but WP needs encoded message to MPC.verify (since both the sdk and hsm are signing the encoded version)

fix: multiple issues with message signing

---

modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts

fix(sdk-core): pass custodianMessageId in signMessage

---

modules/bitgo/example/js/create-tss-wallet.js
modules/bitgo/example/ts/create-tss-wallet.ts
modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/bitgo/test/v2/unit/tss/common.ts
modules/bitgo/test/v2/unit/tss/helpers.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

When we create TSS wallets, BitGo returns two signatures so that
the owners of the user and backup keys are able to verify that
there was no man in the middle meddling with the involved key shares
and gpg keys.
These signatures are signed with BitGo's GPG public key and cover the
following items:
* commonKeychain
* key ID of the user GPG key
* key ID of the backup GPG key
* the derived public portion of the BitGo to User key share
* the derived public portion of the BitGo to Backup key share
Ticket: BG-59151

feat(sdk-core): add function to verify wallet signatures for TSS

---

modules/sdk-coin-ada/src/lib/transactionBuilder.ts
modules/sdk-coin-ada/test/unit/transactionBuilder.ts

feat(sdk-coin-ada): add method to set fee for ada

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore: add metamask institutional coin feature to statics

---

modules/sdk-coin-sui/src/lib/transactionBuilder.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transferBuilder.ts

Ticket: [BG-62616](https://bitgoinc.atlassian.net/browse/BG-62616)
`Pay` doesn’t allow the gas payment object in inputCoins, but `PaySui` and `PayAllSui` require `gasPayment`=`inputCoins[0]`
This PR is to fix the validation for input coins and gas payment

fix(sdk-coin-sui): fix sui gasPayment in inputCoins

---

modules/sdk-coin-avaxc/src/avaxc.ts

feat(sdk-coin-avaxc): remove use of suer req sig for hot tx

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-avaxc/src/avaxc.ts
modules/sdk-coin-avaxc/src/iface.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

* Change sendMany to work for custodial wallets
* Remove unused hop tx build options
Ticket: BG-62678

feat(sdk-core): change sendMany to work for custodial wallets

---

modules/bitgo/example/js/get-wallet-token-balance.js
modules/sdk-core/src/bitgo/wallet/iWallet.ts

A script to get token balances from a wallet. We currently only have a script that can get native asset balances.
Ticket: BG-62315

feat(bitgo): sdk script to get token balance from wallet

---

modules/sdk-api/src/bitgoAPI.ts

- BitGoAPI .coin method should declare its actual return type

chore(sdk-api): fix coin return type

---

modules/statics/src/coins.ts

update name to match chain, AnchorUSD
Ticket: BG-62767
BREAKING CHANGE: updated name of XLM USD token

fix: update XLM USD token name

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

fix(sdk-core): add destinationChain to prebuild whitelisted params

---

modules/sdk-coin-celo/src/lib/transactionBuilder.ts
modules/sdk-coin-celo/test/unit/transactionBuilder/singleSigSend.ts
modules/sdk-coin-eth/src/lib/transactionBuilder.ts

Address bug in celo signing that allowed us to sign over potentially inaccurate values. The celo library can only handle certain numbers safely, we throw for unsafe numbers.
BG-62249

fix(sdk-coin-celo): fix precision bug in celo build/sign

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore: onboard starknet token

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/src/iface.ts
modules/sdk-coin-avaxp/src/lib/iface.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

feat(sdk-coin-avaxp): Verify import in P

---

README.md

Clarify branch usage in release process
BG-000000

chore: update readme release information

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

fix(sdk-core): whitelist source and destination chain params

---

modules/sdk-core/src/coins/ofc.ts

fix: update ofc coin for ibasecoin changes

---

modules/sdk-core/src/bitgo/wallet/iWallet.ts

We want to allow users to determine whether or not to use the keepAlive flag with Polkadot's transferAll functionality.
This was logically implemented in a separate PR: https://github.com/BitGo/BitGoJS/pull/3084
Add this keepAlive option as a generalized Prebuild flag to allow for future use as well as use in Polkadot tx building.
More details:
> Right now this is only used in DOT consolidation's sweep feature.
> When we sweep, we sweep all funds in the address to the destination (including the 1 dot minimum), or if we sweep with keepAlive, we send all funds except for 1 DOT.
> Specifically the current use case of this flag is so the customer can choose to consolidate all addresses' funds, or all except for the 1 DOT minimums.
> Right now, we default to having keepAlive be true (current …

chore(sdk-core): add keepAlive option to PrebuildTransactionOptions

---

modules/express/package.json
yarn.lock

* Resolve github advisories for express and qs
* Advisory: https://github.com/advisories/GHSA-hrpp-h998-j3pp
BG-63378

fix: resolve express and qs dependencies

---

modules/bitgo/test/unit/local.ts
modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/test/unit/bitgoAPI.ts

fix: enable cookie propagation gating in local, pr, dev

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Adds some information.
BG-00000

doc: adding info

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Adds some information.
BG-11430

chore: adding info

---

modules/sdk-coin-avaxp/src/avaxp.ts

fix(sdk-coin-avaxp): verify transaction memo only for p chain tx

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

this ungates creation on forwarder v2
from sdk.
TICKET: BG-61874

feat(sdk-core): allow forwarder version 2

---

modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts

exclude sui signer data

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts

fix(sdk-coin-avaxp): fix parseTransaction throwing error for pending

---

modules/sdk-coin-avaxc/src/avaxc.ts

feat(sdk-coin-avaxc): verify signature for hop export tx

---

modules/sdk-coin-sui/src/sui.ts

Ticket: BG-63779
add Sui allowAccountConsolidations, should support consolidation now

fix(sdk-coin-sui): add allowAccountConsolidations

---

modules/sdk-coin-avaxp/src/lib/iface.ts
modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/test/unit/lib/transactionBuilderFactory.ts

feat(sdk-coin-avaxp): add cros chain data to tx json

---

modules/sdk-coin-trx/package.json
modules/sdk-coin-trx/src/lib/index.ts
modules/sdk-coin-trx/src/lib/tokenTransferBuilder.ts
modules/sdk-coin-trx/src/lib/transaction.ts
modules/sdk-coin-trx/src/lib/utils.ts
modules/sdk-coin-trx/src/lib/wrappedBuilder.ts
modules/sdk-coin-trx/test/resources.ts
modules/sdk-coin-trx/test/unit/transactionBuilder/tokenTransferBuilder.ts
modules/sdk-coin-trx/test/unit/util.ts
modules/statics/src/account.ts
modules/statics/src/coins.ts
modules/statics/src/tokenConfig.ts

Added tron token transaction builder, which utilizes tron's contract call builder. Also needed to update statics.
TICKET: [BG-61339](https://bitgoinc.atlassian.net/browse/BG-61339?atlOrigin=eyJpIjoiMzczZTZmYjJjYzNhNDU1NDk4MDA2ZDJkNjczYTViNDMiLCJwIjoiaiJ9)

feat(sdk-coin-trx): add trx token transaction builder

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore: onboard new batch of tokens

---

modules/statics/src/coins.ts

fix(statics): add missing backing erc20 for fil

---

modules/sdk-coin-trx/src/trx.ts

feat(sdk-coin-trx): add tron tokens in verifyTransaction method

---

modules/sdk-coin-trx/src/lib/index.ts

feat(sdk-coin-trx): export trx token transaction builder

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts

feat(sdk-core): derive unhardened method for ecdsa

---

modules/sdk-coin-dot/src/lib/nativeTransferBuilder.ts

The keepAlive conditional was only overriding the value if the value was true. We want to ensure it is also overriden if false. Update the if condition to check if the input is undefined, rather than check if true and exists.
TICKET: BG-64491

fix(sdk-coin-dot): update DOT sweep keepAlive conditional

---

modules/statics/src/index.ts

feat(sdk-coin-trx): export TronErc20Coin class

---

modules/sdk-coin-trx/src/trx.ts

A trx consolidation will return the address info that should be used to sign the transaction. It includes the chain and index for deriving the signing key from the user key.
Ticket: BG-62372

feat(trx): support signing trx consolidations

---

modules/sdk-coin-trx/package.json
yarn.lock

fix: resolve security audit for jsonwebtoken

---

examples/js/trx/consolidate-account-balances.js
examples/js/trx/create-address.js
examples/ts/trx/consolidate-account-balances.ts
examples/ts/trx/create-address.ts

feat(examples): add conslidation examples for trx

---

modules/bitgo/package.json

Tested here: https://github.com/BitGo/BitGoJS/actions/runs/3833456845
Ticket: BG-64985

build(bitgo): increase memory for bundling

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/types.ts

Ticket: [BG-63193](https://bitgoinc.atlassian.net/browse/BG-63193)
See commit messages for details.
1. Pointed a tss wallet creation script to use the local BitgoJS with these changes.
2. TSS ECDSA wallet creations working
[BG-63193]: https://bitgoinc.atlassian.net/browse/BG-63193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BG-63193]: https://bitgoinc.atlassian.net/browse/BG-63193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sdk-core): get bitgo public key based on coin and feature flags

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-63997 
This pr changes the return of ecdsa tss send to tx detail to stay consistent with our api.
[BG-63997]: https://bitgoinc.atlassian.net/browse/BG-63997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sdk-core): ecdsa tss send return tx request detail

---

modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

This was a bug introduced as part of a refactor from this PR: https://github.com/BitGo/BitGoJS/pull/3102

bug(sdk-core): send the passphrase as correct field for eddsa

---

modules/bitgo/test/v2/unit/recovery.ts
modules/sdk-coin-eth/src/eth.ts

fix(sdk-coin-eth): fix recovery flow, add unit test

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Rename variable to be more clear

chore(sdk-core): rename BitGoKRS to BitGoTrustAsKrs

---

modules/bitgo/test/v2/unit/coins/ofcToken.ts
modules/statics/src/coins.ts
modules/statics/src/ofc.ts

feat(prime): add ofc stellar usdc token

---

modules/bitgo/test/v2/unit/keychains.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

add ATOM coin config
Ticket: [BG-64368](https://bitgoinc.atlassian.net/browse/BG-64368)
[BG-64368]: https://bitgoinc.atlassian.net/browse/BG-64368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(statics): add ATOM coin config

---

modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts

Some UI components like OVC that uses electron can not use node Workers. This PR adds a way to generate a public/private key pair in a Paillier cryptosystem synchronously, so that OVC can use the keyShare function.

fix(ecdsa): allow sync paillier key generation for ovc

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

KeepAlive is a flag used currently in the Polkadot consolidation flow. It determines whether or not to sweep the minimum funding amount of an address during a consolidation tx.
TICKET: BG-66035

feat(sdk-core): add keepAlive as a whitelisted consolidate param

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

`HSM` is now expecting a stringify JSON instead of JSON object. Also need `messageEncoded` to be a hex string of the Buffer instead of just a string represenation, as string representation leads to issues recreating the Buffer in `WP` due to encoding.
Ticket: BG-63009

fix: removing generic typing from typeddata associated with eip712

---

CODEOWNERS
Dockerfile
modules/bitgo/package.json
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/index.ts
modules/bitgo/tsconfig.json
modules/sdk-coin-atom/.eslintignore
modules/sdk-coin-atom/.gitignore
modules/sdk-coin-atom/.mocharc.yml
modules/sdk-coin-atom/.npmignore
modules/sdk-coin-atom/.prettierignore
modules/sdk-coin-atom/.prettierrc.yml
modules/sdk-coin-atom/README.md
modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/atom.ts
modules/sdk-coin-atom/src/index.ts
modules/sdk-coin-atom/src/tatom.ts
modules/sdk-coin-atom/test/integration/index.ts
modules/sdk-coin-atom/test/unit/index.ts
modules/sdk-coin-atom/tsconfig.json
tsconfig.packages.json

Create the module and skeleton class for the Cosmos token ATOM.
TICKET: BG-64363

feat(sdk-coin-atom): create atom module

---

CODEOWNERS
modules/sdk-evm/.eslintignore
modules/sdk-evm/.gitignore
modules/sdk-evm/.mocharc.js
modules/sdk-evm/.npmignore
modules/sdk-evm/.prettierignore
modules/sdk-evm/.prettierrc.yml
modules/sdk-evm/README.md
modules/sdk-evm/package.json
modules/sdk-evm/src/evmWalletKeychains.ts
modules/sdk-evm/src/evmWallets.ts
modules/sdk-evm/src/index.ts
modules/sdk-evm/src/types.ts
modules/sdk-evm/test/unit/evmWallets.ts
modules/sdk-evm/tsconfig.json
tsconfig.packages.json

chore(sdk-evm): project init

---

modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/index.ts
modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/index.ts
modules/sdk-coin-atom/src/lib/keyPair.ts
modules/sdk-coin-atom/src/register.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/keyPair.ts
yarn.lock

feat(sdk-coin-atom): add keyPair management to cosmos

---

modules/sdk-coin-trx/src/trx.ts
modules/sdk-coin-trx/src/trxToken.ts

TICKET: [BG-66457](https://bitgoinc.atlassian.net/browse/BG-66457?atlOrigin=eyJpIjoiMGUwMjEwNjY2ZWYwNGY3NWFhMWIxYTljNzYxN2EzZTciLCJwIjoiaiJ9)
[BG-66457]: https://bitgoinc.atlassian.net/browse/BG-66457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sdk-coin-trx): fix verifyTransaction method for trx tokens

---

modules/sdk-coin-trx/test/resources.ts
modules/sdk-coin-trx/test/unit/transactionBuilder/tokenTransferBuilder.ts

TICKET: [BG-66458](https://bitgoinc.atlassian.net/browse/BG-66458?atlOrigin=eyJpIjoiY2Q1YjBkZGZlODRiNGE1MDhjNDE1NDc4ODk1MjY5ODIiLCJwIjoiaiJ9)
[BG-66458]: https://bitgoinc.atlassian.net/browse/BG-66458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(sdk-coin-trx): add token test for building from signed tx

---

modules/express/src/clientRoutes.ts

Ticket: BG-65857
Test: 
The following transaction was performed using external signer successfully https://explorer.solana.com/tx/gdj8H7jkNZbkAwZeEcNMK1kymmiDAcRR3gXV4Kn1h6DRVTSecUU7gBGXHfpeU4Bh8oHHCjjukkTmANGEfDwuhG4?cluster=devnet
Request:

feat(express): support external signer TSS EdDSA in sendMany express endpoint

---

modules/bitgo/test/v2/unit/coins/ofcToken.ts
modules/statics/src/coins.ts
modules/statics/src/ofc.ts

feat(statics): add ofc algorand usdc token

---

CODEOWNERS

chore(key-card): make wallets team owner of the key-card module

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

fix(sdk-core): get low balance forwarder

---

modules/bitgo/test/unit/bitgo.ts
modules/sdk-api/src/bitgoAPI.ts
modules/sdk-core/src/bitgo/environments.ts

fix(bitgo): remove enforcement of HMAC verification on all non-prod envs

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

fix(sdk-core): fix ecdsa tss wallet creation

---

modules/key-card/.mocharc.js
modules/key-card/package.json
modules/key-card/src/index.ts
modules/key-card/src/utils.ts
modules/key-card/test/unit/utils.ts

This function will later be used to split data into multiple pieces before converting it to QR codes on the key cards.

feat(key-card): add utils function to split keys

---

modules/key-card/src/faq.ts
modules/key-card/test/unit/faq.ts

feat(key-card): add function to generate key card faqs

---

modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts

feat(sdk-core): add challenge endpoint for tss rangeproof

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/opengpgUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/types.ts

feat(sdk-core): use trust backup gpg for encrypting

---

modules/utxo-bin/package.json
yarn.lock

fix(utxo-bin): lock @types/yargs to last working version

---

modules/bitgo/test/v2/unit/internal/opengpgUtils.ts
modules/sdk-core/src/bitgo/utils/opengpgUtils.ts

Adds an ECDSA path to the verifyShareProof function to be used for verifying
ECDSA keyshares.
Ticket: BG-65151
BREAKING CHANGE: The `verifyEdShareProof` function is renamed to
`verifyShareProof` and now expects a 4th parameter which must be a
string of either `eddsa` or `ecdsa`.

feat(sdk-core): add ecdsa to verifyShareProof()

---

examples/js/atom/create-wallet.js

feat(sdk-coin-atom): create wallet script

---

modules/bitgo/test/v2/unit/coins/abstractUtxoCoin.ts
modules/bitgo/test/v2/unit/internal/blsUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/bitgo/test/v2/unit/keychains.ts
modules/bitgo/test/v2/unit/staking/stakingWalletNonTSS.ts
modules/bitgo/test/v2/unit/staking/stakingWalletTSS.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts

feat(sdk-core): add type property to Keychain

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

feat: send enterprise id to backupkeys end-point

---

modules/key-card/package.json
modules/key-card/src/generateQrData.ts
modules/key-card/test/unit/generateQrData.ts
modules/key-card/tsconfig.json

The added functions receive the keycards and some optional extra fields as an input and return an object that can then be passed to the drawKeycard function (to be added in a future PR) to fill the data for the different boxes.

feat(key-card): add code to select qrData

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/types.ts

Types should start with an upper case letter, otherwise they can
be confused with variable names which usually start with a lower case
letter.
BREAKING CHANGE: rename type backupGpgKey to BackupGpgKey

feat(sdk-core): rename type

---

modules/sdk-unified-wallet/src/ecdsa-unified-wallet/ecdsaEVMUnifiedWallets.ts
modules/sdk-unified-wallet/src/iUnifiedWallets.ts
modules/sdk-unified-wallet/src/unifiedWallets.ts
modules/sdk-unified-wallet/test/unit/ecdsaUnifiedWallets.ts

Create all getter API calls:
- `getUnifiedWalletById`
- `getUnifiedWalletByAddress`
- `getAllUnifiedWallets`

Bg 65105 get wallet API calls

---

modules/account-lib/package.json
modules/account-lib/src/index.ts
modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/index.ts
modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/iface.ts
modules/sdk-coin-atom/src/lib/index.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-atom/src/lib/transferBuilder.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/transaction.ts
yarn.lock

Adds basic functionality for decoding transactions for ATOM transfers.
Also added skeleton for transaction builder factory, transfer builder, and account-lib exposure.
Will be working on adding additional testing in follow up PRs, working out skeleton right now to unblock account-lib KeyPair access on the WP side.
TICKET: BG-64363

feat(sdk-coin-atom): skeleton for transaction building and account-lib ATOM

---

modules/web-demo/README.md

chore(web-demo): add README

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

feat(sdk-core): ecdsa signing use derivation path

---

modules/key-card/src/generateQrData.ts
modules/key-card/test/unit/generateQrData.ts

The recovery process for when BitGo Trust holds the backup key for TSS wallets looks a bit different from the normal recovery flows. The purpose of the key card for TSS wallets where BitGo Trust holds the backup key is for the scenario where BitGo Inc goes out of business. In this situation BitGo Trust will publish the encrypted backup seed. Users will then be able to combine it with the two key shares on their key card (from user and from BitGo to backup).

feat(key-card): support BitGo Trust holding TSS backup key

---

modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/utils.ts

feat(atom): implement basic util methods for atom

---

modules/sdk-coin-sui/package.json
modules/sdk-coin-sui/src/lib/constants.ts
modules/sdk-coin-sui/src/lib/keyPair.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilder.ts
modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts

Ticket: BOS-933
- add intent bytes to signable hex (signablePayload)
- add serialized signature to include Signature scheme bytes, signature, public key

fix(sdk-coin-sui): fix sui signing

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/express/encryptedPrivKeys.json
modules/express/test/unit/clientRoutes/externalSign.ts
modules/sdk-coin-bsc/test/unit/transactionBuilder/send.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/rangeproof.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

TICKET: BG-67692
If we want to do this, all tests pass locally.

feat(account-lib): make rangeproof stuff async

---

modules/sdk-core/src/bitgo/keychain/keychains.ts

- check for keychain type when creating ChangedKeychains map
Ticket: CR-846

fix(sdk-core): update password for tss

---

modules/bitgo/test/v2/unit/coins/ofcToken.ts
modules/statics/src/coins.ts
modules/statics/src/ofc.ts

feat(statics): add ofc hedera usdc token

---

examples/ts/sui/build-pay-transaction.ts
examples/ts/sui/create-wallet.ts
modules/sdk-coin-sui/package.json
modules/sdk-coin-sui/src/lib/bcs.ts
modules/sdk-coin-sui/src/lib/constants.ts
modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/stakingTransaction.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilder.ts
modules/sdk-coin-sui/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sui/src/lib/transferBuilder.ts
modules/sdk-coin-sui/src/lib/transferTransaction.ts
modules/sdk-coin-sui/src/lib/txnSchema.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/payTransaction.ts
modules/sdk-coin-sui/test/unit/stakingTransaction.ts
modules/sdk-coin-sui/test/unit/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/stakingBuilder.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transferBuilder.ts
yarn.lock

BOS-892
1. Refactor and create generic transaction and transactionBuilder to support TransferTx and StakingTx 
2. Creates StakingTransaction and StakingBuilder
2. Serialize and deserialize `RequestAddDelegation` transaction

feat(sdk-coin-sui): add support for staking transactions

---

modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/stakingTransaction.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sui/src/lib/txnSchema.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/stakingBuilder.ts

feat(sdk-coin-sui): add withdrawDelegation staking tx

---

modules/key-card/package.json
modules/key-card/src/drawKeycard.ts
modules/key-card/src/generateQrData.ts
modules/key-card/src/index.ts
modules/key-card/test/unit/generateQrData.ts
modules/web-demo/src/components/KeyCard/index.tsx
yarn.lock

* check out the PR branch locally
* run the following commands
```
yarn install
cd modules/web-demo
yarn dev
```
Open `localhost:8080/keycard` in your browser and click on the Download button. This should generate and download a key card, compare it against the one attached to this PR:
[BitGo Keycard for Hello World.pdf](https://github.com/BitGo/BitGoJS/files/10697355/BitGo.Keycard.for.Hello.World.pdf)

feat(key-card): add support for qrcodes

---

modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/iface.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/getBuilderFactory.ts
modules/sdk-coin-atom/test/unit/transaction.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transferBuilder.ts

We found that we no longer need the accountNumber or the chainId to properly construct a raw tx.
Also adds more testing regarding transactionBuilder and factory building.
TICKET: BG-67573

refactor(sdk-coin-atom): only decode sequence from raw atom tx

---

modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/index.ts
modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/stakingTransaction.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sui/src/lib/txnSchema.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/stakingTransaction.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/stakingBuilder.ts
modules/sdk-core/src/account-lib/baseCoin/enum.ts

feat(sdk-coin-sui): add switch delegation tx

---

modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts

chore(sdk-core): require privateShareProof from third party

---

modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

fix(sdk-core): ecdsa signing vss share

---

.iyarc

TICKET: BG-68073
https://github.com/github/advisory-database/pull/1693
https://github.com/sindresorhus/got/issues/2220

chore(sdk-core): ignore false positive causing SDK builds to fail

---

modules/bitgo/test/v2/unit/tss/eddsa.ts
modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

fix(sdk-core): eddsa signing vss share

---

modules/key-card/src/drawKeycard.ts
modules/web-demo/src/components/KeyCard/fixtures.ts

Upon printing some key cards it was realized that some QR codes could get too dense for being able to scanned by a phone. This commit reduces the density of the QR codes and arranges them properly across multiple pages if necessary.
Ticket: BG-67970
1. Check out this branch locally
2. Run `yarn install` in the root of the repository
3. `cd modules/web-demo`
4. `yarn dev`
5. Go to http://localhost:8080/keycard
6. Download all three types of key cards and compare to the ones attached to this PR.
[BitGo Keycard for SMHA Polygon Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10734322/BitGo.Keycard.for.SMHA.Polygon.Wallet.pdf)
[BitGo Keycard for Hot ETH TSS Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10734323/BitGo.Keycard.for.Hot.ETH.TSS.Wallet.pdf)
[BitGo Keycard for Hot LTC …

fix(key-card): reduce size of QR codes

---

modules/key-card/src/generateQrData.ts
modules/key-card/test/unit/generateQrData.ts

In Box B we now put both "toBackup" key shares which allows us to leave Box C as it was before (the common keychain). This has the benefit that it follows more closely the format that we use for regular TSS wallets.
Ticket: BG-68191
1. Check out this branch locally
2. Run `yarn install` in the root of the repository
3. `cd modules/web-demo`
4. `yarn dev`
5. Go to http://localhost:8080/keycard
6. Download the key card for the Self Managed Advanced Hot Polygon Wallet and compare to the one attached to this PR.
[BitGo Keycard for SMHA Polygon Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10743264/BitGo.Keycard.for.SMHA.Polygon.Wallet.pdf)

feat(key-card): change contents of Boxes B & C for SMHA wallets

---

modules/sdk-unified-wallet/src/ecdsa-unified-wallet/types.ts

fix(sdk-unified-wallet): fix typo in coin names

---

modules/statics/src/account.ts
modules/statics/src/ada.ts
modules/statics/src/avaxp.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/errors.ts
modules/statics/src/ofc.ts
modules/statics/src/utxo.ts
modules/statics/test/unit/coins.ts

Generate and add UUIDs to all of the assets currently supported in BitGoJS/statics.
The AMS will support getting assets by name or id
Ticket: BG-66595

feat(statics): add a unique id to every asset

---

modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transactionBuilder.ts

feat(sdk-coin-atom): add function to validate amount data

---

modules/bitgo/test/v2/unit/tss/helpers.ts
modules/sdk-core/src/bitgo/tss/common.ts

fix: use post on get challenge end-point

---

modules/statics/src/errors.ts
modules/statics/src/map.ts
modules/statics/test/unit/coins.ts

feat(statics): enable getting asset by id

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

fix(sdk-core): append bitgo challenge to bitgo a share

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

fix(sdk-core): fix parameter misordering for user gpg key

---

modules/bitgo/test/v2/lib/recovery-nocks.ts
modules/bitgo/test/v2/unit/recovery.ts
modules/sdk-coin-trx/src/lib/iface.ts
modules/sdk-coin-trx/src/lib/utils.ts
modules/sdk-coin-trx/src/trx.ts

Adding tron token support to tron recovery method. 
TICKET: [BG-67603](https://bitgoinc.atlassian.net/browse/BG-67603?atlOrigin=eyJpIjoiNjZmZWIwYjA0MTE5NGY1ZWE2MzI4YmE4YzEzNTFlM2MiLCJwIjoiaiJ9)
[BG-67603]: https://bitgoinc.atlassian.net/browse/BG-67603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sdk-coin-trx): add tokens to tron recovery method

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

feat: onboard new sol tokens

---

modules/sdk-unified-wallet/src/ecdsa-unified-wallet/ecdsaEVMUnifiedWallets.ts
modules/sdk-unified-wallet/src/unifiedWallets.ts

As part of BGMS API [response changes](https://github.com/BitGo/bitgo-microservices/pull/29315), we needed to modify the SDK to accomodate said changes in `sdk-unified-wallet`.

Bg 68337 bug fixes

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore: add new tokens

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

BREAKING CHANGE: return txreqid and raw message

---

modules/sdk-unified-wallet/README.md

chore: add readme to unified-wallet

---

modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/atom.ts
modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/iface.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/atom.ts
modules/sdk-coin-atom/test/unit/transaction.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transferBuilder.ts
modules/sdk-coin-atom/test/unit/utils.ts

feat(sdk-coin-atom): add support to serialise unsigned txn

---

modules/statics/src/coins.ts

BREAKING CHANGE: overrode address coin from deprecated teth to gteth for tofcerc20s
Ticket: [BG-69417](https://bitgoinc.atlassian.net/browse/BG-69417)
Please see parent ticket for context: [BG-69357](https://bitgoinc.atlassian.net/browse/BG-69357)
[BG-69357]: https://bitgoinc.atlassian.net/browse/BG-69357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BG-69417]: https://bitgoinc.atlassian.net/browse/BG-69417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(statics): set addressCoin to gteth for new tofcerc20 tokens

---

modules/statics/src/coins.ts

updating tbsc:busd with updated
fauset address
BREAKING CHANGE: updated contract address for tbsc:busd
TICKET: BG-69321

fix(statics): update tbsc:busd contract

---

modules/sdk-core/src/bitgo/wallet/iWallet.ts

- `halfSigned` in `params` of `submitTransaction` accepts `signedChildPsbt`
- `signedChildPsbt` is PSBT that has the output of `txHex` in `halfSigned`
- as input with a signature
- parsing and validations will be done in the backend server
Ticket: BG-68142

feat(sdk-core): add signedChildPsbt to halfSigned object

---

modules/sdk-coin-eth/src/eth.ts

fix(eth): consolidation verification tx params

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/constants.ts
modules/statics/src/tokenConfig.ts
modules/statics/test/unit/account.ts
modules/statics/test/unit/constants.ts

added xrp token config and test token
BG-69212

feat(statics): add xrp token config and test token

---

modules/sdk-unified-wallet/src/iUnifiedWallets.ts
modules/sdk-unified-wallet/src/types.ts
modules/sdk-unified-wallet/src/unifiedWallets.ts
modules/sdk-unified-wallet/test/unit/ecdsaUnifiedWallets.ts

Bg 69090 evm wallets pagination

---

modules/sdk-coin-sui/src/sui.ts

feat(sui): implement generateKeyPair

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

chore(statics): onboard new batch of tokens

---

modules/sdk-coin-atom/package.json
modules/sdk-coin-atom/src/atom.ts
modules/sdk-coin-atom/src/lib/StakingActivateBuilder.ts
modules/sdk-coin-atom/src/lib/StakingDeactivateBuilder.ts
modules/sdk-coin-atom/src/lib/StakingWithdrawRewardsBuilder.ts
modules/sdk-coin-atom/src/lib/constants.ts
modules/sdk-coin-atom/src/lib/iface.ts
modules/sdk-coin-atom/src/lib/keyPair.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-atom/src/lib/transferBuilder.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/atom.ts
modules/sdk-coin-atom/test/unit/transaction.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingActivateBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingDeactivateBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingWithdrawRewardsBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-atom/test/unit/utils.ts
yarn.lock

Ticket: BG-69278
BREAKING CHANGE: type MessageData is changed

feat(sdk-coin-atom): add staking transaction builders

---

modules/statics/src/networks.ts

updating explorer urls for bsc to
correctly link transfers
TICKET: BG-70893

fix(statics): update explorer urls for bsc

---

modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/unit/transaction.ts

fix(sdk-coin-atom): allow transaction creation from both Hex and Base64

---

CODEOWNERS

chore(CODEOWNERS): move core functionality to shared ownership

---

modules/sdk-coin-bsc/src/tbsc.ts
modules/sdk-coin-bsc/test/unit/bsc.ts

this change allows account consolidations
for tbsc
TICKET: BG-71550

feat(tbsc): allow account consolidations

---

modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/mystenlab/framework/sui-system-state.ts
modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/stakingTransaction.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transferTransaction.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/stakingBuilder.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-sui/test/unit/transferTransaction.ts

feat(sdk-coin-sui): build staking transaction

---

modules/sdk-coin-sui/src/lib/stakingTransaction.ts
modules/sdk-coin-sui/test/unit/sui.ts

fix(sdk-coin-sui): staking explain transaction

---

modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transferBuilder.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts

fix(sdk-coin-sui): tx signing flow

---

modules/sdk-coin-sui/src/lib/constants.ts
modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/stakingBuilder.ts
modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sui/src/lib/unstakingBuilder.ts
modules/sdk-coin-sui/src/lib/unstakingTransaction.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/unstakingBuilder.ts

feat(sdk-coin-sui): build unstaking transaction

---

modules/sdk-coin-sui/src/lib/index.ts

fix(sdk-coi-sui): export unstaking

---

modules/sdk-coin-sui/src/lib/unstakingTransaction.ts

fix(sdk-coin-sui): fix tx type

---

modules/sdk-coin-atom/src/lib/iface.ts
modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/src/lib/utils.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/atom.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transferBuilder.ts

feat(sdk-coin-atom): add memo support for atom

---

modules/sdk-coin-atom/src/atom.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/atom.ts

Implemented isWalletAddress for atom coin

---

modules/sdk-coin-xrp/src/xrp.ts

TICKET: [BG-76963](https://bitgoinc.atlassian.net/browse/BG-76963?atlOrigin=eyJpIjoiZTNkNTMzZDdiMzJkNDM4OWJkMzc2NTZjOTFmZDgwYjYiLCJwIjoiaiJ9)
[BG-76963]: https://bitgoinc.atlassian.net/browse/BG-76963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(sdk-coin-xrp): add coin field to xrp unsigned transaction

---

CODEOWNERS

fix(bitgo): update codeowners file to reflect team rename

---

modules/sdk-coin-sui/src/lib/transferBuilder.ts
modules/sdk-coin-sui/src/lib/transferTransaction.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/unit/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transferBuilder.ts

fix(sui): support split coin

---

modules/sdk-coin-sui/src/lib/utils.ts

fix(sui): fix amount parsing

---

modules/sdk-coin-sui/.prettierignore
modules/sdk-coin-sui/src/lib/mystenlab/README.md

docs(sdk-coin-sui): add README.md for lib/mystenlabs/

---

CODEOWNERS

- adds hsm as codeowners to sdk-core and sdk-lib-mpc
- updates wallets to wallet-platform

feat(root): update codeowners

---

modules/sdk-coin-ada/src/lib/utils.ts
modules/sdk-coin-ada/test/resources/index.ts
modules/sdk-coin-ada/test/unit/utils.ts

support validation for validator address
EA-513

chore(ada): update `isValidAddress` implementation

---

CODEOWNERS

chore: change codeowners to use ethalt-team instead of eth-team

---

modules/key-card/src/drawKeycard.ts

fix(key-card): key-card no longer throws NPE if passcode QR undefined

---

CODEOWNERS

updated CODEOWNERS for core modules
WP-345

chore(root): update CODEOWNERS for core modules

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

chore(sdk-core): add clarity to other commonKeychain util

---

modules/sdk-core/.mocharc.js
modules/sdk-core/package.json

This allows running individual tests from IntelliJ
Issue: BTC-368

fix(sdk-core): move --recursive flag to package.json

---

modules/sdk-core/src/bitgo/utils/codecProps.ts
modules/sdk-core/src/bitgo/wallet/BuildParams.ts
modules/sdk-core/src/bitgo/wallet/SendTransactionRequest.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
modules/sdk-core/test/unit/bitgo/wallet/SendTransactionRequest.ts

Foray into io-ts codecs in SDK. This is a first step towards validating
the request body before sending it to the server.
We are phasing it in gradually, so that we discover any issues with
the codec in a controlled manner.
Issue: BTC-368

feat(sdk-core): add, use SendTransactionRequest codec

---

modules/bitgo/test/v2/unit/accountConsolidations.ts
modules/sdk-core/src/bitgo/wallet/BuildParams.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
modules/sdk-core/test/unit/bitgo/wallet/SendTransactionRequest.ts

feat(sdk-core): use BuildParams codec in Wallet.sendAccountConsolidation

---

modules/sdk-lib-mpc/src/util.ts
modules/sdk-lib-mpc/test/unit/util.ts

feat(sdk-core): add getDerivationPath method for smc wallets

---

modules/sdk-core/src/bitgo/environments.ts

chore(sdk-core): update zeta testnet URL

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Currently the sign method returns a VAShare that includes bigints but the default JSON cant parse bigints, until phase 5 is implemented and fixed, we filter out the not needed fields of the response for external signer S share step
WP-708
TICKET: WP-708

fix(sdk-core): fix ecdsa with external signer

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Added a new method to get the user key and sign a tss tx
WP-799
TICKET: WP-799

feat(sdk-core): add new method to sign tss txs

---

modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/iWallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

feat(sdk-core): add distributed custody params to wallet creation

---

modules/bitgo/test/unit/bitgo.ts
modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts

chore: add ecdh keychain creation on login

---

modules/sdk-core/src/bitgo/keychain/keychains.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

`isDistributedCustody` is a boolean, not a stirng
TICKET: BTC-553

fix(sdk-core): fix dc wallet creation

---

modules/sdk-api/src/v1/transactionBuilder.ts

chore: log unspents when creating a v1 transaction

---

modules/bitgo/test/v2/unit/coins/utxo/util/keychains.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

New bulk flag signals to build N number of consolidate txs
TICKET: BTC-608

feat(sdk-core): add support for bulk unspent consolidation

---

modules/bitgo/README.md

updated examples link to point to the root directoy examples
WP-0000
TICKET: WP-0000

docs(bitgo): update example link

---

modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Added source check for bitgo key for TSS SMC wallet creation to avoid continuing if the id provided is not a bitgo key
WP-991
TICKET: WP-991

fix(root): add source to tss smc wallet creation

---

modules/sdk-core/src/bitgo/utils/opengpgUtils.ts
modules/sdk-test/src/bitgo/lib/test_bitgo.ts

test(bitgo): tests should used nocked public key

---

modules/sdk-core/src/bitgo/staking/iStakingWallet.ts

TICKET: EA-2430
STX staking would need FE to pass in `duration` and `subType`.
Duration as in the number of delegation cycles.
SubType is to distinguish delegation vs self-stack.
corresponding change in `staking-service`: https://github.com/BitGo/staking-service/pull/1639

feat(sdk-core): add optional StakeOptions fields to support STX staking

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(sdk-core): provide skipKeychain to wallet share API request

---

CODEOWNERS

feat: add prime to codeowners

---

modules/sdk-core/src/bitgo/staking/iStakingWallet.ts

Add subtype to unstaking request.
Ticket: EA-2564
TICKET: EA-2564

chore(staking): add unstaking subtype

---

modules/sdk-core/src/bitgo/wallet/BuildParams.ts
modules/sdk-core/test/unit/bitgo/wallet/BuildParams.ts

feat: whitelist rbf build params

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

fix: add pendingApprovaId in prebuildTxTss response

---

modules/sdk-core/src/bitgo/staking/iStakingWallet.ts

Ticket: EA-2440
TICKET: EA-2440

chore(sdk-core): add cancel request to staking wallet interface

---

modules/deser-lib/.npmignore

fix(deser-lib): add .npmignore to deser-lib

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/test/unit/bitgoAPI.ts

The c'tor was changed after the version bump to v6.
Added unit test and manually tested with one of the example.
Ticket: WP-1431

fix(sdk-api): fix proxy after proxy-agent version bump

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/commsLayer.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/types.ts

fix(sdk-lib-mpc): fix mpcv2 commitment and signatureR serialization

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/util.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDsg.ts

feat(sdk-lib-mpc): add derivation to verify mpcv2 signature

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dkg.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dsg.ts

fix(sdk-lib-mpc): fix wasm init in mpcv2 wallets

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/util.ts

fix(sdk-lib-mpc): fix mpcv2 sig combine to pad signatures to 64 bytes

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/test/unit/bitgoAPI.ts

feat: support bech32 recipient for v1 wallets

---

modules/sdk-lib-mpc/package.json
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dkg.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dsg.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/types.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/util.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDkg.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDsg.ts

Support general t of n retrofit

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/v1/transactionBuilder.ts
modules/sdk-api/src/v1/verifyAddress.ts
modules/sdk-api/test/unit/v1/wallet.ts

feat: support creating v1 transaction to bech32 recipient 

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts

Ticket: [CE-4038](https://bitgoinc.atlassian.net/browse/CE-4038)
This PR introduces a forReset2fa flag in the authentication options. When forReset2fa is set to true, it enables the creation of an authenticated session using the user_2fa_reset scope with only the username and password. This allows the user to perform a 2FA reset.
[CE-4038]: https://bitgoinc.atlassian.net/browse/CE-4038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add forReset2fa flag in authenticate options

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dkg.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/util.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDkg.ts

Support seeded mpcv2 dkg

---

modules/express/.env.example
modules/express/EXTERNAL_SIGNER.md
modules/express/src/fetchEncryptedPrivKeys.ts

Updated external signer doc, with the right format for env vars
WP-0000
TICKET: WP-0000

docs(express): minor updates for external signer docs

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/commsLayer.ts

fix(sdk-lib-mpc): fix time warp issues with pgp verifications

---

modules/sdk-api/src/v1/transactionBuilder.ts

Ticket: BTC-1351
TICKET: BTC-1351

feat: add debug logs to transactionBuilder

---

CODEOWNERS

Added .iyarc to the Codeowners file, owned by WP, HSM and Velocity team. This file is used to ignore yarn vulnerabilities checks
WP-2463
TICKET: WP-2463

ci(root): add .iyarc to Codeowners

---

CODEOWNERS

Change code owner to btc team for lightning coin
TICKET: BTC-1477

feat(express): fix CODEOWNERS file

---

modules/express/src/clientRoutes.ts

signerSteps to signerStep
TICKET: BTC-1487

fix(express): typo in express signer param name for musig2 sign

---

modules/sdk-api/.mocharc.js
modules/sdk-api/package.json

Otherwise it is impossible to run single test files from IntelliJ
Issue: BTC-1351

fix: move spec to unit-test script

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts

Ticket: WP-2592
Add a new method `authenticateWithPasskey`

feat(sdk-api): authenticate with passkey params

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/index.ts

changed the redirectRequest method so it returns the original status from WP not only the body of the response
[WP-2961](https://bitgoinc.atlassian.net/browse/WP-2961)
TICKET: [WP-2961](https://bitgoinc.atlassian.net/browse/WP-2961)
[WP-2961]: https://bitgoinc.atlassian.net/browse/WP-2961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WP-2961]: https://bitgoinc.atlassian.net/browse/WP-2961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(express): fix express overriding 2xx status

---

modules/deser-lib/src/cbor.ts
modules/deser-lib/test/unit/deser-lib.ts

chore(deser-lib): remove canonical ordering

---

modules/express/README.md

See [Slack thread](https://bitgo.slack.com/archives/C057BHBRG4B/p1738252860991539) from[ #notify-dev-portal](https://bitgo.enterprise.slack.com/archives/C057BHBRG4B).

docs: Update README.md

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/test/unit/bitgoAPI.ts

feat(sdk-api): add support of v3 in sdk-api

---

modules/express/EXTERNAL_SIGNER.md
modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/signPayload.ts

feat(express): take walletPassphrase as body parameter

---

modules/express/src/clientRoutes.ts

To differentiate between backend and express route. When used for lightning the express route will do extra layer of verificaiton to ensure the request comes from the user with the correct auth key.
Ticket: BTC-0

refactor: add express prefix to update wallet route

---

modules/sdk-api/src/bitgoAPI.ts
modules/sdk-api/src/types.ts

fix: fixed baseeth half-signed txn generation

---

modules/express/README.md

fix(express): display corruption in markdown #5747

---

CODEOWNERS

chore:changing codeowner for lightning examples

---

modules/sdk-api/src/bitgoAPI.ts

chore: add non bitgo recovery mon,stt,soneium,world

---

modules/sdk-api/src/bitgoAPI.ts

The AMS endpoints are public and do not need any HMAC validations, this PR adds a method to create and execute requests for public AMS endpoints. A follow up PR will be created in `bitgo` package to use this method and fetch asset details.
Ticket: WIN-5839

feat(sdk-api): add method to create request for public AMS endpoints

---

modules/sdk-api/src/bitgoAPI.ts

- Added code in `fetchConstants()` to check if `getAdditionalHeadersCb` is set
- When available, retrieves additional headers using the callback with appropriate parameters
- Applies any returned headers to the request before execution
TICKET: WP-000000

feat(root): use additonal headers on constants fetch

---

modules/express/src/clientRoutes.ts
modules/express/src/expressApp.ts
modules/express/src/typedRoutes/api/common/login.ts
modules/express/src/typedRoutes/api/index.ts
modules/express/test/unit/typedRoutes/decode.ts

feat(express): migrate user.login to typed routes

---

modules/express/src/clientRoutes.ts
modules/express/src/typedRoutes/api/common/verifyAddress.ts
modules/express/src/typedRoutes/api/index.ts
modules/express/test/unit/typedRoutes/decode.ts

feat(express): migrate verify address to typed routes

---

modules/express/src/typedRoutes/api/index.ts
modules/express/src/typedRoutes/api/v1/acceptShare.ts
modules/express/test/unit/typedRoutes/acceptShare.ts

fixing test cases and moving to appr file
Ticket: WP-5407

fix(express): fix testcases and move to correct file

---

CODEOWNERS

ci: change codeowners for lockfiles to sdk-reviewers team

---

modules/sdk-coin-canton/package.json

Ticket: [WP-6258](https://bitgoinc.atlassian.net/browse/WP-6258)
[WP-6258]: https://bitgoinc.atlassian.net/browse/WP-6258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(sdk-coin-canton): added 'files' in package json to fix the publish issue

---

modules/express/src/clientRoutes.ts
modules/express/src/typedRoutes/api/index.ts
modules/express/src/typedRoutes/api/v2/walletRecoverToken.ts
modules/express/test/unit/typedRoutes/walletRecoverToken.ts

feat(express): migrate recover token to typed routes
