example/transactionOPReturn.js

`bitcoinjslib.scripts` should be`bitcoinjslib.script`
See https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/advanced.js#L36

opreturn example, fix incorrect bitcoinjs-lib reference

---

src/transactionBuilder.js

Some engineers might be confused with "dust" in this context...
dust in the context of outputs is the limit that defines a standard transaction by the value of its outputs being over `((34+148)÷1000)×(3×minRelayTxFee)` which with current default of 0.00001 BTC will give 0.00000546 BTC
dust in the context of spending a utxo (adding an input) is "if you must spend more than x% of the value of the unspent to pay the extra fees from the added unspent, you should consider not including it at all"
There is currently no best practice for what x is, and fee estimation algorithm variance can greatly affect the meaning of dust in this context...
but at the very least we should address this fact so novice developers say "oh, well I never got a 546 satoshi or less utxo before so I'm good." when a …

Fix typo and add explanation of minUnspentSize

---

package-lock.json
package.json

Prova-lib is a fork of bitcoinjs-lib, with added support for the RMG blockchain. It was recently updated to fix a vulnerable dependency, and so we need to update to 0.2.10 to pick up that fix.

BG-9007: update prova to 0.2.10

---

src/expressApp.js
test/v2/integration/bitgoExpress.js

BG-9093: Prevent proxying of non-api routes through bitgo-express

---

src/v2/coins/xlm.js

Summary: We need to be able to catch the csp error in the client.
Reviewers: bigly, luis
Subscribers: tyler
Differential Revision: https://phabricator.bitgo.com/D10765

BG-9047 - Throw error on federation lookup csp error

---

README.md
src/errors.js
src/expressApp.js
test/v2/unit/bitgoExpress.js

When node is running in development mode, it can output some debugging information which reveals sensitive data about the system running bitgo-express. It is currently possible to run express against the BitGo production environment, while the node environment is development (which is the default), thus potentially exposing customer system information.
By requiring that NODE_ENV is production when running against prod, express will not output this debugging information.
Note that this behavior is overridable by passing the `--disableenvcheck` flag when starting bitgo express, in case some customer wants to keep using the current behavior.

BG-9584: Require node production config when running express against prod

---

src/v2/coins/abstractUtxoCoin.js
src/v2/errors.js
test/v2/unit/coins/abstractUtxoCoin.js

https://bitgoinc.atlassian.net/browse/BG-9024
[BG-9024] Currently verifyAddress throws if a custom address is provided with no chain and index. We should allow custom addresses. So if no chain and index are provided to the "verifyAddress," we return and allow the user to continue with their custom output address.
successfully tested with the script linked in the duplicate ticket here: https://bitgoinc.atlassian.net/browse/BG-8650

[BG-9024] verifyAddress change

---

src/bitgo.js

Let's not print a big scary error message if users want to use bitgo offline. Instead leave the one-line warning log, but move the big stack trace message to "debug".

BG-9640 suppress offline error message

---

src/config.js
src/v2/baseCoin.js
src/v2/coins/ofc.js
src/v2/coins/ofcToken.js
test/v2/unit/coins/ofc.js
test/v2/unit/coins/ofcToken.js

I've attached some example code using this. 
[ofc_spend.txt](https://github.com/BitGo/BitGoJS/files/2763140/ofc_spend.txt)

BG-9228: Add support for ofc tokens and signing transactions.

---

src/v2/baseCoin.js
src/v2/coins/susd.js
src/v2/coins/tsusd.js
test/v2/unit/coins/ofcToken.js
test/v2/unit/coins/susd.js

I did the bare minimum so that the coin itself can be used when requesting resources from the server. The following should work:
```
const Promise = require('Bluebird');
const co = Promise.coroutine;
const BitGoJS = require('../src/index.js');
const env = 'localNonSecure';
const accessToken = 'v2x1234';
const bitgo = new BitGoJS.BitGo({ env });
co(function *() {
bitgo.authenticateWithAccessToken({ accessToken });
const res = yield bitgo.coin('tsusd').pendingApprovals().list({ walletId: '5c0edba1a1d79908e1409f8b4612f5da' }); // you have to be a user on the wallet
console.log(res.pendingApprovals[0]);
})();
```

BG-10483: Adding SUSD coin to SDK

---

src/v2/coins/abstractUtxoCoin.js

The recovery route was not including the amount for some altcoins, because it had a different name ("value_int" vs "amount") when getting it from the public block explorer

[BG-10112] must include amount for altcoins

---

src/transactionBuilder.js
src/wallet.js
test/unit/wallet.js

This change allows you to request segwit ledger unspents from `wallet.unspents()`, as well as allowing you to pass in custom unspent fetch params to `TransactionBuilder.createTransaction()`. The custom unspent fetch params will be passed to `wallet.unspents()` inside `createTransaction()`.
This change also adds a test to ensure that custom unspent fetch params are correctly passed from `createTransaction()` through to `wallet.unspents()`

BG-10687: Allow fetching and usage of ledger segwit unspents

---

test/scripts/ci.sh

* Today a vulnerability was announced in a dependency of karma: https://nodesecurity.io/advisories/786
* The fix has not yet been included in karma, causing npm audit failures
* Travis fails if npm audit fails, so we need to temporarily disable that in order for builds to pass

BG-10736: Temporarily disable npm audit to unbreak travis

---

src/bitgo.js
test/unit/bitgo.js

We need to add a connection to the microservices api
the client microservices will use the sdk to make the requests to the backend microservices.
this allows client microservices to use the authenticate method of the sdk to call teh auth-service login method instead of platform login method
client microservices can also make sdk calls using the microservicesUrl that is passed in.

BG-10632 / SDK to Microservices connection

---

src/v2/coins/eth.js

There is no reason for this and it causes pain when debugging
problems.
If we want some soft fallback we at least have to track the error that
was given, and guard all calls that depend on the unavailable packages.

BG-10459: Do not swallow errors for eth dependencies

---

src/v2/wallet.js
test/v2/integration/wallet.js

Only wallets returned from wallet.get() will have the receiveAddress property,
and specifically, wallets returned from wallets.list() will not have this property.
This causes an access of an undefined property when we try to create a
new address on these wallets.

BG-6956: Fix access of undefined property in createAddress

---

src/v2/wallets.js

Jira Ticket: [BG-9575](https://bitgoinc.atlassian.net/browse/BG-9575)
We need to pass the root private when we create the wallet so that the keycard matches with the wallet root address.
API already supports this, we just need to update sdk to pass the parameter along.
- Create an stellar wallet using: https://github.com/BitGo/bitgo-client-private/pull/1076
- After the wallet is created the keycard box C must be the wallet address

BG-9575 - Add root private key for wallet add

---

src/config.js

The token actually has 2 decimals, not 8

[BG-11145] Change BlockBid token decimals

---

src/config.js
src/v2/recovery.js
test/v2/lib/recovery-nocks.js
test/v2/unit/recovery.js

https://bitgoinc.atlassian.net/browse/BG-9989
Necessary SDK change to allow WRW to support BSV wrong-chain recoveries

BG-9989 support bsv cross-chain recovery

---

src/v2/wallet.js

Superseded by chain. Safe to remove because it was never used in platform.

BG-11182: Remove bech32 arg from createAddress

---

src/v2/coins/abstractUtxoCoin.js
test/v2/unit/coins/btc.js

BG-11239: Handle undefined txInfo for p2sh-p2wsh txs in `explainTransaction()`

---

src/v2/coins/abstractUtxoCoin.js
src/v2/coins/bch.js
test/v2/unit/coins/bch.js
test/v2/unit/coins/btc.js
test/v2/unit/coins/ltc.js

- BCH cashaddr addresses were incorrectly being called bech32
addresses. Cashaddr is similar to bech32 but not the same so this
was cleaned up to avoid confusion between the two.
- Bech32 was being used in abstractUtxoCoin to describe inputs.
Bech32 is an address format; native segwit is the input type.
This was cleaned up as well.

BG-8732: Clean up usage of bech32 as a var name

---

src/v2/coins/abstractUtxoCoin.js

BG-11426: Treat errors thrown from verifySignature as invalid signatures

---

package-lock.json
package.json

In order to build an electron app on macOS we need to fall back to `ripemd160` if `rmd160` is not supported. Updated `bitgo-utxo-lib` and released v1.3.1 to npm.

BG-10188 bump bitgo-utxo-lib version

---

package-lock.json
package.json
src/errors.js
src/v2/coins/abstractUtxoCoin.js
src/v2/coins/btc.js
src/v2/coins/btg.js
src/v2/coins/ltc.js
test/v2/unit/coins/btc.js
test/v2/unit/coins/btg.js
test/v2/unit/coins/ltc.js
test/v2/unit/recovery.js

Currently there are 4(!) params in generateAddress that conflict in
specifying what kind of address to create. Chain is the ultimate
source of truth in determining what kind of unspent (and thus what
kind of address) is created by our platform. This commit deprecates
the addressType, segwit, and bech32 params from the generateAddress
function. However, since they are already in the SDK API they are
not removed in this commit, nor is their functionality changed.
There are only two functionality changes to the function. The
first is a check that the addressType derived from addressType,
segwit, and bech32 matches the chain passed. Otherwise an error is
thrown. The second is to check that wrapped segwit is supported
when creating an address for a wrapped segwit unspent. This check
already …

BG-11323: Deprecate conflicting params in generateAddress

---

src/bitcoin.ts
src/errors.ts
src/v2/coins/txrp.ts
src/v2/coins/xrp.ts

Additionally, this pull request runs prettier on txrp.ts and xrp.ts, and updates the eslint rules so that prettier output satisfies eslint.
Will squash before merging. The first commit adds type information, the second and third are the result of running prettier on the first commit.

BG-11566: Add type information for XRP

---

README.md

Replace the git clone example with "npm install bitgo".  This is the
traditional way to install 3rd party dependencies with npm.  Clean up
trailing white space.
---
https://bitgoinc.atlassian.net/browse/BG-11677

BG-11677: Update npm install instructions

---

package-lock.json
package.json

Use caret dependency to avoid having to do this kind of change in the
future.
Issue: BG-11717

BG-11717: Fix build, update @bitgo/unspents to 0.5.1

---

.drone.jsonnet
.drone.yml
test/integration/wallet.ts
test/v2/integration/wallets.ts

* CI: update drone config to install with `--unsafe-perm`. This is
necessary because otherwise the prepublish script will not be run,
which will cause drone to not compile the typescript source. This is not
optimal, but will catch type errors in drone.

BG-11836: Fix typo in v1 wallets test

---

src/bitgo.ts

If @types/superagent is installed when we build the sdk it will do a type checking for the superagent library. We want to disable that checking by not doing an es6 import and doing a _const_ require instead

BG-11845 - Require superagent without es6 import

---

src/v2/coins/abstractUtxoCoin.ts
test/v2/unit/coins/btc.ts

JIRA: BG-11570, BG-8702
Previously `explainTransaction()` skipped counting signatures for
p2wsh inputs. This must have been an artifact of previous inability
to verify p2wsh sigs because simply removing the check enabled
p2wsh signature counting. No changes to signature validation were
necessary. This commit also refactors `explainTransaction()` and
enables the p2wsh tests for it.

Enable p2wsh in explainTransaction()

---

.drone.jsonnet
.drone.yml

We should really have a small script instead which does this measurement, but this will get us the metrics we need to move forward on reducing the installed package size.

BG-11931: Add slow-deps CI pipeline to measure install size and timing

---

.drone.yml
package.json
src/v2/coins/abstractUtxoCoin.ts

JIRA: BG-12002, BG-11994
Validation of number of signatures and pubkeys was added to
parseSignatureScript in #286. However, this validation fails for
our taint inputs, which are not multisig scripts. This commit
wraps `parseSignatureScript` within `explainTransaction` in a try
block to gracefully handle this failed validation.

BG-12002: Wrap parseSignatureScript in a try block

---

.drone.yml
package-lock.json
src/v2/coins/abstractUtxoCoin.ts

JIRA: BG-12002, BG-11994
Validation of number of signatures and pubkeys was added to
parseSignatureScript in #286. However, this validation fails for
our taint inputs, which are not multisig scripts. This commit
wraps `parseSignatureScript` within `explainTransaction` in a try
block to gracefully handle this failed validation.

Wrap parseSignatureScript in a try block

---

.drone.yml

* Re-enables integration tests failures causing CI failures
* Integration test failures were disabled as part of PR #314

BG-12022: Don't ignore integration test failures

---

src/v2/wallet.ts

The SDK docs don't mention that the platform API requires an empty
recipients parameter. The unit tests don't capture this because we are
not testing against the real backend.
This fix checks that `recipients` is either undefined or an empty
array (for backward compatibility), and sets it to an empty array.
Issue: BG-12074

Supply `recipients` in `accelerateTransaction()`

---

src/config.ts
test/v2/unit/coins/ofcToken.ts

We recently updated the ofc tokens in client constants. This updates the cache inside the SDK. The frontend likely works without this since it will get the live client constants quickly, but this makes scripting easier.

BG-11728: Rename OFC tokens

---

src/v2/trading.ts
src/v2/wallet.ts
test/lib/test_bitgo.ts
test/v2/unit/trading.ts

Started the new trading module with a couple of methods to build and sign a DAX payload authorizing a trade. 
buildTradePayload calls the microservices stack to request a DAX payload
signTradePayload first builds the payload then signs it with the user key on the OFC wallet
Added an integration test to validate everything, but it's pretty loose on the validation as the DAX schema is subject to change somewhat often

BG-11902 / Build and sign a trade payload

---

src/v2/wallet.ts
test/v2/unit/wallet.ts

In #337, it was reported that the `type` field was not being propertly
forwarded to the platform server by the `wallet.transfers()` function.
After further investigation, there were two more fields which were also
not properly forwarded.
This change fixes `wallet.transfers()` so that it correctly forwards all
valid parameters to the platform, and updates an existing test so that
we ensure that all valid parameters continue to be passed in the future.

CT-173: Forward all valid parameters to platform for transfers listing

---

src/v2/wallet.ts
test/v2/unit/wallet.ts

We are currently throwing an error when a share is initiated without the `skipKeychains` flag for a cold wallet (no encryptedPrv on any of the wallet keys). This is a problem because there are some wallets that are not marked as cold, i.e. the customer created them via the API by creating their own keys (e.g. having their user key in a customer HSM). This change modifies the wallet share function to ignore this error and to continue with the share.

BG-7960: v2 wallet share succeeds without encryptedPrv

---

README.md

The default windows terminal does not respect the shebang line which
starts the bin/bitgo-express startup script. Instead, we should invoke
node directly, and pass it the startup script as an argument. This
should be portable across all supported platforms.

CT-180: Fix bitgo-express startup command for windows

---

src/v2/wallet.ts
test/v2/unit/wallet.ts

The original fix didn't fully solve the problem because platform expects a keychain param to be passed when doing the share. When the skipKeychain param is passed into the SDK `shareWallet` function, we already set the keychain to an empty object, we have to do the same for any cold wallets even if the skipKeychain param wasn't passed.

BG-7960: pass empty keychain for wallet share for cold wallet

---

package-lock.json
package.json

JIRA: CT-230
Adds support for Dash special transactions.

Update bitgo-utxo-lib to v1.5.0

---

package-lock.json
package.json
src/v2/baseCoin.ts
src/v2/coins/eth.ts
src/v2/wallet.ts
test/v2/unit/ethWallet.ts
test/v2/unit/wallet.ts

Build a hop transaction with flag `hop`
Send a hop transaction with flag `hop`
Verify hop transaction and signature from the HSM
Send a commitment signature to the HSM, so it can verify that the tx was actually intended from the user

[CT-27] Add Hop transactions building and sending

---

src/v2/coins/eth.ts

Payment id is meant to be a string, when changing it from the current ISODate to a random number, we broke this and the platform rejects it as a valid payment id

[CT-27] Make payment ID a string rather than a number

---

package-lock.json
package.json

[BRE-515](https://bitgoinc.atlassian.net/browse/BRE-515)
Upgrading SDK version for sprint Austin release ra20190530.
Per discussion with @marktoda, there was a mixture of keccak versions 1.4.0 and 2.0.0, so when I ran "npm install --package-lock-only", it reverted keccak from 2.0.0 to 1.4.0.
```
Jamess-MacBook-Pro:BitGoJS jamesmn$ git show 6c9276610a97616d489997e3d28129a59a5e815c
commit 6c9276610a97616d489997e3d28129a59a5e815c (origin/CT-27-hop-transactions)
Author: Mark Toda <mtoda@bitgo.com>
Date:   Fri May 17 17:41:22 2019 -0700
[CT-27] Add Hop transactions building and sending
Build a hop transaction with flag hop
Send a hop transaction with flag hop
Sign and verify hop parameters
diff --git a/package-lock.json b/package-lock.json
index 7e86d99..65b8fe2 100644
--- a/package-lock.json …
```

BRE-515 Upgraded SDK version for sprint Austin release ra20190530.

---

modules/core/src/v2/coins/eth.ts

This was causing issues if the user tried sending a tx with non-lowercased address, the comparison failed.

CT-24 Lowercase hop destination before checking

---

README.md
lerna.json
modules/core/README.md
modules/core/RELEASE_NOTES.md
modules/express/RELEASE_NOTES.md

* Update release notes versions for 5.3.0, 5.4.0, core@6.0.0, and express@6.0.0
* Don't restrict lerna versioning to rel/* branches
* Improve READMEs and fix links

CT-374: Update release notes

---

modules/core/package.json
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/keycard.ts
modules/core/src/v2/types.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/integration/wallet.ts
modules/core/test/v2/integration/wallets.ts
modules/core/test/v2/unit/coins/algo.ts
modules/core/test/v2/unit/coins/btc.ts
modules/core/test/v2/unit/coins/dash.ts
modules/core/test/v2/unit/coins/ltc.ts
modules/core/test/v2/unit/coins/xlm.ts
modules/core/test/v2/unit/coins/zec.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts
modules/core/test/v2/unit/trading/tradingPartner.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts
yarn.lock

* Refactor example keycard code into separate file
* Introduce and begin using standard callback type
* Fix inconsistent error behavior in some methods

CT-364: Convert Wallet and Wallets to ES6 class and improve type support

---

modules/core/src/v2/coins/eth.ts

The amount being sent can actually have a big impact on the gas used -- we need to pass this through to get a more accurate estimate
See https://github.com/BitGo/platform/pull/805 for the collary platform diff

CT-428 Fix ETH Hop tx gas Estimation

---

modules/core/src/common.ts

The previous explorer used for doing non-BitGo recovery for ZEC, zcash.blockexplorer.com, is no longer running, so a new explorer had to be found. The new explorer zcashnetwork.info is now used. This new explorer returns the same JSON information as the previous website, so no code changes were needed.
I explored having two explorers used so that there would be redundancy in case one explorer went out of service like zcash.blockexplorer.com did, however making that change for just ZEC would be inconsistent with how the current recovery code for the other coins works, so I decided not to.

[BG-12973] Change recovery ZEC block explorer

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

The isValidMemo SDK method is used by the client to validate memos for XLM and EOS. The format of the parameters must be the same for the call to work for both coins.
https://bitgoinc.atlassian.net/browse/CT-593

CT-593 - Fix EOS isValidMemo params in SDK

---

modules/core/src/bitgo.ts

Jira Ticket: [BG-](https://bitgoinc.atlassian.net/browse/BG-13379)
Since the custom config for is initialized with `process.env.BITGO_CUSTOM_ROOT_URI` it is setting up the URL as `https://undefined/api/v2/txlm/federation`
We need to be able to set that from the client.
Ability to overwrite the stellarFederationServerUrl config.

BG-13379 - Overwrite stellar federation url in custom config

---

modules/core/src/v2/coins/algo.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/fixtures/algo.ts
modules/core/test/v2/unit/coins/algo.ts

Algorand offline signing.
Note this changes the Algorand signing flow (instead of the build return json it returns the pre-signed tx encoded as base64) and is tied to a client and platform PR as well.

CT-256 - algorand offline signing

---

modules/core/src/v2/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts

txHex is used throughout platform for cold signing and would have to mangle a lot of platform/ovc/SDK to keep base64. renaming to txHex instead

CT-256 - renaming txbase64 to txhex in algo

---

modules/core/src/v2/coins/algo.ts

JIRA: CT-684
This commit checks if the `to` field exists on a tx before
attempting to derive the address from its public key. Prior to this
commit there was no check and `explainTransaction` would blindly
try to derive an address froma transaction's `to` field, which does
not exist on keyreg txes.

CT-684: Handle keyreg txes in algo explainTransaction

---

modules/core/example/v2/send-wallet-transaction.js
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/rmg.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/test/v2/integration/wallet.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/btc.ts
modules/core/test/v2/unit/coins/eos.ts
modules/core/test/v2/unit/coins/rmg.ts
modules/core/test/v2/unit/coins/xlm.ts
modules/core/test/v2/unit/coins/xrp.ts

The explainTransaction method for EOS makes an asynchronous call and returns a promise. In order to be consistent, other coins should return a promise as well.
References:
https://bitgoinc.atlassian.net/browse/CT-656
https://bitgoinc.atlassian.net/browse/CT-637

CT-656 - Make explainTransaction methods return promise

---

modules/core/src/v2/trading/payload.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/test/v2/fixtures/trading/affirmation.ts
modules/core/test/v2/fixtures/trading/payload.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/unit/trading/payload.ts

Fees are now specified in the trade payload returned from the backend. Update verification logic to match the requested amount against the `subtotal` field, and also verify that the total is calculated correctly

BG-13597 / Update payload verification for settlement fees

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

Corrolary platform: https://github.com/BitGo/platform/pull/1009/files
We want the result of build to be compatible with the halfSigned input to "send". This PR changes the field names so it works like that

CT-711 Fix EOS signTransaction params and result

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts
modules/core/test/v2/unit/recovery.ts

As a result of https://github.com/BitGo/BitGoJS/pull/454 and https://github.com/BitGo/platform/pull/1009, the tx param used by the explainTransaction and deserializeTransaction methods should be renamed transaction.

CT-779 - Fix EOS deserializeTransaction param names

---

modules/core/src/v2/enterprise.ts
modules/core/src/v2/trading/affirmation.ts
modules/core/src/v2/trading/affirmations.ts
modules/core/src/v2/trading/settlement.ts
modules/core/src/v2/trading/settlements.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/src/v2/trading/tradingPartner.ts
modules/core/src/v2/trading/tradingPartners.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/fixtures/trading/affirmation.ts
modules/core/test/v2/fixtures/trading/settlement.ts
modules/core/test/v2/fixtures/trading/tradingPartner.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts
modules/core/test/v2/unit/trading/tradingPartner.ts

We refactored the settlement APIs to be much more consistent, this PR updates the SDK to call the new routes.
You can now call `.settlements()` and `.affirmations()` on an enterprise to list objects across the entire enterprise. But creating and updating settlements/affirmations requires a Settlements/Affirmations controller attached to a specific trading account, not an enterprise.

BG-13831 / Refactor Settlement APIs

---

modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallets.ts

We need to pass the "address" parameter to createWallet to create a new EOS wallet with a custom address.

CT-940 Add EOS custom address parameter

---

modules/core/src/bitgo.ts
modules/core/test/unit/bitgo.ts

We've updated all authentication routes in microservices to
/api/auth/v1 instead of /api/v1/auth.

BG-14020 / Update microservices auth route

---

modules/core/test/v2/integration/coins/xrp.ts

https://bitgoinc.atlassian.net/browse/BLOCK-3
The XRP testnet reset has broken our tests. This PR temporarily disables the broken test until we're ready to land the fix.

BLOCK-3 temporarily disable txrp test

---

modules/core/src/v2/coins/eos.ts

https://bitgoinc.atlassian.net/browse/BLOCK-7
When adding Non-BitGo EOS recoveries to the WRW, we ran into an hmac error because the EOS recovery function uses ```bitgo.post``` rather than ```request.post``` and therefore expects an hmac response, but doesn't get one.
Calls to third party blockchains should use ```request``` rather than ```bitgo```

BLOCK-7 fix hmac error in non-bitgo eos recovery

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/recovery.ts

https://bitgoinc.atlassian.net/browse/BLOCK-7
There's an issue with our transaction building for EOS recoveries. We need to have 4 decimal places included in the amount, otherwise broadcasted transactions fail.
In addition to the test suite, this has been tested by successfully doing a non-bitgo recovery and (after juicing the wallet) broadcasting the transaction

BLOCK-7 fix decimal error on eos recovery

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/ethWallet.ts

https://bitgoinc.atlassian.net/browse/BLOCK-16
A customer has identified a bug - when inputting a custom gasLimit in the UI, the value does not get recognized by the SDK, and does not get included in the transaction.
This PR fixes the SDK so that ```prebuildTransaction``` correctly handles gasLimit as a parameter

BLOCK-16 prebuild should accept gasLimit

---

modules/core/package.json
modules/core/src/config.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/erc20Token.ts
modules/core/src/v2/coins/stellarToken.ts
modules/core/test/v2/unit/baseCoin.ts
modules/core/test/v2/unit/coins/stellarToken.ts

This change allows instantiating a Stellar token defined in the statics library as:
`bitgo.coin('txlm:BST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L');`
The token name is composed of `<coin>:<token code>-<token issuer>`
Depends on: https://github.com/BitGo/statics/pull/57

CT-823 - Add support for Stellar tokens

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/stellarToken.ts
modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/xlm.ts

Adds trustline data to the `operations` property, so trustline txs can be displayed correctly.
Adds the `outputAmounts` property to track balance changes for different coins. `outputAmount` continues to track the output amount for XLM-only txs for compatibility.
https://bitgoinc.atlassian.net/browse/TOKS-13
Depends on: https://github.com/BitGo/statics/pull/57

TOKS-13 - Change explainTransaction method to work with Stellar trustline and token txs

---

modules/core/src/v2/coins/stellarToken.ts
modules/core/test/v2/unit/coins/stellarToken.ts

The `getChain` method in the SDK is used by the `url` method to get the token name, not its actual chain.
https://bitgoinc.atlassian.net/browse/TOKS-27

TOKS-27 - Fix getChain method of stellarCoin

---

modules/core/src/v2/internal/util.ts

To verify fix follow these steps:
1) In bitgojs, run these commands:
* `cd modules/core`
* `yarn clean`
* `yarn`
* `yarn compile`
* `yarn pack`
* `cp bitgo-v8.1.2.tgz ~/path/to/client-private`
2) In the client, run these commands:
* Edit package.json to set bitgo version to `./bitgo-v8.1.2.tgz`
* `npm run full-build`
3) Start platform with this version of client, try to send a teth transaction. It should be successful and there should be no errors about ethereumjs-util.
I'm not sure why this PR fixes the issue exactly.  My WAG is that there is some optimization that tsc or webpack can do when it sees `import('static-string')` that it can't do when it sees `import(dynamicVariable)`. If anyone knows anything about this, please share.

SERV-46: Fix importing ethereumjs-util in browsers

---

modules/core/src/v2/environments.ts

This makes it easier to connect to test microservices and other test environments using a custom URL.

ACID-38: Custom env should use test serverXpub if network is test

---

modules/core/src/v2/environments.ts
modules/core/src/v2/pendingApproval.ts

https://bitgoinc.atlassian.net/browse/SERV-32
Hop TX's didn't work with pending approvals. 
There was a platform change that got us closer.
This should be the final change to enable hop tx's with pending approvals.

SERV-32 fix hop on pending approval

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/stellarToken.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/xlm.ts

Hot wallets need the ability to send trustline txs to manage tokens they support.

TOKS-31 - Allow sending trustline txs from SDK

---

modules/core/README.md
modules/core/package.json
modules/core/src/bitgo.ts
modules/core/src/index.ts
modules/core/tsconfig.json
tsconfig.json
types/superagent/index.d.ts

* Add @types/bluebird and @types/superagent to the deps list from dev deps,
since these types are exported by the BitGoJS public API
* Export BitGo object interfaces
* Return custom `BitGoRequest` instead of raw superagent Request.
Methods patched onto the superagent Request object will be declared on
this interface instead of augmenting superagent.Request.
* Separate source files from type declarations in dist/
This commit covers the following tickets:
* SDKT-32
* SDKT-33
* SDKT-31

SDKT-32: Improve usability for typescript dependents

---

package.json
yarn.lock

https://bitgoinc.atlassian.net/browse/SERV-445
Note: this only fixes the issue in CI, and lets us merge other PRs. A correct fix will require merging and releasing these changes in dependencies:
* https://github.com/ripple/ripple-lib/pull/1054
* https://github.com/TooTallNate/node-proxy-agent/pull/47
* https://github.com/TooTallNate/node-pac-proxy-agent/pull/22

SERV-445: Update https-proxy-agent to ^3.0.0

---

modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/xlm.ts

Use base units for Stellar token trustline limits in params.
https://bitgoinc.atlassian.net/browse/TOKS-66
Related to platform PR: https://github.com/BitGo/platform/pull/1418

TOKS-66 - Use base units in Stellar trustlines

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/coins/trx.ts

[TRON-60](https://bitgoinc.atlassian.net/browse/TRON-60) Fix some problems with the return types of explain transaction while testing the OVC:
- `outputs` field is an array (Tron transactions have only one output).
- `fee` is the `feeInfo`

TRON-60: Make outputs field an array

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/coins/trx.ts

If an xprv is used to sign a Tron transaction, convert it to the uncompressed version, and then sign.

Allow trx to sign with an xprv

---

modules/core/src/v2/coins/trx.ts

The TRX implementation was throwing "not implemented" error even though
the base coin had a perfectly good implementation that works fine for
TRON. Remove the override implementation in the tron coin

Remove TRX Derive Key With Seed

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/coins/trx.ts

Valid addresses need to encompass both hex and base58 variations. (Both are legit in Tron)

TRON-109 - valid address need to be over base58 and hex addresses

---

modules/core/package.json
modules/core/src/v2/coins/trx.ts
yarn.lock

[TRON-133](https://bitgoinc.atlassian.net/browse/TRON-133) Updated account lib account generation code to use the same libs and logic than bitcoin. This PR updates the version used by the SDK

TRON-133 Update account-lib dep

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

This is an upgraded version of DAI. We are adding it as a separate coin
rather than upgrading the old one because our customers need to manually
upgrade from one to the other and want to be able to swap in their own
time.

[ERC20-157] Add MCDai ERC20 Token

---

modules/core/src/v2/coins/trx.ts
modules/core/test/v2/unit/recovery.ts

Typings for recoveries lack enforcement for how it's implemented downstream (mainly in wallet-recovery-wizard). Hopefully this leans towards some consistency for this. As well, tron needs to be changed to something that the wrw understands. (one of the three scenarios below)
EDIT: I've pared out the original intent of this PR - this now just fixes Tron recoveries.

TRON-36 - tron WRW fixup

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/ethWallet.ts

https://bitgoinc.atlassian.net/browse/BG-14806
Customer was getting a weird error when they tried this and was confused. We should have this error more explicit because we don't support hops for ERC-20 tokens and there is no reason to.

BG-14806 reject hop param for erc-20 token build

---

modules/core/src/errors.ts
modules/core/src/v2/coins/xlm.ts
modules/core/test/v2/unit/coins/xlm.ts

The change in https://github.com/BitGo/platform/pull/1508 adds ability to perform Federation lookups through the `v2.federation` platform API
The SDK can now pass the params to look up the account through the BitGo Federation server instead of making the request directly to the external federation server
BLOCK-147

BLOCK-147: Call API route for Federation lookups

---

DEVELOPERS.md

Made a few small changes in the `DEVELOPERS.md` file in order to clean up readability for new devs:
- Fix formatting of the "Things To Avoid" header.
- Clean up grammar/readability in "Things To Avoid" section.

SERV-581 Clean Up `DEVELOPERS.md`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add two GitHub issues templates to this project (https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository):
1. Bugs: Add a standardized template for contributors to report bugs to
the project maintainers.
2. Feature Requests: Add a template that allows contributors to request
features.
There is no standardized way for people to report their issues to this project. When bugs are reported, they tend to omit critical details such as node version, os, etc. which are extremely helpful in diagnosing the issue.
Addresses: https://bitgoinc.atlassian.net/browse/SERV-582

SERV-582 Add issue tracker template

---

modules/core/src/v2/wallet.ts

https://bitgoinc.atlassian.net/browse/BG-14844
For some reason a wallet object is getting added to the params before we do submitTransaction, and this is causing a failure as it shouldn't be there. This just deletes that wallet param and fixes the issue.
To test the issue and the fix, use the script linked in the comments below

BG-14844 Fix accelerateTx circular json bug

---

modules/core/package.json

JIRA Ticket: [BLOCK-226](https://bitgoinc.atlassian.net/browse/BLOCK-226)
Updated bitgo-utxo-lib version to 1.7.0-rc (then 1.7.0 later) which supports new Blossom network params.

BLOCK-226 Update bitgo-utxo-lib to use new Zcash params.

---

modules/core/src/v2/trading/tradingPartner.ts
modules/core/src/v2/trading/tradingPartners.ts
modules/core/test/v2/fixtures/trading/tradingPartner.ts
modules/core/test/v2/unit/trading/tradingPartner.ts

add trading partner by referral code added to SDK
update trading partner responses to new trading partner response object
add trading partner type ('direct' or 'agency') to response
add requester side ('primary' or 'secondary') and type ('direct', 'agency') to request parameters for referral form and referral code

AGS-18 / Add by referral code and specify trading partner type

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/eos.ts

JIRA: ETSTK-11
This commit adds functionality to deserialize EOS staking
transactions. EOS staking transactions consist of two actions,
delegatebw and voteproducer. The delegatebw action specifies the
amount of EOS to be staked and the account to stake it for. In our
case the staker and the receiver of the stake will always be the
same. The voteproducer action specifies the proxy or producers that
the staked funds will vote for.

Properly deserialize EOS staking transactions

---

modules/core/src/v2/recovery.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

https://bitgoinc.atlassian.net/browse/SERV-579
If a wrong-chain transaction has two outputs to the same wrong-chain address, then the WRW fails. This fixes

SERV-579 filter out duplicate addresses in cross-chain

---

modules/core/src/v2/coins/eos.ts

https://bitgoinc.atlassian.net/browse/BLOCK-200
EOS addresses *can* start with a number

BLOCK-200 fix eos address validation

---

modules/express/src/config.ts
modules/express/test/unit/config.ts

Boolean flags for bitgo-express (eg, `disableSSL`, `disableProxy`, etc)
currently have no effect.
The issue is that the environment config, which is highest in
precedence, casts undefined env vars to booleans if the config field is
of boolean type. This means the lower precedence configs are not
considered (args and default configs). Therefore, all command line flags
which set booleans are not able to be set, and instead must be set via
environment instead.
fixes #599

fix(SERV-593): Correctly handle undefined boolean config items

---

modules/core/src/errors.ts
modules/core/test/v2/unit/errors.ts

The `Error.captureStackTrace` function is only available in V8, so error
construction fails in other JS runtimes. This makes it difficult to
determine the root cause of errors. Instead, we should only call this if
it is defined.

fix(SERV-597): Ensure `Error.captureStackTrace` is defined before call

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/integration/wallet.ts

The locktime denominates the height at which a transaction gets valid
and may be relayed. Only a block with a height greater than the locktime
may include the locktimed transaction.
Consequently, the `nLockTime` should be set to the _current_ height to
allow relaying immediately and to make the transaction eligible to be
included in the next block. For the locktime to be respected, the
`nSequence` on at least one input must be set to `UINT_MAX - 1`. If
`nSequence` on all inputs is set to the maximum value of `0xffffffff`
this signals that a transaction is final and the locktime will be
disregarded. Setting it lower signals BIP-125 replaceability, which we
don't want either at this time.
References:
* https://btcinformation.org/en/developer-guide#locktime-and-sequence-number
* …

Set nLockTime to next block

---

modules/statics/src/networks.ts

TBH I'm not sure why we even redeclare these constants in statics if they are already declared in bitgo-utxo-lib

Fix utxo constants

---

modules/core/test/integration/wallet.ts

The method `bufferutils.reverse` was removed a long time ago:
https://github.com/BitGo/bitgo-utxo-lib/commit/29a865788d30b8b776cc1a1a2fd042d70085ec5f#diff-73e64645f9c04dc17e67b782cb9342fd
It is unclear why this did not cause an error
Issue: BG-16466

fix(test): remove illegal use of `bufferutils`

---

modules/core/src/v2/environments.ts

We are not able to resolve stellar addresses through the federation server because the sdk library
Is throwing “Cannot connect to insecure federation server”, this is because the configs for the MS environments are using http instead of https, we should use https.
Jira: BG-17307

Use https for stellar federation server URL configuration

---

modules/statics/src/coins.ts

Per client request, we are updating the contract address
for the ZMT token
Ticket: BLOCK-278

Update ZMT token contract address

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

Express filters body parameters before calling platform, so we have to
whitelist the `allowPartialSweep` parameter for it to be available.
Ticket: BG-17594

Add `allowPartialSweep` option to sweep

---

modules/express/README.md
modules/express/src/config.ts
modules/express/test/unit/config.ts

* Emit warning upon usage of a deprecated environment variable
* Update README to clearly explain the preferred environment
variables, and which ones are deprecated but still usable for backwards
compatibility reasons
JIRA: BG-17569

fix(express): Deprecate older forms of environment variable config

---

modules/core/test/v2/integration/coins/xlm.ts

Quarterly XLM testnet reset was done on 1/31, and we need to recreate
the wallets.
Ticket: BG-17683

fix(core): Recreate XLM integration test wallets

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

The "calculateFeeAmount" function of UTXO recoveries
can fail for two reasons:
- krsProvider's fee structure not configured
- 3rd party market data site is down
We don't want either of these to block the recovery
from happening, so lets encapsulate this call in
a try-catch and just log the error if there is one
Ticket: BG-18417

Add try-catch to recoveries

---

modules/core/src/v2/coins/btg.ts

BTG incorrectly inherits BTC's verify
function during the recovery process,
which causes an error because the BTG
block explorer does not support the
/decodetx endpoint. This commit throws
the proper error for BTG in this situation
so that the recovery does not get blocked
Ticket: BG-18467
You can see why this error is necessary to throw by looking [here](https://github.com/BitGo/BitGoJS/blob/master/modules/core/src/v2/coins/abstractUtxoCoin.ts#L1778)

Skip verify in BTG Recovery

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/recovery.ts
modules/express/test/mocha.opts

Resolves https://github.com/BitGo/BitGoJS/issues/677 by extending EOS recovery expiration from 1 to 8 hours.
Adds a unit test to demonstrate that the correct expiration date is encoded, by comparing it to the head block time (which is mocked [here](https://github.com/BitGo/BitGoJS/blob/ade4e9ab1459055bf6805e8ca551e98fb44d9a45/modules/core/test/v2/lib/recovery-nocks.ts#L2594)). Also updates the expected packed transaction used across EOS recovery unit tests. (Note: only the first seven bytes are different from the prior packed transaction, which presumably is where the expiration date is encoded.)

Extend EOS recovery expiration from 1 to 8 hours

---

modules/core/test/mocha.opts
package.json
yarn.lock

A low-severity vulnerability was recently disclosed for `kind-of`
versions below 6.0.3: https://www.npmjs.com/advisories/1490
This change forces the installed version of kind-of to be at least
6.0.3.
Ticket: BG-18814

Resolve kind-of to ^6.0.3

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/integration/wallet.ts
modules/core/test/v2/unit/wallet.ts

Platform has had support for adding extra metadata to a transaction
prebuild which would assist in offline verification of the transaction
inputs. However, SDK did not support passing the parameter which would
tell platform to append this extra data.
This commit adds support for passing the `offlineVerification` flag when
calling `prebuildTransaction`, closing this feature gap.
Ticket: BG-18802

Add support for retrieving offline verification data

---

modules/core/src/bitgo.ts
modules/core/test/unit/bitgo.ts

Before our typescript refactor last year, these properties were checked
with the deprecated `common.validateParams`, which takes an array string
literals of the properties to check for on the given object. When we
refactored however, we continued using the string literal instead of the
variable of the same name.
This is the only location in the code where the string `isString('`
appears, so I don't think we have made this mistake anywhere else.
Ticket: BG-18946

Fix incorrect type check on string literal

---

package-lock.json
package.json
yarn.lock

Github alerts notified repo of a prototype pollution vulnerability in
the minimist package.
Ref: CVE-2020-7598
When running `npm audit`, found:
`1098 vulnerabilities (826 low, 272 high) in 41713 scanned packages`
So decided to run `npm audit fix` to clean up all known issues.
Ticket: BG-19024

Ran `npm audit fix` to resolve sec issues in pkgs

---

modules/core/src/config.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/lib/recovery-nocks.ts

Bitcoin Average recently deprecated their free endpoint, so we can no
longer use them to get transaction data for recoveries.
This change swaps out bitcoin average for coingecko for recovery cases.
Ticket: BG-18654

Retrieve prices from CoinGecko API

---

Dockerfile

The default version of npm in the docker base image fails during npm
prune with `npm ERR! invalid bin entry for package msgpack-lite`.
This is a known and fixed bug in npm: https://github.com/npm/cli/issues/613
Ticket: BG-19035

Install latest npm in container before express

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

A common use case in the front end is building a URL to a block explorer
for a specific transaction, so a user can see the status of their
transaction on chain.
For some account coins, fees are paid from the Enterprise, instead of
from the wallet itself. For those coins, we'd like to be able to:
1) Know that this is one of those coins where the enterprise pays fees
2) How to build an explorer URL so a user can look at the on chain
balance of their Enterprise fee address
This commit adds the ENTEPRISE_PAYS_FEES coin feature, and adds this
feature to XTZ and ETH (the only two coins which currently pay fees from
the Enterprise gas tank). This solves for case #1.
This commit also adds a new optional field to `AccountNetwork` called
`accountExplorerUrl`. This can be used for building urls just …

Add ENTERPRISE_PAYS_FEES and accountExplorerUrl

---

modules/core/test/unit/bitgo.ts
modules/core/test/v2/integration/bitgo.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

In order to run e2e tests on ERC20 tokens, we needed to add one to our
regtest deployments. We added a token which  will be initialized
with the first transaction from the hard-coded
rich address on the regtest chain. This means the token will always
have the same address: 0x731a10897d267e19b34503ad902d0a29173ba4b1.
Ticket: BG-19512

Add Regtest ERC20 Token

---

modules/core/package.json
modules/core/src/v2/coins/xtz.ts
modules/core/test/v2/unit/coins/xtz.ts
yarn.lock

In tezos, we need to pass the message in hex format before creating a signature.
TICKET: BG-19590

Convert messages to hex before signing

---

modules/core/src/v2/coins/xtz.ts
modules/core/test/v2/unit/coins/xtz.ts

Signature verification was failing in the platform because the signature was not a buffer.
TICKET: BG-19801

Send XTZ signatures as buffer

---

modules/core/src/errors.ts
modules/core/test/v2/integration/wallet.ts
modules/core/test/v2/unit/errors.ts

https://nodejs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt
> The optional constructorOpt argument accepts a function. If given,
> all frames above constructorOpt, including constructorOpt, will be
> omitted from the generated stack trace.
> The constructorOpt argument
> is useful for hiding implementation details of error generation from
> an end user.
Issue: BG-20357

BitGoJsError: include stack trace

---

modules/core/src/v2/coins/xrp.ts
modules/core/test/v2/integration/coins/xrp.ts
modules/core/test/v2/integration/wallets.ts
modules/core/test/v2/unit/coins/xrp.ts

With the DeletableAccounts amendment enabled, platform can't rely on SDK to
build and sign initialization txs because their sequence id has to be obtained
from the network once the account has been funded
Ticket: BG-20878

Stop generating XRP initialization txs for new wallets

---

modules/core/src/errors.ts
modules/core/test/v2/unit/coins/token.ts

BitGoJS throws an error whenever a user tries to use a coin that is not
supported in the current version of BitGoJS. Oftentimes the fix is to
simply update BitGoJS to a version that includes the desired coin or
token. This commit adds an extra sentence to that error message to
hopefully lead users to the solution more quickly.
Ticket: BG-21130

Update UnsupportedCoinError to to include tip

---

modules/core/src/v2/coins/abstractEthLikeCoin.ts

The class should never be instantiated by itself -- it's meant to be the
base for coins with ETH-like behavior. This commit adds the abstract
flag to make it more clear that it shouldn't be instantiated
Ticket: BG-17980

Update AbstractETHLikeCoin to actually be abstract

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

The CELO blockchain supports the ERC20 standard and thus has various
ERC20 tokens just like Ethereum. This commit adds a new factory builder
for those tokens, and adds our first one -- the celoUSD token, which
comes by pre-compiled with the blockchain.
Ticket: BG-21618

Add Celo USD ERC20 token

---

modules/statics/src/index.ts

Other libraries need to be able to compare statics `Coin` objects with
the type of coin that they are an instance of. This commit exposes
`CeloCoin` so that this functionality is available
Ticket: BG-21696

Expose CeloCoin from @bitgo/statics

---

modules/core/RELEASE_NOTES.md
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

Express whitelisted `maxNumUnspentsToUse`, but Platform is expecting
`maxNumInputsToUse`.  `maxNumInputsToUse` matches the documentation.
The issue is fixed by updating Express to whitelist `maxNumInputsToUse`
instead.  Since the currently whitelisted parameter in Express would
never have resulted in the desired outcome, this commit does not break
working functionality of existing integrations.
FIXES TICKET: BG-21100

Fix fanout parameter mismatch in Express

---

.drone.jsonnet
.drone.yml
modules/core/package.json
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/cgld.ts
modules/core/src/v2/coins/etc.ts
modules/core/src/v2/coins/rbtc.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts
modules/statics/src/account.ts
package.json
yarn.lock

This commit adds implementations for some key and address validation
functions in abstractEthLikeCoin and child implementations such as etc,
cgld and rbtc. These will be required to continue adding support for
those coins
Ticket: BG-21730

Implement validation functions for ETH-like coins

---

modules/core/src/v2/coins/eth.ts
modules/core/src/v2/environments.ts

Etherscan now requires an API key for mainnet requests. This PR adds it as an ENV variable.
Source: https://medium.com/etherscan-blog/psa-for-developers-implementation-of-api-key-requirements-starting-from-february-15th-2020-b616870f3746

BG-22155 Add etherscan API Key

---

modules/core/package.json
modules/core/src/v2/coins/xtz.ts
modules/core/test/v2/unit/coins/xtz.ts
modules/core/test/v2/unit/keychains.ts
yarn.lock

SECP key generation needs to be enforced uniformly for offline signing
and UI applications. This adds a Key curve feature to statics to help
with this aspect of testing.
Ticket: BG-22126

Key generation enforcement and key curve into statics

---

modules/statics/src/account.ts
modules/statics/src/coins.ts
modules/statics/src/index.ts

The CGLD coin on CELO chain is both the native asset of the chain AND
a token following the ERC20 interface standard. BitGo intends to *send*
the coin using the ERC20 token interface, but must support receives of
it from both the token interface and the native asset interface. This
commit adds the token version of CELO to @bitgo/statics, including its
token address on celo mainnet chain
Ticket: BG-22179

Add CGLD Celo token

---

modules/core/package.json
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

This commit adds an implementation of signTransaction and
explainTransaction for ETH-like coins relying heavily on logic in
bitgo-account-lib. The transaction explanation logic in
bitgo-account-lib is not fully finished yet, but that doesn't block an
initial implementation here -- when that is updated, we can simply add
a new change with the new verion of the library and extend our tests to
cover the newly explained fields.
This commit also bumps the version of dependency @bitgo/account-lib to
include new fixes required for signing transactions
Ticket: BG-22079

Implement sign and explain for ETH-like coins

---

modules/core/src/bitgo.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/environments.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

It is easier for a user to pass the API key as a method paramter than exposing it as an env variable.
Having it as an ENV variable it's still useful in test environments, so it doesn't hurt to leave it.
TICKET: BG-22155

BG-22155 Add API Key as a parameter

---

modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

This commit fixes CGLD sending with xprvs by mapping all keys to
compressed format before signing transactions with them. After this
commit, signTransaction will work with both xprv and compressed prv
passed as the prv parameter
Ticket: BG-22282

Fix CGLD sending with xprv

---

modules/core/src/v2/pendingApproval.ts
modules/statics/src/base.ts
modules/statics/src/networks.ts

These are not handled well by isolated modules until we change our
Typescript settings.
Ticket: BG-22339

Change export const enums to export enums

---

modules/core/package.json
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

This commit updates to the latest version of Bitgo-account-lib and
removes an unnecessary field that we had to set for every transaction
built for ETHlike coins
Ticket: BG-22391

Remove source for ETH-like transaction building

---

modules/core/package.json
yarn.lock

This commit updates @bitgo/account-lib to 1.7.0 to pull in an important
security fix for CELO, ETC and RSK
Ticket: BG-22449

Update @bitgo/account-lib to 1.7.0

---

modules/statics/src/account.ts

CELO is a weird edge case in that it is both the native coin on its
chain and follows the ERC20 token interface. Thus we had to make a new
class for it to illustrate that. However, the coin should not be
specified as a "token" as that causes some components to fail, as they
assume that all "token"s as children of another coin and thus should not
be displayed as first class citizens. This commit changes CELO to not be
considered a token in this way
Ticket: BG-22435

Make CELO not a "token"

---

modules/core/src/bitgo.ts
modules/core/src/keychains.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/ofc.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/internal/util.ts
modules/core/test/v2/unit/coins/algo.ts
modules/core/test/v2/unit/coins/xlm.ts

This avoid an unwanted deprecation notice.
See https://github.com/nodejs/node/issues/23203 for more details.
Ticket: BG-22502

Remove usages of `import * from crypto`

---

modules/core/package.json
modules/core/src/v2/coins/celo.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts
yarn.lock

This commit pulls in a new version of @bitgo/account-lib dependency
which includes the change to change the name of CGLD coin to CELO
Ticket: BG-22688

Update Bitgo-account-lib to 2.0.0-rc.0

---

modules/core/test/unit/bitgo.ts

We added a new testnet token to statics, and this is causing a unit test
to fail in modules/core. Instead of asserting the exact number of
testnet tokens, let's just make sure the property exists and has a
length greater than zero.
Ticket: BG-22644

Improve failing test for testnet tokens

---

modules/account-lib/src/coin/baseCoin/enum.ts
modules/account-lib/src/coin/eth/transactionBuilder.ts
modules/account-lib/src/coin/eth/types.ts
modules/account-lib/src/coin/eth/utils.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/singleSigSend.ts

This commit adds the ability for ETH clones transaction builders to send
single-signature transactions. This is useful for BitGo to craft
transactions from the fee address, including recoveries and fixing nonce
holes.
Ticket: BG-22801

Add single sig transactions for ETH clones

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

When CELO addresses are generated, it throws a validation error but
still actually generates the address. This is because it tries to
"verify" the address, but since it is pending chain initialization the
address is not there yet. This commit changes the verifyAddress function
to only verify addresses that are not pending chain initialization.
Ticket: BG-22647
https://bitgoinc.atlassian.net/browse/BG-22647

Fix CELO receive address generation

---

modules/core/test/v2/integration/wallets.ts

There is a wallet integration test that creates a new webhook and checks
that it works. However, it is stateful and if anything happens in the
middle of a test, for example it gets canceled - it's possible that the
webhook will be left in existence and all future tests will fail due to
this. To avoid this issue, this commit adds a before hook which removes
the webhook, hopefully making it self-healing
Ticket: BG-22987

Remove webhook in wallet integration test

---

.drone.jsonnet
.drone.yml
package.json

This commit adds a step to publish a canary to a npm proxy repository
upon merging in order to get quick access to integrate with new versions
of packages in this repository
Ticket: BG-22965

Add internal publish step

---

modules/statics/src/networks.ts

Smartbit doesn't work for testnet anymore so I'm updating the testnet explorer. We should probably update the mainnet one too to match.
Thoughts?
TICKET: BG-22526

BG-22526 Update bitcoin explorer

---

modules/statics/src/coins.ts

The CELO  statics object did not have the correct features set - this
commit sets the ETH features for the CELO coin objects
Ticket: BG-22984

Add ETH features to CELO

---

modules/core/README.md
modules/express/README.md

It was brought up that there was no comprehensive list of debug
namespaces supported by `core` and `express`, nor was there information
on how to use them to get extra debug information.
This commit adds this information to the `express` and `core` package
READMEs.
Ticket: BG-22900

Add documentation about debug namespaces

---

modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts

We need keeys as string instead of Uint8Array.
TICKET: BGA-240

BGA-240 Change HBAR Keys format

---

modules/account-lib/src/coin/baseCoin/ed25519KeyPair.ts
modules/account-lib/src/coin/baseCoin/errors.ts
modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/src/coin/hbar/utils.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/resources/hbar/hbar.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/xtz/transactionBuilder.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xtz.ts
modules/core/test/v2/unit/coins/hbar.ts

I'm making some adjustments to the abstraction model to better accommodate for core logic sharing and new specialized coins Key pairs:
I'm introducing `@stablelib/hex` dependency again because I noticed hex encoding/decoding with Buffer and Uint8array is not idempotent. An example of a buggy conversion is:
`302e020100300506032b657004220420302e020100300506032b65700422042062b0b669de0ab5e91b4328e1431859a5ca47e7426e701019272f5c2d52825b011` 
This key converted back and forth from hex string to Uint8array did not result in the same string, which is extremely dangerous.

BGA-240 Improve Key Pair abstraction

---

modules/core/package.json
modules/core/src/v2/coins/hbar.ts
modules/core/test/v2/unit/coins/hbar.ts
yarn.lock

Update to the latest SDK version and update the `generateKeyPair()` method with the new `getKeys()` return type (string) + protocol specific format.
TICKET: BG-23336

BG-23336 Return Strings in HBAR getKeys

---

modules/core/src/v2/wallets.ts
modules/core/test/v2/integration/coins/xlm.ts
modules/core/test/v2/unit/wallets.ts
package.json
yarn.lock

Whitelist signingKeyId param for add wallet
This commit whitelists the signingKeyId parameter for the wallet.add
function, which allows the user to specify a custom address to pay the
fees for a wallet creation transaction for certain coins.
This commit also fixes an npm audit issue for elliptic and dot-prop, and
fixes an XLM integration test issue
Ticket: BG-23036

Whitelist signingKeyId param for add wallet

---

modules/account-lib/src/coin/xtz/transaction.ts
modules/account-lib/src/coin/xtz/transactionBuilder.ts
modules/account-lib/test/unit/coin/xtz/transactionBuilder.ts

This commit adds the ability for XTZ transaction builders to send
single-signature transactions. This is useful for BitGo to craft
transactions from the fee address, including recoveries
relates to Ticket: BG-22530

Add single sig transactions for XTZ

---

modules/account-lib/src/index.ts

Need to be able to instantiate an hbar builder with the getBuilder
helper utility - this commit adds it to the map that allows us to do so
Ticket: BG-23580

Add hbar to coinbuildermap

---

modules/account-lib/src/coin/hbar/ifaces.ts
modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transactionBuilder.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/walletInitialization.ts

Sometimes we need to be able to generate signatures outside of the
account-lib library. In this case we need to be able to insert these
signatures into a transaction and re-serialize it accordingly. This
commit adds this functionality to the hedera transaction builder
Ticket: BG-23598

Insert external HBAR signatures

---

modules/core/src/v2/wallet.ts

Allow targetAddress on consolidate and fanout
The SDK's parameter whitelist actually did not include the
`targetAddress` parameter, so it was added here now.
Ticket: BG-23451

Bg 23451.whitelist target address

---

modules/account-lib/package.json
yarn.lock

This commit updates the @celo/contractkit dependency version in
account-lib to a version that includes an updated elliptic dependency,
void of a critical signature malleability issue. We had alerady patched
this issue in this library using yarn resolutions, but this update will
patch it for packages which depend on account-lib and do not use yarn
- as they will not follow the resolution
Ticket: BG-23661

Update @celo/contractkit in accountlib

---

modules/core/src/v2/wallet.ts

* Rename "prebuildConsolidateTransactionParams" to
"prebuildConsolidateAccountParams" as the name suggested that they
apply to all consolidation transactions.
Ticket: BG-23459

Add consolidateAddresses parameter to whitelist

---

modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

Adds required fields for explaining/signing OVC transactions. Specifically, needs expiryTime, signature, and recipients in halfsignedTx.
Ticket: https://bitgoinc.atlassian.net/browse/BG-23403

Add RSK to the OVC

---

modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/src/coin/hbar/transferBuilder.ts
modules/account-lib/src/coin/hbar/walletInitializationBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts

This commit fills in the transaction type field for HBAR transactions so
that users of the library can know what type of transactions they be
dealin with
CLOSES TICKET: BG-23897

Add Transaction Type for HBAR transactions

---

.drone.yml
modules/account-lib/src/coin/baseCoin/baseTransaction.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/walletInitialization.ts
modules/account-lib/webpack.config.js
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xtz.ts
modules/core/webpack.config.js
package.json

-- core module's webpack config uses the web version of account-lib
-- core module's webpack config performs a post processing step to replace unsafe eval code with window
-- xtz & trx fixed import statement
-- account-lib baseTransaction fixed invalid typescript declarations/assignments. 
-- disables flaky integration test, to fix in https://bitgoinc.atlassian.net/browse/BG-23925 later

fix global unsafe code in webpack bundles

---

modules/account-lib/src/coin/hbar/transaction.ts
modules/account-lib/test/unit/coin/hbar/transactionBuilder/transferBuilder.ts

This commit exposes inputs and outputs for HBAR transactions throgh the
baseTransaction inputs and outputs interface. These were previously left
empty - this commit fills them in whenever the transaction body is
initialized. This is useful for callers that need to quickly parse this
data from transactions using the common interface
CLOSES TICKET: BG-23927

Expose inputs and outputs for HBAR txs

---

modules/core/src/v2/coins/hbar.ts
modules/core/test/v2/unit/coins/hbar.ts

This commit fixes the sign transaction logic for HBAR and adds a test to
ensure that it continues to work in the future as more changes are made.
It also implements signMessage function, which unfortunately had to use
the algosdk library as @bitgo/account-lib does not implement signMessage
functionality
CLOSES TICKET: BG-24080

Fix HBAR Sign Transaction

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/btc.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

Users are likely to get rate limited by blockchair while doing recovery, due to the number of calls they would have to make to blockchair. We add an option for them to add api key to the calls to blockchair. There will be a follow up PR in the WRW side to make the frontend flow with the backend changes done here.

BG-24067 modify recovery function to take blockchair API key

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/internal/parseOutput.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/promise-utils.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts

This PR adds the following features to `AbstractUtxoCoin` transaction parsing and verification.
1) When parsing transactions, try deriving addresses from the custom change wallet keys before assuming the address to be external
2) If an output address was found to be derived from the custom change wallet keys, mark the transaction as needing verification of the custom change wallet key signatures
3) If this flag is found to be set on the parsed transaction, transaction verification requires valid signatures from the spending wallet's user key over the custom change wallet user, backup and bitgo public keys. If the signatures or keys are missing or otherwise found to be invalid, the transaction validation fails
Ticket: BG-23613

Add support for verifying transactions which spend to custom change wallets

---

modules/core/test/v2/lib/recovery-nocks.ts

They are not needed and we are trying to phase them out
Issue: BG-23552

BitGoJS: remove numTx, numUnspents from nocks

---

modules/core/src/v2/environments.ts
modules/core/src/v2/recovery/blockstreamApi.ts
modules/core/test/v2/unit/recovery/blockstreamApi.ts

We need an alternative for BTC that does not require payment. Blockstream does not require an API key.
CLOSES TICKET: BG-24147
This PR does not change the current recovery functionality since we should talk what's the best mechanism to allow the user to choose an API.

Add Blockstream as a RecoveryProvider

---

modules/core/src/v2/coins/btc.ts
modules/core/test/v2/fixtures/coins/recovery.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/recovery.ts

This PR makes blockstream the default block explorer.
Additionally, it also refactored existing unit tests to be less coupled with the specific implementation of any block explorer by using mock function values.

BG-24157: Use Blockstream as Default BTC Explorer

---

modules/core/src/v2/coins/btc.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

- Currently, when bitcoinfee.earn.com goes down, we would let the
error interfere with the recovery transaction. But since we have
the default fee value anyways, we should just catch the error and
use the default fee value to continue with the recovery
Ticket: BG-24305

Do not throw error if bitcoinfee does not respond in recovery

---

modules/core/src/v2/coins/celoToken.ts
modules/core/test/v2/unit/coins/celoToken.ts

A bug previously existed where signing transactions was invalid due to an issue getting a CELO token's chain. This fix resolves such bug
Ticket: BG-24642

Fix CUSD sign transaction

---

modules/account-lib/src/coin/baseCoin/secp256k1ExtendedKeyPair.ts
modules/account-lib/src/coin/eth/transferBuilder.ts
modules/account-lib/src/coin/xtz/keyPair.ts
modules/account-lib/src/coin/xtz/utils.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/unit/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/hbar/transaction.ts
modules/account-lib/test/unit/coin/xtz/util.ts
modules/core/src/bitcoin.ts
modules/core/src/bitgo.ts
modules/core/src/ripple.ts
modules/core/src/transactionBuilder.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/xtz.ts
modules/core/src/v2/internal/util.ts
modules/core/src/v2/recovery.ts
modules/core/test/integration/keychains.ts
modules/core/test/unit/hdnode.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts
modules/core/test/v2/unit/coins/xlm.ts
modules/core/test/v2/unit/coins/xtz.ts

Use of new Buffer() is deprecated and emits annoying warnings when used
for the first time on node.
Instead, use Buffer.from() for initializing new buffers with known
contents. For allocating buffers with new Buffer, use Buffer.alloc()
instead.
Ticket: BG-24579

Replace usages of new Buffer() with Buffer.from()

---

modules/core/src/bitgo.ts
modules/core/src/v2/environments.ts
modules/core/test/unit/bitgo.ts

Disabling HMAC validation is useful in dev environments, but we must be
very careful to enforce HMAC validation in other environments.
This commit allows disabling HMAC verification for the development
environments only.
Ticket: BG-24938

Add optional constructor parameter to skip HMAC Verification

---

modules/core/src/v2/coins/celoToken.ts
modules/core/test/v2/unit/coins/celoToken.ts

CUSD token sends presently look at CELO balance to determine spendable balance requirements. This points spendable balance checks back to the balance of CUSD (or whatever celo token is in question)
Ticket: BG-24677

Fix cusd token sends

---

modules/core/src/v2/coins/bch.ts
modules/core/src/v2/recovery/blockchairApi.ts
modules/core/test/v2/unit/recovery.ts

Our current blockexplorers for BCH mainnet and testnet recovery are both down. Changing them to blockchair. We will only have mainnet support for BCH recovery as a result. 
https://blockdozer.com/insight-api/addr/3CkKr9gykRKP8V5sE2zZS5L8c32TVX3mvg
https://test-bch-insight.bitpay.com/api/addr/3Fn25AxxbzRu4g4mJH1TdXmo4hTfkxfAz7 
Ticket: BG-24863

Use blockchair as the BCH block explorer

---

modules/core/src/bitcoin.ts
modules/core/src/errors.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/unit/hdnode.ts

The current address derivation logic assumes that all keys have paths that start with prefix `m/0/0`, which isn't true for all user keys of v1 wallets, as some might have different path param. 
This PR allows us to take an optional parameter for the user keypath that can override the default
Ticket: BG-24941

Allow param for userkey path for address derivation

---

modules/core/src/bitgo.ts
modules/core/test/unit/bitgo.ts
modules/core/test/v2/unit/trading/affirmation.ts
modules/core/test/v2/unit/trading/payload.ts
modules/core/test/v2/unit/trading/settlement.ts
modules/core/test/v2/unit/trading/tradingAccount.ts
modules/core/test/v2/unit/trading/tradingPartner.ts

BitGoJS will no longer use `/user/login` to login in any environment and will instead always use the `/api/auth` routes for authenticating.

remove _microservicesUrl and always use auth route

---

modules/account-lib/package.json

Fixes an issue where we import stellar in account-lib but it sources
from core. problematic for installs that only install account-lib
Ticket: BG-25637

Add stellar to account lib

---

modules/core/src/v2/coins/eth.ts

- We currently use the wrong comparator to check whether
a keynonce is undefined. This could lead to the wrong
keynonces to beUse right semantics to check for undefined var
- This was introduced in BG-24643
Ticket: BG-25181

Use right semantics to check for undefined var

---

modules/core/src/v2/coins/abstractUtxoCoin.ts

- Our current instantiation of the cross chain recovery tool diabled
logging of recovery steps, which makes it hard to get error traces
when debugging.
- This PR enable logging by setting "logging" to true, logging info
to console.log (default logger when none provided)
Ticket: BG-22261

Turn on logging of the crosschain recovery tool

---

modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/celoToken.ts
modules/core/test/v2/unit/coins/celoToken.ts

BitGoJS is currently nonconformant with our standard naming scheme of:
- getChain() = the base chain that the coin lives on
- getName() = the coin name
Instead, getChain() returns the token name for tokens and the chain name
for native coins. This was causing an issue instantiating accountlib
transactionbuilder objects which expected the base chain. Ideally the
solution would involve refactoring the naming scheme to conform to
standard, though this would require changes to ERC20 and XLM tokens as
well, and be a breaking change. This would likely cause integration
issues both for us and clients.
This commit fixes the issue in a non-breaking way by adding a new
function getBaseChain() for abstractEthLike coins and tokens which
returns the expected base chain. This is the value used for …

Fix CELO token transactionBuilder

---

.drone.yml

The check-commits step defined in the drone.jsonnet wasn't actually being run, since the drone.yml
is the file that drone actually executes.
Ticket: BG-25260

ci: regenerate .drone.yml

---

DEVELOPERS.md

We're now using and enforcing conventional commits in the SDK repo. To inform external developers,
information about how this works is added to the DEVELOPERS.md file.
Ticket: BG-25945

docs: update DEVELOPERS.md with info on conventional commits

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/bcha.ts
modules/core/src/v2/coins/tbcha.ts
modules/core/src/v2/recovery/blockchairApi.ts
modules/core/test/v2/unit/recovery.ts
modules/core/test/v2/unit/recovery/blockchairApi.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

This PR adds BCHA as a new coin in the SDK, so we could recover it with non bitgo recovery functions after the fork.
Please note that the chain params of BCHA and BCHN are identical, so we are reusing the same set of params defined on the UTXO lib. (Since UTXO Lib is a bit messy anyhow.) Therefore, BCHA does not need to override the constructor of BCHN.

BG-26001 support Bitcoin-ABC (BCHA) recovery in SDK

---

modules/core/src/config.ts

We need to add bsv and bcha under the supportedCoins param of SDK, so that the recovery transaction can be initiated.

fix(config): add BSV and BCHA as recoverable coin with coincover

---

modules/account-lib/package.json
modules/account-lib/src/coin/baseCoin/baseKeyPair.ts
modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/src/coin/eth2/index.ts
modules/account-lib/src/coin/eth2/keyPair.ts
modules/account-lib/src/index.ts
modules/account-lib/test/resources/eth2/eth2.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts
yarn.lock

Adds ability to create user and backup keys for ETH2 wallets client-side.
Ticket: BG-26379

Add BLS key generation for eth2

---

modules/core/src/v2/coins/zec.ts

Use "Canopy" consensus branch https://zips.z.cash/zip-0251
countdown: https://z.cash/upgrade/canopy/
BG-26072

🚫 Do Not Merge until ~Nov 18 2020: update ZEC consensusBranchId for Caopy hardfork

---

Dockerfile

gcompat installs to /lib, which is where loady looks for dynamic libraries, instead of /lib64.
Because it was in the wrong location, this was causing the library to still not be found when
starting up.
Ticket: BG-26745

fix(express): use gcompat instead of libc6-compat

---

Dockerfile

gcompat is not meant to be a long term solution for providing glibc
compatibility for compiled binaries. Instead, we should compile these
binaries in an environment which has the same libc implementation as the
one which will be present in the final production container.
This change replaces the `node:10` build container with
`node:10-alpine`, removes `gcompat` from the production container.
Ticket: BG-26745

fix(express): remove gcompat, switch to alpine build container

---

modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts
modules/core/src/v2/coins/eth2.ts
modules/core/test/v2/unit/coins/eth2.ts

This commit implements the signMessage functionality for ETH2 so that we can perform key signatures
while generating wallets

feat(eth2): add signMessage for ETH2

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/index.ts
modules/account-lib/src/coin/cspr/keyPair.ts
modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transactionBuilder.ts
modules/account-lib/src/coin/cspr/transactionBuilderFactory.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/walletInitializationBuilder.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/walletInitialization.ts

Add casper coin skeleton structure, this include transactions skeletons, keyPair, index and finally
some unit test
This PR Add casper coin skeleton structure, this include transactions skeletons, keyPair, index and finally
some unit test
- Add transactions skeleton files
- Add keyPair skeleton file
- Add tentative unit tests
- silvialvado
- ipelaez-simtlix
- FabianSimtlix
SimTLiX ticket: https://simtlix.atlassian.net/browse/BGA-655

AccountLib- BGA-655 Implement casper coin skeleton structure

---

modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/core/src/v2/coins/eth2.ts

This commit fixes the key signatures by parsing the keys as hex rather
than utf-8, and fixes the BLS lib initialization by removing
setImmediate
CLOSES TICKET: BG-27361

Fix ETH2 lib initialization and key signatures

---

modules/statics/src/coins.ts

Jira card: https://simtlix.atlassian.net/browse/BGA-1047

Modify Static module to see "Testnet Casper" instead of Casper when testnet

---

modules/core/package.json
modules/core/src/bitcoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/ethWallet.ts
yarn.lock

The library needed to support casper in account-lib requires
@types/secp256k1@4, but this causes type errors when compiling core,
since it uses a much older version.
This PR updates secp256k1 to 4.0.2, and fixes all issues caused by
breaking changes in the new major version.
Ticket: BG-27646

feat: update secp256k1 in core to ^4

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/keyPair.ts
modules/account-lib/src/index.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/keyPair.ts

BGA-656 KeyPair Generation Implemented along with Unit Tests.
**Notes**:
- @bitgo/statics version has been updated to 6.1.0-rc.1 since it's required for unit tests in this task. Previous version was v6.0.0.
- Build is failing in drone due to a version issue with secp256k1 lib between BitGoJs and casper-client.

feat(accountlib): BGA-656 Implement KeyPair Generation and Unit Tests

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/integration/coins/eth.ts
modules/core/test/v2/unit/ethWallet.ts

Wallet platform was denying sendMany calls because the isBatch field was not included in the output of signTransaction. The isBatch param is returns when calling /tx/build in wallet platform and is set automatically if the length of recipients is more than 1.
This commit fixed this issue by adding isBatch to the output of signTransaction and would pass the param value from tx/build.
https://bitgoinc.atlassian.net/browse/BG-27047
Ticket: BG-27047

Enable batching eth transfers

---

modules/core/src/v2/wallet.ts

When creating ETH wallets, there is a forwarderVersion flag that can be
used to toggle between the old forwarders and the fee-improved
forwarders. This commit passes that flag when given to the createAddress
function
CLOSES TICKET: BG-28044

Pass forwarderVersion flag

---

modules/account-lib/src/coin/baseCoin/enum.ts
modules/account-lib/src/coin/eth/transactionBuilder.ts
modules/account-lib/src/coin/eth/utils.ts
modules/account-lib/src/coin/eth/walletUtil.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/flushCoins.ts

Sometimes, clients might send ETH to an address before the wallet deployment tx has been confirmed due to fee spike, which results in ETH stuck in forwarders that need to be flushed. 
This PR adds a transaction type to the ETH transaction builder. This allows us to build flush tx in Wallet Platform later.

feat(support flush coins): support flushing native ETH coin

---

modules/core/src/v2/coins/cspr.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/coins/cspr.ts

Implement supplementGenerateWallet for CSPR, in order to provide the
rootPrivateKey needed to initialize the account in WP
Fix getFamily() method for CSPR
Add isValidPrv() method for CSPR
Make generateKeyPair() method for CSRP return extended keys
Ticket: BG-28544

fix(core): fix wallet creation for CSPR

---

modules/express/src/clientRoutes.ts

Log keys `bitgoJsVersion` and `bitgoExpressVersion` on error. This
makes it easier to identify where an error originates (WP or SDK).
Issue: BG-22899

fix(express): log bitgo-express and bitgojs versions on error

---

.drone.jsonnet
.drone.yml
modules/express/README.md
modules/express/src/args.ts
modules/express/src/config.ts
modules/express/src/errors.ts
modules/express/src/expressApp.ts
modules/express/test/unit/bitgoExpress.ts

Sometimes it can be desirable to further restrict access to the BitGo
Express API endpoint beyond that of a localhost TCP connection. An
effective low-effort way of accomplishing further restriction is by
using a Unix domain socket instead. For example, the Unix domain socket
can be placed in a part of the file hierarchy where only the Unix
users/groups that require access to BitGo Express have access. Other
users/groups will be unable to access the Unix socket.
Ticket: BG-28829

feat(express): add support for binding to an IPC socket (unix socket)

---

modules/core/src/v2/wallet.ts
modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/consolidateAccount.ts
modules/express/test/unit/clientRoutes/generateWallet.ts

It's convenient for callers of `wallet/generate` to be able to get the
keychains for their newly generated wallet in the response, instead of
needing to make additional API calls.
To do this in a backwards-compatible way, this change adds a
`includeKeychains` query parameter which, if set, will return the return
of the SDK `generateWallet()` call directly, which includs the wallet
keychains.
Ticket: BG-28844

feat(express): add support for returning keychains with generated wallet

---

modules/express/src/config.ts
modules/express/test/unit/config.ts

When the "IPC" argument was added, all subsequent configs had their
index increased by one. This revealed a bug where odd-numbered config
item indexes incorrectly preferred the env var arguments to the command
line arguments. Because the env vars defaulted to testnet, this broke
the ability to start bitgo express in the production configuration with
the `-e` flag on the command line.
Instead of reversing the configs in the `get()` call, just provide the
configs in the correct order to start with.
Ticket: BG-29084

fix(express): always prefer command line arguments to env var args

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

Recovery of an ETH transaction takes four calls to etherscan, but it bans the 4th call since it exceeds their rate limit of 3 calls per second. We wait one second between the 3rd and 4th call to avoid hitting this limit. 
Ticket: BG-29196

fix: wait a second between 2 subsequent API calls

---

modules/core/src/v2/internal/parseOutput.ts
modules/core/src/v2/wallet.ts

This log info is currently behind a debug namespace flag, but we should
log these unconditionally, because it means something is wrong with the
prebuild that requires investigation.
Ticket: BG-29890

fix(core): improve logging when encountering prebuild validation error

---

modules/core/src/v2/wallet.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/integration/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts

[BG-29057](https://bitgoinc.atlassian.net/browse/BG-29057)
This enhancement adds support for Algorand non-participating key registration transaction. Marking an account non-participating makes an account to not earn rewards.
https://developer.algorand.org/docs/reference/transactions/#key-registration-transaction
The updates are done for "/tx/build" and "tx/initiate" routes which accept an additional nonParticipation flag which generates non-participating key registration transactions. These transactions can then be signed as submitted similar to any other transaction.
Requirements documentation:
https://docs.google.com/document/d/1ZemGLPmf5E9YY1cvqEoNZ7K4wOXxwj75_uQFyDQ09lM/edit?ts=600faba5#

feat: BG-29057: Add non participant keyreg transaction support for Algorand

---

modules/account-lib/package.json
modules/account-lib/src/coin/cspr/ifaces.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/resources/cspr/cspr.ts
modules/account-lib/test/unit/coin/cspr/signMessage.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts

[STLX-676](https://bitgoinc.atlassian.net/browse/STLX-STLX-676) is a SDK-Core story. However, I need Account-Lib changes before so I decided to create this PR with those required changes.
Implemented signMessage and verifySignature methods on utils for Casper.
Used for signMessage on sdk-core.
[STLX-676](https://bitgoinc.atlassian.net/browse/STLX-STLX-676)

feat(account-lib): SignMessage and VerifySign for Casper

---

modules/express/src/clientRoutes.ts

This is useful to help narrow down failing requests within a single
proxied express call.
Also, print stack trace and error message for any type of 5xx error,
instead of only 500's.
Ticket: BG-29870

feat(express): log request method and url upon failed request

---

modules/account-lib/src/coin/cspr/transaction.ts
modules/account-lib/src/coin/cspr/transferBuilder.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/transaction.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/transferBuilder.ts

Return `undefined` if there's no transferId set on the deploy instead of throwing
The transferId value is optional
Depends on: #1047
Ticket: STLX-2082

fix(account-lib): fix getTransferId method of cspr utils

---

modules/statics/src/networks.ts

Kovan moved the API endpoints to the `api-kovan` subdomain, but the block explorer UI is still on `kovan`.
Ticket: BG-30204
Refs: f83b5cd742149f81d2a9a2074f22d8aa812a964c

fix: use correct kovan testnet explorer urls

---

.drone.yml
package.json

These were making the assumption that the PR branch was not yet merged
to master, which isn't the case for PR builds (only push builds).
Please note that this isn't actually merging the PR into the master
branch as if the PR was accepted and merged - this is only a tentative
merge which exists ephemerally within drone during the build pipeline.
Additionally, improve the `generate-drone` script (now called `gen-drone` for
consistency with other scripts) to sign the updated .drone.yml. This should
prevent test secret leakage due to modifications to the .drone.yml from pull
requests.
Ticket: BG-30341

ci: fix ci scripts to work for PR events

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/bch.ts

Currently we don't have a way to see which exact xprv user uses when signing a tx, which makes it hard to debug. This PR 1) sanity checks that the user is not providing an xpub and 2) logs out the corresponding xpub of the xprv that they are using.
BG-24535

feat: add log for xpub during tx signing

---

modules/account-lib/package.json
modules/account-lib/src/coin/stx/iface.ts
modules/account-lib/src/coin/stx/index.ts
modules/account-lib/src/coin/stx/keyPair.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/src/index.ts
modules/account-lib/test/resources/stx/stx.ts
modules/account-lib/test/unit/coin/stx/keyPair.ts
modules/account-lib/test/unit/coin/stx/util.ts
yarn.lock

This PR adds support for the Stacks keypair implementation, along with tests.
The PR is extracted from the exploratory code in [feat/stacks-tx-builer](https://github.com/fariedt/BitGoJS/tree/feat/stacks-tx-builder).
Cc: @wesgraham

feat(account-lib): add stx coin (blockstack) and supporting utils

---

modules/core/src/v2/pendingApproval.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/pendingApproval.ts

Explicitly tag these special types of self-sends, and only call the
specialized build routes for these types when that tag is set.
This prevents inadvertent consolidations due to approving a pending
approval with no recipients (self-sends, since only external recipients
appear in the recipients list).
Note: fanout pending approvals won't work correctly, since their
specialized build route is not implemented in the pending approval
rebuild process.
Ticket: BG-29732

fix(core): add route name as tx type for consolidate/fanout

---

modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

fee param was renamed to feeInfo in explainTransaction method for Casper. Unit test added.
Jira Ticket: [STLX-2278](https://bitgoinc.atlassian.net/browse/STLX-2278)
- fix fee information param name in explainTransaction method for Casper

fix(core): rename feeInfo param in explain tx method for Casper

---

modules/account-lib/src/coin/stx/keyPair.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/resources/stx/stx.ts
modules/account-lib/test/unit/coin/stx/keyPair.ts
yarn.lock

`isValidPublicKey` and `isValidPrivateKey` also support extended keys.
While STX doesn't use extended keys anywhere, this looks like it's needed for functionality in `modules/core`.
Cc: @wesgraham

stx: add support for generating keypairs using extended public/private keys

---

modules/core/src/v2/coinFactory.ts
modules/core/src/v2/coins/index.ts
modules/core/src/v2/coins/stx.ts
modules/core/src/v2/coins/tstx.ts
modules/core/test/v2/unit/keychains.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/networks.ts

STX was removed from statics (https://github.com/BitGo/BitGoJS/pull/1072) due to a behaviour break from other secp256k1 based coins. STX doesn't produce xpubs from it's generateKeyPair function, and instead produces derived keys directly. We have addressed and fixed this in https://github.com/BitGo/BitGoJS/pull/1076/ - and as such are ready again to add STX to statics
Ticket: BG-30487

feat: add STX back to statics

---

modules/express/src/args.ts
modules/express/src/config.ts
modules/express/test/unit/config.ts

The config precedence system expects that command line options which
aren't present to not exist (ie, set to `null` or `undefined`), but when
we use the `storeTrue` action for argparse arguments, omitted options
get set to `false`, which causes them to override any values passed via
environment variables.
Instead, use `storeConst` and store `true` explicitly if the option is
given. This will cause argparse to set the argument value to `null` if
it is omitted.
Ticket: BG-30729

fix(express): don't store false when boolean flags are not given

---

modules/account-lib/src/index.ts

This adds an entry for STX to the `coinBuilderMap` in `account-lib`.  This lets the builder be used from `modules/core`.

add stx to account-lib's coinBuilderMap

---

modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts

The `derivedFromParentWithSeed` parameter allows a user to provide a
seed for deriving a deterministic wallet public key from a cold master
key.
This was implemented directly in the UI wallet generation flow, but
wasn't supported when generating wallets with the SDK.
Ticket: BG-30809

fix(core): send `derivedFromParentWithSeed` when generating wallet

---

modules/core/src/v2/keychains.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

The BitGo server keeps the cold derivation seed on the
`derivedFromKeyWithSeed` property of a user keychain. Unless there's an
explicit `coldDerivationSeed` provided, use the `derivedFromKeyWithSeed`
property when deriving the signing private key.
Ticket: BG-30809

fix(core): use `derivedFromParentWithSeed` from user keychain if present

---

modules/core/src/v2/wallet.ts

There's not much useful info we can glean from the wallet object, and
it's a big object that creates a lot of logging noise.
Ticket: BG-30841

fix(core): don't log wallet upon tx prebuild validation failure

---

.drone.jsonnet
.drone.yml

Node 10 is running out of support at the end of April. The clock is
ticking...
Since we don't yet know if these versions work and don't want to block
further PRs, ignore failures for the new versions for now.
Ticket: BG-30806

ci: run unit tests in node 12, 14, and 15

---

modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/stx/util.ts

* `isValidMemo` ensures that the memo field is valid (not too long).
* `padMemo` right-pads the memo string with nulls (\u0000).  This is useful in tests when comparing a transaction's memo field with expected output.

stx: add util functions to check for valid memo strings and to pad them

---

modules/account-lib/src/coin/stx/index.ts
modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/util.ts

Takes a list of public keys as strings, an optional `AddressVersion` to select between the mainnet (default) and testnet, and an optional `AddressHashMode` (defaults to `SerializeP2SH`).
A second commit exports `AddressVersion` and `AddressHashMode` from `@stacks/transactions`.

stx: getSTXAddressFromPubKeys for multisig transactions

---

.drone.jsonnet
.drone.yml

Otherwise, we might see some regressions which break these
newly-supported versions.
Ticket: BG-23173

ci: require unit tests to pass with node 12, 14, 15

---

modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/src/coin/stx/transferBuilder.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts

This PR implements functionality to add sender public key in builder for unsigned transactions.
cc @wesgraham

stacks: add fromPubKey in transaction builder

---

modules/account-lib/src/coin/celo/resources.ts
modules/account-lib/src/coin/etc/resources.ts
modules/account-lib/src/coin/eth/resources.ts
modules/account-lib/src/coin/rbtc/resources.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/flushCoins.ts
modules/statics/src/account.ts
modules/statics/src/networks.ts

This commit adds the Ethereum chainid to bitgo statics so we can include
it in our built transactions. Account-lib already does this, but
Ethereum does not use account-lib in platform currently. Adding the
field to statics will give us a single source of truth for these values
and allow us to do it in platform. This commit also updates
account-lib's store of chainids to use statics instead of its own
hard-coded values
Ticket: BG-30890

fix(ethlike): add chainid to statics

---

modules/statics/src/networks.ts

Currently statics has Nile info instead Shasta testnet, we need Shasta explorer info to use it on
TAT on links
---
- modules/statics/src/networks.ts
---
stlx-2264

refactor(statics): change trx test network from nile to shasta

---

modules/core/src/v2/coins/btc.ts
modules/core/test/v2/lib/recovery-nocks.ts

The earn.com endpoint is provided inaccurate data and doesn't appear to
be maintained any longer. The mempool.space endpoint is API-compatible
with our use case and provides a more accurate fee estimation.
Closes: #1126
Ticket: BG-31192

fix(core): use mempool.space instead of earn.com for recovery fee

---

README.md

New node versions were recently added to the supported versions list,
but the README was not updated with this information.
Ticket: BG-30998

fix: update version support policy

---

modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/test/unit/coin/stx/transaction.ts

* transactionSize returns the size of the serialized transaction in bytes for accurate fee calculation

stx: add transactionSize

---

modules/core/src/v2/coins/cspr.ts

Use account-lib utils method to validate Casper address
[STLX-2929](https://bitgoinc.atlassian.net/browse/STLX-2929).
**Instructions to test**
1. Download `bitgo-11.13.0.zip` and rename it to `bitgo-11.13.0.tgz`
2. Copy it to packages `clients` and `client-wallet-platform`.
3. Run the following command on both packages root folders:
`npm i bitgo-11.13.0.tgz`
4. Execute client and try to generate new address for a Casper Wallet.
Packaged bitgo build to install:
[bitgo-11.13.0.zip](https://github.com/BitGo/BitGoJS/files/6401082/bitgo-11.13.0.zip)

fix(core): STLX-2929 Fix address validation for Casper

---

modules/core/src/v2/wallet.ts

Transfer id is not stored to in mongodb in entries and coin specific. 
Prebuild is failing because prebuildTransaction method is missing transferId as param, so we added it.
Jira ticket: [stlx-2967](https://bitgoinc.atlassian.net/browse/STLX-2967)

fix(core): transfer id is not stored to in mongodb in entries and coin specific

---

modules/core/src/v2/wallet.ts

fix transferId issue by adding it to the expected sendMany options
[STLX-2967](https://bitgoinc.atlassian.net/browse/STLX-2967)

fix(core): Add transferId to sendMany options

---

modules/core/src/v2/coins/zec.ts

This is not ideal, but the ZCASH_SAPLING_VERSION is missing from the
latest version of utxo lib, so zcash sends are not working currently.
Ticket: BG-31417

fix(core): hard code zcash transaction version

---

modules/account-lib/src/coin/stx/transaction.ts
modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/contractBuilder.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts

this PR fixes issue of multi sig with spending conditions. 
A multisig tranaction when deserialized converted to SingleSigSpendingCondition instead of MultiSigSpendingCondition.
Include some tests improvement around multisig tx.
cc @wesgraham

stacks: fix multi sig issue

---

modules/account-lib/package.json
modules/account-lib/src/coin/celo/utils.ts
modules/account-lib/src/coin/eth/transactionBuilder.ts
modules/account-lib/test/unit/coin/celo/transactionBuilder/staking.ts
modules/account-lib/test/unit/coin/eth/transactionBuilder/contractCall.ts
modules/account-lib/test/unit/coin/trx/util.ts
modules/core/package.json
modules/core/src/v2/coins/stellarToken.ts
modules/core/src/v2/coins/txlm.ts
modules/core/src/v2/coins/xlm.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/unit/coins/xlm.ts
modules/core/test/v2/unit/recovery.ts
modules/express/package-lock.json
package.json
yarn.lock

Update superagent-proxy to ^2.1.0
Update stellar-sdk to ^8.1.1
Update tronweb to ^3.2.6
Update lerna to ^4.0.0
This should resolve (some of) the dependency audit failures.
Ticket: BG-27462

chore: update dependency versions

---

modules/core/src/v2/coins/erc20Token.ts
modules/core/test/v2/integration/coins/eth.ts

Add ability to create unsigned sweep for erc20 tokens. This is for advanced wallets in which the
user has private keys for user and backup key, and there is no password

fix(wrw recoveries): enable unsigned sweeps for recovery of erc20 tokens

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts

Allow disabling implicit external outputs (aka PayGo outputs) during
utxo transaction verification. Some customers don't ever intend to use
the pay-as-you-go model and would like all spends to be explicit (either
to an intended recipient address specified by the customer, or to a
change address which can be provably derived from the wallet keys).
Ticket: BG-30090

feat(core): allow disabling paygo outputs during utxo tx verification

---

modules/account-lib/package.json
modules/core/src/v2/coins/algo.ts
yarn.lock

We want to replace all usages of the algosdk fork that we have with account-lib and have account-lib
consume the latest version of algosdk directly. This is because we don't want to maintain this fork
anymore and we want to standardize the implementation for all our coins to use account-lib.
This change adds the latest version of algo-sdk to account-lib. It also augments the algosdk module in the core package because the types from the latest version of the sdk are overriding the untyped fork.
ticket: [BG-31597](https://bitgoinc.atlassian.net/browse/BG-31597)

feat(account-lib): add latest version of algo-sdk

---

modules/account-lib/.eslintrc.js

Updates ecma version to 2021 to make use of the `BigInt` type.
CLOSES TICKET: BG-31991

chore(account-lib): update ecma version to 2021

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts

The UI will pass an empty object for the verifications options, so this
caused a breaking change in behavior for PayGo users who use the UI.
Instead, consider paygo outputs to be allowed unless the verification
option to allow them is both set and false.
Ticket: CR-296

fix(core): allow paygo outputs for empty verification options object

---

.eslintrc.json
modules/core/src/bitgo.ts
modules/core/test/v2/unit/auth.ts
modules/express/README.md
modules/express/src/args.ts
modules/express/src/clientRoutes.ts
modules/express/src/config.ts
modules/express/test/unit/config.ts

Auth v3 is an extension to the existing auth v2 authentication scheme,
which adds defenses against replay attacks and protocol downgrades.
This commit adds support for Auth v3 to the SDK, and adds flags for
enabling mandatory auth v3 to BitGo Express. Auth v2 is still the
default auth scheme for now until we gain more confidence that Auth v3
is working as intended.
Ticket: BG-30091

feat(core): implement support for auth v3

---

modules/core/example/ts/send-with-provided-public-keys.ts

Some users may want to provide their wallet's keychains directly to the
SDK when sending transactions, so they don't have to trust (potentially
unsigned) keychains received from the BitGo server.
Addresses derivable from these keys will be considered to be part of the
wallet (change addresses), and won't be counted towards the external
send amount.
Ticket: BG-30090

chore(core): add example showing tx verification using provided keys

---

modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts

This change changes the spy to be put on the validateAddress method rather than sender because the latter is moot and doesn't do validation.
ticket: BG-31556

fix(account-lib): Fix validate algo address test.

---

modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts

This change adds a number of signers setter to transaction builder. This is required because the client cannot access the transaction object for which the number of signers is set to before the transaction is built because it is [protected](https://github.com/BitGo/BitGoJS/blob/master/modules/account-lib/src/coin/algo/transactionBuilder.ts#L293).
ticket: BG-31556

feat(account-lib): Add number of signers setter to algo

---

modules/account-lib/package.json
modules/account-lib/src/coin/algo/transactionBuilder.ts
modules/account-lib/src/coin/algo/txnSchema.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/base.ts
yarn.lock

Add transaction validation methods to transaction builder for algo. It uses a joi schema to validate to make things concise and predictable. 
Depends on #1179 
ticket: BG-31558

feat(account-lib): add algo txn validation methods to txn builder

---

modules/account-lib/src/coin/algo/transactionBuilder.ts

Adds support for decoding signed and unsigned algo transactions. It is expected for implementations of transaction builder to have tests to validate that it can decode a signed and unsigned txn.
ticket: BG-31558

feat(account-lib): add support for decoding signed algo txns

---

modules/account-lib/src/coin/algo/transactionBuilder.ts

Algosdk has a issue with its type system right now where the decoded sign transaction is of type EncodedTransaction when it is actually Transaction. This fix is a temporary work around until the issue is resolved.
See the github link in the comments for more context.
tests will be added in a subsequent PR.
ticket: BG-31558

fix(account-lib): fix decode signed algo transaction

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

Freeze wasn't sending the params with the post-call, so it always defaulted to 1 hour.

fix: Update freeze request to include sending params

---

modules/account-lib/package.json
modules/account-lib/src/coin/algo/index.ts
modules/account-lib/src/coin/algo/utils.ts
modules/account-lib/test/unit/coin/algo/utils.ts
yarn.lock

Adds a utility function to convert an algorand public key to an algorand address. This is required for wallet platform
integration which requires a utility function to convert an ED25119 PK to an algorand address.
The [existing utility function](https://github.com/BitGo/bitgo-microservices/blob/develop/packages/wallet-platform/app/controllers/api/v2/coins/algo.js#L216) needs to be refactored to use account-lib instead.
The new addition of the `hi-base32` should be considered safe since the algo-sdk library uses it as well.
https://github.com/algorand/js-algorand-sdk/blob/develop/package.json#L22
ticket: BG-31592

feat(account-lib): add utility function to convert algo pk to addr

---

package.json
yarn.lock

`trim-newlines` has had a recent disclosure of a ReDoS vulnerability.
While we wait for upstream packages to update to a fixed version,
resolve the package to a non-vulnerable version using a yarn resolution.
Ticket: BG-32720

chore(root): add yarn resolution for trim-newlines

---

.drone.jsonnet
.drone.yml
check-package-versions.js
modules/utxo-lib/package.json
package.json

Check versions of in-repo packages to make sure they match with the package.json version.
This is to prevent inadvertent updates of dependency versions for packages which are symlinked
by lerna. The dependency versions of these packages should only ever be updated in the release branch.
Ticket: BG-31227

chore: add step to drone to check managed package version numbers 

---

package.json
yarn.lock

normalize-url has a Regular Expression Denial of Service vulnerability, so this change fixes that.
https://www.npmjs.com/advisories/1755
CLOSES TICKET: BG-32818

chore(root): add yarn resolution for normalize-url

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/recovery.ts

Card: BG 33901: https://bitgoinc.atlassian.net/browse/BG-33091?filter=-1
Abstracting the tx explorer from recovery to UTXO coin controller

BG 33901: Moved block exploring into coin controllers

---

modules/account-lib/src/coin/cspr/delegateBuilder.ts
modules/account-lib/src/coin/cspr/undelegateBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/delegateBuilder.ts
modules/account-lib/test/unit/coin/cspr/transactionBuilder/undelegateBuilder.ts

Use string values to handle large amounts for delegate & undelegate builders
CLOSES TICKET: STLX-4299

fix(account-lib): fix amount in cspr delegate & undelegate builders

---

modules/account-lib/src/coin/cspr/ifaces.ts
modules/account-lib/src/coin/cspr/utils.ts
modules/account-lib/test/unit/coin/cspr/util.ts
modules/core/src/errors.ts
modules/core/src/v2/coins/cspr.ts
modules/core/test/v2/unit/coins/cspr.ts

Change isValidAddress method for cspr in core to validate address with transferId
Add isValidAddressWithPaymentId method to account-lib to validate address with transferId

fix(core): fix cspr address validation to account for transferId

---

modules/core/src/v2/coins/erc20Token.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/gteth.ts
modules/core/src/v2/coins/teth.ts
modules/core/test/v2/unit/coins/eth.ts
modules/statics/src/networks.ts

Client-side verification of transaction pre-builds received from BitGo servers should be verified to match transaction parameters specified by the client before the client signs the transaction.
This is an extra safeguard to protect the client from blindly signing malicious transaction pre-builds from the BitGo servers that do not match the transaction parameters specified by the client. An example of when this can be an issue is if BItGo servers were to be compromised and pre-builds are getting sent to the client that try to send funds to an attacker instead of the recipient address provided by the client.
This PR implements the `verifyTransaction` function for Eth which accepts `txParams` supplied by the client, `txPrebuild` supplied by the BitGo server, and the `wallet` for the …

feat(eth): verify pre-built eth txns

---

modules/core/src/v2/wallet.ts

We're not getting much from whitelisting the tx verification options,
since it's too easy to add a new param and not add it to the whitelist.
Failing to do so silently drops the new parameter and doesn't produce
any warnings or errors about an unknown property.
Instead, let's just pass the whole object to `verifyTransaction` and let
it use any properties on the object that it knows how to handle.
Ticket: BG-30090

fix(core): don't pick individual tx verification options

---

modules/core/src/v2/coins/ltc.ts
modules/core/test/v2/lib/recovery-nocks.ts
modules/core/test/v2/unit/recovery.ts

Link to card: https://bitgoinc.atlassian.net/browse/BG-33091
Changes in this PR:
- Added LTC block explorer to getTxInfo in ltc.ts
- Added nock response for LTC block explorer
- Modified LTC Wrong Chain Recovery Unit Tests to account for new nock response

(BG-33901) Replace IMS Services with 3rd Party Litecoin explorer for Wrong Chain Recoveries

---

modules/core/src/v2/coins/eth.ts
modules/core/test/v2/unit/coins/eth.ts

A bug in the new Eth verification logic for hop transactions caused valid Eth hop transactions to be rejected. As a result, the verification logic was temporarily disabled for hop transactions.
The bug was caused by the verification logic requiring the `txPrebuild` from the sender to the hop address to have an amount exactly equal to the amount the client wanted to send to the final recipient. This was incorrect as the sender actually needs to send an extra amount to the hop address for the hop address to pay the gas fees and still get the desired amount to the final recipient.
This PR adds the non-buggy hop transaction verification logic back to the BitGoJS client. 
It omits the buggy check for the amount sent to the hop address as adding such a check in a robust way does not seem …

fix(eth): restore fixed hop transaction verification

---

DEVELOPERS.md

The platform [url](https://platform.bitgo.com/) is not reachable. From bitgo [homepage](https://www.bitgo.com/), the public Wallet SDK & API link points to this [url](https://app.bitgo.com/docs/). The updates for DEVELOPERS.md and the link in the About section in the repo homepage will be helpful for new developers.

docs(developers.md): update the SDK & API doc link

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/ltc.ts
modules/core/src/v2/recovery.ts
modules/core/test/v2/lib/recovery-nocks.ts

Changes in this PR:
- Added function getUnspentInfoForCrossChainRecovery in abstractUtxoCoin.ts to get unspents using IMS API
- Added LTC block explorer to getUnspentInfoForCrossChainRecovery function in ltc.ts to get unspents
- Used getUnspentInfoForCrossChainRecovery inside findUnspents function in recovery.ts
- Added nock response for LTC block explorer unspents API
Link to the ticket: https://bitgoinc.atlassian.net/browse/BG-32738

BG-32738-fix(core): use ltc explorer to get unspents during cross chain recovery

---

modules/core/src/api.ts
modules/core/src/bitgo.ts
modules/core/src/blockchain.ts
modules/core/src/errors.ts
modules/core/src/keychains.ts
modules/core/src/markets.ts
modules/core/src/pendingapproval.ts
modules/core/src/pendingapprovals.ts
modules/core/src/travelRule.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/enterprise.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/markets.ts
modules/core/src/v2/pendingApproval.ts
modules/core/src/v2/trading/tradingAccount.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts
modules/core/src/v2/webhooks.ts
modules/core/src/wallet.ts
modules/core/src/wallets.ts
modules/express/src/clientRoutes.ts
types/superagent/index.d.ts

BREAKING CHANGE: bluebird-specific promise methods are no longer present
on the `get`/`post`/`put`/`del`/`patch` request helper methods on BitGo
objects.
BREAKING CHANGE: remove support for callbacks to async fns
Native promises don't support the `asCallback` or `nodeify` helpers that
are on Bluebird promises. We will need to add a compatiblity layer for
these since we don't (yet) want to entirely deprecate support for
callback style usage of Bitgo object methods, but for now let's remove
all the callback params and make everything work correctly as regular
async functions.
We still want the current API surface to remain callback compatible for
the moment, so convert from raw promises to bluebird promises where
callbacks are needed.
Ticket; BG-31214

chore!(core): remove bluebird from bitgo object http methods

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/internal/parseOutput.ts
modules/core/test/v2/unit/coins/abstractUtxoCoin.ts

This new transaction verification flag allows user to prevent the
transaction verification logic from considering "migrated from"
addresses as internal to the wallet. For more information on migrated
from addresses, please see the block comment on the `isMigratedAddress`
function in `internal/parseOutput.ts`.
Ticket: BG-30090

feat(core): add `considerMigratedFromAddressInternal` verification flag

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/bcha.ts
modules/core/src/v2/recovery/blockchairApi.ts
modules/core/test/v2/unit/recovery/blockchairApi.ts

Changes in this PR:
- Bitcoin Cash ABC has been rebranded to eCash. Blockchair has changed the routes related to Bitcoin Cash ABC. Replaced "bitcoin-abc" with "ecash" in blockchair related code and tests
- Fixed a typo in JSDoc comment for the function getUnspentInfoForCrossChainRecovery
- Clean up formatting errors in touched files
Ticket: BG-32764

fix(core): replace bitcoin-abc with ecash in blockchair apis

---

modules/core/src/v2/coins/eth.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/eth.ts
modules/core/test/v2/unit/wallet.ts

Adds eip1559 params to send/sendMany routes. If we pass in the new params it will pass it /build and insert the new params as part of the halfSignedTx body to /send route.
Throws an error if a user passes both `gasPrice` and `eip1559` params

Add eip1559 params in send/sendMany

---

modules/core/src/bitgo.ts
modules/core/test/unit/bitgo.ts

The request body for an authenticated request was always `undefined`because it wasn't wrapped in the `then` callback of the request. This fixes that.
ticket: BG-34460

fix(core): request body not being included in HMAC

---

modules/core/src/v2/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts

Wallet platform is returning addresses within the pubs array and this causes an error when we try to sign a tx. This fix should allow us to sign and send enable token transactions.
[STLX-5074](https://bitgoinc.atlassian.net/browse/STLX-5074)

fix(core): fix verify sign parameters for Algorand

---

modules/core/src/v2/coins/eth2.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

After upgrading the `@celo/contractkit` package, a new version of the
`@types/ethereumjs-util` package was also installed. However, since we're using
an old version of `ethereumjs-util` from before it had built-in types support,
we were forced to start using the incompatible `@types` package.
To work around this, we added an alias for the old version of `ethereumjs-util`
in `account-lib` called `ethereumjs-utils-old`. This stopped typescript from
using the incompatible `@types/ethereumjs-util` types since the package names
no longer match. However, since that change was done only in `account-lib`,
that alias package is only resolvable within the `account-lib` source and
tests.
This caused an issue when code in the `core` library was modified to use the
`ethereumjs-utils-old` package. …

fix(core): ignore typescript errors from incompatible `@types/ethereumjs-util`

---

modules/core/package.json
yarn.lock

This is no longer required in any part of the code base, so we can now
remove it.
Ticket: BG-25653

chore(core): remove `prova-lib` dependency

---

modules/core/package.json
modules/core/src/bitgo.ts
modules/core/test/unit/bitgo.ts

We have two separate places where we use ECDH: token issuance and wallet sharing.
They are mutually incompatible but internally compatible, which is what counts.
Issue:  BG-34381

refactor(core): use secp256k1 for ECDH

---

modules/core/src/v2/coins/trx.ts

fix getExtraPrebuildParams for TRX coin, contractCalls weren't building correctly
stlx-4989

fix(core):[STLX-4989] fix getExtraPrebuildParams

---

yarn.lock

Update deps of `lerna` and `@celo/contractkit` to fix audit issues
See https://www.npmjs.com/advisories/1771 for more info
Ticket: BG-34751

Update deps to fix `tar` audit failures

---

modules/core/package.json
modules/core/src/bip32path.ts
modules/core/src/bitcoin.ts
modules/core/test/lib/keys.ts
modules/core/test/unit/bip32path.ts
modules/core/test/unit/hdnode.ts

Add helper for converting buggy invalid bip32 paths into somewhat
reasonable bip32 paths that can be used with standard libraries.
Issue: BG-34708

feat(core): add bip32path.fromLegacyPath()

---

modules/account-lib/package.json
modules/blake2b-wasm/package.json
modules/blake2b/package.json
modules/core/package.json
modules/express/package.json
modules/statics/package.json
modules/utxo-lib/package.json

This updates the `repository` property in package.json for the various modules to ensure they point to the current repository and to refer to their directory within the monorepo.
I noticed that a few of these were pointing to old repository URLs that are no longer in use or which we have since forked from.

chore: update repository metadata in package.json

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/utxo/recover.ts

The class method implementation was using deprecated coroutine wrappers and
was way too long.
5e89226e (Otto Allmendinger, 36 minutes ago)
chore(core): apply prettier to abstractUtxoCoin

refactor(core): move utxo recover method to separate file

---

modules/core/src/bip32util.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/unit/bip32util.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts

Add bip32-aware signMessage/verifyMessage wrappers.
Remove redundant implementations and tests.

feat(core): add bip32util with signMessage/verifyMessage

---

modules/core/package.json
yarn.lock

Should fix flaky build: https://github.com/stellar/js-stellar-sdk/issues/645
Issue: BG-34800

fix(core): bump stellar-sdk

---

modules/core/src/transactionBuilder.ts

The `hdPath()` wrapper is not needed any longer.
99ed890a (Otto Allmendinger, 6 minutes ago)
fix(core): transactionBuilder: ignore `walletSubPath === 'm'`
The `m` component is only allowed at the very beginning, but some of our
tests have it in the middle of a path.
Sadly our buggy `deriveKey` method allows it anywhere (and simply ignores
it).

chore(core): deprecate hdPath in transactionBuilder

---

modules/core/src/bitcoin.ts
modules/core/src/bitgo.ts
modules/core/src/keychains.ts
modules/core/src/transactionBuilder.ts
modules/core/src/travelRule.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/xtz.ts
modules/core/src/v2/wallets.ts
modules/core/src/wallet.ts
modules/core/src/wallets.ts
modules/core/test/integration/travelRule.ts

Instead of `hdPath(v).derive(p)` use `v.derivePath(p)` or
`v.derivePath(sanitizeLegacyPath(v))` depending on context.
Instead of `deriveKey(p)` use `derivePath(p).keyPair`.

refactor(core): deprecate hdPath

---

modules/core/src/bitgo.ts

Prior to v12, the `Authorization` header was applied just before sending a
request, but in v12 it was applied when the request was instantiated. It's
possible for tokens to be swapped out in time between the request getting
instantiated and getting sent, so we need to continue to lazily apply the
`Authorization` header.
Ticket: BG-34772

fix(core): defer application of authorization headers

---

modules/core/src/bitgo.ts
modules/core/src/ecdh.ts
modules/core/src/travelRule.ts
modules/core/src/v2/wallet.ts
modules/core/src/v2/wallets.ts
modules/core/src/wallet.ts
modules/core/src/wallets.ts
modules/core/test/ecdh.ts
modules/core/test/integration/travelRule.ts
modules/core/test/unit/bitgo.ts

* Move from class method to regular function (we don't use the bitgo
object)
* Move tests
* Add support for bip32 arguments
* Return buffer, convert to `hex` at callsite

refactor(core): use bip32 in ecdh operations

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/utxo/recover.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/recovery/initiate.ts

This method has an awkward type signature that does not really fit well with
non-bip32 coins (XLM). It is also needlessly async.
Instead of messing around with complex generics we can simply define methods
`getBip32Keys()` and `getStellarKeys()` with good type signatures.
Outside of BitGoJS this method is only used in the Wallet-Recovery-Wizard, which can simply
use `getBip32Keys()` instead.
See individual commits for details.

refactor(core): deprecate coin method `initiateRecovery()`

---

modules/core/src/config.ts
modules/core/test/v2/unit/baseCoin.ts

Before, we assumed erc20 tokens are either mainnet or kovan (If it is not eth, then it is teth).
erc20 tokens now can be eth, teth, and gteth
More information can be found on this related PR on the WP: https://github.com/BitGo/BitGoJS/pull/1351
Ticket: BG-34419

fix(eth): goerli coins now set to gteth in core/src/config.ts

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

During uploading an unsigned EOS transaction file in OVC, an issue was coming "coin undefined is not defined"
because field "coin" was expected in the recovery file but it was not being added while forming the
recovery transaction. I have added the coin field at the time of forming recovery transaction in function `recover()` in eos.ts
While signing the unsigned EOS transaction using EOS, an
issue was coming because `signTransaction()` function was expecting a field "txHex", but this field was
not there in the unsigned transaction. So I have added "txHex" field as well in unsigned recovery transaction
file
Ticket: BG-30012

fix(core): fix issue while signing eos transaction using OVC

---

modules/account-lib/package.json
modules/core/package.json
modules/statics/package.json

Version numbers for packages inside the bitgojs monorepo are managed by lerna
and should not be updated except on the rel/rc branch during the release
process.
Ticket: NO-000

revert: return master branch package versions to non-rc versions

---

modules/account-lib/src/coin/stx/utils.ts
modules/account-lib/test/unit/coin/stx/util.ts

Added a signatureRequired parameter to getSTXAddressFromPubKeys with a default value of 2, needed for a correct address generation
Fixed related unit Tests
Jira Ticket: [stlx-5754](https://bitgoinc.atlassian.net/browse/STLX-5754)

fix(accountlib): fix getStxAddressFromPubKeys to add signatures required paramater

---

modules/core/src/v2/wallet.ts

This parameter is a free-form string and not a number.
Ticket: BG-35021

fix(core): change type of `sequenceId` to string

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/express/src/expressApp.ts
tsconfig.json

This allows typescript to compile with native `async`/`await` syntax,
greatly improving stack traces.

feat(root): set tsconfig target to `es6`

---

modules/core/src/v2/coins/eth.ts

The version of `@ethereumjs/tx` which was recently upgraded to no longer needs
an explicit `0x` prefix added to the `to` field on transaction objects.
A merge race allowed this to get into master without failing any tests.
Ticket: BG-35058

fix(core): don't add extra `0x` prefix when formatting for offline vault

---

modules/core/src/bitcoin.ts

Sadly we can't fully remove them just yet because there are a few
legacy sites that use it.

chore(core): add deprecation notice in bitcoin.ts

---

modules/core/src/v2/internal/util.ts

The `publicToAddress()` method does in fact accept compressed keys
Remove deprecated `p2shMultisigOutputScript`.

chore(core): use bip32 in internal/util

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
tsconfig.json

Turns out even though es6 (aka 2015) supports async/await, we have to set
the target to es2017 to get it
See https://stackoverflow.com/a/50109624
chore(core): add deprecation marker to getCoinLibrary()

chore(root): set target to es2017

---

modules/core/src/v2/coins/erc20Token.ts
modules/core/src/v2/coins/eth.ts

Removes the extraneous spendAmount field which is not used anywhere for constructing an eth transaction.
Not even used in the constructor: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/baseTransaction.ts#L71
ticket: BG-35058

refactor(core): remove extraneous spendAmount field

---

modules/utxo-lib/package.json
modules/utxo-lib/src/bitgo/index.ts
modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/outputScripts.ts
modules/utxo-lib/test/integration_local_rpc/generate/fixtures.ts
modules/utxo-lib/test/integration_local_rpc/generate/main.ts
modules/utxo-lib/test/integration_local_rpc/generate/outputScripts.util.ts
modules/utxo-lib/test/integration_local_rpc/generate/types.ts
modules/utxo-lib/test/integration_local_rpc/parse.ts

We need to be able to support verification of half-signed (1-of-3)
transactions, so we must also support signing these kinds of transactions.
f7597ff9d
feat(utxo-lib): add getDefaultSigHash(network)
We can finally add a method that gives a good default `sigHash` value per
network.
52e31eb81
refactor(utxo-lib): use bip32 in outputScripts.util.ts
95f1c92e4
feat(utxo-lib): add createSpendTransaction match test
Assert that re-signing the transaction with the same inputs and keys 
results in the exact same hex output.

feat(utxo-lib): add tests for half-signed transactions

---

DEVELOPERS.md
package.json
yarn.lock

We already check commit message formats during drone builds, so this
extra local check seems to just get in the way and confuse new
developers.
Let's remove it and rely instead on the commit message format checks in
drone.
If this makes for too slow an iteration cycle, we can instead run the
commitlint check in a pre-push script. We can revisit this in a later
PR.
Ticket: BG-35311

chore(root): remove `commitizen`

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/test/v2/unit/coins/btc.ts
modules/utxo-lib/src/bitgo/index.ts
modules/utxo-lib/src/bitgo/signature.ts

Use functionally identical `verifySignature()` method from utxolib.

refactor(core): use utxolib.bitgo.verifySignature()

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Reverting DYNS ticker name back to DYN due to downstream billing and platform issue and blocking wallet creation for DYN wallets
stlx-6496

feat(statics): revert DYNS token to DYN

---

modules/utxo-lib/test/bitgo/signature.ts
modules/utxo-lib/test/integration_local_rpc/parse.ts

We have an implicit test in `integration_local_rpc` but it is worth having
a more thorough dedicated one.
1e0b6bfe6
refactor(utxo-lib): improve integration_local_rpc signature test
More exhaustive `verifySignature(..., { publicKey })` test.

refactor(utxo-lib): extend verifySignature test

---

modules/statics/src/networks.ts

**Background**
calculateEthAddress2 function which is used to create ethereum addresses for forwarder version 1 was being used in bitgo-microservices. Now, this function has been added in bitgojs core and bitgo-admin as well. This function uses forwarderFactoryAddress and forwarderImplementationAddress for calculating the addresses.
**Changes**
Add forwarderFactoryAddress and forwarderImplementationAddress  for ethereum networks in network.ts
Ticket: BG-35734

refactor(statics): add forwarder config address used for creating forwarder version 1 eth addresses

---

modules/core/src/bitcoin.ts
modules/core/src/bitgo.ts
modules/core/src/transactionBuilder.ts
modules/core/src/wallets.ts
modules/core/test/integration/wallets.ts
modules/core/test/v2/unit/trading/payload.ts

The `ECPair.getAddress()` API will be deprecated soon

refactor(core): add, use getAddressP2PKH()

---

modules/account-lib/src/coin/stx/transactionBuilder.ts
modules/account-lib/test/unit/coin/stx/transaction.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/contractBuilder.ts
modules/account-lib/test/unit/coin/stx/transactionBuilder/transferBuilder.ts

Fixed the transactionBuilder constructor to set the network based on the coin stx or tstx  
Added and fixed Unit test based on env
[stlx-7056](https://bitgoinc.atlassian.net/browse/STLX-7056)

fix(accountlib): stx transactionBuilder network fix

---

modules/core/src/bitcoin.ts
modules/core/test/v2/unit/bitcoin.ts

The typescript types are broken somehow and the `key` parameter is getting
typed as `any`, which caused us to incorrectly handle the case where the `key`
was an ECPair instance.
Ticket: BG-36337

fix(core): correctly handle ECPair case in `getAddressP2PKH`

---

modules/core/package.json
modules/core/src/config.ts
modules/core/src/v2/coins/erc20Token.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/internal/util.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/eth.ts
yarn.lock

**Background**
BitGo Express does not adequately verify the addresses returned by BitGo Servers while building transactions. If the BitGo servers are compromised, the address verification logic ensures that BitGo Express cannot be tricked by providing a wrong address. 
**Changes**
- Added function `verifyAddress()` for Ethereum.
- Added `calculateEthAddress2()`: function to create ethereum address for forwarder version 1, `calculateEthAddress()`: function to create ethereum address for forwarder version 0, `getProxyInitcode()`: function to get the initcode which is used to create address with forwarder version 1  in utils file
- Added constants for forwarderFactoryAddress and forwarderImplementationAddress in config file
- Added unit tests for the Address verification function
- Added …

feat(core): add function for verifying ethereum addresses in bitgo express

---

modules/statics/src/networks.ts

Ticket: [BG-36505](https://bitgoinc.atlassian.net/browse/BG-36505)
It seems useful to be able to differentiate between different networks at runtime. For example, on Ethereum we are trying to support Goerli testnet in addition to Kovan, and so it can be useful to know which `network` a given `CoinToken` corresponds to. This was required in [another PR](https://github.com/BitGo/bitgo-microservices/pull/11717) and it didn't seem like we had a clear way to do this. Initially, the most obvious way seemed to be a regex/substring match on the explorerUrl, which did not seem very robust. 
Now, a developer could head over to this repo, take a look at the network classes and use something like `network.constructor.name` to determine the name of a given network (and that seems valid). But I would …

feat(statics): Add 'name' property to networks

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Relates to ticket: [BG-34816](https://bitgoinc.atlassian.net/browse/BG-34816)
For a given coin, we decide which icon to load for it based on its `assetStr` which comes from its UnderlyingAsset property here in statics. We want to load different icons for Kovan and Goerli on the frontend, so this PR changes Goerli to have a different underlying asset than Kovan. Note: it might also be worth changing Kovan's UnderlyingAsset to `TETH` or something like that for consistency (although this would require storing duplicate icons for TETH and ETH in the frontend src).

fix(statics): change Goerli ETH underlying asset from ETH to GTETH

---

modules/utxo-lib/src/address.ts

This exports the `Base58CheckResult` and `Bech32Result` types from bitcoinjs-lib to make them available for use in external projects.
Ticket: BG-32852

feat(utxo-lib): export address check types

---

modules/core/src/config.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/internal/util.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

**Background**
In order to calculate forwarder version 1 address for Eth, we had to add calculateEthAddress2, getProxyInitcode methods and forwarderFactoryAddress, forwarderImplementationAddress constants in BitGoJS core module. But the same methods and constants were required in bitgo-admin as well. So we decided to add the methods in account lib and constants in @bitgo/statics
**Changes**
- Used calculateEthAddress2, getProxyInitcode  methods from account lib
- Used forwarderFactoryAddress, forwarderImplementationAddress from @bitgo/statics
- Modified the condition to invoke `verifyAddress()` method in `createAddress()` method. In case of Eth forwarder v1, if the address is pending onchain initialization, then need to verify the address
- Added unit test for this change in condition …

refactor(core): use eth utils method from acctlib

---

modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/test/bitgo/outputScripts.ts
modules/utxo-lib/test/integration_local_rpc/generate/outputScripts.util.ts

This refactors the output script functions so `createTaprootScript2of3` is used as a helper function within `createOutputScript2of3` rather than being exported and used externally on its own. This restores the previous behavior of having a single function used to generate output scripts for all multisig 2-of-3 script types.
Ticket: BG-35573

refactor(utxo-lib): use taproot script helper function

---

modules/statics/src/coins.ts

Grants eos/teos the SUPPORTS_TOKENS feature.
Static coins in client-wallet-platform determines if a coin supports tokens or not by checking for this feature. see [client-wallet-platform/coinConfig.js](https://github.com/BitGo/bitgo-microservices/blob/develop/packages/client-wallet-platform/bitgo/modules/v2/components/coinConfig/coinConfig.js#L940).

feat(statics): update EOS with SUPPORTS_TOKENS feature

---

modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/test/address/fixtures/bitcoin.json
modules/utxo-lib/test/address/fixtures/testnet.json
modules/utxo-lib/test/bitgo/outputScripts.ts

This fixes the tapscript construction to use `OP_CHECKSIG` instead of another `OP_CHECKSIGVERIFY` for the second op code used in the script. This ensures that there is a `true` value in the stack after the script is executed.
Ticket: BG-35573

fix(utxo-lib): use OP_CHECKSIG for 2nd p2tr opcode

---

modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/outputScripts.ts
modules/utxo-lib/test/bitgo/signature.ts
modules/utxo-lib/test/integration_local_rpc/parse.ts
modules/utxo-lib/test/transaction_util.ts

* Add method `createOutputScriptP2shP2pk(Buffer): SpendableScript`
* Add new optional property `p2shOutputClassification`, which will be
set for all `p2sh` scripts
* Inputs that are of type `p2shP2pk` will have
`p2shOutputClassification` set to `pubkey`.
Issue: BG-37916

feat(utxo-lib): support p2shP2pk inputs

---

modules/account-lib/package.json

There's currently a breaking issue in `@hashgraph/sdk` which prevents us from
running the latest `bitgo` rc successfully.
https://github.com/hashgraph/hedera-sdk-js/issues/729
This pins the package version to the latest minor version + patch updates.
Ticket: BG-38554

chore(account-lib): accept only patch updates to `@hashgraph/sdk`

---

modules/utxo-lib/test/integration_local_rpc/generate/RpcClient.ts
modules/utxo-lib/test/integration_local_rpc/generate/faucet.ts
modules/utxo-lib/test/integration_local_rpc/generate/fixtures.ts
modules/utxo-lib/test/integration_local_rpc/generate/main.ts

More recent bitcoin core versions do not have a default wallet set and
require `loadwallet` and `createwallet` calls.
The current bitcoind git master version also requires a scoped RPC
path for wallet operations.
This change supports Bitcoin 22.x.x in a backwards-compatible manner.
Issue: BG-38416

test(utxo-lib): add support for bitcoin core 22

---

modules/core/src/stringTextDecoder.ts
modules/core/src/v2/coins/eos.ts
modules/core/test/v2/fixtures/coins/eos.ts
modules/core/test/v2/unit/stringTextDecoder.ts

OVC uses Electron to package their application. There is a known issue
with Electron apps crashing when using TextDecoder with large inputs.
Workaround is to implement our own decoder using StringDecoder.
Ticket: BG-38309
Verified OVC works with locally built BitGoJS
:

fix(eos): fix deserialize transaction with OVC

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/btc.ts

This fixes p2tr script path signing for transactions with multiple inputs. Previously, the prevout scripts needed for signing were missing on p2tr inputs besides the one that was actively being signed for. However, attempting to sign an input would populate all data required for signing that input, includuing its prevout script. This introduces a workaround that makes a second pass at sign attempts for any sign calls that failed on the first attempt. On the second attempt, each input will have had its signing data and prevout scripts populated.
This also adds a test case that creates two p2tr addresses using `createMultiSigAddress` and then creates unsigned tx hex using inputs from both addresses. The unsigned tx is then signed twice using the user and backup keys. The resulting signed tx …

fix(core): sign multi-input p2tr script path txs

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

We need to validate the the memoId in the buildParams and address are equal ONLY when memoId is present in the address as a query param. If the memoId is not present in the address then do not check for equality.
TICKET: BG-38801

fix(core): fix memoid check for eos txn

---

modules/unspents/src/dimensions.ts
modules/utxo-lib/src/bitgo/signature.ts

This adds support for classifying a partially signed p2tr input after parsing the signature by checking for an `inputClassification` of `taproot` and checking the size of the control block to distinguish between a level 1 and level 2 depth script path spend.
Ticket: BG-37329
Note: This fixes the bug mentioned here: https://github.com/BitGo/bitgo-microservices/pull/13243/files#diff-2cc59901c8cb5f7eacecfab40a529dc3c0ac12387846622d9a6ab7423a9a8f46R1129

feat(unspents): classify p2tr script path sigs

---

modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/test/unit/base.ts

each value in UnderlyingAsset represents an asset and clients use the value to determine which icon to show. additionally, the same underlying asset may be used by multiple chains (e.g. USDT exists as an erc20 and eos token).
previously, we had two enum entries with the same value 'box'. one was meant for the erc20 token and the other for eos. this led to us showing the wrong icon for the eos box token. fix is to make sure BOX and EOS_BOX have different values.

fix(statics): ensure UnderlyingAssets values are unique

---

modules/statics/src/coins.ts

Updating GOG contract. We confirmed that there are no transfers existing for the old GOG and updating the contract accordingly. Ticket: STLX-9469
Jira ticket: https://bitgoinc.atlassian.net/browse/STLX-9469
STLX-9469

feat(statics): update Token Gog

---

modules/core/package.json
yarn.lock

The `ripple-address-codec` package published 4.2.0 2 days ago, which
included a breaking change of requiring npm >= 7. This is not the
default version of npm installed with node 14 and is a significant
change in behavior from npm 6, so not all clients can be expected to
update easily.
Therefore we pin `ripple-address-codec` to `~4.1.3`, the last-published
4.1 version.

fix: exclude ripple-address-codec 4.2

---

modules/unspents/src/dimensions.ts
modules/unspents/test/signedTx/txGen.ts
modules/utxo-lib/src/bitgo/index.ts
modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/signature.ts

This allows easy type discrimination.
Add more `parseSignatureScript` tests.
Issue: BG-37883

feat(utxo-lib): add property `scriptType` to ParsedSignatureScript

---

modules/core/src/bitgo.ts
modules/core/src/encrypt.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/internal/internal.ts
modules/core/test/encrypt.ts
modules/core/test/v2/unit/internal.ts

Accessing `encrypt`/`decrypt` via BitGo instance is annoying and
unintuitive.
The vendored sjcl library needs to be replaced with a regular
dependency. Add test fixtures to allow that.

refactor(core): move encrypt/decrypt to separate file, add tests

---

modules/core/src/errors.ts
modules/core/test/v2/unit/errors.ts

The workaround was only required when transpiling to ES5[1], which has
not been the case for a while.
[1]: https://www.dannyguo.com/blog/how-to-fix-instanceof-not-working-for-custom-errors-in-typescript/#upgrade-the-compilation-target

chore(core): remove `Object.setPrototypeOf` workaround

---

modules/statics/src/coins.ts
modules/statics/src/networks.ts
modules/statics/test/unit/coins.ts

The network constants are already defined in utxolib, there is no need
to repeat them in `statics`.
Also add `BitcoinGoldTestnet`.
Sanity check:
```
» yarn ts-node -e '
import * as utxolib from "@bitgo/utxo-lib";
import { coins, UtxoCoin } from "./src";
for (const name in utxolib.networks) {
console.log(
name,
coins
.filter((coin => (coin as UtxoCoin).network.utxolibName === name))
.map(coin => coin.name)
);
}
'
bitcoin [ 'btc' ]
testnet [ 'tbtc' ]
bitcoincash [ 'bch', 'bcha' ]
bitcoincashTestnet [ 'tbch', 'tbcha' ]
bitcoingold [ 'btg' ]
bitcoingoldTestnet [ 'tbtg' ]
bitcoinsv [ 'bsv' ]
bitcoinsvTestnet [ 'tbsv' ]
dash [ 'dash' ]
dashTest [ 'tdash' ]
litecoin [ 'ltc' ]
litecoinTest [ 'tltc' ]
zcash [ 'zec' ]
zcashTest [ 'tzec' ]
```
Issue: BG-39753

fix(statics): use `utxolibName` instead of redefining constants

---

modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/signature.ts
modules/utxo-lib/test/transaction_util.ts

Correctly handle unsigned inputs and return empty signature array.

fix(utxo-lib): do not throw on unsigned inputs

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/btc.ts
modules/core/src/v2/coins/utxo/recovery/crossChainRecovery.ts
modules/core/src/v2/coins/utxo/sign.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/utxo/recovery/crossChainRecovery.ts
modules/core/test/v2/unit/coins/utxo/transaction.ts
modules/core/test/v2/unit/coins/utxo/util/index.ts
modules/core/test/v2/unit/coins/utxo/util/keychains.ts
modules/core/test/v2/unit/coins/utxo/util/unspents.ts
modules/core/test/v2/unit/wallet.ts

* Change AbstractUtxoCoin SignTransactionOptions to accept a `pubs`
string triple and cosignerPub string.
This makes it more consistent with the `prv` parameter which is also
a string.
* Add, use `signAndVerifyWalletTransaction()` method which wraps
`signWalletTransactionWithUnspent`

refactor(core): add, use signAndVerifyWalletTransaction for utxo

---

modules/core/test/v2/unit/coins/utxo/custom/btc.ts

There are now no custom one-off utxo tests in `unit/coins`.
Issue: BG-35154

test(core): move bespoke btc tests to utxo/custom

---

modules/account-lib/src/coin/baseCoin/baseTransaction.ts
modules/account-lib/src/coin/baseCoin/iface.ts
modules/account-lib/src/coin/sol/iface.ts
modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/test/unit/coin/sol/transaction.ts

partially implements explain transaction for solana.
does not handle fees or transaction ids correctly.
Ticket: STLX-8791
Note: follows new standardized pattern, where implementation is in account-lib.
See Dot PR for reference: https://github.com/BitGo/BitGoJS/pull/1723/files

feat(sol): initial implementation of explain transaction

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/utxo/sign.ts
modules/core/test/v2/unit/coins/utxo/transaction.ts
modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/signature.ts

We want to know that a transaction was signed by the wallet keys.

fix(core): use wallet keys in explainTransaction

---

modules/core/src/v2/coins/eos.ts
modules/core/test/v2/fixtures/coins/eos.ts
modules/core/test/v2/unit/coins/eos.ts

There is a current use case where a custodial wallet
wants to send to an alphanumeric memoid for eos.
TICKET: BG-39825

feat(core): allow alphanumeric memoid for eos

---

modules/account-lib/src/coin/sol/transaction.ts
modules/account-lib/test/unit/coin/sol/transaction.ts
modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

implements parse transaction for Solana
also sneaks in a fix to calculate `fee` correctly by using the transaction's `numSignaturesRequired` instead of current number of signatures.
Ticket: STLX-10400

feat(sol): implement parse transaction

---

modules/account-lib/src/coin/dot/addressInitializationBuilder.ts
modules/account-lib/src/coin/dot/index.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilderFactory.ts
modules/account-lib/src/coin/dot/txnSchema.ts
modules/account-lib/test/unit/coin/dot/transaction.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/walletInitializationBuilder.ts

The transaction type for create of a Proxy Account (receive address) should be labelled as `addressInitialization`.
This PR renames the types/schema and the transaction builder for adding a proxy account on the DOT network.
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-10457

chore(account-lib/dot): rename walletInitialization to

---

modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/btc.ts
modules/core/src/v2/coins/btg.ts
modules/core/src/v2/coins/ltc.ts
modules/statics/src/base.ts
modules/statics/src/ofc.ts
modules/statics/src/utxo.ts
modules/utxo-lib/src/bitgo/nonStandardHalfSigned.ts
modules/utxo-lib/src/bitgo/outputScripts.ts
modules/utxo-lib/src/coins.ts
modules/utxo-lib/src/index.ts
modules/utxo-lib/test/address/address.ts
modules/utxo-lib/test/bitgo/outputScripts.ts
modules/utxo-lib/test/bitgo/signature.ts
modules/utxo-lib/test/integration_local_rpc/generate/main.ts
modules/utxo-lib/test/integration_local_rpc/generate/outputScripts.util.ts
modules/utxo-lib/test/networks.ts

Provide canonical place for this information.
BREAKING CHANGE: Removes these methods from AbstractUtxoCoin:
* `supportsP2sh()`
* `supportsP2shP2wsh()`
* `supportsP2wsh()`
* `supportsP2tr()`
Use `supportsAddressType(ScriptType2Of3)` instead.

feat(utxo-lib): add isSupportedScriptType(network, scriptType)

---

modules/account-lib/src/coin/dot/index.ts

In order to use the type def outside of account-lib, we will need to export the type like eth or celo do.
Ticket: STLX-8335

chore(account-lib): export polkadot interface

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts

The method, while optional, is part of the generic coin interface.
Unfortunately it is very difficult to have very strong types here so
we have to add a bunch of type parameters.
The `options` argument in fact is so heterogeneous between coin
implementations that it cannot be narrowed to anything meaningful
besides `any` (see implementation for EOS).
Issue: BG-40467

fix(core): add base `explainTransaction` method

---

modules/account-lib/src/coin/dot/addressInitializationBuilder.ts
modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/addressInitializationBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts

Changing `proxyType` to an enum will allow WP to access the values inside instead of just using `proxyType` as a `type`
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-8351

chore(account-lib): change proxyType to an enum

---

modules/account-lib/DEVELOPER.md
modules/account-lib/README.md

Did a light copyedit to familiarize myself with the account-lib docs. This is step 1 in creating a suite of coin onboarding tutorials.

add light copyedit to account-lib docs

---

modules/core/src/v2/wallet.ts

The `params` are not actually passed to `signTransaction()`
Issue: BG-39265

fix(core): correctly pass `pubs`

---

README.md
modules/account-lib/DEVELOPER.md
modules/blake2b-wasm/README.md
modules/blake2b/README.md
modules/blake2b/index.js
modules/blake2b/package.json
modules/core/README.md
modules/core/example/README.md
modules/core/example/ts/README.md
modules/core/package.json
modules/statics/README.md

As seen here[^1] and here[^2].
[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript
[^2]: https://www.typescriptlang.org/

docs: capitalize JavaScript and TypeScript properly

---

modules/statics/src/networks.ts

Changed send-many-memo contract address in the stx mainnet config
[STLX-11908](https://bitgoinc.atlassian.net/browse/STLX-11908)

fix(statics): fix send many memo contract address for prod

---

modules/statics/package.json
modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
yarn.lock

The package level prettier version is behind, which is causing compilation errors when running precommit hooks on typescript packages that have string literal types. Given the amount of format changes, this will be a standalone PR.
Ticket: STLX-12051

chore(statics): remove package level prettier

---

package.json
yarn.lock

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Exposure of sensitive information in follow-redirects        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ follow-redirects                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.14.7                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bitgo/account-lib                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bitgo/account-lib > casper-client-sdk > axios > …
```

fix(root): resolve `follow-redirects` to version ^1.14.7

---

modules/account-lib/src/coin/dot/iface.ts

the proxy type of “Governance” is no longer supported by the substrate package used for transaction building - removing the type from account-lib will help remove testing for the type which could cause failures.
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-12064

fix(account-lib): remove proxy type from constants STLX-12064

---

modules/core/src/v2/coins/sol.ts
modules/core/test/v2/unit/coins/sol.ts

addresses mismatches between usages of txHex and txBase64
Ticket: STLX-12389
verified in testnet-06:
```
const wallet = await bitgo.coin('tsol').wallets().get({ id: '61e8dfa754e0f10007750aaf8c11640e' });
const sendTx = await wallet.send({
address: 'DHjfEwHhPaK4cmAu7Y77DLArgFz7g9HcoaK9YQvLJVwi',
amount: '1000',
walletPassphrase: 'Ghghjkg!455544llll',
type: 'transfer',
});
console.log(JSON.stringify(sendTx, undefined, 2));
```

fix(core): fix sol send tx

---

modules/core/src/v2/wallet.ts

This is a boolean parameter and typing as a `string` is incorrect.
Ticket: BG-41942

fix(core): correct type of `allTokens` property on `TransfersOptions`

---

modules/core/src/v2/coins/avaxcToken.ts
modules/core/test/v2/unit/coins/avaxcToken.ts

Fixed avaxcToken class to get base chain and build correctly the transaction. Fixed respectly
unit-test
STLX-12548
Signed-off-by: evalenti-simtlix <evalenti@simtlix.com>

fix(core): token transactions does build correctly

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

This change allows a user to pass an arbitrary function as the
`customSigningFunction` property to any function which signs
transactions. This custom signing function will take all the same
arguments which are passed to a coin implementation's `signTransaction`
function, except no private key will be provided - the custom signing
function is responsible for acquiring and applying the user's private
key. It is expected to resolve to a valid half-signed transaction that
will then be sent to BitGo for cosigning via the normal `/tx/send`
route.
This effectively allows the user to bypass the built-in signing flow and use
their own implementation for transaction signing, while still leveraging
BitGoJS to verify the transaction and send it to BitGo for cosigning.
Ticket: BG-41943

User-provided custom signing function

---

LICENSE
package.json

We originally add a license in #225, later removed in #353.
Adding this information back, even with the `private` npm setting
configured in #353, exposes at-a-glance information in the GitHub
UI.
Ticket: OPS-1296

chore(root): add explicit license information

---

modules/core/example/js/eth/set-flush-threshold.js
modules/core/example/ts/eth/set-flush-threshold.ts

Added JavaScript and TypeScript example to set flush threshold for a token.
Ticket: [BG-41448](https://bitgoinc.atlassian.net/browse/BG-41448)

fix(core): add flush threshold example

---

modules/account-lib/src/coin/dot/addressInitializationBuilder.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/test/unit/coin/dot/keypair.ts

Some of the types in dot is still `any`. Adding defined types to avoid loose types.

chore(account-lib): add defined types for dot

---

modules/account-lib/src/coin/dot/iface.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilderFactory.ts

Add getter so that it can be used in WP after `register` is invoked.
WP PR that needs this: https://github.com/BitGo/bitgo-microservices/pull/15379
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-12458

chore(account-lib): add getter to factory for batch transaction builder

---

modules/core/src/v2/wallet.ts
modules/express/package.json
modules/express/src/clientRoutes.ts
modules/express/test/integration/externalSigner.ts
yarn.lock

This commit takes the external signer url passed into the express config
and uses it to create a custom signing function. The custom signing
function is then included in any calls which involve signing. Note that
this commit only covers wallet v2 endpoints.
Ticket: BG-42397

feat: add custom signing function url to requests

---

modules/account-lib/package.json
modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
modules/account-lib/src/coin/baseCoin/iface.ts
modules/account-lib/src/coin/eth2/keyPair.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/resources/eth2/eth2.ts
modules/account-lib/test/unit/coin/eth2/keyPair.ts
modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/eth2.ts
modules/core/test/v2/unit/coins/eth2.ts
yarn.lock

With bls-dkg lib it is possible to verify a signature of a meessage signed by 2 of the 3 key pairs
BREAKING CHANGE: BlsKeyPair is not just a default prv and pub object, instead it has an array of
secretShares and a publicShare which should be merged with the other BLS key pairs to get the common
public key and the private key of each keypair.
BG-35989

feat(account-lib): migrate BLS key pair from @bitgo/bls to @bitgo/bls-dkg lib

---

modules/express/src/clientRoutes.ts
modules/express/test/integration/bitgoExpress.ts

The proxy request routes were not correctly parsing the incoming POST
body and therefore would always drop POST bodies when forwarding
requests to the proxy target.
Add the `parseBody` middleware to the proxy handler route, and add a
test for this case to prevent regression.
Ticket: BG-40647

fix(express): pass POST body for proxy requests

---

modules/core/src/v2/coins/eth2.ts
modules/core/test/v2/unit/coins/eth2.ts

ETH2 BLS shares needs to be aggregated in client side in order to post the new user and backup keys
to platform.
BG-36122

feat(core): add method to aggregate ETH2 BLS shares

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/dot.ts
modules/core/test/v2/unit/coins/dot.ts
modules/core/test/v2/unit/wallet.ts
modules/core/test/v2/unit/wallets.ts

When DOT wallet object is used in core for address creation, use hardened key derivation to generate an address to POST to WP for receive addresses. 
Follows workflow implemented by Solana
JIRA ticket: https://bitgoinc.atlassian.net/browse/STLX-13001

chore(core): add deriveKeypair method to DOT

---

modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/keychains.ts
modules/core/test/v2/unit/internal/tssUtils.ts

backup keychain should output the unencrypted prv share.
this is needed since we do not support KRS w/ TSS yet.
**Before**
```
"backupKeychain": {
"id": "6202d633335cd700089ee54475f4a5f5",
"source": "backup",
"type": "tss",
"addressDerivationKeypair": {},
"commonPub": "45qD39LXNrG8LihJBwRHZD9Dpgxjj4p4fLa142cbbjKN"
},
```
**After**
```
"backupKeychain": {
"id": "6203e72b7c3669000786ad2c98f82ba0",
"source": "backup",
"type": "tss",
"addressDerivationKeypair": {},
"commonPub": "GR69h5Q9Egs7P1CHHdPdE9Xsmo7cbeWghTNocFYX5WAg",
"prv": "{\"i\":\"2\",\"y\":\"e50b10f67243042f16a2842bd307b161d2a25f47f333887dab096735ff383d25\",\"x\":\"f0934db45e7bf984b93d6b7477dbe91f64f00eed1b05bb6ecc8a0883c384940b\",\"prefix\":\"9ab729fbcb16f554522b263435d625ebc6719c881845b279b54138b3a120e306\"}", …
```

fix(core): tss backup keychain output prv

---

modules/express/src/clientRoutes.ts
modules/express/src/errors.ts
modules/express/src/expressApp.ts
modules/express/test/unit/bitgoExpress.ts
modules/express/test/unit/clientRoutes/externalSign.ts

- Add signing functionality for v2 wallet in `handleV2Sign`
- Check config arguments to prevent a user from running as a normal BG Express instance and an external signer instance at the same time
- Check the `signerFileSystemPath` argument on startup to make sure it contains a JSON file with a "prv" field
- Only allow external signer mode to run in test mode

feat: add external signing functionality for v2 wallet

---

modules/express/src/clientRoutes.ts
modules/express/src/expressApp.ts
modules/express/test/unit/bitgoExpress.ts
modules/express/test/unit/clientRoutes/externalSign.ts

Previously the external signer would produce signatures using the single private key provided in the json file (specified by the config arg `signerFileSystemPath`). Now, it'll find the appropriate private key corresponding to the `walletId` for the transaction being signed and use that private key. 
Note: Only the last commit corresponds to this PR. The previous commits are from #1944 waiting to be merged

feat: allow external signer to sign for multiple wallet ids

---

modules/utxo-bin/src/commands.ts
modules/utxo-bin/src/parse.ts

The command now works with odd transactions
```
$ utxo-bin parse -n testnet --txid \
2d0a64a14faa9dc707dc84647a4e0dd1d4f31753e8a85574128bc8110e312e10
fetching txHex via blockapi...
transaction: 2d0a64a14faa9dc707dc84647a4e0dd1d4f31753e8a85574128bc8110e312e10
├── parsedAs: bitcoin testnet
├── version: 2
├── hasWitnesses: true
├── status: unknown
├── vsize: 900105vbytes (3600417wu)
├─┬ inputs: 1
│ └─┬ 0: e162a29a77f0b12adf70051a1135c48c691f44f0371f635b9f6a435dcba6ebb9:0
│   └── sigScript: unknown
└─┬ outputs: 100000 sum=0.03034297
└── (omitted)
```
```
$ utxo-bin parse -n bitcoin --txid \
905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a
fetching txHex via blockapi...
transaction: 905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530
├── parsedAs: bitcoin mainnet
├── version: …
```

feat(utxo-bin): add support for odd transactions

---

modules/account-lib/test/unit/coin/dot/transaction.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/addressInitializationBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/batchTransactionBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/stakingBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unnominateBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unstakeBuilder.ts

Given that the SDK tests are run in parallel, all tests share the same memory resource. In dot tests, the metadata rpc variable has very heavy usage of memory resources given its size, but we seem to duplicate it too much in the unit tests in dot.
In this PR, all unnecessary usage that involves the metadata rpc is refactored through:
* Only use the required variables through deconstructing objects instead of copying the whole
* Making the config variable ephemeral so that this huge variable is eligible for garbage collection
Comparing to:
* In the previous tests, all duplicated metadata was persisted at the top level in the test suites for easy use of its value.
Ticket: BG-43065

chore(account-lib): troubleshoot dot test OOM

---

modules/account-lib/src/coin/algo/keyRegistrationBuilder.ts
modules/account-lib/src/coin/algo/transaction.ts
modules/account-lib/test/unit/coin/algo/transactionBuilder/keyRegistrationBuilder.ts
yarn.lock

add support for offline key registration transactions on accountLib.
This transaction is pretty similar to non-participation keyreg, but it doesn't need "keyregTo" and "nonParticipation" params.
[STLX-13389](https://bitgoinc.atlassian.net/browse/STLX-13389)

feat(account-lib): add support for offline keyreg txn

---

modules/core/src/v2/wallet.ts

When SDK-core is used to create multiple receive addresses (call createAddress on wallet and pass in param count > 2), using `_.times` to loop `count` # of times led to making count # of async calls which means that the requests were getting handled by WP in an order different from the index on the loop. This behavior break derived address creation because WP checks the index used to create the address against the next available index on the wallet. If the incoming index is not 1 greater than the index on the wallet, WP throws. 
WP index verification: https://github.com/BitGo/bitgo-microservices/blob/58318068c355baee01345e84819d3db4cef1c289/packages/wallet-platform/app/controllers/api/v2/coins/base/utils.ts#L119
This PR changes createAddress from using an async loop to using a sync loop …

fix(core): change loop to POST /address

---

modules/express/README.md
modules/express/package.json
modules/express/src/clientRoutes.ts
modules/express/src/retryPromise.ts
modules/express/test/integration/externalSigner.ts
yarn.lock

if the request to the external signer fails with `ECONNREFUSED`, retry the
request three times with exponentially increasing timeout up to 3 times.
Ticket: BG-43083

feat: add retry logic to external signer

---

modules/core/src/v2/wallets.ts

Wallet Platform supports a new multisig type param when adding a wallet
BG-36122

fix(core): add multisig type param on add wallet

---

modules/core/src/v2/coins/dot.ts

DOT TSS is not ready to be integrated. Changing dot to not support TSS so we don't see errors when creating a wallet.

remove tss support for dot tss

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/coins/abstractEthLikeCoin.ts
modules/core/src/v2/coins/abstractUtxoCoin.ts
modules/core/src/v2/coins/algo.ts
modules/core/src/v2/coins/cspr.ts
modules/core/src/v2/coins/dot.ts
modules/core/src/v2/coins/eos.ts
modules/core/src/v2/coins/eth.ts
modules/core/src/v2/coins/eth2.ts
modules/core/src/v2/coins/hbar.ts
modules/core/src/v2/coins/near.ts
modules/core/src/v2/coins/ofc.ts
modules/core/src/v2/coins/sol.ts
modules/core/src/v2/coins/stx.ts
modules/core/src/v2/coins/susd.ts
modules/core/src/v2/coins/trx.ts
modules/core/src/v2/coins/xlm.ts
modules/core/src/v2/coins/xrp.ts
modules/core/src/v2/coins/xtz.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/coins/abstractEthCoin.ts
modules/core/test/v2/unit/coins/sol.ts
modules/core/test/v2/unit/coins/stx.ts
modules/core/test/v2/unit/wallet.ts

Rename to `isWalletAddress()` and throw exceptions where it is not
implemented correctly.
Issue: BG-43225

fix(core): rename verifyAddress and remove invalid implementations

---

modules/core/src/v2/environments.ts
modules/core/test/lib/test_bitgo.ts
modules/core/test/v2/lib/recovery-nocks.ts

The recover function calls etherscan internally to get some details regarding the address but seems like it defaults to kovan even if we initialise the sdk with goerli. Since kovan is already retiring, reverting the default to goerli instead of kovan.
Ticket: [BG-42778](https://bitgoinc.atlassian.net/browse/BG-42778)

fix(core): change etherscan url to default goerli

---

modules/core/src/v2/baseCoin.ts
modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/internal/tssUtils.ts
modules/core/test/v2/unit/wallet.ts

adds functionality to build, sign, and send transactions from a
tss wallets. previously, sendMany would handle this, but we want to be
able to build, sign, and send independently.
Ticket: STLX-13780
this change is needed to support UI clients, where the build, sign, and send operations are performed separately. this is typically:
1. User builds transaction
2. Client displays details for user to review
3. User inputs password
4. Client signs and sends transaction
sample script that mimics the above:
```
async function prebuildTransaction() {
const wallet = await bitgo.coin('tsol').wallets().get({ id: walletId });
console.log(wallet);
const builtTx = await wallet.prebuildTransaction({
recipients: [{
address: '6DadkZcx9JZgeQUDbHh12cmqCpaqehmVxv6sGy49jrah',
amount: '1000'
}],
type: …
```

chore(core): improve support for tss wallets

---

modules/core/src/v2/internal/blsUtils.ts
modules/core/src/v2/internal/mpcUtils.ts
modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/keychains.ts
modules/core/src/v2/wallets.ts
modules/core/test/v2/unit/internal/blsUtils.ts
modules/core/test/v2/unit/internal/tssUtils.ts

Create Keychains with originalPasscodeEncryptionCode and enterprise
populated if client provides as input.
`originalPasscodeEncryptionCode` is sent when creating the User key.
`enterprise` is sent when creating  the BitGo Key and Wallet
Ticket: STLX-14231

fix(core): support password reset and enterprise with MPC

---

modules/express/EXTERNAL_SIGNER.md
modules/express/README.md
modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/externalSign.ts

- When running in external signer mode, express will expect the private
key json file to be in the encrypted format (same as on the keycard but
with escape characters).
- Express expects the wallet passphrase to be set in the environment
with the name `WALLET_<walletId>_PASSPHRASE`
- Update documentation and move to new file EXTERNAL_SIGNER.md

feat: external signer to read encrypted privkeys

---

modules/express/src/expressApp.ts
modules/express/test/unit/bitgoExpress.ts

remove the restriction that allowed the external signer to be used only in a test env
Note: This should only be merged after the following PRs have been merged
- #2069
- #2080
- #2082

feat: enable external signer mode for production

---

modules/account-lib/src/coin/dot/keyPair.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/src/coin/near/utils.ts
modules/account-lib/src/utils/crypto.ts
modules/account-lib/test/unit/coin/dot/utils.ts
yarn.lock

This PR includes changes to support validating base58 public keys. During TSS wallet creation, base58 keys are generated and should be valid. Dot needs to validate hex keys therefore there is check added to determine whether a key is in base58 format and decodes to length of 32. If so, it should convert that to hex before validating. 
Closes TICKET: STLX-14315

feat: support validation of  base58 dot public keys

---

modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

This PR propagates the `keychain.commonPub`  received from the BitGo backend to the create wallet share endpoint to support TSS wallet sharing.

feat(core): support TSS wallet sharing

---

modules/core/src/v2/coins/algo.ts
modules/core/test/v2/unit/coins/algo.ts

support creating algo wallets when client provides coldDerivationSeed
Ticket: BG-43801
Note: This is nearly identical to XLM's solution. We should generalize the solution for all ed25519 keys when we have the bandwidth: https://bitgoinc.atlassian.net/browse/BG-43801
verified wallet creation working as expected:
```
async function createTalgoWallet() {
const newWallet = await bitgo.coin('talgo').wallets().generateWallet({
label: 'joey test algo 3/9',
userKey: 'UBI2KNGT742KGIPHMZDJHHSADIT56HRDPVOOCCRYIETD4BAJLCBMQNSCNE',
coldDerivationSeed: 'this is my seed',
backupXpub: '7M5KGULVPK3VKIMANQMEP3EN2EL5DMN4WGQJ3SM7ELYU4IEZ52UDDTOORA',
});
console.log(JSON.stringify(newWallet, undefined, 2));
}
```

feat(core): support creating algo wallets with seed

---

modules/core/src/v2/internal/tssUtils.ts
modules/core/src/v2/wallet.ts
modules/core/test/v2/unit/wallet.ts

surface feeInfo in PrebuildTransactionResult when building transactions
with Tx Requests.
Ticket: STLX-14462

fix(core): expose feeInfo when building txns from tx requests

---

modules/core/example/ts/send-hop-transaction.ts
modules/core/src/v2/coins/avaxc.ts
modules/core/src/v2/coins/avaxcToken.ts
modules/core/test/v2/unit/coins/avaxc.ts

Enable hop transaction for AVAXC
When it comes to the choice of design, the options were
1. modify ethlike to add hop + 1559
2. extend from eth by typescriptifying
3. copy paste and keep redundant code to decouple development and move fast
we picked option 3 due to time and complexity reason. And also to avoid modifying and breaking another eth-like coin.

Avax hop transaction

---

.github/workflows/test_package_updates.yml

On package updates, the current CI won't prevent breaking changes with running all unit tests but instead relies on running unit test diff. This is what we encountered in the Solana and Dot tests updates, where it broke some tests. With package updates, most likely there will not be new test cases introduced and it may risk breaking the code. 
- A new workflow that runs all unit tests if there are changes involved in any of the `package.json`
An additional commit was introduced to purposedly trigger the workflow in the PR, and will be borked before merging
I was going to add `integration` tests into the run options too but seems like they are mostly obsolete.
There isn't really a quick native way to run jobs on file changes without relying on 3rd party actions. Reference: …

feat(root): add unit-test-all to ci

---

modules/utxo-lib/src/bitgo/signature.ts
modules/utxo-lib/test/bitgo/signature.ts
modules/utxo-lib/test/bitgo/signatureModify.ts

Per consensus rules, signatures must have a lower-S value
See https://github.com/bitcoin/bips/blob/master/bip-0146.mediawiki for 
details.
This change replaces the indirect call to `ecc.verify()` inside
`ECPair.verify()`[^1] with a direct call that sets the last argument
`strict` to `true`.
Note that this strict (low-S) verification is the default in the
`noble-secp256k1` library[^2], which is the prospective secp256k1 library going
forward.
Issue: BG-44787
----
adba1c287
test(utxo-lib): add test  for high-S ECDSA signatures
Add `verifySignature()` test where we take an existing signature and tweak
the signature `S` value to `n - S` (high-S).
The resulting signature is valid according to old consensus rules, but 
invalid according BIP-0146 which requires a low-S value. …

fix(utxo-lib): always verify ECDSA in strict mode

---

modules/statics/src/account.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts

Add supports for nft tokens to statics.
We add two testnet tokens: a test ERC721 and a test ERC1155 and we add a ERC721 token in mainnet: Crypto Covens which will be using for testing.
https://opensea.io/collection/cryptocoven
ticket: BG-44467

feat: add nft tokens to statics

---

modules/core/src/v2/internal/tssUtils.ts
modules/core/test/v2/unit/internal/tssUtils.ts

In preparation for TSS HD Wallets, we now need an optional `path` parameter when signing transactions with signature shares.

feat: update params to post /signatureshares

---

modules/account-lib/src/coin/sol/ataInitializationBuilder.ts
modules/account-lib/src/coin/sol/tokenTransferBuilder.ts
modules/account-lib/src/coin/sol/utils.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/ataInitBuilder.ts
modules/account-lib/test/unit/coin/sol/utils.ts

STLX-14417
Add `getAssociatedTokenAccountAddress` to be used in wp, this avoids adding a dependency on spl-token in wp. 
Also refactor token builders to use new util methods

feat(account-lib): add solana util functions for use in wp, refactor

---

modules/express/README.md

Was exploring SDK and Express, and found the current README link we have for express API is broken. 
I'm guessing this is the new one? - https://api.bitgo.com/docs/#tag/Express

chore: update express API link in readme

---

modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts

The api docs expect keyname of symbol rather than asset
in the amount object. amount: {value: string; symbol: string}
TICKET: STLX-15129

fix: change keyname from asset to symbol in amount

---

modules/account-lib/src/mpc/curves.ts
modules/account-lib/src/mpc/hdTree.ts
modules/account-lib/src/mpc/shamir.ts
modules/account-lib/src/mpc/tss.ts
modules/account-lib/src/mpc/util.ts
modules/account-lib/test/tsconfig.json
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/near/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/transactionBuilder.ts
modules/account-lib/test/unit/mpc/tss.ts
modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts

General quality of life improvements to MPC module.
Changes MPC module's internal format from Buffer to BigInt.
Adds deterministic coefficient generation for Shamir splitting.
Adds chaincode generation and combination.
Adds HDTree interface and Ed25519BIP32 implementation.
Adds keyDerive method to Ed25519 TSS implementation.
TSS signing key combination moved from `keyCombine` to `sign`.
TSS `sign` method now requires Y shares of non-signers to facilitate key combination.
Note that integration work between core and account-lib needs some work (see TODO).

BG-44315: Support MPC HD keys

---

modules/statics/src/networks.ts

Ticket: BG-0000
For GTETH Coin the batcher contract address in BitGoJS and wallet-platform are different.
So changed in BitGoJS to use the one in wallet-platform

refactor(statics): change batcher addr for gteth

---

modules/account-lib/test/resources/dot/index.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/addressInitializationBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/batchTransactionBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/claimBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/stakingBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transactionBuilderFactory.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unnominateBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/unstakeBuilder.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/withdrawUnstakedBuilder.ts

Updates dot tss tests to use `addSignature` instead of `.sign` since we're now using TSS to add a signature to a dot transaction.
TICKET: BG-45942

chore: update dot tests to use tss way of signing

---

modules/bitgo/src/v2/coins/avaxcToken.ts
modules/bitgo/test/v2/unit/coins/avaxc.ts
modules/bitgo/test/v2/unit/coins/avaxcToken.ts

Becasuse missing this method, it uses AVAXC verifyCoin
Ticket: BG-0

fix(core): fix avaxctoken cannot withdraw

---

modules/bitgo/src/v2/wallet.ts

Nonce is added on frontent with [STLX-14845](https://bitgoinc.atlassian.net/browse/STLX-14845)
This whitelisted is blocking that ticket. 
STLX-15355

feat(bitgo): Add nonce in prebuild whitelisted params

---

modules/account-lib/test/unit/mpc/tss.ts
modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/src/v2/pendingApproval.ts
modules/bitgo/src/v2/wallet.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts
modules/bitgo/test/v2/unit/pendingApproval.ts
modules/bitgo/test/v2/unit/wallet.ts

Update TSS key creation and signing to support hd
Also refactors some of the input params to be objects.
Primary change is to support signing using the updated `UserSigningMaterial` instead of the user's `PShare`:
```
const userSigningMaterial: UserSigningMaterial = JSON.parse(prv);
const signingKey = MPC.keyDerive(
userSigningMaterial.uShare,
[userSigningMaterial.bitgoYShare, userSigningMaterial.backupYShare],
path
);
const signerShare =
signingKey.yShares[ShareKeyPosition.BITGO].u + signingKey.yShares[ShareKeyPosition.BITGO].chaincode;
...
```
Ticket: STLX-14661, STLX-14661

feat: update tss key creation and signing to support hd

---

modules/bitgo/src/v2/coins/eth2.ts
modules/bitgo/test/lib/test_bitgo.ts
modules/bitgo/test/v2/integration/coins/eth2.ts

Integration test for ETH2 BLS keychains signing methods. We should be able to sign a message and
verify its signature.
BG-36125

test(bitgo): integration test for ETH2 BLS keychains message signing

---

modules/bitgo/src/v2/coins/utxo/recovery/crossChainRecovery.ts

Currently, bitgo throws a 400 error for v1 wallet Ids that are not found in the `api/v2/:coin/wallets/:walletId` route, causing cross chain recovery for v1 wallets to fail. This commit expands the range of error responses to prevent similar errors occurring in the future.
A test for this will be created in another ticket (BG-46179)
Ticket: BG-44440

fix: v1 wallet cross chain recovery

---

modules/bitgo/src/v2/baseCoin.ts
modules/bitgo/src/v2/coins/dot.ts
modules/bitgo/src/v2/coins/sol.ts
modules/bitgo/src/v2/internal/blsUtils.ts
modules/bitgo/src/v2/keychains.ts
modules/bitgo/src/v2/wallet.ts
modules/bitgo/src/v2/wallets.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/bitgo/test/v2/unit/wallets.ts

With TSS HD, we can perform unhardened derivation. No need to use single
sig addresses and addressDerivationKeypair.
Ticket: STLX-14663
Notable changes:
- no longer generating `addressDerivationKeypair` and storing in keychain
- `addressDerivationKeypair` not used for signing
- Address creation / derivation is all server side, so no need for inputting password when creating receive addresses

chore: remove single sig receive addresses

---

modules/account-lib/package.json
modules/express/package-lock.json
modules/express/package.json
modules/express/src/config.ts
modules/express/test/unit/config.ts
yarn.lock

Enable secure urls for all environments unless explicitly disabled. This follows the --disablessl flag | BItGO_DISABLE_SSL environment key rule. Possibly a breaking change to existing deployments.
Polkadot required a version upgrade to pass tests.
BG-43342

fix: force secure urls unless disabled

---

modules/account-lib/test/unit/coin/avaxc/transferBuilder.ts
modules/bitgo/src/v2/coinFactory.ts
modules/bitgo/src/v2/coins/avaxcToken.ts
modules/bitgo/test/v2/unit/coins/avaxcToken.ts
modules/statics/src/coins.ts

we are deprececating all avaxc tokens that do not have a faucet and thus
cannot be tested

chore(avaxc): depcrecate some avaxc tokens

---

modules/bitgo/src/v2/coins/dot.ts
modules/bitgo/src/v2/coins/tdot.ts
modules/bitgo/test/v2/unit/coins/dot.ts

The base factor defaults to 1e12 which is only valid for
Westend transaction since 12 decimal places is used vs 10
decimal places in mainnet.
TICKET: BG-0000

fix(statics): update base factor for dot and tdot

---

modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/src/v2/wallet.ts

If nonce is passed as part of a transfer request then send that nonce value to wallet-platform to build the transaction accordingly. Tested in testnet-05 for dot successfully.

fix: whitelist nonce as an intent param

---

modules/bitgo/src/v2/baseCoin.ts
modules/bitgo/src/v2/coins/sol.ts
modules/bitgo/src/v2/wallet.ts
modules/bitgo/test/v2/unit/coins/sol.ts
modules/bitgo/test/v2/unit/wallets.ts

rebuild solana hot wallet transactions right before signing to reduce
chances of tx becoming expired.
Verified manually:
```
async function sendMany() {
const wallet = await bitgo.coin('sol').wallets().get({ id: '62507b4ede430a000806cd722da9ebe3' });
const sent = await wallet.sendMany({
recipients: [{
address: 'GQQpr6bV4Vbro7iKDtTdCuPFzUetFa3U68RkYED43Z1o',
amount: '10000',
}],
type: 'transfer',
walletPassphrase: PASSPHRASE,
});
console.log(JSON.stringify(sent, undefined, 2));
}
```

chore: improve robustness of Sol transactions

---

CODEOWNERS
modules/account-lib/package.json
modules/bitgo/test/lib/test_bitgo.ts
modules/bls-dkg/package.json
modules/express/package.json
modules/express/test/lib/test_bitgo.ts
modules/sjcl/package.json
modules/statics/CODEOWNERS
modules/statics/package.json
modules/unspents/package.json

Update support and codeowner references for SDK code ownership and contact points.
Looks like @BitGo/sdk-team needs to be fixed for assigned repositories. Same with eth-team? @BitGo/git-admins 
BG-000000

chore: update support and owner references

---

modules/bitgo/src/v2/coins/utxo/recovery/crossChainRecovery.ts
modules/bitgo/test/v2/unit/coins/utxo/recovery/crossChainRecovery.ts

A bad fix was introduced in #2180, this is now the correct version. 
When `getWallet` is called, if `coin.wallets().get({ id: walletId })` returns a 4xx error, the correct behavior is to search for the wallet using the v1 endpoint.
Originally the condition was just `if (e.status !== 404) {` so that if the wallet wasn't found, it would search v1 wallets. The problem was the v1 endpoint was returning a 400 error. It's not necessarily incorrect because if v1 wallets are a different format to v2 wallets, that would be an appropriate response. So that's why the range of errors was expanded to any 4xx error
Ticket: BG-44440

fix: v1 get wallet

---

modules/bitgo/src/v2/coins/algoToken.ts
modules/bitgo/test/v2/unit/coins/algoToken.ts

Do not merge  ####
Fix decimalPlaces for algorand tokens in order to get the right maxSpendable balance
The AlgoToken class extends from Algo class. And the getBaseFactor method was declarated only in Algo class returning the value from its own decimalPlaces. Now getBaseFactor method is overwriting on AlgoToken class taking the right decimalPlaces.
STLX-15317

fix(bitgo): fix non native decimalPlaces

---

modules/account-lib/src/mpc/tss.ts
modules/account-lib/test/unit/mpc/tss.ts

This will be used by OVC, which generates some random entropy used
during key creation
Ticket: BG-43873

feat(account-lib): support creating TSS keyshares with seed

---

modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts

Add api versioning for tx requests to differentiate light v full

chore: add api versioning to tx requests

---

modules/bitgo/src/v2/coins/eos.ts
modules/bitgo/test/v2/unit/coins/eos.ts

Hedaers are set from the server and not the client, therfore removing
this check which has caused client issues due to time rounding.
TICKET: BG-46365

chore: remove header check from eos verifyTransaction

---

modules/bitgo/src/v2/internal/opengpgUtils.ts
modules/bitgo/test/v2/unit/internal/opengpgUtils.ts

add util functions to
- encrypt and sign
- decrypt and verify
this will be used for TSS key creation
Ticket: BG-45374

feat: support opengpg signatures

---

modules/account-lib/src/mpc/curves.ts
modules/account-lib/src/mpc/hdTree.ts
modules/account-lib/src/mpc/tss.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/near/transactionBuilder/transferBuilder.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/transactionBuilder.ts
modules/account-lib/test/unit/mpc/tss.ts
modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts

- deriveUnhardened returns full keychain; clients will need to take the
first 32 bytes if they wish to use it as a public key
- initialize functions will also return a newly instantiated object

chore: refactor TSS lib

---

modules/bitgo/src/v2/internal/blsUtils.ts
modules/bitgo/src/v2/internal/mpcUtils.ts
modules/bitgo/src/v2/internal/tssUtils.ts
modules/bitgo/src/v2/keychains.ts
modules/bitgo/test/v2/unit/internal/blsUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts

type was originally used to differentiate different types of backup keys
(i.e. using an external key provider or holding on to your own).
this was overloaded with the introduction of TSS and BLS.
this change refactors to use keyType to determine multisig type (tss,
bls, or independent/onchain).
Ticket: BG-43890

chore: use keyType instead of type for tss + bls keys

---

modules/account-lib/src/mpc/curves/baseCurve.ts
modules/account-lib/src/mpc/curves/ed25519.ts
modules/account-lib/src/mpc/curves/index.ts

This commit refactors the mpc folder to easily add more curves by defining base interfaces and dedicated files specific to each implementation rather than having everything defined in a single file
TICKET: BG-47401

refactor(account-lib): refactor mpc folder to easily add more curves

---

modules/bitgo/src/transactionBuilder.ts

We have seen an issue for at least one production v1 wallet where an
input is unable to be signed for due to using an incorrect derivation
path for the user keychain. We believe this wallet has a non-standard
derivation scheme may have been broken in a change to the v1
transaction builder.
In the event of a signing failure, try to use a fallback path derivation
scheme which we believe will work for the wallet in question. If the
fallback path derivation fails, log the error which caused the fallback
derivation signing to fail, but throw the original error to maintain
previous error behavior.
Ticket: BG-46497

fix(bitgo): attempt to sign using fallback derivation for v1 wallet

---

modules/sdk-api/src/bitgoAPI.ts

added sdk version to constants call in order to tell to wallet platform if UI needs the new format token names or the old one for Algorand.
stlx-14556

feat(chore): added sdk version to constants call

---

modules/bitgo/src/v2/coins/utxo/recovery/crossChainRecovery.ts
modules/bitgo/test/v2/unit/coins/utxo/recovery/crossChainRecovery.ts

`bitgo.wallets().get()` mistakenly had a `this.` in front of it, causing the function to be `undefined`.  
This type of bug isn't caught automatically by typescript (surprisingly), but we can add `no-invalid-this` to the lint rules to prevent it. A ticket for that has been created: https://bitgoinc.atlassian.net/browse/BG-48397
Ticket: BG-48417

fix: v1 getWallet call

---

modules/account-lib/package.json
modules/account-lib/src/mpc/curves/baseCurve.ts
modules/account-lib/src/mpc/curves/ed25519.ts
modules/account-lib/src/mpc/curves/index.ts
modules/account-lib/src/mpc/curves/secp256k1.ts
modules/account-lib/src/mpc/tss.ts
modules/account-lib/src/mpc/util.ts
modules/account-lib/test/unit/mpc/curves/secp256k1.ts
modules/account-lib/test/unit/mpc/tss.ts

this change adds support for secp256k1 curve for MPC / TSS and also changes verify function in ed25519 to return boolean
TICKET:BG-47402

feat(account-lib): add support for secp256k1 curve TSS

---

modules/account-lib/src/mpc/tss/eddsa/eddsa.ts
modules/account-lib/src/mpc/tss/eddsa/index.ts
modules/account-lib/src/mpc/tss/eddsa/types.ts
modules/account-lib/src/mpc/tss/index.ts
modules/account-lib/test/unit/mpc/tss/eddsa/eddsa.ts

Since different signature schemes have its own specific functions without having necessary similarity in function parameters and intermediate steps needed, it's not feasible to properly define a base class / interface. But that said, the naming convention may be similar especially when it comes to shares which may have different parameters for different signature schemes causing name collisions. 
This PR proposes a new architecture to define signature schemes in its on sub modules there by abstracting its own implementation avoiding potential collisions.
```
├── eddsa
│   ├── eddsa.ts
│   ├── index.ts
│   └── types.ts
├── ecdsa
│   ├── ecdsa.ts
│   ├── index.ts
│   └── types.ts
└── index.ts
```
All implemenation specific to a signature scheme can be accessed from importing like as below …

refactor(account-lib): refactor tss folder to easily add new signature schemes

---

modules/bitgo/src/wallet.ts

Add missing 'Bluebird.resolve()' to get address call
Ticket: BG-44440

fix(bitgo): fix v1 wallet get address

---

modules/account-lib/src/coin/near/utils.ts
modules/account-lib/test/resources/near/index.ts
modules/account-lib/test/unit/coin/near/utils.ts

fix isValidAccountId method
What happened?
If an empty string is sent to isValidAccountId it returns true.
Requeriments:
Should not pass for empty strings ' '.
STLX-16458

feat(account-lib): fix is valid account id

---

modules/bitgo/example/js/cross-chain-recovery.js

I was debugging a cross-chain-recovery issue using the sdk so it wasn't much to turn it into this example.
Ticket: BG-0000

chore(sdk): add example cross-chain-recovery.js

---

modules/bitgo/src/v2/coins/avaxp.ts
modules/bitgo/src/v2/coins/tavaxp.ts

this change fixes build issues caused by avax files by correctly importing basecoin from sdk core
TICKET: BG-49438

fix(account-lib): fix sdk avax build issues

---

modules/bitgo/src/bitgo.ts
modules/sdk-api/src/bitgoAPI.ts
modules/web-demo/src/components/BitGoAPI/index.tsx

- BitGoAPI uses distinct version & userAgent string
- BitGoAPI no longer abstract
- Bitgo uses own version & userAgent string
Ticket: BG-49713

fix(sdk-api): api uses own version

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Adds TSS as a coin feature.
Updates Sol, Dot, and Near to include TSS as a coin feature.
Motivation is to provide a generic solution to determine which coins
use TSS.

feat(statics): add TSS as a coin feature

---

modules/bitgo/src/v2/coins/polygon.ts
modules/bitgo/src/v2/coins/tpolygon.ts
modules/bitgo/test/v2/unit/coins/polygon.ts

This commit adds an implementation of explainTransaction for Polygon
Ticket: [BG-41729](https://bitgoinc.atlassian.net/browse/BG-41729)

feat(bitgo): add explain tx polygon

---

modules/express/bin/bitgo-express
yarn.lock

- Prevented express from crashing on unhandled promise rejections.
- This fix should be removed once BG-49996 is implemented.
Ticket: BG-48910
Starting from version 15, node process would terminate if there’s any unhandled promised rejection without the unhandledRejection hook. More info could be found [here](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#throw-on-unhandled-rejections---33021) and [here](https://nodejs.org/docs/latest-v16.x/api/cli.html#--unhandled-rejectionsmode).

chore(bitgo-express): add unhandledRejection hook to bitgo express

---

modules/bitgo/test/v2/unit/coins/sol.ts
modules/bitgo/test/v2/unit/internal/tssUtils.ts
modules/bitgo/test/v2/unit/pendingApproval.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/iTssUtils.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
yarn.lock

TSS custodial wallets will use TxRequest full.
This change updates the TxRequest interface to match 'full' and updates
impl to fix building transactions using full.
Ticket: BG-49655

feat: update TxRequest schema for full version

---

modules/bitgo/test/v2/unit/accountConsolidations.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

[stlx-13299](https://bitgoinc.atlassian.net/browse/STLX-13299)
Handle new consolidation/build endpoint 204 - no content - response
Since we have this PR: https://github.com/BitGo/bitgo-microservices/pull/16613 on [this line](https://github.com/BitGo/bitgo-microservices/pull/16613/files#:~:text=if%20(!builtConsolidationTransactions.length,ctx%2C%20wallet%2C%20intent)%3B) on file `packages/wallet-platform/app/controllers/api/v2/transactions/buildConsolidation.ts`
The endpoint 'consolidation/build' will response a 204 HTTP no content if you try to consolidate a root address with addressess without balance to consolidate. So there is no error but there is nothing to do. 
This PR hanlde this situation. Without this changes the file `modules/bitgo/src/v2/wallet.ts` in line 2143 try to do a _for …

feat(bitgo): handle new consolidation/build endpoint 204 response

---

modules/bitgo/test/v2/unit/tss/eddsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/index.ts
modules/sdk-core/src/bitgo/tss/eddsa/types.ts
modules/sdk-core/src/bitgo/tss/index.ts
modules/sdk-core/src/bitgo/tss/types.ts
modules/sdk-core/src/bitgo/utils/index.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/index.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/index.ts

This pr is moving eddsa into a sub folder of tss so we can ecdsa to tss. 
Ticket: BG-49287

refactor(sdk-core): tss refactor moving eddsa into a sub folder

---

modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

HSM is now expecting secp2561k key pairs instead of the default ed25519.
Ticket: BG-50200
Verified by creating a wallet in test:
```
async function createTssWallet() {
const newWallet = await bitgo.coin('tsol').wallets().generateWallet({
label: 'tss sol 605',
passphrase: 'Ghghjkg!455544llll',
multisigType: 'tss',
passcodeEncryptionCode: 'passcodeEncryptionCode',
// enterprise: '60c7f599fdbda8000657d147f5c08f6e'
});
console.log(JSON.stringify(newWallet, undefined, 2));
}
```

fix: fix tss wallet creation

---

commitlint.config.js
modules/bitgo/src/v2/coins/eth.ts
modules/bitgo/src/v2/coins/near.ts
modules/bitgo/test/v2/fixtures/staking/stakingWallet.ts
modules/bitgo/test/v2/unit/staking/stakingWalletCommon.ts
modules/bitgo/test/v2/unit/staking/stakingWalletNonTSS.ts
modules/bitgo/test/v2/unit/staking/stakingWalletTSS.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/index.ts
modules/sdk-core/src/bitgo/staking/iStakingWallet.ts
modules/sdk-core/src/bitgo/staking/index.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

- Adds staking functionality via `IStakingWallet`
> - Currently only supports NEAR and ETH
- Added `supportsStaking` method to `IBaseCoin`
- Added `toStakingWallet` method to `IWallet`
- IStakingWallet methods
> - `stakingWallet.stake`
> - `stakingWallet.unstake`
> - `stakingWallet.getTransactionsReadyToSign`
> - `stakingWallet.build`
> - `stakingWallet.sign`
> - `stakingWallet.send`
> - `stakingWallet.signSendAndBuild` 
Ticket: BOS-360

feat(sdk-core): add staking SDK functionality

---

modules/bls-dkg/.mocharc.js

A bls-dkg UT is failing because of timeout. There is nothing causing it to not return successfully
or an error, seems that sometimes it takes longer than expected. BTW, it just takes as much as 300ms
to complete on local. So increase the timeout property for mocha when running UT on this package.
BG-50890

chore(blsdkg): fix bls-dkg package UT failing because of timeout

---

.github/workflows/ci.yml

CI Checks running unit test cases for both 14.x and 16.x roughly takes 8+ minutes where roughly 50%-60% time is taken for dependency installation + build (~4 minutes) which is essentially redundant if packages are not updated. This changes adds the ability to cache dependencies and install if and only if packages are updated saving roughly 2-3 mins CI build time per workflow (14.x and 16.x). Reference [here](https://github.com/actions/cache/blob/main/examples.md#node---lerna)
TICKET:  BG-00000

feat(root): improve CI workflow

---

modules/account-lib/src/coin/dot/claimBuilder.ts
modules/account-lib/src/coin/dot/keyPair.ts
modules/account-lib/src/coin/dot/stakingBuilder.ts
modules/account-lib/src/coin/dot/transaction.ts
modules/account-lib/src/coin/dot/transactionBuilder.ts
modules/account-lib/src/coin/dot/transferBuilder.ts
modules/account-lib/src/coin/dot/utils.ts
modules/account-lib/src/coin/hbar/keyPair.ts
modules/account-lib/test/unit/coin/dot/address.ts
modules/account-lib/test/unit/coin/dot/keypair.ts
modules/account-lib/test/unit/coin/dot/transactionBuilder/base.ts
modules/account-lib/test/unit/coin/dot/utils.ts
modules/bitgo/src/v2/coins/dot.ts
modules/sdk-core/src/account-lib/baseCoin/ed25519KeyPair.ts
modules/sdk-core/src/account-lib/baseCoin/enum.ts
modules/sdk-core/src/account-lib/baseCoin/index.ts

TICKET: BG-51443
The outputs/inputs of a built dot transaction were always showing the generic substrate address. This data is used within wallet-platform when whitelisting addresses. Whitelisting was failing since we were whitelisting a polkadot address (starting with `1`) but our logic used the address in the outputs which was a generic substrate address (starting with `5`). 
The changes in this PR enforce that an Address Format must be passed when calling getAddress() in the Dot Keypair class. We leverage the statics data to determine whether we're building a transaction for `dot` which uses address starting with `1` and `tdot` which uses addresses starting with `5`.
A new util method was [added](https://github.com/BitGo/BitGoJS/pull/2449/files#diff-9265d4394b8add7bea465014873d17751e57c …

fix: use correct address encoding when decoding polkadot txn

---

modules/bitgo/test/v2/unit/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts

rounded value on spendable balance.
i add this line of code because by default bigNumber use 20 decimal places 
https://mikemcl.github.io/bignumber.js/#decimal-places
and near need 24 
image of the fix
STLX-17105

fix(bitgo): rounded value on spendable balance

---

modules/account-lib/src/coin/sol/ataInitializationBuilder.ts
modules/account-lib/src/coin/sol/ataInitializationTransaction.ts
modules/account-lib/src/coin/sol/iface.ts
modules/account-lib/src/coin/sol/instructionParamsFactory.ts
modules/account-lib/test/unit/coin/sol/instructionParamsFactory.ts
modules/account-lib/test/unit/coin/sol/solInstructionFactory.ts
modules/account-lib/test/unit/coin/sol/transactionBuilder/ataInitBuilder.ts

fixes a couple of issues with solana token init transactions
- output should be in base SOL instead of token (transferring sol for
rent exemption)
- add token name to parsed output
Ticket: BG-51901

fix: sol ata init transactions

---

modules/bitgo/package.json
modules/bitgo/src/v2/coins/polygon.ts
modules/sdk-coin-avaxc/package.json
modules/sdk-coin-avaxc/src/lib/utils.ts
modules/sdk-coin-celo/package.json
modules/sdk-coin-celo/src/lib/stakingBuilder.ts
modules/sdk-coin-celo/src/lib/types.ts
modules/sdk-coin-celo/test/unit/transactionBuilder/send.ts
modules/sdk-coin-eth/package.json
modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-eth/src/lib/transferBuilder.ts
modules/sdk-coin-eth/src/lib/types.ts
modules/sdk-coin-eth/src/lib/utils.ts
modules/sdk-coin-eth/test/unit/utils.ts
modules/sdk-coin-rbtc/test/unit/transactionBuilder/send.ts
modules/sdk-coin-stx/package.json
modules/sdk-coin-stx/src/lib/utils.ts
modules/sdk-core/package.json
yarn.lock

It pulls in some old dependencies, that waste time and fail to build in our CI (and falls back to slower JS variants).
I tried to keep things minimal and as close to the previous version as possible.
Please be aware of this node.js papercut:
```
> Buffer.from('abc', 'hex').toString('hex');
'ab'
```
Ticket: BG-45514

feat(account-lib): get rid of old ethereum lib

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/curves/secp256k1.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts

This change fixes the issue while representing a compressed point. 
Interesting issue to note is that converting to a hex from a equivalent value in buffer and bigint do not give equivalent result especially in cases where you have a parity bit like '0x02' in compressed points, bigInt.toString(16) will skip the leading zero but Buffer.toString('hex') gives expected results.
TICKET: BG-52274

fix(account-lib): fix proper format for compressed hex points

---

modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/tss/index.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/index.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/index.ts

This change refactors tss utils for reusing common functionalities for different signature schemes. The major changes can be summarised as follows
1. Introduced a new `BaseTssUtils` class which each signature scheme has to inherit. This class has implementations which can be reused for different schems
2. Introduced baseType and common files which will have methods and types which can be reused for every scheme
3. Introduced scheme specific naming to avoid confusions and added relevant deprecation flags to prompt people to use scheme specific names (eg TssUtils --> EDDSAUtils)
4. All changes are backward compatible
Will be porting ECDSA to use this in a separate PR for ease of review
TICKET: BG-52194

chore(bitgo): refactor tss utils

---

modules/sdk-coin-avaxp/package.json
modules/sdk-coin-avaxp/src/lib/keyPair.ts
modules/sdk-coin-avaxp/test/unit/avaxp.ts

Derive the address buffer manual incase it crashes - this is related to the errors that happen in the OVC for avalanche.
STLX-17971

fix(sdk-coin-avaxp): ovc safe address derivation for avalanche

---

modules/statics/src/account.ts

remove `kind` parameter from FIAT factory and FiatCoin class.
Fix its value to `CoinKind.FIAT`
STLX-18052

feat(statics): remove 'kind' parameter from FIAT factory 

---

Dockerfile
scripts/update-dockerfile.ts

When pushing docker images, `LABEL` was not included. As feature
requested, release information such as created timestamps, version
and git hash will be added.
You can verify it after the image is built with `docker image inspect localhost/bitgosdk/express:latest | jq '.[0].Config'`: 
```
...
"Config": {
"User": "node",
...
"Entrypoint": [
"/sbin/tini",
"--",
"/usr/local/bin/node",
"/var/bitgo-express/bin/bitgo-express"
],
"Labels": {
"created": "Mon, 18 Jul 2022 20:03:36 GMT",
"git_hash": "973a8b01131f5958dd5b588a17dc4346b148acb3",
"io.buildah.version": "1.26.1",
"version": "9.12.0"
}
},
...
```
Ticket: BG-52008

build(express): add label metadata to image

---

modules/sdk-coin-avaxp/src/lib/delegatorTxBuilder.ts
modules/sdk-coin-avaxp/test/resources/avaxp.ts
modules/sdk-coin-avaxp/test/resources/errors.ts
modules/sdk-coin-avaxp/test/unit/lib/validateTxBuilder.ts

feat(sdk-coin-avaxp): update stake validation check

---

modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

There is a bug regarding build intent with the `enabletoken` `createAccount` intent flow when enabling tokens on Solana.
We need to add the missing tokenName to the token property of the whitelistedParams in prebuildTxWithIntent.
Previously, the bug would output this when trying to use the `enabletoken` flow on the txrequests endpoint:
```
(node:65500) UnhandledPromiseRejectionWarning: ApiResponseError: .intent.intentType should be equal to one of the allowed values, .intent should have required property 'token', .intent.intentType should be equal to one of the allowed values, .intent should have required property 'stakingRequestId', .intent should have required property 'stakingRequestId', .intent should have required property 'stakingRequestId', .intent should match some schema in anyOf …
```

fix(bitgo): add token to whitelistedParams in eddsa prebuildTxWithIntent BG-52482

---

modules/sdk-coin-eth/src/lib/utils.ts

Instead of converting `BN` to `Buffer` eagerly,
just make it another case that we can return, and let
the code outside use it directly as they see fit.

fix(bitgo): `Buffer` does not exist in browsers

---

modules/sdk-coin-avaxp/src/avaxp.ts
modules/sdk-coin-avaxp/src/lib/delegatorTxBuilder.ts
modules/sdk-coin-avaxp/src/lib/transaction.ts
modules/sdk-coin-avaxp/src/lib/transactionBuilder.ts

Don't calculate outputs in SDK since IMS has already selected unspents. Doing this can lead to utxo selection issues since the outputs are sorted during serialization. 
BG-00000

chore(avaxp): create change only

---

modules/sdk-core/src/bitgo/wallet/iWallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

walletes.add was missing a required "label" field and optional fields
All defined parameters will now be pass to request if included
BG-51948

fix: update AddWalletOptions

---

modules/bitgo/test/v2/unit/internal/opengpgUtils.ts
modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/opengpgUtils.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

u value proof will be required and validated by HSM during key creation.
Ticket: BG-52374
Verified creating hot wallets continue to work (HSM ignores the proof for now):
```
async function createHotWallet() {
const newWallet = await bitgo.coin('tsol').wallets().generateWallet({
label: 'tss sol 722',
passphrase: 'Ghghjkg!455544llll',
passcodeEncryptionCode: 'passcodeEncryptionCode',
enterprise: '60c7f599fdbda8000657d147f5c08f6e'
});
console.log(JSON.stringify(newWallet, undefined, 2));
}
```

feat: add u value proof during tss eddssa key creation

---

modules/bitgo/package.json
scripts/sdk-coin-generator/template/boilerplates/account/index.ts

Quick removal of old way of exports so that new coins aren't implemented this way.
BG-000000

chore: remove old style of export

---

modules/sdk-coin-hbar/src/lib/coinTransferBuilder.ts
modules/sdk-coin-hbar/src/lib/iface.ts
modules/sdk-coin-hbar/src/lib/transaction.ts
modules/sdk-coin-hbar/test/unit/hbar.ts
modules/sdk-coin-hbar/test/unit/transactionBuilder/transferBuilder.ts

Ticket: BG-51282
Rather than removing `to` and `amount` as in https://github.com/BitGo/BitGoJS/pull/2568, we have decided to just mark them as deprecated instead.

refactor(account-lib): deprecate hbar to and amount function

---

Dockerfile
package.json

This cuts the build time (when I try it locally) from:
```
Executed in  293.18 secs      fish           external
usr time  349.22 millis  446.00 micros  348.77 millis
sys time  174.63 millis  239.00 micros  174.39 millis
```
to:
```
Executed in  116.04 secs      fish           external
usr time  348.85 millis  688.00 micros  348.16 millis
sys time  147.11 millis    0.00 micros  147.11 millis
```
when the cache is warm (no dependency changes, just a typical source code change).

chore(bitgo): improve docker build caching

---

modules/sdk-coin-sol/test/unit/transaction.ts
modules/statics/src/coins.ts

BG-52918
BREAKING CHANGE: This breaks the provided token asset used for wp in bitgo-ms, will require to change
available sokana token asset in wp once this merged.
BG-52918

refactor(statics): update sol token asset

---

modules/sdk-coin-xtz/src/lib/index.ts

xtz: fix to enable typescript to infer types from xtz multisigUtils

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-53197
BREAKING CHANGE: We need to deal with the new enableToken intent type for solana on wp.
These are the breaking sdk-core changes from https://github.com/BitGo/BitGoJS/pull/2604

feat(sdk-core): add enable token support for sol

---

modules/bitgo/test/v2/unit/internal/blsUtils.ts
modules/sdk-coin-eth2/src/eth2.ts
modules/sdk-coin-eth2/src/lib/keyPair.ts
modules/sdk-coin-eth2/test/resources/eth2.ts
modules/sdk-coin-eth2/test/unit/eth2.ts
modules/sdk-coin-eth2/test/unit/keyPair.ts
modules/sdk-core/src/account-lib/baseCoin/blsKeyPair.ts
modules/sdk-core/src/account-lib/baseCoin/iface.ts
modules/sdk-core/src/account-lib/util/crypto.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/blsUtils.ts

As part of the BLS-DKG HS implementation, chaincodes needs to be supported at the time of keychain
creation so then it is possible to derive the subkeys when signing tx. Each participant contributes
with its own chaincode and those are added up to the common keychain.
Also fixes BG-47812. Add padding to the secret shares hex so it always
is 64. It sometimes was 62.
BG-46184

feat(bitgo): support chaincodes on BLS-DKG keychains creation

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

We recently introduced an includeTokens param to Wallet Platform.
This makes it easier to filter out wallet addresses with/without the token property.
Adding the param as an option to the SDK.
Additions:
- includeTokens param in Wallet.addresses
- Unit test to ensure non-boolean input is rejected
TICKET: BG-53596

feat(sdk-core): add includeTokens wallet.addresses parameter

---

modules/bitgo/src/index.ts
modules/bitgo/test/unit/bip32path.ts
modules/bitgo/test/unit/hdnode.ts
modules/sdk-core/src/bitgo/index.ts
modules/sdk-core/src/bitgo/legacyBitcoin.ts

- moves legacyBitcoin file to sdk-core, re-exports as bitcoin
Ticket: BG-53175

chore(sdk-core): move legacyBitcoin to sdk-core

---

modules/web-demo/package.json
modules/web-demo/src/components/BitGoAPI/bitgo-api.spec.tsx
modules/web-demo/src/components/BitGoJS/bitgojs.spec.tsx
modules/web-demo/tsconfig.json
package.json
yarn.lock

- webpack will use latest buffer explicitly instead of implicit dep
Ticket: BG-54987
- after running yarn install, go to `/modules/sdk-api` & run `yarn webpack-dev`.
- search generated file `/dist/web/main.js` for `Buffer.prototype.readBigUInt64BE` to verify the latest version is present.

chore(bitgo): set latest buffer polyfil

---

modules/express/package.json
modules/express/src/fetchEncryptedPrivKeys.ts
modules/express/test/unit/clientRoutes/externalSign.ts

Users with unencrypted keys using external signing will now be able to
identify and use wallet credentials to manual sign transactions where an
encrypted key is unavailable
BG-54633

fix: add ability to use unencrypted private key

---

modules/account-lib/test/unit/mpc/shamir.ts
modules/account-lib/test/unit/mpc/tss/eddsa/eddsa.ts
modules/sdk-core/src/account-lib/mpc/index.ts
modules/sdk-core/src/account-lib/mpc/shamir.ts
modules/sdk-core/src/account-lib/mpc/tss/eddsa/eddsa.ts

This PR contains fixes for shamir secret sharing and MPC. All changes specific to a unique ticket is a seperate commit for the ease of review. The changes in the PR are as follows.
1.  ****BG-00000** chore(account-lib): add unit tests in shamir**  
This change adds some missing unit test cases for shamir secret implementation.
2.  ****BG-52167** refactor(account-lib): preferring try catch over asserts** 
This change prefers using try catch with meaningful error messages for shamir and eddsa tss implementations over asserts. While assert successfully aborts execution, the fact that the functions throw uncaught exceptions means that function termination can lead to unpredictable program behavior. Note that uncaught exceptions also concern outright program terminations executed at the …

fix(account-lib): BG-52162 shamir sharing changes

---

package.json

Update root command to match `express` package command in scripts.
BG-000000

chore: update express build package scripts

---

.github/workflows/stale.yml

This is very unfriendly for users who report longer term issues.
We don't have so many issues that we need to close them for being stale
automatically. Let's make sure we're handling all relevant issues
reported by users and closing them with fixes instead of timeouts.
See https://github.com/BitGo/BitGoJS/issues/1631#issuecomment-1223440714
Ticket: BG-55730

chore(root): disable closing issues for being stale

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

Allow signing cold wallet token enablement transactions. For cold wallets users have to pass their private key in plain text format in the request body like `prv: "<prvKey>"`
i.e:
```
const result = await wallet.sendTokenEnablements({
enableTokens: [{ name: 'thbar:usdc' }],
prv: 'prvKey',
});
```
TICKET: BG-0000

fix: allow token enablement for cold wallet

---

modules/sdk-core/src/bitgo/staking/iStakingWallet.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts

- add optional `delegationId` to unstake requests
- add new API support to GET `delegations` from staking-service
BOS-537

feat(sdk-core): add support for delegation in staking flow

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Adds support for testnet Polygon (TMATIC) as an ERC20 token.
Ticket: BG-55777

feat: add testnet polygon

---

modules/sdk-coin-ada/src/lib/transaction.ts
modules/sdk-coin-ada/src/lib/transactionBuilder.ts
modules/sdk-coin-ada/test/unit/ada.ts
modules/sdk-coin-ada/test/unit/transaction.ts
modules/sdk-coin-ada/test/unit/transactionBuilder.ts

Add transaction fee and getFee to transaction class. The transaction fee and getFee were then de-duplicated from the transaction builder class. Tests were updated accordingly to reflect changes. 
TICKET: [BG-55867](https://bitgoinc.atlassian.net/browse/BG-55867?atlOrigin=eyJpIjoiNzhlNjIyMjFjZTUxNDlhYjkxZjFhYmY3YWExYzA2YTkiLCJwIjoiaiJ9)

feat(sdk-coin-ada): add getfee to transaction class

---

modules/sdk-coin-sol/src/lib/index.ts

was missing exporting TransferBuilderV2 in `index.ts`, needed for sol token consolidation

fix(sdk-coin-sol): added missing member to export

---

modules/bitgo/README.md

The synk badge was broken for both shield and link. Updated according
to the documentation here: https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories

chore: update synk badge

---

modules/sdk-core/package.json
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
yarn.lock

this change expands the random number
range for nuo and beta0 in ecdsa tss
to be within [1:n] where n is maxint
of paillier keys
TICKET: BG-55963

refactor(account-lib): modify random gen for nu0 and beta0

---

modules/sdk-coin-sol/src/sol.ts
modules/sdk-coin-sol/test/unit/sol.ts

A user recently reported an issue where they were unable to create a transfer where the amount was a leading zero `0002`.
This updates validateTransaction for SOL to account for this case and adds a unit test to ensure the input is now valid.
TICKET: BG-56546

fix(sdk-coin-sol): update validateTransaction for leading zero transfer amounts

---

modules/statics/src/coins.ts

adds test polygon as erc20 token for goerli because we are deprecating kovan
BOS-556

feat(statics): adds test polygon as erc20 token for goerli

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Ticket: BG-56442
The sign method in ecdsa hashes the message therefore we need to send not hashed serialized transaction i.e serializedTxHex

fix(sdk-core): ecdsa sign serializedTxHex

---

lerna.json
package.json
yarn.lock

Lerna schema was introduced post 5.2: https://github.com/lerna/lerna/releases/tag/v5.2.0,
and some refactor work was being done on `git` commands.
To reproduce the change in `lerna.json` and `package.json`, run:
```
> npx lerna@latest init
```
Reference here: https://lerna.js.org/docs/getting-started#adding-lerna
Ticket: BG-56327

build: update lerna to latest and add schema

---

modules/sdk-core/package.json
package.json
yarn.lock

This seems to help resolve issues with conflicting versions
pulled by utxo-lib and polkadot
Issue: BG-41154

fix(root): resolve @noble-secp256k1

---

modules/bitgo/test/v2/fixtures/lightning/lightning.ts
modules/bitgo/test/v2/unit/lightning.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts

This fix allows for unpaid invoices, which do not have any value for `amtPaidSats` yet, to be properly decoded. Without this, calling `getInvoices` when there are any unpaid invoices in the result set fails.
NEW TICKET: BG-43813
This has been tested both manually with a testnet BitGo wallet that had open invoices which were triggering this bug, and by expanding the test cases for fetching invoices to include open invoices.

fix(sdk-core): allow undefined for amtPaidSats

---

modules/bitgo/test/v2/unit/lightning.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts
modules/sdk-core/src/bitgo/lightning/lightning.ts

Removed `address` param for `lightning().deposit` from SDK because there is no easy way to check if address is lightning address. A user could potentially provide an arbitrary, non-lightning address which we’d send funds to and end up not adding anything to the wallet’s custodial lightning balance
Ticket: BG-57388

fix(bitgo): remove address param from lightning().deposit

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/externalSign.ts
modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
modules/sdk-core/src/index.ts

The purpose of this PR is to add support for TSS EdDSA signing through using the external signer. In summary, the approach taken is as follows:
External signer is responsible for generating R and G shares destined to BitGo. This is achieved by refactoring the existing code that performs TSS for EdDSA signing. Through modularization of R and G share generation we can now have the external signer call the separate modules according to the current step in TSS signing.
Please refer to this link for the multisig endpoint for signing at external signer: https://github.com/BitGo/BitGoJS/blob/997dcfb5bc2812a56459c19b2613a8ee32bcee91/modules/express/src/clientRoutes.ts#L385

feat(express): Version 1 of external signer TSS support

---

modules/sdk-coin-eth/src/eth.ts
modules/sdk-coin-ethw/test/unit/index.ts

When building an ETH tx, create a custom ETH common if chain id is not supported by ethereumjs. This is needed to support ETHw.
BG-55611

fix(sdk-coin-eth): create custom ETH common for unsupported chain ids

---

modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Ticket: BG-57787
Coins that support tss are defaulting to tss wallets, we wants wallets to be tss only if users explicitly ask for tss wallets. This change makes tss not the default type for wallets.
Ticket: BG-57787
Updated test to reflect the current flow.

fix(sdk-core): default wallet to non tss

---

modules/account-lib/test/unit/mpc/tss/eddsa/eddsa.ts
modules/sdk-core/src/account-lib/mpc/curves/ed25519.ts

We were converting our public keys to Buffers but were cutting off
leading zeroes during the process (because we first converted the
hex strings to BigInts). This led to us passing a buffer with less
than 32 Bytes into the sodium library as a public key. The library
then threw an error which we hid by assuming that any error means
that the signature we are verifying is invalid.
The fix is to always pass in a Buffer with a length of 32 Bytes and
to fill it with zeroes if necessary.
Ticket: BG-50442

fix(account-lib): fix EDDSA MPC key validation for small number keys

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Ticket: BG-57413
Fixes for ecdsa key chain encryption to match hsm. 
BG-57413 
Updated test.
Created jira ticket for test that was disabled.  BG-58151

fix(sdk-core): ecdsa keychain creation types mach

---

modules/sdk-coin-sol/src/sol.ts
modules/sdk-coin-sol/test/fixtures/sol.ts
modules/sdk-coin-sol/test/unit/sol.ts

Ticket: BG-57227
Implement unsigned sweep flow for Solana. Unsigned sweep flow is differentiated from a non-bitgo flow by the missing user key, backup key, and wallet passphrase from the frontend, and will return a serialized **unsigned** transaction hex string.
Unsigned sweep will always require a durable nonce account, and sign transactions with the durable nonce account.
BG-57227
Unit tested, verified that we receive a transaction hex for unsigned transactions

feat(sdk-coin-sol): Unsigned Sweep Recovery

---

modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/keychain/keychains.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/wallet/iWallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Making an update to the generate wallet flow for TSS wallets, to allow for the passphrase to be optional.
https://bitgoinc.atlassian.net/browse/BG-56687

fix(wp): allow for optional passphrase on tss wallets

---

.github/workflows/beta-publish.yml
scripts/prepare-beta.ts

- adds script to rename packages to @bitgo-beta scope
- adds github action to generate a beta on demand. Will wire up to master once we confirm this works with secrets
Ticket: BG-57161
- Once the secrets are configured in GitHub we can then publish beta builds to https://www.npmjs.com/search?q=%40bitgo-beta

chore(root): add steps to automate publishing @bitgo-beta

---

modules/statics/src/coins.ts

Fixes the tsol orca mint address to the properly generated one, the old/current one is accidentally the same as USDT.
TICKET: STLX-19257

fix(statics): update tokenAddress for tsol:orca

---

modules/sdk-coin-sol/src/lib/transactionBuilder.ts
modules/sdk-coin-sol/src/lib/transactionBuilderFactory.ts
modules/sdk-coin-sol/test/unit/transactionBuilder/transferBuilderV2.ts

Ticket: BG-58613
Currently the sol tx deserialize doesn't set feePayer, so when the feePayer is different than the sender, it throws unknown signer error. Fixed with adding feePayer.

fix(sdk-coin-sol): fix sol deserialize incorrect feePayer

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Expand typing of recipient array for token related transfer data. Add transfertoken type to switch/case to call prebuildTxWithInent for tokenTransfer intent.
Add unit tests to make sure requestst to WP are made with proper/expected params.
BG-57935

feat(core): support transfertoken type transactions

---

modules/account-lib/test/unit/mpc/tss/ecdsa/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

SDK fixes for ETH TSS. This change includes 2 fixes
1. fix to/from of how we're sending user s share to pass signature share validation in platform
2. fix how we are signing eth tss txs to ensure we sign the hashed, RLP encoded tx rather than the hashed serialized tx
bg-58807

Bg 58807 fix eth tss signing verifying

---

modules/sdk-coin-polygon/test/unit/polygonToken.ts
modules/statics/src/base.ts
modules/statics/src/coins.ts
modules/statics/src/tokenConfig.ts

- adds NAME NFT to Statics within Polygon Mumbai testnet
- if coin instance is of ERC721 class then the coin should be added to the polygon constructor so that `bitgo.coin(<tokenName>)` works
JIRA ticket: https://bitgoinc.atlassian.net/browse/BG-58416

feat(statics): support NAME NFT on tpolygon BG-58416

---

modules/sdk-coin-dot/src/dot.ts
modules/sdk-coin-dot/test/fixtures.ts
modules/sdk-coin-dot/test/unit/dot.ts

Add support to sweep wallet with multiple addresses; these addresses derivation path are 0 indexed and Users must pass in the index to start the search at. User can also optionally pass in how many iteration to search for (ie iteration of 20 with starting index 0 results in index 19 being the last index searched). The default iteration to search for is 20.
Recover function now returns the serialized transaction hex plus the index of the address with the funds being swept so that the user can start at this index + 1 for the next recover call.
BG-58560
Unit tests, and end to end test confirming that we were able to sweep address 1 of a test wallet

feat(sdk-coin-dot): update dot recover function to traverse addresses

---

modules/sdk-coin-near/src/near.ts
modules/sdk-coin-near/test/fixtures/near.ts
modules/sdk-coin-near/test/unit/near.ts

Update Near recover function to perform address scanning. Logic is the same as for Sol, Dot, and Ada.
BG-59027
3 new unit tests

feat(sdk-coin-near): implement address scanning for near recover

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/prebuildAndSignTx.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts

Adds Express endpoint and handler.
Add endpoint and handler for request which are meant to be routed to sdk-core prebuildAndTransaction.
This express endpoint will be useful for customers with TSS wallets trying to send funds and transfer tokens.
This is part of a broader task to support NFT transfers for Polygon TSS wallets (and other EVM-coin TSS wallets).
JIRA ticket: BG-58191 subtask of https://bitgoinc.atlassian.net/browse/BG-57934
- [*] New feature (non-breaking change which adds functionality)
- [*] This change requires a documentation update
Unit test which stubs async calls to Platform. Checks the request flows through properly and stubbed response is returned properly.
all have been checked (and removed from description)

feat(express): support routes to prebuildAndSignTransaction

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

this change introduce a new coin deprecation feature. This helps to distinguish coins which are
currently being deprecated.This is especially helpful when coins have multiple testnets which were previously supported but deprecated now. This change also deprecates teth.
TICKET: BG-59177

feat(statics): introduce deprecation coin feature

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

the underlying asset for GTETH should
be ETH similar to that of 'TETH'.
TICKET: BG-59194

fix(statics): update underlying asset of GTETH to ETH

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-58636
when sharing ecdsa wallet common key chain validation fails because currently it uses eddsa getPublicKeyFromCommonKeychain. This pr changes it where the wallet uses the correct curve method.
Updated old test

fix(sdk-core): ecdsa commonkeychain validation

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Add the ability to make tx accelerations for eth through the acceleration intent. Added unit tests
Ticket: bg-53422

feat(wp): add acceleration capability for eth

---

modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/utils.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/utils.ts

Ticket: BG-59876
bsc deserialization removes '0x' prefix automatically, needs to add the prefix back after bcs deserialization

feat(sdk-coin-sui): prefix sui addresses with 0x

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Adds the ability to build eth txs with the fillNonce intent. Adds unit tests as well.

Bg 58778 add eth fillnonce capability

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/keychain/keychains.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/wallet/iWallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Ticket: [BG-59055](https://bitgoinc.atlassian.net/browse/BG-59055)
This modifies the ecdsa TSS flow to support third party backup key
providers (for Nike, BitGo is the backup provider) where the backup key
is created via Bitgo (i.e WP->HSM). It involves two additional calls
to the WP, first to create the backup shares, and second time to
update the backup key in WP with the bitgoToBackup shares and verifying
the common keychain. Rest of the flow remains the same.

feat(sdk-core): tss ecdsa key creation flow with third party backup

---

modules/bitgo/test/unit/bitgo.ts
modules/sdk-core/src/bitgo/environments.ts

This change updates the SDK to point to the correct staging urls
Internal ticket : BG-59878

new env setup for staging

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts

This PR fixes the tests and the switch/case statement that check for the intent type set when the tx type is `transfertoken`.

fix(core): properly translate tx type to transferToken intent BG-60250

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts

The SDK currently uses `userPub` for the user gpg key, but the API accepts it as `userGPGPublicKey`. This fixes the api param.

fix(sdk-core): update user gpg API param name to create backup keys

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Add support for MMI transactions and message signing.
Transactions
- Pass custodianTransactionId into the intent in txRequest
Messages
- Pass custodianMessageId into intent in txRequest

feat: pass custodianTransaction and messageId

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Remove logic to pass in 'isTss' to eth tx request builds. This flag is being deprecated in WP in https://github.com/BitGo/bitgo-microservices/pull/25007 (please do not merge this until 25007 is merged).
Ticket: bg-60332

chore(sdk-coin-eth): deprecate isTss for eth sends

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-57866
Allow WalletId to be passed as argument (under `recipient`) when we build txn
Ticket: BG-57866

feat(sdk-core): Allow preBuildTransaction to Accept Wallet Id

---

modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/src/lib/transactionBuilder.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/transactionBuilder.ts

Ticket: BG-60866
Added signature to sui transaction.
Note: Since Sui has the detached signature, the txHex doesn't change, and needs to call `txBuilder.addSignature` after calling `from(tx)`

fix(sdk-coin-sui): added signature to sui transaction

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

Add polygon tokens to statics
[BG-61047](https://bitgoinc.atlassian.net/browse/BG-61047)

feat(statics): add polygon tokens

---

modules/bitgo/test/v2/unit/tss/eddsa.ts
modules/sdk-core/src/account-lib/mpc/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts

VSS verification does not currently work with current APIs. Will need to make changes before re-enabling.
Ticket: BG-61040

fix: disable vss verification

---

modules/bitgo/test/v2/fixtures/lightning/lightning.ts
modules/sdk-core/src/bitgo/lightning/iLightning.ts

This updates the SDK code to expect the new response format used for lightning withdrawal requests, which specifies a `txid` in the body rather than a `transfer` and `status`.
Ticket: BG-59192
This does not break or change any of the SDK APIs, but rather brings it up to date with a breaking change on the BitGo API side. 
Direct requests against the BitGo API in test confirm that the response body for this call only contains `txid`.

feat(sdk-core): expect txid response for lightning withdrawal

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/bitgo/test/v2/unit/tss/ecdsa.ts
modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Ticket: BG-61217
This pr reenables ecdsa vss compatible with older wp versions. 
Verified this change bye end to end wallet creation testing and reenabling unit test.

fix(sdk-core): ecdsa vss

---

modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Pass custodianTransactionId to prebuildTxWithIntent so it gets included inside the payment intent
Tested E2E with MMI Transactions

fix: pass custodianId to prebuildTxWithIntent

---

modules/utxo-lib/package.json
yarn.lock

Updated bitcoinjs-lib uses the transaction class specified by the PSBT subclass for parsing nonWitnessUtxos
Issues: BG-55848, BG-56123

fix(utxo-lib): Bump bitcoinjs-lib for PSBT fix

---

modules/sdk-core/package.json
modules/sdk-core/src/index.ts
modules/sdk-core/src/units.ts
modules/sdk-core/test/unit/units.ts

This PR introduces units conversion functions that are based on the `statics` part of the SDK. These functions are tightly coupled with the map of coins in `statics`, so it makes sense for the utility functions to live in the SDK.
BG-61910
I mainly tested by adding unit tests. I'm not a domain expert here, so please let me know if you want other boundary conditions to be tested.

feat: add units functions to sdk core

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

This reverts commit a797e38b0269bc0ea6e4834f0aca4605ef297265.
We are rolling back this change to remove the ability to send to a wallet id
Ticket: BG-62517

Revert "feat(sdk-core): allow preBuildTransaction to accept wallet id"

---

modules/sdk-coin-avaxp/src/avaxp.ts

`verifyTransaction` fails when the tx type is `importToC` because the type is not present in the TransactionType enum
Ticket: BG-62009

chore(sdk-coin-avaxp): disable tx type verification

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/consolidateAccount.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

feat(express): consolidate account support in external signer

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts

Issue was that `transactions` only exists on txRequest for api version `full`, which was throwing an error for api version `lite`. Added in fix to account for this.
TICKET: [BG-62852](https://bitgoinc.atlassian.net/browse/BG-62852?atlOrigin=eyJpIjoiZTY2ZWNmZTBhNWQ5NDRmYWJmZjk3ZGZmYTgwYTgxOTQiLCJwIjoiaiJ9)

fix(sdk): fix tss signing

---

modules/statics/src/coins.ts

Adding only ETH, ETH2, BSC, and Polygon for TSS feature support flag. We can incrementally refactor them into `ETH_FEATURES` later.
Ticket: BG-62565

feat(statics): add TSS feature flag to ETH

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-sol/src/sol.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/utils/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Add API version input to prebuildTransactionTss method
[BG-57753](https://bitgoinc.atlassian.net/browse/BG-57753)
This PR changes the default version of the API from lite to full. This causes the txRequest endpoint to fail when prebuilding transactions without sending the preview param true.
- To prebuild transactions is needed to use the preview param true.
- To send transactions needed to send the OTP to unlock the token.

feat(bitgo): add api version input

---

modules/sdk-coin-dot/src/lib/transaction.ts
modules/sdk-coin-dot/test/unit/transactionBuilder/transferBuilder.ts

Polkadot transferAll transactions (used in consolidation) do not deserialize amounts. Set the value of the transaction to zero.
Currently the value is 'sweep', but this string does not merge well with the Amount type when parsing the tx internally.
TICKET: BG-62062
Internal Users - BG-62062
External Users - Please link to any relevant github issues as necessary.

fix(dot): update DOT transferAll value to zero

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-63034
Sui requires a `gasBudget` input, so this PR is to support passing `gasLimit` parameter in prebuild

chore(sdk-core): sui pass gas limit param in prebuild

---

modules/sdk-coin-dot/src/lib/nativeTransferBuilder.ts
modules/sdk-coin-dot/test/unit/transactionBuilder/transferBuilder.ts

Adds the keepAlive flag as an optional parameter to the sweep() constructor used when building DOT transactions.
TICKET: BG-62062

feat(sdk-coin-dot): add keepAlive flag to DOT sweep constructor

---

modules/sdk-coin-sui/src/lib/transaction.ts

Ticket: BG-63522
Sui's sdk is throwing `invalid length 27, expected an byte array of size 32` error when executing transaction, this PR is to fix the serialization byte size.

fix(sdk-coin-sui): fix serialization byte size

---

modules/bitgo/test/v2/unit/wallets.ts
modules/sdk-core/src/bitgo/wallet/wallets.ts

Fix generateWallet which  incorrectly sets isCold as long as the userKey is present. This should only happen if the wallet type is tss - the result is hot wallet creation via the /generateWallet endpoint with Express is broken & only creates hot wallets.
https://bitgoinc.atlassian.net/browse/BG-63468
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code compiles correctly for both Node and Browser environments
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My commits …

fix(sdk-core): fix generate wallets isCold param

---

modules/bitgo/test/v2/unit/recovery.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/recovery/initiate.ts

Ticket: BG-61005
This change supports building/signing a recovery transaction with TSS. It expects the user/backup key shares to perform TSS signing. A couple unit tests were added to test building an unsigned tx and to fully build/sign a recovery tx.
More work needs to be done on the WRW side to actually allow for an end user to perform the recovery flow like other coins.

feat(eth): add support for tss recoveries

---

modules/sdk-coin-algo/package.json
yarn.lock

- latest algosdk breaks browser apps downstream with /dist import used here
Ticket: CR-804

chore(sdk-coin-algo): lock algosdk version

---

modules/sdk-coin-sui/src/lib/transaction.ts
modules/sdk-coin-sui/test/unit/transaction.ts

Ticket: BG-64130
Fix explainTransaction when `amounts` is empty

fix(sdk-coin-sui): fix explainTransaction when amounts is empty

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/package.json
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/baseCoin/baseCoin.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts
webpack/bitgojs.config.js
yarn.lock

[EIP-712 standard](https://eips.ethereum.org/EIPS/eip-712) describe how to encode the data before hashing. This is usually handled by the `@metamask/eth-sig-util` library. Normally we would just call the `eip712hash` function of that library, however that function applies the `keccak` transformation to the encoded data. In our case, we just needed the raw encoding, so we ended up doing everything shy of the `keccak`

Bg 62806 eip712 encoding

---

modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/features/constructFinalSignedMessageHash.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Recovery ID (v) is required for Ethereum message signing, in addition to the r and s values from the ECDSA standard. Previously this [was being computed and concatenated](https://github.com/BitGo/BitGoJS/blob/master/modules/sdk-coin-eth/src/eth.ts#L1761) inside of SDK, however MMI does not use SDK but still need the final form of the message hash. Hence this computation[ is being moved to WP](https://github.com/BitGo/bitgo-microservices/pull/27035), and being deleted here.
Ticket: BG-64064

fix!: remove final sig construction for message signing

---

examples/ts/eth/fund-forwarder.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

TICKET: BG-64628
This change adds a function to support calling the `api/v2/{coin}/wallet/{walletId}/fundForwarder` endpoint via BitGoJS.

feat(sdk-core): support fund forwader

---

package.json
yarn.lock

`lerna` and `eslint-plugin-import` both imported `tsconfig-paths` that uses a vulnerable version of `json5`. While `lerna` patched the fix in the latest release already, the later has not pushed any fixes at this point yet.
Considering the `lerna` version that was patched is one major version ahead of our current lerna version, `json5` is added for resolution instead of a version update.

fix(root): patch CVE-2022-46175

---

modules/statics/src/account.ts

fiat currencies should be named following the pattern /^t?fiat([a-z]{3})$/ in which the 3 characters are the ISO currency codes
Ticket: BG-62244
[BG-62244]: https://bitgoinc.atlassian.net/browse/BG-62244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(statics): document fiat naming pattern

---

modules/statics/src/base.ts
modules/statics/src/coins.ts

This PR creates a new CoinFeature that will be used on TSS account based coins. This will be used in SDK-Core and WP to track which coin-specific wallets should be created with the same set of keys.

feat(statics): add EVM_WALLET coin feature

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-coin-eth/src/eth.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-60728
This pr enables sdk to make address creation request to BitGo with forwarder version 3. Forwarder version 3 is support for eth and eth like coin forwarders.

feat(sdk-core): forwarder version 3

---

modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Changes the `createBitgoKeychain()` function to use the distinct backup GPG keys that are generated, whether it is a third party backup or not.
BG-62364

feat(sdk-core): change third party to backupGpgKey

---

package.json
yarn.lock

Patched package is for `react-json-view`, but since yarn workspace will not take inner package resolution yet, it will live in the root package.json. Blocks #3197 
Ticket: BG-66404

fix(web-demo): patch GHSA-fhg7-m89q-25r3

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Adds a function to verify wallet signatures during ECDSA key generation.
BG-65151

feat(sdk-core): add ecdsa wallet sig verification

---

modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/wallet/iWallets.ts

This PR adds a narrow type for BackupProvider to make it easier to understand all the valid values it can hold.
TICKET: BG-66601
This PR does not change any existing functionality.

chore: add narrow types for backupProvider

---

modules/statics/src/avaxp.ts
modules/statics/test/unit/coins.ts

We recently introduced new custody coin features where every coin has a feature for all the `BitGo` entities it belongs to. We're now enforcing these features in the `Wallet Platform`, and during this change, it came about that `Avax-P` is currently missing all the custody flags. As part of this PR, we're adding the `BitGo Trust` and `BitGo Germany` custody flag for `Avax-P` coin.
The list of BitGo entities for `Avax-P` was confirmed by the `Altcoin` team!
[BG-66028](https://bitgoinc.atlassian.net/browse/BG-66028)
- Modified: modules/statics/src/avaxp.ts
- Modified: modules/statics/test/unit/coins.ts
[BG-66028]: https://bitgoinc.atlassian.net/browse/BG-66028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(statics): Add Custody Coin Features For AVAX-P Coin

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts

Corrects verification of wallet signatures received from the HSM during TSS ECDSA wallet
generation.
BG-68087

fix(sdk-core): correct ecdsa verifyWalletSigs()

---

modules/sdk-coin-bsc/test/unit/transactionBuilder/send.ts
modules/sdk-coin-eth/src/lib/transactionBuilder.ts

Ticket: BG-66898
Allow txs to build from txHex for coins without
factoryImplementationAddress

fix(sdk-coin-bsc): build from txHex

---

modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

TypedDataRaw is already `stringify` and that was causing an issue in `hsm` where this could not be parsed properly.
Ticket: BG-67362

fix(sdk-core): sign typed data json stringify

---

modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts

Passes the `hex` parameter to the `toString()` calls within the ECDSA `verifyWalletSignature()` function.
TICKET: BG-65152

fix(sdk-core): use hex toString() verify ecdsa

---

modules/key-card/package.json
modules/key-card/src/drawKeycard.ts
modules/key-card/src/index.ts
modules/web-demo/package.json
modules/web-demo/src/App.tsx
modules/web-demo/src/components/KeyCard/index.tsx
modules/web-demo/src/components/Navbar/index.tsx
modules/web-demo/tsconfig.json
modules/web-demo/webpack/base.config.js
modules/web-demo/webpack/dev.config.js
modules/web-demo/webpack/prod.config.js
yarn.lock

* adds code in the key-card module that creates the key cards
* skips the QR codes on the key-cards for now, will come in a
followup
* adds some sample code in the web-demo module that allows creation
of a sample key card
* check out the PR branch locally
* run the following commands
```
yarn install
cd modules/web-demo
yarn dev
```
Open `localhost:8080/keycard` in your browser and click on the Download button. This should generate and download a key card, compare it against the one attached to this PR:
[BitGo Keycard for Hello World.pdf](https://github.com/BitGo/BitGoJS/files/10675748/BitGo.Keycard.for.Hello.World.pdf)

feat(key-card): add basic code to generate key cards

---

modules/sdk-coin-atom/src/lib/keyPair.ts
modules/sdk-coin-atom/test/resources/atom.ts
modules/sdk-coin-atom/test/unit/keyPair.ts

Ticket: [BG-68083](https://bitgoinc.atlassian.net/browse/BG-68083)
Wallet creation workflow does not seem to create unique root address and instead creates same root address for different public keys. This seems to be happening since the SDK key pair changes were [incorporated into WP](https://github.com/BitGo/bitgo-microservices/pull/28855).
On looking further, the `getAddress()` method inside the atom sdk module was computing the same base64 string, from an empty usigned int array. This base64 string was always `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` and therefore, returned the same cosmos root address, when the corresponding cosmjs libraries were called to convert the base 64 string to a cosmos specific address.
[BG-68083]: …

fix(sdk-coin-atom): fix get address method to generate unique address

---

modules/sdk-core/src/bitgo/tss/common.ts
modules/sdk-core/src/bitgo/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/tss/eddsa/eddsa.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts

The VSS proof data should be with the signature share. The `signatureShare` field will be replaced by `signatureShares` field (an array) in the future and the VSS proof data will be different for each of them.
More info on multiple shares to be signed at once: https://bitgoinc.atlassian.net/browse/BG-52812
Ticket: BG-67907

feat: move vss proof data to be with signature share

---

modules/statics/src/coins.ts

Ticket: [BG-68307](https://bitgoinc.atlassian.net/browse/BG-68307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
This ticket follows step 1 of the document in the ticket to onboard three new ofc erc20 tokens in TEST. This PR is part of the effort for making testing erc20-related features for trading accounts in TEST possible. 
UUIDs are generated with https://www.uuidgenerator.net/
[BG-68307]: https://bitgoinc.atlassian.net/browse/BG-68307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(statics): add ofc erc20 tokens

---

modules/bitgo/test/v2/unit/staking/stakingWalletCommon.ts
modules/sdk-core/src/bitgo/staking/iStakingWallet.ts
modules/sdk-core/src/bitgo/staking/stakingWallet.ts

add support for `SWITCH_VALIDATOR` staking request.
currently only SUI will be using the new type

feat(sdk-core): add `switchValidator` for stakingWallet

---

.github/workflows/ci.yml

Even browser-test does not need Node.js to run, `yarn install` still checks the Node version in package.json files. Since the CI is picking up version `18` as default, which is not what we support, specifying Node version in `brower-test` step.
This will unblock various the build issues we have in `origin/master` right now
Ticket: BG-0

build(root): node verison was not specified

---

modules/sdk-coin-eth/package.json
package.json
scripts/check-package-dependencies.ts
yarn.lock

The patched package is to fix a dependency for installed dependency `@metamask/eth-sig-util`.
Ticket: BG-69103

fix(sdk-coin-eth): fix @ethereumjs/util version to support node 14

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

Ticket: BG-69569
This fixes failing non-TSS custodial consolidations, such as TRX and ALGO.
BG-69569

fix: conditional check to custodial consolidation

---

CODEOWNERS

fix: set CODEOWNERS for `utxo-ord`

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/signPayload.ts
modules/sdk-core/src/bitgo/trading/iTradingAccount.ts
modules/sdk-core/src/bitgo/trading/tradingAccount.ts

This endpoint will enable our Clients and Partners to leverage
BitGo Express to sign arbitrary http post request payloads, with
their trading account key, in order to integrate with our systems.
Ticket: BG-66430

feat: express route for signing arbitrary payloads

---

modules/statics/src/coins.ts
modules/statics/test/unit/coins.ts

We have gotten approval to create custodial wallets for `CSPR`, `MATIC` and `ETH` coins within the BitGo Switzerland entity. As part of this PR, we're updating the coin features on these coins to support custodial wallets in Switzerland.
[BG-69987](https://bitgoinc.atlassian.net/browse/BG-69987)
- Modified: modules/statics/src/coins.ts
- Modified: modules/statics/test/unit/coins.ts
[BG-69987]: https://bitgoinc.atlassian.net/browse/BG-69987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(statics): Add Custody Coin Features Switzerland

---

modules/statics/src/coins.ts
modules/statics/test/unit/coins.ts

We have gotten approval to create custodial wallets for `POLYGON` coin within the BitGo Switzerland entity. As part of this PR, we're updating the coin features on this coin to support custodial wallets in Switzerland
BG-69987
- Modified: modules/statics/src/coins.ts
- Modified: modules/statics/test/unit/coins.ts

feat(statics): Add Custody Coin Features For Switzerland To Polygon

---

modules/sdk-core/src/bitgo/environments.ts

Previous testnet ada node url was deprecated and had to be updated with the new one.
TICKET: [BG-69958](https://bitgoinc.atlassian.net/browse/BG-69958?atlOrigin=eyJpIjoiMjFlMDBkYzgzNjJhNGY4ZWJlZGY4YzRhOTc5ZWMwNDIiLCJwIjoiaiJ9)
[BG-69958]: https://bitgoinc.atlassian.net/browse/BG-69958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(sdk-core): change testnet ada node url in config

---

modules/sdk-rpc-wrapper/src/constants.ts
modules/sdk-rpc-wrapper/src/evmRPCWrapper.ts
modules/sdk-rpc-wrapper/src/types.ts
modules/sdk-rpc-wrapper/test/fixtures/evmRPCWrapperFixtures.ts
modules/sdk-rpc-wrapper/test/unit/evmRPCWrapper.ts

Adding `eth_sendTransaction` method 
Ticket: BG-69639

feat(sdk-rpc-wrapper): add send transaction

---

modules/statics/src/coins.ts

added solana valid USDC for devnet  as tsol:usdcv2 token data
BG-0000

fix(statics):  add tsol valid usdc for devnet token data

---

modules/sdk-coin-atom/src/lib/transaction.ts
modules/sdk-coin-atom/src/lib/transactionBuilder.ts
modules/sdk-coin-atom/test/unit/keyPair.ts
modules/sdk-coin-atom/test/unit/transaction.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingActivateBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingDeactivateBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/StakingWithdrawRewardsBuilder.ts
modules/sdk-coin-atom/test/unit/transactionBuilder/transferBuilder.ts

BaseTransaction has five properties: id, type, inputs, outputs and signature. There is coin specific txn object is also present in extended transaction classes, AtomTransaction in this case. This PR adds a function to transaction class to load inputs and outputs from AtomTransaction. This PR also makes sure that `loadInputsAndOutputs` is called while building the transaction in TransactionBuilder
Ticket: BG-70311

feat(sdk-coin-atom): add function to load inputs and outputs of a txn

---

modules/sdk-core/src/account-lib/mpc/index.ts

Exporting ecdsa and bip32 classes to use in WP.
TICKET: BG-69708

chore(sdk-core): export ecdsa and bip32 classes

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/mpcUtils.ts
modules/sdk-core/src/bitgo/utils/tss/baseTypes.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

This PR adds support for nonce hole filling and consolidation accelerations on an ETH TSS receive address
BG-69374
BG-69376

feat(sdk-core): enable fillNonce and acceleration tx for receive address

---

modules/sdk-coin-atom/src/lib/keyPair.ts
modules/sdk-coin-atom/test/unit/keyPair.ts

Atom KeyPair class is creating public key 64 bytes long similar to EDDSA and to match the secp256k1 key size, one extra byte is prepended. This generates wrong address.
Slicing initial 66 bytes from full public key to get the correct compressed key
Ticket: BG-72104

fix(sdk-coin-atom): fix getAddress of KeyPair

---

modules/sdk-coin-atom/src/lib/index.ts

Ticket: BG-72595
Atom staking builders are not available to be consumed in WP because they’re not exposed yet. This PR involves a simple change in the SDK where we export the necessary builders. Once this change is through, we will need to bump SDK in WP to actually consume the staking builders.

chore(SDK): export atom staking builders

---

modules/sdk-coin-sui/src/sui.ts
modules/sdk-coin-sui/test/unit/sui.ts

fixed sui verifyTransaction method to handle recipients amount in string or number
BG-0000

fix(sdk-coin-sui): fix sui verifyTransaction method

---

modules/sdk-coin-xrp/src/ripple.ts
modules/sdk-coin-xrp/src/xrp.ts
modules/sdk-coin-xrp/test/unit/xrp.ts

Currently, the sdk only has support for signing once with the sdk. But for the case of recovery transactions for smc wallets, signing may be need to be done twice with both the client's user and backup key. The appropriate changes were made to add support for this.
TICKET: BG-77113

feat(sdk-coin-xrp): add backup signing for xrp

---

modules/sdk-coin-sui/src/lib/compareTransactionBlocks.ts
modules/sdk-coin-sui/src/lib/constants.ts
modules/sdk-coin-sui/src/lib/iface.ts
modules/sdk-coin-sui/src/lib/mystenlab/framework/sui-system-state.ts
modules/sdk-coin-sui/src/lib/unstakingBuilder.ts
modules/sdk-coin-sui/src/lib/unstakingTransaction.ts
modules/sdk-coin-sui/test/local_fullnode/transactions.ts
modules/sdk-coin-sui/test/resources/sui.ts
modules/sdk-coin-sui/test/unit/compareTransactionBlocks.ts
modules/sdk-coin-sui/test/unit/transactionBuilder/unstakingBuilder.ts

- The UnstakingBuilder.unstake() method now accepts an optional `amount`
parameter.
- When the `amount` parameter is provided, the transaction block
will contain two transactions:
- The first transaction will split the staked amount into two
staked amounts, one with the `amount` and the other with the
remaining amount.
- The second transaction will use the result of the first
transaction as input and will unstake the `amount` from the
staked amount.
- Improve tests
Issue: BG-78857

fix(sdk-coin-sui): add support for partial unstaking

---

CODEOWNERS

chore: change codeowners to use ethalt-team instead of defi-team

---

modules/key-card/.npmignore

In the absence of an .npmignore file, npm uses .gitignore to determine which files to not publish -- as a result the built distribution was not exported.
Ticket: CE-1215

fix(key-card): add .npmignore to fix npm export

---

modules/sdk-core/src/bitgo/pendingApproval/iPendingApproval.ts
modules/sdk-core/src/bitgo/pendingApproval/pendingApproval.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

This PR adds the pendingApprovalId in the buildTransaction call to the wallet platform for handling the case  related to rebuild of transactions for XRP nonce handler.
EA-944

fix(sdk-core): add pendingapproval id in build api

---

modules/sdk-core/src/bitgo/utils/postWithCodec.ts
modules/sdk-core/test/unit/bitgo/utils/postWithCodec.ts
modules/sdk-core/tsconfig.json

This is a helper method for the development of request codecs.
Since it is difficult to get the codec right the first time, this method 
allows to send the request with the original body and set some header flags
to indicate that the codec failed to decode or encode the body.
Issue: BTC-368

feat(sdk-core): add postWithCodec utility function

---

modules/bitgo/test/v2/unit/internal/tssUtils/eddsa.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/baseCoin/iBaseCoin.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

In the txRequest full flow, we have to check if the txRequest is pending approval before trying to sign.
WP-439
TICKET: WP-439

fix(sdk-core): handle txRequest full PA before signing

---

modules/bitgo/test/v2/unit/enterprise.ts
modules/sdk-api/src/bitgoAPI.ts
modules/sdk-core/src/bitgo/bitgoBase.ts
modules/sdk-core/src/bitgo/enterprise/enterprise.ts
modules/sdk-core/src/bitgo/enterprise/enterprises.ts
modules/sdk-core/src/bitgo/enterprise/iEnterprise.ts
modules/sdk-core/src/bitgo/enterprise/iEnterprises.ts
modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/tss/ecdsa/types.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
modules/sdk-core/src/bitgo/utils/tss/ecdsa/types.ts

Currently when we create new enterprise MPC config's, they are signed by one of the admins. During signing, we verify that the config's signature by admin's keychain to confirm it's validity. 
In the case if the admin forgets and resets their password (in which case a new keychain is created), the MPC config needs to be re-signed. This PR exposes methods to support re-signing. Also, if an admin is removed from the enterprise, same helper methods can be used to resign. 
NOTE: Recommend reviewing commit by commit.

feat(sdk-core): support resigning enterprise and bitgo tss configs

---

modules/sdk-core/src/bitgo/wallet/wallet.ts

This PR is adding deleteSignatureShares in `signTransactionTssExternalSignerEdDSA ` method so that the transaction gets rebuilt just before signing for TSS SMC wallets (external signer)
EA-1488

fix(sdk-core): add rebuild step before eddsa signing

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/utils/tss/baseTSSUtils.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Previously we had a check against `mustUseTxRequestFull` before we checked if we should skip signing in the preBuildAndTransaction function. This works fine for ecdsa, but fails for eddsa hot wallets that are using apiVersion === full since they also support lite. 
Reading through the code, we shouldn't need to restrict flows if a coin supports only txRequestFull, instead we should base the flows based on what version of the txRequest we are dealing with. 
TICKET: WP-664

fix(sdk-core): do not sign txRequest full with PA

---

modules/sdk-core/src/bitgo/wallet/BuildParams.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/test/unit/bitgo/wallet/SendTransactionRequest.ts

The name of the build param addressType is misleading. So it is deprecated and replaced with changeAddressType in WP.
Ticket: BTC-446

fix(sdk-core): add change address type for utxo coins

---

modules/sdk-core/src/bitgo/keychain/iKeychains.ts
modules/sdk-core/src/bitgo/keychain/keychains.ts

We need to be able to pass in `isDistributedCustody` in for creating a bitgoKey.
TICKET: BTC-396

feat(sdk-core): whitelist distributed custody params

---

modules/sdk-core/src/bitgo/pendingApproval/pendingApproval.ts

fix(core): use BuildParams.encode when consolidating unspents

---

modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Modified the getUserPrv method to allow using the provided unencrypted prv and not try to derivate if its a TSS wallet, also fixed the signTransaction use the txRequestId if the txPrebuild is empty for a TSS wallet
WP-990
TICKET: WP-990

feat(sdk-core): allow tss signing with unencrypted prv

---

modules/bitgo/test/v2/unit/accountConsolidations.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

Using the wallet method sendAccountConsolidations if the wrong password was provided there was no check for it, so now before building and trying to sign the tx, it will fail earlier. Also when the buildConsolidation returned an empty array(meaning no receive address has balance to consolidate) we return an error.
WP-1034
TICKET: WP-1034

fix(root): improve error handling for consolidateAccount

---

modules/sdk-api/src/v1/wallet.ts

Check to see if the xpub derived from the decrypted private key matches the key on file. 
This came up because it seems that wallet sharing is broken on v1 - and had to spend hours to figure that out.
TICKET: BTC-683

feat(sdk-api): add check to see if the derived xpub matches

---

modules/bitgo/test/v2/fixtures/nfts/nftResponses.ts
modules/bitgo/test/v2/unit/wallet.ts
modules/sdk-core/src/bitgo/wallet/iWallet.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

- add nft/unsupportedNfts typing to walletData
- add getter function for the 2 fields
- add helper method to get both sets as a single list
Ticket: WP-1094
TICKET: WP-1094

chore(sdk-core): add typing and methods for nfts

---

modules/sdk-core/src/bitgo/staking/iStakingWallet.ts

Add `btcRewardAddress` to `StakeOptions` 
and enumerate subType string
previous PR: https://github.com/BitGo/BitGoJS/pull/4128
TICKET: EA-2430

feat(sdk-core): add new fields to StakeOptions

---

modules/express/src/clientRoutes.ts
modules/express/test/unit/clientRoutes/consolidateAccount.ts
modules/sdk-core/src/bitgo/wallet/wallet.ts

In order to start migrating TSS EdDSA to full txRequest, we need to allow this param to be passed to use txRequest full, similar on how we do for sendMany
WP-1123
TICKET: WP-1123

feat(root): whitelist apiVersion for buildAccountConsolidations

---

modules/sdk-core/src/bitgo/utils/postWithCodec.ts
modules/sdk-core/test/unit/bitgo/utils/postWithCodec.ts

Ticket: [CE-3344](https://bitgoinc.atlassian.net/browse/CE-3344)
As we should not be calling .set('some-header', undefined/null/'') , so only add headers if they exist and are not empty string
Old
see empty header for `lo-Ts-Codec-Decode-Error` & `lo-Ts-Unknown-Properties`
New
[CE-3344]: https://bitgoinc.atlassian.net/browse/CE-3344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(sdk-core): only add headers if they exist and nonempty

---

modules/sdk-core/src/bitgo/utils/postWithCodec.ts
modules/sdk-core/test/unit/bitgo/utils/postWithCodec.ts

- removes encoding errors from request headers
Ticket: CE-00000

fix: remove unused dynamic headers

---

modules/deser-lib/src/cbor.ts

TICKET: HSM-236
cbor.encodeCanonical has it's own ordering rules that are actually incompatible with our internal specs, so we must use cbor.encode after properly transforming input data

fix(deser-lib): use cbor.encode instead of cbor.encodeCanonical

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/index.ts
modules/sdk-lib-mpc/src/tss/ecdsa-dkls/types.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDkg.ts

added a few dkls related utils, to deserialized single messages and get the commonkeyChain from the keyShare
WP-0000
TICKET: WP-0000

feat(sdk-lib-mpc): add dkls utils

---

modules/sdk-lib-mpc/src/tss/ecdsa-dkls/dsg.ts
modules/sdk-lib-mpc/test/unit/tss/ecdsa/dklsDsg.ts

implemented new methods for DSG class to get current session and restore session that are required for async signing used in external signer
WP-2166
TICKET: WP-2166

feat(sdk-lib-mpc): implement session get and restore for dsg

---

modules/sdk-api/src/encrypt.ts
modules/sdk-api/test/unit/encrypt.ts

added adata param to encryption methods
WP-2177
TICKET: WP-2177

feat(sdk-api): add adata param to encryption methods

---

modules/key-card/src/drawKeycard.ts

TICKET: WP-2122
KeyCardImage rendered on pdf (the one with the coin logo) was using as dimensions 303 x 40 for every coin but some images comes with different sizes so the solution is to re-scalate based on the available size and checking if one of the dimensions still exceeds after the dimensions change.

fix(key-card): broken keycard img scaling based on fixed size

---

modules/key-card/src/drawKeycard.ts
modules/key-card/src/index.ts

chore(key-card): make jspdf nodejs compatible

---

modules/express/src/clientRoutes.ts

Order matters when listing the routes. The lightning routes should come before the any `any other` logic.
Ticket: BTC-1911

fix: move lightning routes to before the any other calls

---

modules/express/src/clientRoutes.ts
modules/express/src/errors.ts
modules/express/test/unit/clientRoutes/index.ts

Ticket: DX-1197
This PR ensures that the name field is populated when there's an error. Additionally, if the error does not have a name, the name will be set to "BitGoExpressError" by default.

feat(express): add name field with default name on error

---

CODEOWNERS

chore: add devex as codeowners for monorepo files

---

modules/express/src/clientRoutes.ts
modules/express/src/typedRoutes/api/index.ts
modules/express/src/typedRoutes/api/v1/pendingApproval.ts
modules/express/test/unit/typedRoutes/common.ts
modules/express/test/unit/typedRoutes/pendingApproval.ts

moving pendingApprovals api to typed router
Ticket: WP-5410

feat(express): typed-router for pendingApprovals

---

modules/express/src/typedRoutes/api/v1/acceptShare.ts
modules/express/src/typedRoutes/api/v1/pendingApproval.ts
modules/express/test/unit/typedRoutes/acceptShare.ts
modules/express/test/unit/typedRoutes/pendingApproval.ts

adding jsdoc to support openapi doc gen
Ticket: WP-5643

fix(express): adding jsdoc

---

package.json
yarn.lock

Applied targeted resolution to pin `store2` to 2.14.4 for avalanche package. This addresses GHSA-w5hq-hm5m-4548, a low-severity XSS vulnerability.
The ticket requested updating `avalanche` to a version with `store2` 2.14.4+, however the latest `avalanche` version (3.16.0) only includes `store2` 2.14.2. Used resolution to force `avalanche@3.15.3` to use `store2@2.14.4` instead of vulnerable 2.13.2.
**Direct store2 usage audit**: No direct `store2.get()` operations found in codebase
- Searched for `store2.get` and `store.get`
**localStorage XSS vectors review**: No vulnerable patterns found
- All localStorage usage is safe (documentation examples only)
**Input validation**: N/A (No user-controlled data used in store operations)
Ticket: DX-1562
- `yarn audit` - GHSA-w5hq-hm5m-4548 resolved, …

fix: resolve store2 vulnerability via yarn resolution

---

package.json
yarn.lock

TICKET: 1558 
This PR addresses vulnerability GHSA-p8p7-x288-28g6, which involves Server-Side Request Forgery in the request package. Since request is a deprecated, we use a [patched, forked version](https://github.com/advisories/GHSA-p8p7-x288-28g6) of the package. 
This PR addresses and forces @celo/connect to stray away from transitively depend on the vulnerable request package, and instead force it to use the patched version `"npm:@cypress/request@3.0.9"`
**Validation results**
- Celo module tests: All passing
- No runtime errors detected
- @cypress/request@3.0.9 is a maintained fork designed as a drop-in replacement for the deprecated request package. While servify expects ^2.79.0, the updated package version is still compatible.
- `Yarn Audit` shows that the GHSA-p8p7-x288-28g6 is …

fix: force request to use @cypress/request@3.0.9 to address GHSA-p8p7-x288-28g6

---

modules/express/src/clientRoutes.ts
modules/express/src/typedRoutes/api/index.ts
modules/express/src/typedRoutes/api/v1/constructPendingApprovalTx.ts
modules/express/test/unit/typedRoutes/constructPendingApprovalTx.ts

feat(express): migrate constrctTx to typed routes
